### ISSUE TITLE
Проблема с chatId в сообщениях

### ISSUE THREAD

**Issue by ERussel** [VKCOM/vk-ios-sdk#102]
Работая с LongPollServer заметил, что chat_id в новом сообщении приходит странный, например 2000000011 вместо 11. Тоже самое происходит когда приложение запускается после пуш уведомления и в поле uid такое же странное значение. Возможно это сделано, чтобы отличать диалоги от чатов, но нигде не нашел описания. Посоветуйте, пожалуйста, как это обрабатывать?

**Comment by AllDmeat** [comment]
Сейчас при получении сообщения от лонгполла я проверяю на наличие «20» в начале строки. И если что — обрезаю и достаю остаток с конца.
Почему в начале именно 2 и куча нулей? Как безопаснее обрабатывать, чтобы точно отделить ID чата? Я к тому, что не поменяется ли эта двойка в начале на другую цифру? Не сократится или не увеличится ли длина строки? 

*риторический вопрос* 

Что будет, если у меня миллиард чатов? Добавятся дополнительные нули между двойкой и ID чата?

**Comment by Dreddik** [comment]
Когда будет миллиард чатов, тогда это действительно станет проблемой.
Сейчас peer_id чата = chat_id + 2e9
