### ISSUE TITLE
Мульти/сложный запрос

### ISSUE THREAD

**Issue by adman44** [VKCOM/vk-ios-sdk#103]
Может я гдето не дочитал но VKBatchRequest является сугубо только результатом сложений запросов из массива. Если в масиве у меня допустим 20 запросов на получение записей со стены групп, 7-8 запросов обработается, а дальше вылетит ошибка -101.

Пример:

    NSMutableArray *requestsArray = [[NSMutableArray alloc] init];
    for (int i=0;i<[_groups count];i++) {
        VKRequest * getWall = [VKRequest requestWithMethod:@"wall.get" andParameters:@{@"owner_id": [_groups objectAtIndex:i],@"filter" : @"owner",@"count":@"10",@"extended":@"1"} andHttpMethod:@"GET"];
        [requestsArray addObject:getWall];
       
        getWall.completeBlock = ^(VKResponse* response) {
           NSLog(@"response %@",i);
        };
    }

    VKBatchRequest * batch = [[VKBatchRequest alloc] initWithRequestsArray:requestsArray];

    [batch executeWithResultBlock:^(NSArray *responses) {
       NSLog(@"%i",[responses count]);
     // do some
    } errorBlock:^(NSError *error) {
        NSLog(@"Error: %@", error);
    }];

Как правильно получить ответ на такой вот запрос. Спасибо

**Comment by Dreddik** [comment]
Проверьте на последнем релизе, возможно проблема исправится
