### ISSUE TITLE
Ошибка при авторизации через приложение

### ISSUE THREAD

**Issue by Quatja** [VKCOM/vk-ios-sdk#105]
Ошибка при авторизации через приложение:
{"error":"invalid_request","error_description":"sdk not set up, check application settings"}

В принципе. я хочу обойтись и без СДК, потому что мне нужно только лишь авторизоваться, но что в случае с СДК, что без него, если авторизовываться через приложение - приходит эта ошибка.
Что нужно настроить?

**Comment by RomaGeekHubAcc** [comment]
Получаю ту же ошибку при авторизации: {"error":"invalid_request","error_description":"sdk not set up, check application settings"},  если установлен VK app на iPhone, если удалить VK app с девайса - авторизация работает.

**Comment by CoolMind** [comment]
@RomaGeekHubAcc, надо правильно заполнить поля в https://vk.com/editapp?id=номер_вашего_приложения (попасть туда можно из https://vk.com/apps?act=manage).
См. также https://github.com/VKCOM/vk-android-sdk/issues/10 про то, что "Название пакета
для Android" нужно брать из build.gradle, оно может меняться для debug- и release-версий. "Main activity для Android" нужно выставить как название стартовой активности. Также нужно добавить отпечатки сертификата без двоеточий.

**Comment by Alinaki** [comment]
> См. также [VKCOM/vk-android-sdk#10](https://github.com/VKCOM/vk-android-sdk/issues/10) про то, что "Название пакета для Android" нужно брать из build.gradle, оно может меняться для debug- и release-версий. 

У меня другая проблема, например. Приложение, установленное из APK отлично работает и с приложением, и с вебвью, а установленное из Google Play – не логинится, если стоит официальное приложение ВК, но успешно входит через вебвью.
