### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by maxbpro** [VKCOM/vk-ios-sdk#113]
Добрый день, не могу найти как произвести logout пользователя при использовании ios sdk. В андроид sdk есть метод logout. А тут не могу найти. Описание в документации тоже не нашел. Как выйти?

**Comment by AlexSiarheyeu** [comment]
> `[VKSdk forceLogout]` - это симуляция логаута. Удаляется текущий access_token и очищаются куки для встроенного webview.

Подскажите пожалуйста, а как полностью "разлогиниться", чтобы при нажатиии на кнопку выход, после, пользователю нужно было заново вводить логин и пароль? force logout этого не делает..
