### ISSUE TITLE
Не видит VKAccessToken.h

### ISSUE THREAD

**Issue by antonnab** [VKCOM/vk-ios-sdk#118]
Собственно сделал все по инструкции. Вначале не видел VKSdk.h, почитал что была такая проблема и заменил в AppDelegate.m на #import <VKSdk/VKSdk.h>. Но теперь не видит файл 'VKAccessToken.h' file not found хотя при зажатии cmd переходит на него. Сторонних библиотек не юзаю. в UserSearchPath добавлял ../*\* не помогло

**Comment by g-andronchik** [comment]
Такая же проблема. Причем это происходит в вашем тестовом проекте
