### ISSUE TITLE
Постоянно выпадает сообщение "Пожалуйста не копируйте данные из адресной строки для сторонних сайтов. Таким образом вы можете потерять доступ к своему аккаунту"

### ISSUE THREAD

**Issue by antonnab** [VKCOM/vk-ios-sdk#120]
Когда уже вызывается метод vkSdkReceivedNewToken и, более того объект VKAccessToken заполнен всем чем необходимо вызываю в методе performSegueWithIdentifier (метод push) а он мне на экране показывает это сообщение.

**Comment by abadef576** [comment]
> Когда уже вызывается метод vkSdkReceivedNewToken и, более того объект VKAccessToken заполнен всем чем необходимо вызываю в методе performSegueWithIdentifier (метод push) а он мне на экране показывает это сообщение.

I Love is VK app

**Comment by abadef576** [comment]
Nothing To Preview

**Comment by abadef576** [comment]
https://github.com/VKCOM/vk-ios-sdk/issues/120#issue-40975428

**Comment by abadef576** [comment]
i Love is VK app
