### ISSUE TITLE
Можно ли получить email пользователя?

### ISSUE THREAD

**Issue by nullproduction** [VKCOM/vk-ios-sdk#130]
В файле VKAccessToken.h нашел проперти email.
Попробовал при акторизации запрашивать доступ к email, но поле все равно пустое?
Можно ли получить email пользователя или это проперти лишняя?

```
@property (nonatomic, readwrite, copy) NSString *email;
```

**Comment by pcherednichenko** [comment]
Передавая в scope VK_PER_EMAIL в ответ не приходит email, у Android VK SDK все хорошо, а на iOS данный баг есть
