### ISSUE TITLE
проблема с получением push уведомлений после регистрации устройства методом account.registerDevice

### ISSUE THREAD

**Issue by Serguitar** [VKCOM/vk-ios-sdk#136]
Доброго времени суток!

Никак не могу разобраться с push уведомлениями, прошу помощи. Цель: получить push уведомление в ios приложение о том что пришло новое сообщение. Что я для этого сделал:
- SSL сертификат и ключ собраны в pem файле.
- pem файл загружен в vk приложение, выбран APNS и стоит галочка "Использовать sandbox сервер"
- полученный pem  файл проверял через php скрипт запущенный из терминала, тестовый push приходит
- запускаю свое ios приложение и разрешаю пуши
- авторизую свою страницу в моем ios приложении
- передаю account.registerDevice, в ответ приходит 1
- сворачиваю приложение, с компа с другого вк аккаунта отправляю себе сообщение - никаких пушей на айфон не приходит

Подскажите пожалуйста все ли я сделал или что то упустил?

**Comment by mfsnbt** [comment]
Та же проблема, выполнил все пункты, что и автор - не работает. Параметры 
 @{ @"token" : [VKSdk getAccessToken].accessToken, @"sandbox" : @"1" }

**Comment by Dreddik** [comment]
@mfsnbt token – это APNS токен, а не access token
