### ISSUE TITLE
Получение не Token, а code.

### ISSUE THREAD

**Issue by oks** [VKCOM/vk-ios-sdk#15]
Всем привет. Меня очень интересует возможность запроса а auth_token, а code, потому как мы пробрасываем запросы через сервер после авторизации, и дальнейший токен после запроса кода на клиенте уже получает сервер.
Посему у меня вопрос, есть ли в сдк возможность запросить не токен а код?

**Comment by cutalion** [comment]
@RomanTruba Добрый день. Подскажите, пожалуйста, что-нибудь изменилось за 2 года? 
Получается, что невозможно получить токен для сервера, через приложение на устройстве.
Приходится процедуру выполнять через webview с вводом пароля, который еще вспомнить надо.
У нас в приложении можно зарегистрироваться через соц. сети. При регистрации через ВК пользователи просто сдаются и даже не пытаются вспомнить пароль.

**Comment by RomanTruba** [comment]
@cutalion я больше не работаю в ВК и не поддерживаю SDK.
Насколько я знаю, планов не было.

**Comment by cutalion** [comment]
@RomanTruba понял, спасибо. Кто бы мог прояснить ситуацию? @suzhaev?

**Comment by suzhaev** [comment]
@cutalion да, в этом направлении ничего не поменялось, если получаете токен для standalone приложения, то используете его только в приложении. Либо так: https://vk.com/dev/auth_sites

**Comment by cutalion** [comment]
@suzhaev я правильно понял, что чтобы получить токен юзера для сервера, никак нельзя использовать установленное на телефоне приложение?

**Comment by suzhaev** [comment]
@cutalion вы можете использовать [эту схему](https://vk.com/dev/auth_sites), чтобы получить токен для сервера через приложение. Но через SDK это сделать не получится, т.е только если сами будете реализовывать

**Comment by appdrop** [comment]
@suzhaev пытаюсь использовать эту схему без SDK, ссылка выглядит вот так: `vkauthorize://authorize?client_id=1&scope=friends,offline&response_type=code&v=5.95&redirect_uri=https://oauth.vk.com/blank.html` и приложение VK все равно возвращает access_token. 

Я чего-то недопонимаю?
