### ISSUE TITLE
[VKApi audio]

### ISSUE THREAD

**Issue by MaxPovver** [VKCOM/vk-ios-sdk#158]
У вас в примерах указан этот вызов, но в самом sdk его нет, как и нормальных средств работы с музыкой, только напрямую получить ее удается(только через [VKApi requestWithMethod...)

Вы его специально удалили?

**Comment by Dreddik** [comment]
На самом деле, его не и не делали

**Comment by Dreddik** [comment]
Класс VKApi предоставляет простые вызовы, глядя на которые, вы можете расширить функциональность под ваши нужды.
Хотя у меня и есть идеи по написанию нужных вызовов, это займёт слишком много времени, и не факт, что окажется кому-то реально полезным
