### ISSUE TITLE
VKActivity+UIPopoverController crash on iPad iOS 6

### ISSUE THREAD

**Issue by kambala-decapitator** [VKCOM/vk-ios-sdk#159]
Обнаружил 2 вида краша в иос 6 на айпаде при отображении UIActivityViewController в поповере:

1. открыть поповер – выбрать вк – отмена – снова открыть поповер и выбрать вк
2. открыть модальный контроллер – открыть поповер – выбрать вк – отмена – закрыть модальный контроллер – снова открыть модальный контроллер

Оба сценария крашатся с сообщением
> -[VKShareDialogController isKindOfClass:]: message sent to deallocated instance

Отображается поповер незамысловато:
```objc
UIActivityViewController *vc = [[UIActivityViewController alloc] initWithActivityItems:@[@"test"] applicationActivities:@[[VKActivity new]]];

self.popover = [[UIPopoverController alloc] initWithContentViewController:vc];
[self.popover presentPopoverFromBarButtonItem:sender permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];
self.popover.passthroughViews = nil; // disable navbar touches
```

В иос 7 проблемы не наблюдается.

Тестовый проект: http://www28.zippyshare.com/v/17258134/file.html

**Comment by Dreddik** [comment]
Более подробная информация есть? Например, крэшлог или что-то в этом духе

**Comment by kambala-decapitator** [comment]
к сожалению, нет.

судя по сообщению, где-то остается необнуленная ссылка на мертвый VKShareDialogController.

**Comment by Dreddik** [comment]
Но тогда бы и в 7 крашилось

**Comment by kambala-decapitator** [comment]
в иос 7 же кастомное отображение контроллера — видно поэтому и не крашит.

кстати в иос 7 симуляторе контроллер вообще не появляется, но видно, что он как бы существует (кнопки навбара слегка затемняются).

а, и еще мелкий баг в иос 6 на айпаде: при повороте девайса из ландшафта в портрет контроллер не центрируется на экране, а уезжает в левую сторону экрана.

**Comment by Dreddik** [comment]
>>кстати в иос 7 симуляторе контроллер вообще не появляется, но видно, что он как бы существует (кнопки навбара слегка затемняются).
Видимо, это связано с проблемой в ios 7, потому что UIActivityViewController по всей видимости пытается презентовать диалог внутри поповера. Попробую покопать, как это обойти.
С iOS 6 подумаю, как можно разобраться

**Comment by Dreddik** [comment]
Попробуйте так

**Comment by kambala-decapitator** [comment]
на иос 6 и 7 теперь все супер. спасибо!

но теперь контроллер корявый в иос 8 в обоих ориентациях :) перед этим коммитом все было нормально.

**Comment by kambala-decapitator** [comment]
еще обнаружился баг на айфоне/айподе иос 6 при перевороте из портрета в ландшафт (но не наоборот) :)

**Comment by Dreddik** [comment]
>>еще обнаружился баг на айфоне/айподе иос 6 при перевороте из портрета в ландшафт (но не наоборот) :)

Это посмотрю после выходных

**Comment by Dreddik** [comment]
Вы могли бы проверить сейчас на iPad с iOS 6?

**Comment by kambala-decapitator** [comment]
на айпаде и до этого все было прекрасно :) а вот на айфоне/айподе теперь корректное поведение. спасибо!

**Comment by Dreddik** [comment]
Ну я про iPad на всякий случай спросил, нет возможности протестировать

**Comment by kambala-decapitator** [comment]
можно установить Xcode 5 ;)
