### ISSUE TITLE
VKShareDialogController появляется полупустым

### ISSUE THREAD

**Issue by Nikolaiko** [VKCOM/vk-ios-sdk#161]
Добрый день. Использую код из примера для ShareDialogController : 

    VKShareDialogController * shareDialog = [VKShareDialogController new]; //1
    shareDialog.text = @"This post created using #vksdk #ios"; //2
    shareDialog.vkImages = @[@"-10889156_348122347",@"7840938_319411365",@"-60479154_333497085"]; //3
    shareDialog.shareLink = [[VKShareLink alloc] initWithTitle:@"Super puper link, but nobody knows" link:[NSURL URLWithString:@"https://vk.com/dev/ios_sdk"]]; //4
    [shareDialog setCompletionHandler:^(VKShareDialogControllerResult result) {
        [self dismissViewControllerAnimated:YES completion:nil];
    }]; //5
    [self presentViewController:shareDialog animated:YES completion:nil]; //6

Диалог показывается, на нем нет никаких кнопок для отправки на публикацию. 
![img_0355](https://cloud.githubusercontent.com/assets/3236822/5680438/35e7ed6a-982f-11e4-9720-52ba8041f15e.PNG)
При нажатии на нижнюю строку открывшегося диалога появляется следующее :
![img_0356](https://cloud.githubusercontent.com/assets/3236822/5680460/650708d8-982f-11e4-87d0-348da5887ea6.PNG)
Нажатие на Back возвращает нас на экран с предыдущего фото, переключение элемента switch ничего не меняет.

**Comment by Dreddik** [comment]
Скопируйте VKSdkResources.bundle в свой проект

**Comment by Nikolaiko** [comment]
А надо именно этот файл копировать? Просто я шел по пути : Установка из исходного кода, в инструкциях. То есть я добавил файл sdk.xcodeproj, а потом, в секции "Link Binary with Libraries" libVKSdk.a. В добавленом проекте в ресурсах есть bundle, попробую добавить его именно в свой проект

**Comment by Nikolaiko** [comment]
Добавил, все появилось, спасибо.

**Comment by hellc** [comment]
@interface VKShareDialogController : UIViewController
/// Array of prepared VKUploadImage objects for upload and share. User can remove any attachment
@property (nonatomic, strong) NSArray  *uploadImages;

/// Other attachments, defined as array strings. Now supported only links
@property (nonatomic, strong) NSArray  *otherAttachmentsStrings;

/// Text to share. User can change it
@property (nonatomic, strong) NSString *text;

/// You can post not only on user wall, but also his friends walls and groups walls
@property (nonatomic, strong) NSNumber *ownerId;

/**
 Correctly presents current view controller in another
 @param viewController Parent view controller
 */
- (void)presentIn:(UIViewController *)viewController;
@end 

где всё? У меня этот же пример с ошибками. Pod обновленный.

**Comment by Dreddik** [comment]
@hellc это устаревший код

**Comment by hellc** [comment]
@Dreddik да уж, проглядел http://obhodvk.ru/dev/ios_sdk. Странный у нас google. Спасибо.

**Comment by xpams** [comment]
Доброго времени суток. Приложение вылетает при добавлении изображений к посту. Если убрать строку с добавлением изображений - все отлично работает... Не подскажите в чем проблема?

 var shareDialog : VKShareDialogController = VKShareDialogController();
        shareDialog.text = "123456789";
        shareDialog.vkImages = ["-10889156_348122347","7840938_319411365","-60479154_333497085"];
        shareDialog.completionHandler = {
                        (result : VKShareDialogControllerResult) -> Void in
                        self.dismissViewControllerAnimated(true, completion: nil);
        };
        self.presentViewController(shareDialog, animated: true, completion: nil);
        println("posted");
