### ISSUE TITLE
Revoke token deadlock

### ISSUE THREAD

**Issue by Vyazovoy** [VKCOM/vk-ios-sdk#162]
If I use SDK only for sharing extension and if I revoke access in settings on web, then I can't resubmit token request from application. It is very strange behaviour. If I disable app in my web settings page, why I can't grant again access for this app through sharing process.

**Comment by Dreddik** [comment]
I read your problem several times and still can't get what do you exactly mean.

**Comment by Vyazovoy** [comment]
Steps:
1 Integrate SDK
2 Implement native Apple sharing with VKActivity
3 At first attempt to share:
  3.1 Switch to VK App for login
  3.2 Switch to app and successfully share
4 Go to account settings pane on web
5 Revoke app from the app list
6 Open the app and try to share with error but no option to login again

Until I go to settings and turn back my app in app list, I'll not be able to share. It's problem. @Dreddik

**Comment by Dreddik** [comment]
Must be fixed now
