### ISSUE TITLE
Работа SDK в iPhone 5S, 6 или 6 Plus

### ISSUE THREAD

**Issue by Tristamoff** [VKCOM/vk-ios-sdk#164]
У меня вот такая вот проблема /Users/....../VKsdk/Source/VKActivity.m:38:9: No visible @interface for 'UIDevice' declares the selector 'systemVersion'
![2015-01-22 17 04 36](https://cloud.githubusercontent.com/assets/2246794/5857005/306c6c9c-a259-11e4-9b91-3b7dd5094c21.png)

Собрать приложение в итоге не получается.

Причем проявляется только если в эмуляторе выбрано устройство 5S, 6 или 6 Plus. 
На 4, 4S и 5 - работает корректно.
XCode 6.1

**Comment by matrosovDev** [comment]
У меня совсем не работает ничего. В описание как работать с апи как то не последовательно все изложено. Где что вызывать. Ели нашел какой массив в scope закидывать. В описании опять таки ноль информации об этом. Пока убил пару часов на то что бы разобраться с амортизацией. Не веб вью ни апа не запускается. Как авторизироваться?

**Comment by Dreddik** [comment]
Попробуйте запустить тестовое приложение, или использовать cocoapods.
Возможно, у вас выбран какой-то неправильный xcode sdk.
-systemVersion в UIDevice доступно с iOS SDK 2.0, так что его не может не быть.
Проверяйте настройки проектов, что-то где-то наменяли, видимо.

**Comment by Tristamoff** [comment]
Скачал заново ваш проект, запустил тестовый-та же проблема.
Сидел в настройках и решил проблему тыкая пальцев в небо, а именно изменением настройки "Enable Additional Vector Extensions"
По умолчанию она стоит "Platform default". Если изменить на SSE - всё работает.
![2015-01-23 10 49 32](https://cloud.githubusercontent.com/assets/2246794/5871386/8ea3988c-a2ed-11e4-8327-c0de997eac8d.png)

![2015-01-23 10 46 39](https://cloud.githubusercontent.com/assets/2246794/5871393/9763bc0e-a2ed-11e4-9806-e9609190dd5f.png)

Может кому пригодятся.

**Comment by Dreddik** [comment]
Возможно, вы работаете на хакинтоше?
У меня собирается с дефолтной настройкой.

**Comment by Tristamoff** [comment]
Нет, на маке работаю.
OS X Yosemite 10.10

**Comment by matrosovDev** [comment]
У меня тоже OS X Yosemite 10.10.1 качаю черз подс и запускаюсь с workspace файла. Все собирается норм.
