### ISSUE TITLE
Как авторизироватся?

### ISSUE THREAD

**Issue by matrosovDev** [VKCOM/vk-ios-sdk#165]
Добавил в апп делегат метод. Добавил АПП ид в URL Schemes и Idetifer в Info.plist.

Пытаюсь вызвать так:

- (void)shareVkontakte
{
    [VKSdk initializeWithDelegate:self andAppId:APP_ID_VKONTAKTE];   
    [VKSdk authorize:@[VK_PER_WALL,VK_PER_PHOTOS] revokeAccess:YES];
}

Но прога падает

**Comment by Dreddik** [comment]
Скорее всего не определены методы VKSdkDelegate.
Я не телепат

**Comment by ashitikov** [comment]
1. Убедитесь, что AppDelegate имплементирует протокол VKSdkDelegate
2. Убедитесь, что [VKSdk authorize:..] вызывается после события viewDidAppear.
3. Лог в студию

**Comment by matrosovDev** [comment]
Сейчас разобрался плюс минус с авторизацией. Но повторно запустил прогу сегодня. Метод wakeUPSession возвращает YES. Но реквест сообщает failed - срабатывает:

} errorBlock:^(NSError *error) {
        NSLog(@"failed");
    }];

Что то упустил?

- (void)shareVkontakte
{
    if ([VKSdk wakeUpSession])
    {
        [self shareVkontakteOnTheWall];
    }
    else
    {
        [VKSdk initializeWithDelegate:self andAppId:APP_ID_VKONTAKTE];
        
        [VKSdk authorize:@[VK_PER_WALL,VK_PER_PHOTOS] revokeAccess:YES];
    }
}

- (void)shareVkontakteOnTheWall
{
    VKRequest *request = [[VKApi wall] post:@{VK_API_ATTACHMENTS : @"http://somelink", @"wall_id":@"0",}];
    
    [request executeWithResultBlock:^(VKResponse *response) {
        NSLog(@"OK");
    } errorBlock:^(NSError *error) {
        NSLog(@"failed");
    }];
}

- (void)vkSdkNeedCaptchaEnter:(VKError *)captchaError {}

- (void)vkSdkTokenHasExpired:(VKAccessToken *)expiredToken {}

- (void)vkSdkUserDeniedAccess:(VKError *)authorizationError {}

- (void)vkSdkShouldPresentViewController:(UIViewController *)controller
{
   [self presentViewController:controller animated:YES completion:nil];
}

- (void)vkSdkReceivedNewToken:(VKAccessToken *)newToken;
{
    if ([VKSdk wakeUpSession])
    {
        [self shareVkontakteOnTheWall];
    }
}

-(BOOL)vkSdkIsBasicAuthorization
{
    return YES;
}

**Comment by Dreddik** [comment]
Сначала initializeWithDelegate: , потом всё остальное
