### ISSUE TITLE
VKAccessToken expiresIn property is @"0"

### ISSUE THREAD

**Issue by banshchikov** [VKCOM/vk-ios-sdk#166]
I use VK SDK 1.0.9.3 and receive token in method vkSdkRenewedToken with expiresIn property set to @"0" - what does it mean?

**Comment by Dreddik** [comment]
It means the token is valid forever until a user revoke it on the site, or change his password on the site

**Comment by banshchikov** [comment]
Thank you! And how expiresIn looks when it is not a zero?

**Comment by Dreddik** [comment]
In a current implementation of the SDK you should never get a situation when `expiresIn` isn't equals to zero.
But if it would, it will represent a number of seconds before the token will become invalid.
