### ISSUE TITLE
'Build framework' build phase breaks project archiving

### ISSUE THREAD

**Issue by Sega-Zero** [VKCOM/vk-ios-sdk#167]
Trying to build an archive of a project and get an error:
> cp: /Users/user/project/Build/Intermediates/ArchiveIntermediates/Release/IntermediateBuildFilesPath/UninstalledProducts/include/VKSdk/: No such file or directory

The trouble goes away if I remove 'Build framework' build phase from static library project. Easily reproducable on a sample project.

**Comment by Tristamoff** [comment]
I also have so bug. I cant build archive.

**Comment by Dreddik** [comment]
Remove this build phase as temporary solution

**Comment by Tristamoff** [comment]
Пробовал.
Тут вроде бы всё правильно сделал, 
![2015-02-09 14 22 41](https://cloud.githubusercontent.com/assets/2246794/6105340/39edf6b6-b067-11e4-9460-d01221310520.png)
С этим https://github.com/VKCOM/vk-ios-sdk/issues/146 ознакомился, всё согласно https://github.com/VKCOM/vk-ios-sdk/issues/146#issuecomment-66758726

**Comment by Dreddik** [comment]
Выберите проект VKSdk, там Build Phases в конце списка будет Build framework, его и нужно убрать

**Comment by Tristamoff** [comment]
Да, точно. С трудом нашел это место, удалил и архив собрался. Спасибо большое, это моё первое приложение)))
