### ISSUE TITLE
Отправка приглашения на standalone приложение

### ISSUE THREAD

**Issue by dilshod** [VKCOM/vk-ios-sdk#168]
Добрый День,
Отправляю запрос на приглашение по api:
https://vk.com/dev/apps.sendRequest

Для чего нужно поле name? И как пользоваться полем key для подсчета конверсии?

**Comment by mishaboldov** [comment]
Key передается в приложение при переходе из запроса. Таким образом, вы можете понять, сколько запросов с определенным key было отправлено, и сколько было переходов. На основе этого можно посчитать конверсию.

Поле name — внутренний идентификатор для каждого уникального текста запроса. Он используется для статистики.

Обратите внимание, что метод apps.sendRequest доступен только для приложений, размещенных на [Мобильной игровой платформе] (http://vk.com/dev/mobile_games).

**Comment by dilshod** [comment]
Спасибо за ответ.
А как мне получить этот key в vk ios sdk? Я так понимаю Key получает приложение у друга, когда он в первый раз открывает игру?

**Comment by mishaboldov** [comment]
Это текстовое поле, вы можете разместить в него всё, что угодно. Далее, вы делаете запрос через apps.sendRequest. Когда пользователь переходит по вашему запросу в клиенте VK, значение передается обратно в приложение.
