### ISSUE TITLE
Не прикрепляются изображения к посту

### ISSUE THREAD

**Issue by xpams** [VKCOM/vk-ios-sdk#169]
Доброго времени суток. Приложение вылетает при добавлении изображений к посту. Если убрать строку с добавлением изображений - все отлично работает... Не подскажите в чем проблема?
<i>
 var shareDialog : VKShareDialogController = VKShareDialogController();
        shareDialog.text = "123456789";
        shareDialog.vkImages = ["-10889156_348122347","7840938_319411365","-60479154_333497085"];
        shareDialog.completionHandler = {
                        (result : VKShareDialogControllerResult) -> Void in
                        self.dismissViewControllerAnimated(true, completion: nil);
        };
        self.presentViewController(shareDialog, animated: true, completion: nil);
        println("posted");
</i>

Вот такой екзепшин:

2015-02-01 03:03:49.349 RadioKPI[3913:107822] -[__NSCFArray photoSizeWithType:]: unrecognized selector sent to instance 0x7fd3896bb860
2015-02-01 03:03:49.385 RadioKPI[3913:107822] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFArray photoSizeWithType:]: unrecognized selector sent to instance 0x7fd3896bb860'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ad15f35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010ca9cbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010ad1d04d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010ac7527c ___forwarding___ + 988
	4   CoreFoundation                      0x000000010ac74e18 _CF_forwarding_prep_0 + 120
	5   RadioKPI                            0x000000010a24af6b __52-[VKShareDialogControllerInternal createAttachments]_block_invoke1153 + 843
	6   RadioKPI                            0x000000010a259aeb -[VKRequest finishRequest] + 1163
	7   RadioKPI                            0x000000010a2593c6 __44-[VKRequest provideResponse:responseString:]_block_invoke + 38
	8   libdispatch.dylib                   0x0000000110e11ba6 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x0000000110e2f7f4 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x0000000110e188fb _dispatch_main_queue_callback_4CF + 949
	11  CoreFoundation                      0x000000010ac7dfe9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	12  CoreFoundation                      0x000000010ac40eeb __CFRunLoopRun + 2043
	13  CoreFoundation                      0x000000010ac40486 CFRunLoopRunSpecific + 470
	14  GraphicsServices                    0x000000010d1659f0 GSEventRunModal + 161
	15  UIKit                               0x000000010b7e4420 UIApplicationMain + 1282
	16  RadioKPI                            0x000000010a234cbe top_level_code + 78
	17  RadioKPI                            0x000000010a234cfa main + 42
	18  libdyld.dylib                       0x0000000110e64145 start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(Recorded Frame)

**Comment by Dreddik** [comment]
Возможно, нет разрешения на photos

**Comment by freeman1387** [comment]
та же проблема. Зачем разрешение на доступ к Фото? если мы не используем свои фото? 
разрешение на PHOTOS не решило проблему
