### ISSUE TITLE
Подскажите по поводу метода friends.getAppUsers

### ISSUE THREAD

**Issue by SergeyOleynich** [VKCOM/vk-ios-sdk#172]
А как мне доставая таким образом друзей достать еще базовую информацию о друге? здесь нет fields. И я получаю только id, это чтоб получить информацию о друге мне надо еще делать запросы? Почему не сделать так как в получении списка всех друзей чтоб было поле fields и мне приходила базовая информация?

**Comment by nullproduction** [comment]
никак. делайте два запроса. если знаете javascript можете открыть настройки своего приложения и сделать свой кастомный метод который выполняет эти два запроса

**Comment by Dreddik** [comment]
Сделайте execute без хранимых процедур
```return API.users.get({user_ids: API.friends.getAppUsers(), fields:"photo_100"});```

**Comment by SergeyOleynich** [comment]
Я не уточнил но я использую iOS SDK и пользуюсь VKRequest execute. Подскажите как быть в этой ситуации?

**Comment by nullproduction** [comment]
Не проверял, ну то что вам показал Dreddik это javascript который нужно выполнить в методе https://vk.com/dev/execute

Примерно так:

    NSDictionary *parameters = @{
        @"code" : @"return API.users.get({user_ids: API.friends.getAppUsers(), fields:\"photo_100\"});",
    };
    
    VKRequest *request = [VKRequest requestWithMethod:@"execute"
                                        andParameters:parameters];

**Comment by SergeyOleynich** [comment]
Спасибо) попробую)

**Comment by SergeyOleynich** [comment]
Работает)
