### ISSUE TITLE
VKShareDialogController presenting problem in IOS 8

### ISSUE THREAD

**Issue by Sh1mor1nka** [VKCOM/vk-ios-sdk#174]
Здравствуйте. Есть у меня поповер с кнопками соц сетей для шаринга, когда из него пытаюсь вызвать VKShareDialogController 

```Objective-C
VKShareDialogController * shareDialog = [VKShareDialogController new];
    shareDialog.text         = text;
    shareDialog.uploadImages     = @[[VKUploadImage uploadImageWithImage:image andParams:[VKImageParameters pngImage]]];;
    shareDialog.shareLink    = [[VKShareLink alloc] initWithTitle:@"Salatiki!" link:[NSURL URLWithString:@"https://itunes.apple.com/ru/app/salatiki/id951969465"]];
    [shareDialog setCompletionHandler:^(VKShareDialogControllerResult result) {
        [vc dismissViewControllerAnimated:YES completion:nil];
    }];
    [vc presentViewController:shareDialog animated:YES completion:nil];
```

ничего не происходить и вызалит тако лог:

```Objective-C
2015-02-10 13:51:43.619 MyApp[42436:792908] Warning: Attempt to present <VKShareDialogController: 0x79ce0830>  on <MyViewController: 0x7b3b2800> which is already presenting (null)
```

я полагаю что в IOS8 если что-то есть на экране(окно/поповер) то еще что-то поверх него нельзя вызвать, в IOS 7 работает отлично. 

Если есть какие-то решения, предложения буду рад.

**Comment by Dreddik** [comment]
Закрыть поповер через `dismissViewControllerAnimated:completion:`, дождаться завершения в completion, показать share dialog

**Comment by Sh1mor1nka** [comment]
я думал об этом, а вот сейчас еще раз подумал и понял что я так даже код оптимизирую слегка и выглядит это адекватно, спасибо))

**Comment by Dreddik** [comment]
Да, только учитывайте iOS 7, в которой поповер всё ещё нужно скрывать стандартным способом

**Comment by Sh1mor1nka** [comment]
Спасибо еще раз!

**Comment by Sh1mor1nka** [comment]
Я бы советовал обратить внимание как реализовано у Facebook, на примере FBWebDialogs, оно поверх всего вылазит не зависимо от версии IOS. Возможно у Вас в будущих билдах выйдет что-то супер универсальное сделать.
