### ISSUE TITLE
MD5 unrecognized selector

### ISSUE THREAD

**Issue by TaHyKu** [VKCOM/vk-ios-sdk#175]
Добрый день!

Добавлял фреймворк в проект руками.
При авторизации, все работает, но вылетает

-[__NSCFString MD5]: unrecognized selector sent to instance

Что это может быть?

Заранее благодарен!

**Comment by Dreddik** [comment]
Нужно добавить флаг в линкер `-ObjC` и/или `-all_load`

**Comment by TaHyKu** [comment]
Спасибо) У Вас одна из лучших поддержек)

**Comment by kabkasik** [comment]
Спасибо
