### ISSUE TITLE
Обработка ошибки "User authorization failed: user revoke access for this token"

### ISSUE THREAD

**Issue by vboyko07** [VKCOM/vk-ios-sdk#177]
В процессе реализации шаринга через sdk, застрял на такой ситуации:
1. пользователь авторизировался (разрешил доступ приложении, получил accessToken)
2. зашел со своей страницы(веб версии vk) в "настройки приложений" и удалил моё приложение
3. если попытаться пошарить изображение через VKShareDialogController + VKUploadImage
в лог получаю ошибку "Error: VKError: 0x15852a20; API error {code: 5; message: User authorization failed: user revoke access for this token.;}"

подскажите как обработать такой кейс? так как колбек с ошибкой не вызывается(его вообще нету, или не нашел). После инициализации приложения в коде, метод [VKSdk wakeUpSession] возвращает true, хотя токен был убит в пункте "2". Получается до шаринга я не смогу проверить валидность токена? И в процессе шаринга не смогу, так как нету колбека

**Comment by kavolorn** [comment]
Я тоже наблюдаю такое поведение. Я запускаю авторизацию второй раз и получаю новый токен.

**Comment by Dreddik** [comment]
Верно, обычно эту ошибку вы должны обрабатывать сами, но я понял, что в Share Dialog мне её тоже нужно обработать.
Доделаю

**Comment by kavolorn** [comment]
Как я понимаю, вызов "stats.trackVisitor" вручную (в дополнение к имеющемуся в wakeUpSession) на старте приложения является хорошей практикой и может детектировать плохой токен? То есть еще до диалога расшаривания возможно определить плохой токен.

**Comment by Dreddik** [comment]
@kavolorn я думаю, что туда и добавлю проверку.
Второй вызов с вашей стороны немного поломает вам статистику входов.

**Comment by kavolorn** [comment]
Непредсказуемое поведение, необходимо обработать! Вот здесь описано https://vk.com/dev/stats.trackVisitor что данные о текущем сеансе добавятся в статистику. Я это трактовал так, что можно хоть пять раз вызвать этот метод и ничего не испортится - сеанс то один. Если это не так, то необходимо решение.

**Comment by Dreddik** [comment]
Ну, просто у вас будет 1 пользователь с 2 входами, нужно ли вам это?)
Если так хочется обработать ошибку руками, можно просто вызвать, например, `friends.getAppUsers`

**Comment by kavolorn** [comment]
Не нужно! Нада бы отметить такое поведение в документации. Возвращаясь к нашей ситуации, как временный воркэраунд сойдет вызов любого метода и отлавливание ошибки при старте приложени.

**Comment by vboyko07** [comment]
Решил сначала загружать изображение на сервер и отдавать в VKShareDialogController уже готовые id. Но вот с какой штукой столкнулся:
* Загружаю изображение на сервер, получаю 
```json
(lldb) po response
        "album_id": "-14",
        "id": "355009002",
        "owner_id": 281181177,
        "photo_807": "https://pp.vk.me/c624118/v624118177/1bffc/bKtxSsLBgQs.jpg"
         ...
```
* Собираю атач
```json
(lldb) po photoAttachment
photo281181177_355009002
```
* Отдаю атач в: 
```
shareDialogController.vkImages = @[photoAttachment];
```
* В итоге изображение в VKShareDialogController не отображается, бесконечно крутится активити. Выяснил что в VKShareDialogController (ст. 1129) создается запрос на получение изображений и его completeBlock не вызывается, добавив errorBlock к тому же запросу, получил ошибку
```
(lldb) po error
Error Domain=VKSdkErrorDomain Code=-101 "Access denied" UserInfo=0x17591c20 {NSLocalizedDescription=Access denied, VkErrorDescriptionKey=<VKError: 0x18a26e00; API error {code: 200; message: Access denied;}>}
```

права на фото, при авторизации запрашивал. Если заапрувить такой диалог, то изображение пошарится.
Подскажите в чем дело?

**Comment by Dreddik** [comment]
@vboyko07 а каким методом загружаете? Какой-то странный альбом для фото, как будто вы фото грузите для диалога

**Comment by vboyko07** [comment]
@Dreddik с помощью
```
VKRequest *uploadPhoto = [VKApi uploadWallPhotoRequest:image parameters:p userId:0 groupId:0];
```

**Comment by Dreddik** [comment]
@vboyko07 точно.
В таком случае, можно просто отдать изображение на загрузку самому диалогу в параметр `uploadImages`, например `[VKUploadImage uploadImageWithImage:image andParams:[VKImageParameters jpegImageWithQuality:1.0f]]`

**Comment by vboyko07** [comment]
@Dreddik в первом сообщении этого issue я так и делал, но как помните ошибка "убитого" токена не обрабатывается в таком случае. 
А как можно решить 
```
API error {code: 200; message: Access denied;}>}
```
если можно

**Comment by Dreddik** [comment]
Простите, с утра что-то туго соображаю.
Проблема code 200 в том, что фото ещё не опубликовано (или уже не опубликовано, но это другое). Поэтому лучше изображение отдать на загрузку в диалог, а перед диалогом запрашивать какой-нибудь другой "лёгкий" метод

**Comment by vboyko07** [comment]
Понял, спасибо. Тикет закрываю
