### ISSUE TITLE
Запрос users.get игнорирует первый и последний элемент

### ISSUE THREAD

**Issue by MitryBur** [VKCOM/vk-ios-sdk#181]
VKRequest *userDetailsReq = [[VKApi users] get:@{VK_API_FIELDS:@"first_name, last_name, uid, photo_100", VK_API_USER_IDS:@[@(1),@(2),@(3)]}];
    [userDetailsReq executeWithResultBlock:^(VKResponse *response){
        NSArray *responseArray = response.parsedModel) 
...}];
В responseArray будет только один результат - объект с uid 2.

**Comment by Dreddik** [comment]
Хех, вообще-то параметр типа NSArray не поддерживался, добавил поддержку сериализации в строку, разделённую запятыми

**Comment by Dreddik** [comment]
Fixed 6bfcec15d0412c9a43926473e7b8d7e3465d6805

**Comment by MitryBur** [comment]
Документация-то предлагает использовать именно NSArray 
`VKRequest * request2 = [[VKApi users] get:@{VK_USER_IDS : @[@(1), @(6492), @(1708231)]}]; `

Спасибо!
