### ISSUE TITLE
Нужен метод vkSdkDismissViewController

### ISSUE THREAD

**Issue by vmalov** [VKCOM/vk-ios-sdk#182]
Есть кейс:

```
- (void)vkSdkReceivedNewToken:(VKAccessToken *)newToken {
    [self someMethod];
}

-(void) someMethod{
    [self performSegueWithIdentifier:@"segue" sender:nil];
}
```
Случается следующее:
```
Warning: Attempt to present <ViewController: 00000000> on <UINavigationController: 00000> whose view is not in the window hierarchy!
```

Обходить через `viewDidAppear` и какой-нибудь флаг не кажется красивой идеей.

Может быть, сделать метод делегата что-то вроде `vkSdkDismissViewController` наподобие `vkSdkReceivedNewToken`, либо же вызывать  `vkSdkReceivedNewToken ` в SDK в `complition`-блоке закрытия модального окна?

**Comment by Dreddik** [comment]
Это проблема после авторизации через webview?

**Comment by DangeloID** [comment]
Да, у меня похожая проблема. После логина через вебвью пытаюсь зашарить текст сразу из метода - (void)vkSdkReceivedNewToken:(VKAccessToken *)newToken. Но контроллер с вебвью еще живет в этот момент и отображается.
