### ISSUE TITLE
Утечки памяти

### ISSUE THREAD

**Issue by TullerVal** [VKCOM/vk-ios-sdk#183]
При вызове каждого запроса, вроде users.get или groups.get, происходят утечки памяти.
Данные нигде не храню, все чищу. Память течет именно в запросе. 
Класс VKRequest может кешировать в памяти то, что скачал? Размер утечек чуть больше всего скачанного трафика.
В чем может быть дело?

**Comment by Dreddik** [comment]
Какая версия SDK?

**Comment by Dreddik** [comment]
Ну и пример выполнения запроса

**Comment by TullerVal** [comment]
Версия СДК последняя. В предпоследней аналогичное поведение.

Вот зацикленный запрос:

-(void)updateWithId:(NSString*)user_id {
    request.errorBlock = nil;
    [request cancel];
    
    request = [VKRequest requestWithMethod:@"groups.get" andParameters:
               @{VK_API_USER_ID : user_id, @"extended" : @(1), @"filter" : @"groups,publics",
                 @"fields" : @"photo_50,screen_name"} andHttpMethod:@"GET"];
    [request executeWithResultBlock:^(VKResponse * response) {
        NSLog(@"groups.get Json result: %@", response.json);
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 1 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
            [self updateWithId: user_id];
        });
    } errorBlock:^(NSError * error) {
    }];
}
если запустить на реальном девайсе и подождать минут 10, то приложение закроется из-за нехватки памяти.

**Comment by Dreddik** [comment]
Да, не релизится VKRequest, разбираюсь, почему так произошло

**Comment by Dreddik** [comment]
Стоп, нет, всё релизится.
У вас проект ARC?

**Comment by TullerVal** [comment]
Да, всё ARC. Analyze в XCode тоже ничего не показал.
Получилось повторить утечку?

**Comment by Dreddik** [comment]
Да, есть небольшая, и весьма странная

**Comment by TullerVal** [comment]
Добрый день. Получилось как-то исправить баг?

**Comment by Dreddik** [comment]
Пока что нет. Баг вызывает не SDK, что-то ниже. Возможно, где-то подвисает data

**Comment by kambala-decapitator** [comment]
судя по приведенному коду, request сидит в классе, а блок захватывает self. решением будет использование weak self.

**Comment by TullerVal** [comment]
request сидел и в классе, и в методе, и вообще нигде не сидел. И даже если бы сидел, при следующей итерации указатель бы очистился.
Плюс у request вызывается dealloc. Тут что-то другое

**Comment by VladimirGoncharov** [comment]
@TullerVal Думаю вам выше все верно подсказали. Скорее всего ошибка - это передача self как сильной ссылки, которая заретейниться, но никогда не зарелизиться ARC. Посмотрите, в офиц. документации об этом [Working with blocks](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithBlocks/WorkingwithBlocks.html#//apple_ref/doc/uid/TP40011210-CH8-SW16). Попробуйте ниже код:

```objc
-(void)updateWithId:(NSString*)user_id {
request.errorBlock = nil;
[request cancel];

__weak typeof(self) wself = self;
request = [VKRequest requestWithMethod:@"groups.get" andParameters:
           @{VK_API_USER_ID : user_id, @"extended" : @(1), @"filter" : @"groups,publics",
             @"fields" : @"photo_50,screen_name"} andHttpMethod:@"GET"];
[request executeWithResultBlock:^(VKResponse * response) {
    NSLog(@"groups.get Json result: %@", response.json);
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 1 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
        if (!wself)
        {
            return;
        }    
        [wself updateWithId: user_id];
    });
} errorBlock:^(NSError * error) {
}];
}
```

Возможно в самом SDK есть такие проблемы. Не заглядывал.

**Comment by kambala-decapitator** [comment]
if (!wself)
        {
            return;
        } 

в данном случае это совершенно бессмысленный код :)

**Comment by TullerVal** [comment]
код бессмысленный еще и потому, что даже без передачи self в блок, без обьявления переменной request, при вызове dealock в классе Request утечки все-таки происходят :) 
Нужно через Инструменты смотреть, правда, конкретно в этом случае я ничего не нашел

**Comment by VladimirGoncharov** [comment]
@kambala-decapitator Ради интереса, а почему бессмысленный?
```objc
    if (!wself)
    {
        return;
    } 
```
Я просто думаю нет смысла дальше посылать сообщения для nil :)

@TullerVal вообще для Request бессмыслен. Но все таки ошибка. :) Вдруг где-то в SDK такая же засела ;)

**Comment by kambala-decapitator** [comment]
@VladimirGoncharov ну послать одно сообщение нилу вполне можно (да и меньше писанины получится).

понятно, что если бы дальше было больше обращений к селфу, то это условие было бы нормальным (плюс в таком случае надо было бы превратить weak self в strong чтобы гарантировать, что weak селф не обнулится в середине блока).

**Comment by SadhuRus** [comment]
Удалось ли найти решение? У меня аналогичное ситуация.. Данные не храню в Request'e утечка памяти. И через некоторое время (10-15 минут приложение крэшится)

**Comment by TullerVal** [comment]
мне не удалось. Я только смог немного это смягчить тем, что стал реже загружать данные и добавил алерт "простите, сейчас упадем".

**Comment by SadhuRus** [comment]
Да, такой алерт я уже тоже добавил =))

**Comment by TullerVal** [comment]
сколько мб ты за 15 минут успеваешь выкачивать?

**Comment by SadhuRus** [comment]
Именно на выкачивании у меня данных не очень много. У меня задача чуть в другом. Я ничего лишнего не сохраняю. А вот крэшится на iphone 5S при превышении лимита 400 мб памяти где-то. Я вот думаю в сторону отказа в Vk SDK и попробовать  написать всё через AFNetnetworking.. Только лениво там будет передавать все токкены и т.п =)

**Comment by TullerVal** [comment]
что у тебя 400 мб заняло? Это явно не VK SDK

**Comment by kambala-decapitator** [comment]
есть такое чувство, что дело вовсе не в сдк

**Comment by TullerVal** [comment]
а не получится отключить запросы и проверить оставшуюся часть?
Я пробовал, но у меня именно в сдк память течет.

**Comment by SadhuRus** [comment]
РЕШЕНИЕ НАЙДЕНО!
Совершенно случайно в голову залетела проста и элементарная идея которая сработала!
Суть проблемы была в том, что утечки возникали из за того, что VKRequest не деаллокался после выполнения. Когда много VKRequest'ов это приводило к сильным утечкам. А их у меня было много. 

Так вот решение: Нужно создать только один VKRequest в синглтоне.  И обращаться к нему. Тем самым не будет никаких утечек. Вчера всё проверил - работает идеально.

**Comment by kambala-decapitator** [comment]
решением будет устранение причины неуничтожения объектов VKRequest ;)

Может ты захватываешь там strong self? (или другой объект в блоке, который не дает релизнуться реквесту)

**Comment by TullerVal** [comment]
ничего мы там не захватываем, это проверяли в первую очередь.

Идея и сингелтоном кажется рабочей. Только как менять параметры в VKRequest, если параметры задаются только при создании обьекта? Ты держишь один обьект для каждого запроса (вроде "database.getCities") и меняешь только параметры?

**Comment by TullerVal** [comment]
или подключил СДК через исходники и добавил свои методы?

**Comment by TullerVal** [comment]
получилось, только пришлось подключать через код и вручную вызывать [request cleanUp] и еще чистить OrderedDictionary *preparedParameters;
тогда и параметры можно каждый раз новые передавать

**Comment by TullerVal** [comment]
PS: _methodParameters тоже чистить не повредит, чтоб параметры, которые не уже используются, не слались при новом запросе

**Comment by SadhuRus** [comment]
TullerVal, отлично!
Я ничего в исходниках sdk не менял и туда не влезал, дабы чего не напортить =)
У меня так всё построено: есть специальный синглтон-класс который хранит в себе все серверные методы с которыми я работаю (как сдк так и мои запросы через AFNetworking), в нём я создал property VKRequest'a которое пересоздаю в каждом серверном методе. 

До OrderedDictionary *preparedParameters и _methodParameters я правда не добрался. 
Вероятно они какую-то дополнительную нагрузку создают. Но столь мизерную что это несущественно.

**Comment by TullerVal** [comment]
Дело не в нагрузке.
_methodParameters хранит параметры запроса
 OrderedDictionary *preparedParameters хранит _подготовленные_ параметры запроса. Т.е. те, которые в сам NSRequest отправляются. И если это всё не чистить, то в один запрос могут попасть параметры прошлого запроса.

так ты пересоздаешь обьект VKRequest? Как в этом случае  старый VKRequest удаляется?
Я повторно использую запросы (с новыми параметрами), как оно будет насчет памяти скажу завтра.
