### ISSUE TITLE
Авторизация, модальное окно, нет кнопки "Закрыть"

### ISSUE THREAD

**Issue by ItsTipTop** [VKCOM/vk-ios-sdk#184]
![ios simulator screen shot 3 2015 17 49 20](https://cloud.githubusercontent.com/assets/1473763/6464789/c09161b8-c1cd-11e4-849d-1572c0be224c.png)

**Comment by Dreddik** [comment]
Не добавлен VKSdkResources.bundle в проект

**Comment by ItsTipTop** [comment]
Добавлял sdk c помощью pods.. Попробуй в ручную bundle добавить
