### ISSUE TITLE
Redirect from VK application to source application

### ISSUE THREAD

**Issue by jogshardik** [VKCOM/vk-ios-sdk#185]
Hey thanks for posting the application it is very usefull to many peoples.
I have use this app for login with VK and it is working fine till i haven't install the vk application in my iphone when i have install vk application in my iphone and then i tap on button in my app for "login with VK" it redirects me to the vk application and when i successfully login there then also i am not coming back to my application. Can you help me in that

**Comment by Dreddik** [comment]
Check correctness of your app url-scheme for "VK"
https://github.com/VKCOM/vk-ios-sdk#setup-url-schema-of-your-application

**Comment by jogshardik** [comment]
I have follow the same steps for the url scheme you have describe in the sdk and from the vk developer site but still i am redirected to the VK application and not getting back to my application after login.

**Comment by Dreddik** [comment]
May I see your `Info.plist` and initialization code?

**Comment by jogshardik** [comment]
Ya sure i am posting here.
![screen shot 2015-03-10 at 11 41 30 pm](https://cloud.githubusercontent.com/assets/5706665/6581786/079eeee8-c77f-11e4-9f68-f211f90640cb.png)

Here is the initilization code.

    SCOPE = @[VK_PER_FRIENDS, VK_PER_WALL, VK_PER_AUDIO, VK_PER_PHOTOS, VK_PER_NOHTTPS, VK_PER_EMAIL, VK_PER_MESSAGES];
    
    [VKSdk initializeWithDelegate:self andAppId:@"4745786"];
    if ([VKSdk wakeUpSession])
    {
        [self vkstartWorking];
    }

- (IBAction)btnVKTap:(id)sender
{
    [VKSdk authorize:SCOPE revokeAccess:YES];
}

#pragma mark - vk intigration method & delegate

- (void)vkSdkTokenHasExpired:(VKAccessToken *)expiredToken
{
    [self btnVKTap:nil];
}

- (void)vkSdkReceivedNewToken:(VKAccessToken *)newToken
{
    [self vkstartWorking];
}

- (void)vkSdkAcceptedUserToken:(VKAccessToken *)token
{
    [self vkstartWorking];
}

- (void)vkSdkShouldPresentViewController:(UIViewController *)controller
{
    [self presentViewController:controller animated:YES completion:nil];
}

- (void)vkSdkUserDeniedAccess:(VKError *)authorizationError
{
    [[[UIAlertView alloc] initWithTitle:nil message:@"Access denied" delegate:nil cancelButtonTitle:@"Ok" otherButtonTitles:nil] show];
}

- (void)vkSdkNeedCaptchaEnter:(VKError *)captchaError
{
    VKCaptchaViewController *vc = [VKCaptchaViewController captchaControllerWithError:captchaError];
    [vc presentIn:self];
}


-(BOOL)vkSdkIsBasicAuthorization
{
    return YES;
}

**Comment by jogshardik** [comment]
Many Thanks for replying but in the code there is no problem but while creating the application on the vk developer site i have forgot to put sdk setting for my application.
