### ISSUE TITLE
Странное выравнивание ссылки в VKShareDialogController

### ISSUE THREAD

**Issue by ItsTipTop** [VKCOM/vk-ios-sdk#186]
Выглядит так как на айфоне, так и на айпаде.

Было бы лучше показывать ее сразу под текстом или в самом низу окна. (если это не баг, конечно)

![2015-03-05 18 10 31](https://cloud.githubusercontent.com/assets/1473763/6507424/006db19c-c363-11e4-83e6-59818d871fca.png)

**Comment by Dreddik** [comment]
Она должна быть под картинками, видимо картинки не догрузились

**Comment by ItsTipTop** [comment]
Я не прикреплял картинок

**Comment by Dreddik** [comment]
Тогда действительно, странное. Посмотрю

**Comment by ItsTipTop** [comment]
Спасибо!
У меня стоит последняя версия из репозитория
<code>pod 'VK-ios-sdk', :head</code>

**Comment by ItsTipTop** [comment]
Еще вот такое предупреждение в консоли
Parsing <VKUser: 0x7ff59b5d02d0> complete. Warnings: (
    "property exports is parcelable, but data is not"
)
Но, вроде, говорили, что это нормально
