### ISSUE TITLE
v1.1.0 contains old files

### ISSUE THREAD

**Issue by kambala-decapitator** [VKCOM/vk-ios-sdk#187]
гит вообще ни одного различия не показывает при обновлении фреймворка

![screen shot 2015-03-09 at 21 37 51](https://cloud.githubusercontent.com/assets/1557784/6562855/f66440cc-c6a4-11e4-9ef3-53379a663645.png)

**Comment by Dreddik** [comment]
Интересный у вас гит, научился сравнивать бинарные файлы

**Comment by kambala-decapitator** [comment]
картинка не с гита. а вообще гит в состоянии понять различаются файлы или нет.

**Comment by Dreddik** [comment]
Я понял, в чём проблема - конкретно тег 1.1.0 содержит старый файл фреймворка, при обновлении не обновил тег

**Comment by Dreddik** [comment]
Обновил тег

**Comment by kambala-decapitator** [comment]
в репозитории никаких изменений. пушнуть тег не забыл? :)

**Comment by Dreddik** [comment]
Пушнул. Надо просто сделать какой-нибудь такой же forced pull
![2015-03-09 22 54 24](https://cloud.githubusercontent.com/assets/1570382/6563055/46cd030a-c6af-11e4-9944-5b968da15d8f.png)

**Comment by Dreddik** [comment]
Что-нибудь типа `git fetch --tags`

**Comment by kambala-decapitator** [comment]
спасибо, стянул новый тег
