### ISSUE TITLE
Доступ к стене сообщества

### ISSUE THREAD

**Issue by negus9** [VKCOM/vk-ios-sdk#188]
Добрый день! Можно ли получить стену сообщества без авторизации? С браузера же можно читать без авторизации.

**Comment by Dreddik** [comment]
Некоторые методы можно вызывать без авторизации. Не уверен, что среди них есть wall.get

**Comment by negus9** [comment]
Да. wall.get без авторизации недоступен. Но можно ли как нибудь это обойти? В приложении необходимо показывать новости из паблика в вк. Но теперь ему необходимо авторизовываться перед использованием приложения, что не очень удобно.

**Comment by Dreddik** [comment]
Так а вы пробовали вызвать метод?
Я попробовал из браузера незалогиненным вызвать и получил нормальный ответ
https://api.vk.com/method/wall.get?v=5.0&owner_id=-1

**Comment by negus9** [comment]
Спасибо! Работает! Раньше приходила ошибка что не авторизован.
