### ISSUE TITLE
SDK options is undefined

### ISSUE THREAD

**Issue by Friend-LGA** [VKCOM/vk-ios-sdk#190]
Если установлено приложение VK, при авторизации через VKShareDialogController в открывшемся VK появляется пустая белая страница с текстом:
```
{
    "error" : "invalid_request",
    "error_description" : "sdk options is undefined"
}
```
Если VK не установлено, то авторизация успешно проходит внутри VKShareDialogController'a.
В чем проблема я так осознать и не смог, все схемы указаны верно, инициализация VKShareDialogController выглядит так:
```
VKShareDialogController *shareDialog = [VKShareDialogController new];
shareDialog.text         = text;
shareDialog.shareLink    = [[VKShareLink alloc] initWithTitle:text link:link];
```

Версия SDK 1.1.0, версия приложения VK самая свежая 2.2, версия iOS 8.2

**Comment by Dreddik** [comment]
А при обычной авторизации всё норм? Разработчики серверной части говорят, что это означает, что bundle_id оказался nil при авторизации

**Comment by Friend-LGA** [comment]
Ну что значит при обычной? Я в VKSdk поменял метод авторизации таким образом:
```
+ (void)authorize:(NSArray *)permissions
     revokeAccess:(BOOL)revokeAccess
       forceOAuth:(BOOL)forceOAuth
{
    [self authorize:permissions
       revokeAccess:revokeAccess
         forceOAuth:forceOAuth
              inApp:YES];
}
```
VKShareDialogController стал вызывать авторизацию внутри самого себя, и все отлично работает.

**Comment by Dreddik** [comment]
У вас 8.2 релизная версия, не бета?
Можете проверить на тестовых приложениях, приходит ли в метод
`- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation`
sourceApplication вашего приложения, не равен ли он nil?

**Comment by Friend-LGA** [comment]
Проверю, немного позже, на неделе постараюсь найти время

**Comment by petropavel13** [comment]
@Dreddik у меня подобная проблема.

Вот так пытаюсь авторизоваться:
```objc
[VKSdk authorize:@[VK_PER_OFFLINE]];
```

Вот тут:
```objc
+ (void)authorize:(NSArray *)permissions
     revokeAccess:(BOOL)revokeAccess
       forceOAuth:(BOOL)forceOAuth
            inApp:(BOOL)inApp
          display:(VKDisplayType)displayType
```
Формируется вот такой урл (id изменен):
Printing description of urlToOpen:
vkauthorize://authorize?client_id=1234567&scope=offline&sdk_version=1.1.7&revoke=0

Вот тут:
```objc
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
```
Получаю следующий ответ:
Printing description of url:
vk1234567://authorize#error=access_denied&error_reason=sdk_error&error_description=sdk%2520options%2520is%2520undefined
Printing description of sourceApplication:
com.vk.vkhd

ЧЯНДТ?

**Comment by DmIvanov** [comment]
@Dreddik 2 дня уже бьюсь с такой же проблемой при интеграции СДК в новое приложение.
Инициализирую СДК, запрашиваю авторизацию, СДК формирует урл (при наличии приложения: vkauthorize://authorize?scope=notify%2Cfriends%2Cphotos%2Coffline&revoke=1&sdk_version=1.2.2&client_id=ххххх - айдишник приложения убрал). Переходим в вк-приложение и возвращаемся оттуда с вышеописанной ошибкой access_denied.

 Старые приложения работают хорошо на той же версии СДК (1.2.2). Ссылка авторизации вк-приложения идентична (за исключением другого айдишника моего приложения). Интерсно, что проблема только при авторизации через vk-приложение, через браузер всё проходит корректно - авторизация проходит, в приложение возвращается вк-токен. Проверил на разных девайсах, под разными вк-аккаунтами. 

Буду рад любой помощи

**Comment by DmIvanov** [comment]
Разобрался - в админке приложения не привязан был bundle id. Банально.. не подумал об этом всерьёз, потому что работала авторизация через сафари, почему-то при авторизации через браузер это не учитывается.
