### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by Friend-LGA** [VKCOM/vk-ios-sdk#191]
Когда начинали делать SDK то вы сделали возможность выбора авторизации
```
+ (void)authorize:(NSArray *)permissions revokeAccess:(BOOL)revokeAccess forceOAuth:(BOOL)forceOAuth inApp:(BOOL)inApp;
```
Но теперь когда у нас есть VKShareDialogController, выбор авторизации стал не возможен, хотя практически вся логика в SDK для этого есть.

Ладно бы все было гладко, у меня вчера возникла проблема, из-за которой я так и не смог авторизоваться через VK (issue по этому поводу уже добавил). Решить эту проблему у меня так и не получилось. Пришлось писать приватный класс чтобы заставать VKSdk авторизоваться в safari. 

Если безопасность данных пользователя для вас так важна, то может быть стоит вообще убрать возможность авторизации внутри webView, и добавить выбор типа авторизации хотябы через VK или в Safari
```
typedef enum : NSUInteger 
{
    VKAuthorizationTypeVkApp  = 0,
    VKAuthorizationTypeSafari = 1
} 
VKAuthorizationType;

+ (void)authorize:(NSArray *)permissions revokeAccess:(BOOL)revokeAccess forceOAuth:(BOOL)forceOAuth authType:(VKAuthorizationType)authType;

VKShareDialogController *shareDialog = [VKShareDialogController new];
shareDialog.authType = ... ;
```
И еще хотел спросить как указывать permissions при авторизации через VKShareDialogController?

Может быть вообще стоит вынести их в инициализацию SDK, к примеру:
```
+ (void)initializeWithDelegate:(id <VKSdkDelegate> )delegate andAppId:(NSString *)appId permissions:(NSArray *)permissions;
```

**Comment by Dreddik** [comment]
Основная идея разных методов авторизации для SDK - возможность пройти модерацию в App Store разными путями. Изначально планировалось совсем отказаться от webview в сторону VK app и Safari. Во-первых, потому что они в большинстве случаев отдадут вам уже залогиненого клиента, во-вторых, потому что это гораздо безопаснее для пользователя, чем возможность потенциального перехвата персональных данных. Затем вернули webview, так как apple не позволяет при первой попытке логина перекидывать в Safari.
Для Share-диалога проблема reject неактуальна, так что не вижу причин отображать пользователю webview.

**Comment by Friend-LGA** [comment]
Странное дело, тот же Google+ сразу же кидает в сафари, это apple типа так на русских давит?))

А на счет Share-диалога не понял. Как уже писал выше не мог авторизоваться через VK app из-за ошибки, а заказчику нужно было продемонстрировать работу шаринга в приложении. Значит у меня какие пути? 
Раньше у меня для авторизации были отдельные методы написаны, которые вызывали:
```
+ (void)authorize:(NSArray *)permissions revokeAccess:(BOOL)revokeAccess ...
```
И если бы авторизация работала по старому, я бы жестко указал авторизацию inApp = YES и решил проблему.
Но теперь то авторизация происходит через VKShareDialogController и он внутри все обрабатывает, следовательно я не могу выбрать способ авторизации. Так почему бы возможность этого выбора не добавить?

И еще раз спрашиваю, как указывать permissions при авторизации через VKShareDialogController?

**Comment by Dreddik** [comment]
Permissions указываются через проперти диалога - requestedScope.

**Comment by Dreddik** [comment]
Добавил флаг для Share-диалога 
`@property (nonatomic, assign) BOOL authorizeInApp;`

**Comment by Friend-LGA** [comment]
Ок, спасибо! :)
