### ISSUE TITLE
[VKAccessToken getAccessToken] vs [VKAccessToken tokenFromDefaults]

### ISSUE THREAD

**Issue by vmalov** [VKCOM/vk-ios-sdk#192]
Кодец:
```objective-c
NSLog(@"%@",[VKAccessToken tokenFromDefaults:@"VK_ACCESS_TOKEN_DEFAULTS_KEY_DONT_TOUCH_THIS_PLEASE"]);
NSLog(@"%@",[VKSdk getAccessToken]);
```

Результат:
```objective-c
2015-03-19 17:18:23.044 App[1111:222] <VKAccessToken: 0x71111110>
2015-03-19 17:18:26.096 App[1111:222] (null)
```
Что делаю не так, либо это SDK?

**Comment by Dreddik** [comment]
А что вы хотите получить?

**Comment by vmalov** [comment]
@Dreddik  userId

**Comment by Dreddik** [comment]
попробуйте [VKSdk wakeUpSession]

**Comment by vmalov** [comment]
@Dreddik оно возвращает `YES`
Кстати, wakeUpSession берет токен из defaults

Дополнительно скажу, что в целом при таком раскладе API говорит, что не отдали access_token.

**Comment by Dreddik** [comment]
Да что вы хотите-то?
Вы делаете [VKSdk wakeUpSession], который достаёт токен из defaults, и запоминает его, потом дёргаете [VKSdk getAccessToken] и оттуда берёте user_id
