### ISSUE TITLE
VK_API_OWNER_ID - выдает ошибку - symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by diretix** [VKCOM/vk-ios-sdk#195]
в общем пишу прогу на swift. подключил sdk, все проверил, все работает - на users().get() ответ приходит. но вот на запрос - var getWall = VKRequest(method: "wall.get", andParameters: [VK_API_OWNER_ID: "-42800749"], andHttpMethod: "GET") - ругается на строчку VK_API_OWNER_ID. с ошибкой - symbol(s) not found for architecture arm64. уже много чего перепробовал из гугла но не помогает(. и если поставить вместо той строчки просто nil то все запускается но ответ то похожий приходит - null. как можно это исправить? сроки слегка поджимают, да и уже все остальное почти дописал, самое значительное осталось только это.

**Comment by Dreddik** [comment]
Если честно, не знаю, как константы бриджатся в swift, проверю

**Comment by Ryskalo** [comment]
С такой же проблемой уже второй день сижу. Нашли решение?
