### ISSUE TITLE
Не подхватывается scope

### ISSUE THREAD

**Issue by baydet** [VKCOM/vk-ios-sdk#197]
При авторизации [VKSdk authorize:@[VK_PER_WALL, VK_PER_PHOTOS] revokeAccess:YES] через приложение не хочет подхватываться scope. То есть вижу что-то такое.
![img_0666](https://cloud.githubusercontent.com/assets/1755124/6944731/f9455d7a-d89d-11e4-9556-c0c7c4d4896c.PNG)

При авторизации через webView такой проблемы не наблюдаю. С чем это может быть связано?

В приложении-примере, к слову, такая же ситуация.

**Comment by Dreddik** [comment]
А на айфоне нормально? Похоже, проблема в iPad клиенте при определённых scope

**Comment by baydet** [comment]
Такая же проблема и на iPhone 6.

**Comment by Dreddik** [comment]
Similar to #210
