### ISSUE TITLE
Cannot authorise

### ISSUE THREAD

**Issue by euroboy** [VKCOM/vk-ios-sdk#198]
I'm trying to authorise to VK from my app using the following code:
[VKSdk authorize:@[VK_PER_AUDIO]];

Then I add my credentials and press Allow the permissions, after this a message appears (see attached screenshot), and I'm switched to Safari, where I can successfully authorise. How to solve this?

![img_0229](https://cloud.githubusercontent.com/assets/6330272/6945126/3c0d8b80-d8a0-11e4-9483-543522e344a9.PNG)

**Comment by baydet** [comment]
There is pull-request for this issue
https://github.com/VKCOM/vk-ios-sdk/pull/196

**Comment by ren6** [comment]
I have the same issue

**Comment by Diwann** [comment]
same for me :( 
-> https://vk.com/support?act=show&id=16092669

**Comment by Dreddik** [comment]
Try to apply #196

**Comment by Diwann** [comment]
@Dreddik : not working for me ... 
The patched code is not called for authentification with the native VK app.

**Comment by Dreddik** [comment]
@Diwann I lost the sense of bug, because someone is writing about webview auth and other ones - about VK app. Do you have same bug in VK app?

**Comment by Diwann** [comment]
For me, and I think for the orignal author : euroboy, it is working with OAuth + safari, but it's not working with the VK app installed.

**Comment by ren6** [comment]
euroboy was talking about modal webview controller. #196 has fixed the issue

**Comment by Diwann** [comment]
sorry but the text is not ambigous : "after this a message appears (see attached screenshot), and I'm switched to Safari". 
The error message appears before switching to safari. 

For me, I have the same error but I am not redirected to safari so I stay on the VK app. 

![img_1041](https://cloud.githubusercontent.com/assets/784023/6968672/c96c6b54-d968-11e4-918a-d0c425bdc579.PNG)

**Comment by ren6** [comment]
Diwann, you have another error. You didn't set up Bundle ID in VK app settings.

**Comment by Diwann** [comment]
of course not. I have all set up on : http://vk.com/editapp?id=XXXXX&section=options 

![2015-04-03_18_49_03](https://cloud.githubusercontent.com/assets/784023/6985307/3aeb3958-da32-11e4-9df2-e491e6e831d9.png)

**Comment by Diwann** [comment]
and it was working for severals months until 2 weeks ago

**Comment by iSpartak** [comment]
same issue here. used to work for more then a year. decided to update vk lib (better I would not do this!) and now I am getting sdk_bundle is incorrect. No code change except new vk sdk :(

**Comment by Dreddik** [comment]
I don't think this is library issue

**Comment by Diwann** [comment]
Indeed, I think it's a platform issue, as it's not working anymore if I downgrade the library ...

**Comment by Dreddik** [comment]
Please, attach a code + user_ids you trying to authorize + screenshots of result here. Will try to debug

**Comment by Diwann** [comment]
The url call : 
vkauthorize://authorize?client_id=4314968&scope=email%2Cfriends%2Coffline&sdk_version=1.1.5&revoke=1

doesn't work with my user id : 250884458 nor all the others I tried

**Comment by iSpartak** [comment]
@Dreddik just wonder if there is any update with this issue?

**Comment by bimawa** [comment]
some bug.

**Comment by Dreddik** [comment]
@iSpartak I asked for debug information not only @Diwann :
<blockquote>Please, attach a code + user_ids you trying to authorize + screenshots of result here. Will try to debug</blockquote>

**Comment by Diwann** [comment]
To reproduce, copy/paste the following authorization url to a device with the vk app installed : 
vkauthorize://authorize?client_id=4314968&scope=email%2Cfriends%2Coffline&sdk_version=1.1.5&revoke=1 

I have tried with several devices and several user id, and non worked.

**Comment by Dreddik** [comment]
@Diwann of course I can easy reproduce without your application bundle id, just because for any other application it will be wrong. Can you share bundle id?

**Comment by Diwann** [comment]
app id : 341329033  
bundle id : com.comuto.comuto

**Comment by Dreddik** [comment]
@Diwann I see normal authorization screen. Please, double check your debug bundle id
![img_1834](https://cloud.githubusercontent.com/assets/1570382/7068549/cb1fc4c8-dedb-11e4-9e66-a35ed5025abd.PNG)

**Comment by Diwann** [comment]
where can I see the debug bundle id  ?

**Comment by Dreddik** [comment]
@Diwann I mean the bundle id you use while checking authorization

**Comment by Diwann** [comment]
Yes, thanks ! 
you're right, I was using my development bundle id to test it. 

and by the way, this would have been avoided by the ability to connect more than one bundle id to an app (or having a wildcard) : 
https://github.com/VKCOM/vk-ios-sdk/issues/101

**Comment by charles0126dev** [comment]
![img_7978](https://cloud.githubusercontent.com/assets/10875536/10935853/c81e0612-8323-11e5-8c24-da55433e7743.jpg)
When I was requesting for authorization, the safari alert me of this. How can I fix it?
