### ISSUE TITLE
Как распарсить VKResponse?

### ISSUE THREAD

**Issue by sartemd174** [VKCOM/vk-ios-sdk#20]
Пока еще не силен в iOS разработке и столкнулся с небольшой проблемой: хочу сделать запрос на wall.get и взять текст допустим со 5 по счету новости.

```
VKRequest * getWall = [VKRequest requestWithMethod:@"wall.get" andParameters:@{VK_API_OWNER_ID : @"1"} andHttpMethod:@"GET"];
[getWall executeWithResultBlock:^(VKResponse * response) {
     NSLog(@"%@",response.json[5][@"text"]);//ошибка
    } errorBlock:^(NSError * error) {
        if (error.code != VK_API_ERROR) {
            [error.vkError.request repeat];
        }
        else {
            NSLog(@"VK error: %@", error);
        }
    }];
```

В месте,помеченном комментарием вываливается эксепшн `[__NSCFDictionary objectAtIndexedSubscript:]: unrecognized selector sent to instance 0xa5911c0`

**Comment by AlexBlack559** [comment]
Что-то совсем не очевидно. Почему тогда это не `response.dictionary`? Это сильно вводит в заблуждение ведь это совсем не json.
