### ISSUE TITLE
VKShareDialogController появляется полупрозрачным

### ISSUE THREAD

**Issue by Nubaslon** [VKCOM/vk-ios-sdk#200]
Добрый день!

Использую тестовый код - 

VKShareDialogController * shareDialog = [VKShareDialogController new]; //1
    shareDialog.text = @"This post created using #vksdk #ios"; //2
    shareDialog.vkImages = @[@"-10889156_348122347",@"7840938_319411365",@"-60479154_333497085"]; //3
    shareDialog.shareLink = [[VKShareLink alloc] initWithTitle:@"Super puper link, but nobody knows" link:[NSURL URLWithString:@"https://vk.com/dev/ios_sdk"]]; //4
    [shareDialog setCompletionHandler:^(VKShareDialogControllerResult result) {
        [_socialVC dismissViewControllerAnimated:YES completion:nil];
    }]; //5
    [_socialVC presentViewController:shareDialog animated:YES completion:nil]; //6

Окошко показывается, но с прозрачной шапкой.
VKSdkResources.bundle копировать в проект пробовал, не помогло( 

![img_0867](https://cloud.githubusercontent.com/assets/5019729/6960536/06bd56d6-d92c-11e4-9ccf-9b9184305440.PNG)

**Comment by Dreddik** [comment]
У вас какая-то кастомная категория для UINavigationBar ломает его

**Comment by Nubaslon** [comment]
Благодарствую! Совет натолкнул на пару мыслей, разобрался! Вернул шапку
