### ISSUE TITLE
VKShareDialogController загружаемая картинка пропадает

### ISSUE THREAD

**Issue by Nubaslon** [VKCOM/vk-ios-sdk#201]
Добрый день!

Пытаюсь показать VKShareDialogController, с загруженной картинкой. Картинку беру из ассетов Но при показе этого окошка картинка появляется и сразу же исчезает. Что можно такое быть?
 Делаю так - 

VKShareDialogController * shareDialog = [VKShareDialogController new];
    shareDialog.text         = NSLocalizedString(@"social", nil);
    shareDialog.uploadImages = @[[VKUploadImage uploadImageWithImage:[UIImage imageNamed:@"logo_100"] andParams:[VKImageParameters pngImage]]];
    shareDialog.shareLink    = [[VKShareLink alloc] initWithTitle:@"Test" link:[NSURL URLWithString:@"http://vk.com"]]; //4
 [shareDialog setCompletionHandler:^(VKShareDialogControllerResult result) {
        [_socialVC dismissViewControllerAnimated:YES completion:nil];
}]; //5
    [_socialVC presentViewController:shareDialog animated:YES completion:nil];

**Comment by Nubaslon** [comment]
up

**Comment by Dreddik** [comment]
У вас при авторизации передаётся scope photos?

**Comment by Nubaslon** [comment]
это место?

- (void)authWithFinishBlock:(dispatch_block_t)finishBlock {
    //инициализируем SDK
    [VKSdk forceLogout];
    
    [VKSdk initializeWithDelegate:self andAppId:VK_CONSUMER_KEY];
    [[VKSdk instance] setDelegate:self];
    
    if ([self isLogin]) {
        dispatch_async(dispatch_get_main_queue(), finishBlock);
    } else {
        //авторизация
        [VKSdk authorize:@[VK_PER_WALL, VK_PER_OFFLINE,VK_PER_MESSAGES] revokeAccess:YES forceOAuth:YES inApp:YES display:VK_DISPLAY_IOS];         
    }
}

**Comment by Dreddik** [comment]
Да, вам нужен ещё VK_PER_PHOTOS

**Comment by Nubaslon** [comment]
Да помогло, благодарю
