### ISSUE TITLE
Авторизация через модальное окно c параметром inApp

### ISSUE THREAD

**Issue by vani2** [VKCOM/vk-ios-sdk#204]
При авторизации с параметром `inApp = true`, авторизация заканчивается на странице с текстом  *Пожалуйста, не копируйте данные из адресной строки...* и метод `- (void)vkSdkReceivedNewToken:(VKAccessToken *)newToken` не вызывается.

Проблема в `VKAuthorizeController.h`

      -(BOOL)webView:(UIWebView *)webView
      shouldStartLoadWithRequest:(NSURLRequest *)request
      navigationType:(UIWebViewNavigationType)navigationType

Проверка `[urlString hasPrefix:REDIRECT_URL]` не проходит, т.к. `urlString = http://oauth.vk.com/blank.html#access_token=...`, а `REDIRECT_URL = https://oauth.vk.com/blank.html`.

**Comment by Friend-LGA** [comment]
+1 Тоже самое
