### ISSUE TITLE
Не работает аутентификация через WebView

### ISSUE THREAD

**Issue by StoneFalcon** [VKCOM/vk-ios-sdk#205]
Здравствуйте!
При первом вызове 

NSArray *permissions = @[VK_PER_FRIENDS, VK_PER_WALL, VK_PER_PHOTOS, VK_PER_NOHTTPS, VK_PER_EMAIL, VK_PER_MESSAGES];
		[VKSdk authorize:permissions];

Показывает окно UIWebView. Функции делегата: vkSdkAuthorizationAllowFallbackToSafari и vkSdkIsBasicAuthorization в делегате не прописаны и работают по умолчанию.
После ввода логина и пароля показывает сообщение: Пожалуйста, не копируйте данные из адресной строки для сторонних сайтов... При этом показывает только кнопку Cancel и не дает залогиниться. URL схема прописана. На второй вызов стартует Safari и все работает нормально, логин проходит (при повторном вводе в сафари).

**Comment by Dreddik** [comment]
Сегодня обновили sdk, проверьте

**Comment by StoneFalcon** [comment]
Благодарю! Все работает теперь.
Я так понимаю теперь нормально можно использовать конфигурацию:

- (BOOL)vkSdkAuthorizationAllowFallbackToSafari{return NO;}
- (BOOL)vkSdkIsBasicAuthorization{return YES;}

Чтобы не иметь проблем с реджектом от эпл? Спасибо!

**Comment by Dreddik** [comment]
Да, должно быть достаточно
