### ISSUE TITLE
[VKSdk wakeUpSession] Не работает как ожидается

### ISSUE THREAD

**Issue by StoneFalcon** [VKCOM/vk-ios-sdk#206]
Добрый день!
После инициализации API вызываю 
if (  [VKSdk wakeUpSession]  )
	{
		//Start working
	}
	else
	{
		NSArray *permissions = @[VK_PER_FRIENDS, VK_PER_WALL, VK_PER_PHOTOS, VK_PER_NOHTTPS, VK_PER_EMAIL, VK_PER_MESSAGES];
		[VKSdk authorize:permissions];
	}

Все работает нормально до тех пор, пока не Завершаю все сеансы на странице приложения в браузере. Токен сбрасывается, но wakeUpSession возращает YES и логин не происходит, так же не выполняются и другие запросы, пишет, что ошибка сессии.

**Comment by Dreddik** [comment]
Он работает как и ожидается. Он проверяет, что локальная сессия существует и не протухла.
При этом запроса не происходит, поэтому SDK не знает о том, что сессия была убита.
Однако, через некоторое время после `wakeUpSession` должна прийти ошибка токена, в соответствующий метод делегата

**Comment by StoneFalcon** [comment]
А как правильно обработать такое поведение при работе с VKShareDialogController. Если сессию сбросили на сайте, то при вызове создании стандартного Share Dialog он показывается с ошибками (скриншот ниже прилагаю). При этом ошибка токена не приходит. Можно ли как-то в этом случае проверить (до того, как показывать диалог), что токен уже не живой и сделать принудительный логаут, тогда при показе диалога, пользователя попросят авторизоваться и все будет хорошо?

![2015-04-22 22 00 00](https://cloud.githubusercontent.com/assets/7931008/7283043/6a55e904-e93c-11e4-8add-5714f2bed7d1.png)

**Comment by Dreddik** [comment]
Хороший вопрос, поработаю над поведением
