### ISSUE TITLE
VKUploadImage‘s uploadImageWithImage method

### ISSUE THREAD

**Issue by zhangyu528** [VKCOM/vk-ios-sdk#207]
+ (instancetype)uploadImageWithImage:(UIImage*)image andParams:(VKImageParameters *)params;
when the image is nil,but return the uploading is not nil.Then, shareDlg.uploadImages = [NSArray arrayWithObject:uploadImg] is exception, CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [nan 0; nan 100]'

**Comment by zhangyu528** [comment]
sading...

**Comment by Dreddik** [comment]
Why you don't check a image for nil?
I will fix it after I find a time for it
