### ISSUE TITLE
Pods и use_frameworks!

### ISSUE THREAD

**Issue by ItsTipTop** [VKCOM/vk-ios-sdk#209]
Если использовать флаг use_frameworks!, который появился недавно в cocoa pods, не подцепляются ресурсы (например, VKSdkResources.bundle), приходится вручную копировать его в проект.
Плюс сам проект не компилится: <code>#import "NSString+MD5.h"</code> нужно заменить на <code>#import \<NSString+MD5.h\> </code> в файле VKRequest.m
Вот тут подробнее написано про то, как это делается:
http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

**Comment by Dreddik** [comment]
Запушил версию 1.1.10, ресурсы подхватываются

**Comment by ItsTipTop** [comment]
@Dreddik Супер! Спасибо)
