### ISSUE TITLE
Не открывается во время авторизации VKapp, всегда открывается Safari 

### ISSUE THREAD

**Issue by ArtemGoryunov** [VKCOM/vk-ios-sdk#21]
На устройстве установлено приложение VKapp, пользователь авторизирован.
Вызываю

```
[VKSdk initializeWithDelegate:self andAppId:@"*******"];
[VKSdk authorize:@[VK_PER_FRIENDS, VK_PER_OFFLINE, VK_PER_NOTIFY]  revokeAccess:YES];
```

всегда открывается Safari.

**Comment by 4tuneTeller** [comment]
2019 год, снова такая проблема?) Или я что-то делаю не так? 
```swift
let sdkInstance = VKSdk.initialize(withAppId: vkId)
sdkInstance?.register(self)
sdkInstance?.uiDelegate = self
```
Всегда открывается WebView, через него все нормально работает, но хотелось бы чтобы использовалось приложение, если оно установлено.
