### ISSUE TITLE
Ошибка VKError (code: 15) при установленном приложении "Vk for iPad"

### ISSUE THREAD

**Issue by DmitriyG1** [VKCOM/vk-ios-sdk#210]
После отправки запроса к VK API приходит ошибка VKError. 

В логе объект ошибки выглядит таким образом:
[VKError: 0x16eba740; API error {code: 15; message: Access denied: no access to call this method;}]
Поля в NSError
error.domain: VKSdkErrorDomain
error.code: -101

Происходит только, если установлено приложение "Vk for iPad". Если удалить приложение "Vk for iPad", то работает нормально. В симуляторе запрос работает нормально.

Проверял на устройстве iPad mini, iOS 8.3
Версия VK-ios-sdk: 1.1.6

Пример кода авторизации
 [VKSdk initializeWithDelegate:self andAppId:@"..."];
        NSArray *scope = @[VK_PER_AUDIO];
        [VKSdk authorize:scope];

При этом вызывается метод делегата vkSdkReceivedNewToken
[VKSdk  isLoggedIn] - показывает "YES"

Запрос к API
[VKApi requestWithMethod:@"audio.get" andParameters:params andHttpMethod:@"GET"];

**Comment by alexbat98** [comment]
Такая же ерунда.

**Comment by Dreddik** [comment]
Похоже, проблема в клиенте, связанная с iOS 8.3
Остаётся только ждать обновления клиента, которое, надеемся, скоро пропустят

**Comment by DmitriyG1** [comment]
Пока проблема решается авторизацией c принужденным вызовом oauth:

[VKSdk authorize:scope revokeAccess:NO forceOAuth:YES];

**Comment by antigp** [comment]
C VK_PER_PHOTOS тоже cамое

**Comment by Dreddik** [comment]
Должно быть всё хорошо
