### ISSUE TITLE
Проблема Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by Ryskalo** [VKCOM/vk-ios-sdk#211]
Подключил с помощью cocoapods VKSDK, пишу на Swift.
var vkuserid:NSString = "......"  
        var request1 = VKApi.friends().get([VK_API_USER_ID: vkuserid, VK_API_ORDER : "name"])

выдает ошибки 

ld: warning: directory not found for option '-L/Users/.../build/Debug-iphoneos'
Undefined symbols for architecture x86_64:
  "_VK_API_ORDER", referenced from:
      __TFC6VKVamp14ViewController21vkSdkReceivedNewTokenfS0_FCSo13VKAccessTokenT_ in ViewController.o
  "_VK_API_USER_ID", referenced from:
      __TFC6VKVamp14ViewController21vkSdkReceivedNewTokenfS0_FCSo13VKAccessTokenT_ in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Dreddik** [comment]
То же, что и #195
Пока не разбирался

**Comment by Ryskalo** [comment]
Есть какая-нибудь альтернатива кроме использования http-запросов?

**Comment by Dreddik** [comment]
Есть, вместо констант указывать значения, например VK_API_USER_ID = "user_id"
