### ISSUE TITLE
Загрузка изображения на сервер

### ISSUE THREAD

**Issue by Frinkey** [VKCOM/vk-ios-sdk#214]
+ (VKRequest *)uploadWallPhotoRequest:(UIImage *)image
                           parameters:(VKImageParameters *)parameters
                               userId:(NSInteger)userId
                              groupId:(NSInteger)groupId;

Возвращает: Error Domain=VKSdkErrorDomain Code=-101 "One of the parameters specified was missing or invalid: photos_list is invalid" UserInfo=0x78762aa0 {NSLocalizedDescription=One of the parameters specified was missing or invalid: photos_list is invalid, VkErrorDescriptionKey=<VKError: 0x78763450; API error {code: 100; message: One of the parameters specified was missing or invalid: photos_list is invalid;}>}

В image лежит UIImage (генерируемый UIGraphicsBeginImageContextWithOptions)
В параметрах [VKImageParameters pngImage]
В userId - userId из токена [VKSdk getAccessToken]
GroupId - 0

Пробовал сохранять изображение в файл (png), считывать его и загружать - результат одинаковый.

Метод используется для предварительной загрузки изображения на сервер, а затем это изображение постится на стену пользователю приложения.
Причем такую ошибку возвращают не все изображения. Единственное, которое не загружается, на данный момент, имеет разрешение 2560(и более) × 129.

Буквально пару недель назад все работало и загружалось как ожидается.

Изображения шириной более 10.000px вообще можно загружать таким образом?

**Comment by Dreddik** [comment]
Говорят, что зависит от ширины, плюс ещё такие условия:
* сумма сторон меньше 14к
* разница сторон не более 20x
