### ISSUE TITLE
VkResponce приходит null

### ISSUE THREAD

**Issue by diretix** [VKCOM/vk-ios-sdk#215]
вот в общем наладил все, точно по туториалу с офф сайта.
далее создаю запрос:
![cvb](https://cloud.githubusercontent.com/assets/11671322/7582417/8e5d9558-f88d-11e4-828f-c82914350d45.PNG)
но ответ приходит null.

**Comment by AlexanderFrolov** [comment]
Как минимум, переменные response и err можно не создавать

**Comment by diretix** [comment]
Во, заработало! Спасибо AlexanderFrolov!
