### ISSUE TITLE
App rejected by Apple because of 10.6

### ISSUE THREAD

**Issue by igorvlassov** [VKCOM/vk-ios-sdk#216]
Здравствуйте!

Эппл режектнула мое приложение по следующей причине:
10.6 - Apple and our customers place a high value on simple, refined, creative, well thought through interfaces. They take more work but are worth it. Apple sets a high bar. If your user interface is complex or less than very good, it may be rejected

10.6 Details

Also, we noticed an issue in your app that contributes to a lower quality user experience than Apple users expect. Specifically, 

- a web page in mobile Safari opens for logging in with VKontakte account, then returns the user to the app. The user should be able to log in without opening Safari first.

Подскажите, пож., как обойти данную проблему. Сейчас для логина используется 
    [VKSdk authorize:SCOPE];

**Comment by SoundBlaster** [comment]
По идее их удовлетворит открытие WebView с этой же страницей в модальном контроллере приложения. Но вот как это сделать, я сейчас не подскажу.

**Comment by igorvlassov** [comment]
Придется, видимо, исходники смотреть. Через oauth с нуля что-то не хочется реализовывать.

**Comment by Dreddik** [comment]
В VKSDKDelegate есть опциональный метод
https://github.com/VKCOM/vk-ios-sdk#pre-requirements
Обсуждалось в #64

**Comment by igorvlassov** [comment]
СПАСИБО!!!

**Comment by ichents** [comment]
Hi,

I'm doing what you suggested and the authorization opens in a modal window but after i log in, i see the next message:

Пожалуйста, не копируйте данные из адресной строки для сторонних сайтов. Таким образом Вы можете потерять доступ к Вашему аккаунту.

What am i missing? I can't login...

BTW - i don't speak Russian so it's pretty hard to understand... :(

Thanks in advance,
Chen

**Comment by Dreddik** [comment]
@ichents try to update sdk to newest version

**Comment by ichents** [comment]
It worked!!
Thank you very much!!

SPASIBA :)
