### ISSUE TITLE
Не работает ShareDialog

### ISSUE THREAD

**Issue by StoneFalcon** [VKCOM/vk-ios-sdk#217]
Делаю вот так (как в документации):
VKShareDialogController * shareDialog = [VKShareDialogController new]; //1 
shareDialog.text = @"This post created using #vksdk #ios"; //2 
shareDialog.vkImages = @[@"-10889156_348122347",@"7840938_319411365",@"-60479154_333497085"]; //3 
shareDialog.shareLink = [[VKShareLink alloc] initWithTitle:@"Super puper link, but nobody knows" link:[NSURL URLWithString:@"https://vk.com/dev/ios_sdk"]]; //4 
[shareDialog setCompletionHandler:^(VKShareDialogControllerResult result) { 
    [self dismissViewControllerAnimated:YES completion:nil]; 
}]; //5 
[self presentViewController:shareDialog animated:YES completion:nil]; //6

ShareDialog появляется, просит выполнить логин, после логина пишет, что требуются дополнительные разрешения, вхожу, нажимаю разрешить, но диалог продолжает писать про extra permissions.

**Comment by Dreddik** [comment]
Можно закрывать?

**Comment by StoneFalcon** [comment]
Я не успел проверить, но думаю, что можно, там решение-то было, спасибо
