### ISSUE TITLE
App rejected by Apple because of 22.4

### ISSUE THREAD

**Issue by gregoryvit** [VKCOM/vk-ios-sdk#218]
Отказали в публикации по пункту 22.4 - Apps that enable illegal file sharing will be rejected

22.4 Details

Your app falls into a category of apps that are often used for illegal file sharing, which does not comply with the App Store Review Guidelines. 

Streaming music from VK is not appropriate for the App Store. We’ve attached screenshot(s) for your reference.

Судя по приложенному скриншоту доступ к странице с аудиозаписями был получен из модального окна.

![temp rnlzpxhi](https://cloud.githubusercontent.com/assets/3230886/7642475/f691500c-fa99-11e4-8448-e6ca885055d2.png)

**Comment by Dreddik** [comment]
Это жесть какая-то...
Подумаю, как можно ограничить переходы в этом окне

**Comment by vmalov** [comment]
Нам сегодня тоже реджектнули

**Comment by vmalov** [comment]
Пулл реквест помог, пропустили в стор.

**Comment by Dwiyer** [comment]
Hi, we also encounter this problem today, our app was rejected. Are there any feasible solutions?

**Comment by gregoryvit** [comment]
Hi, you can try to use [my pull request](https://github.com/VKCOM/vk-ios-sdk/pull/221). It's helped to me and **vmalov**.

**Comment by titkov5** [comment]
А почему пулл реквест отсутвует в коде сдк?

**Comment by Dwiyer** [comment]
@gregoryvit well done! Thank you! We just had a try, hope to be effective!

**Comment by Dreddik** [comment]
@titkov5 потому что это кривое решение

**Comment by sergey-makkena** [comment]
@Dreddik , есть какие нибудь варианты решения, кроме костыля в сдк?

**Comment by vitalisgreek** [comment]
@Dreddik Здравствуйте, сегодня получили реджект от эппла по 22.4, и вот думаем, реализовывать ли через костыль (пуллреквест) или Вы можете посоветовать что-то? спасибо

**Comment by Dreddik** [comment]
Обещали убрать со стороны сервера

**Comment by vitalisgreek** [comment]
@Dreddik извините за назойливость, а когда это может произойти?

**Comment by sergey-makkena** [comment]
я принял решение, выпустить версию с костылем. А как поправят, буду без костылей :)

**Comment by vitalisgreek** [comment]
@sergey-makkena так ее апрувнули?

**Comment by sergey-makkena** [comment]
@vitalisgreek, нет пока, вот только отправил :)
Окно апелляции не доступно к сожалению...

**Comment by vitalisgreek** [comment]
@sergey-makkena желаю гуд лака)))) если апрувнут - напишите пожалуйста

**Comment by sergey-makkena** [comment]
@vitalisgreek хорошо!

**Comment by vmalov** [comment]
@vitalisgreek @sergey-makkena 
 Апрувят такое решение. Выше по треду было

**Comment by sergey-makkena** [comment]
@vmalov , апрувят, если не найдут еще до чего докопаться :)

**Comment by mishaboldov** [comment]
Переходы в окне ограничили, теперь проблем возникать не должно.

**Comment by sergey-makkena** [comment]
@vitalisgreek аппрувнули :+1:

**Comment by vitalisgreek** [comment]
@sergey-makkena круто, но теперь можно убирать костыль, Вконтакте молодцы, пофиксили дырку

**Comment by solarsurfer** [comment]
интересно, а если в приложении ссылка на полный сайт контакта, за это могут отклонить приложение?

**Comment by vitalisgreek** [comment]
@solarsurfer если попадется нормальный ревьювер, то с вероятностью 95% - реждект

**Comment by comm1x** [comment]
Нас тоже зареджектили по этой причине.
Не совсем понятно, что нужно сделать, обновить SDK или еще что-то, но проблема по-прежнему есть.
Сценарий: открывается webview, вводим логин пароль, логинимся, под кнопкой разрешить нажимаем ссылку all languages, вверху появляется ссылка на меню. Там уже полный доступ.

**Comment by vitalisgreek** [comment]
@comm1x Проверьте внимательнее, вк действительно закрыли дырку

**Comment by comm1x** [comment]
@vitalisgreek Что именно проверить? После публикации новости проверил первым делом, буквально минут 10 назад (проверяли командой, на айфона айпадах все одинаково). Подумал, что нужно обновить SDK, но репозиторий обновлялся 2 месяца назад. И вот как-то не понятно.

**Comment by vitalisgreek** [comment]
@comm1x  зайти на полную версию никак сейчас

**Comment by comm1x** [comment]
@vitalisgreek Однако это никак не мешает по-прежнему воспроизводить музыку. Формулировка эпла:
"Specifically, users are able to access shared content through VKontakte within your app."
И присылают вот этот скриншот:
![temp zvrfospu](https://cloud.githubusercontent.com/assets/2980388/8102484/1e2167e8-1029-11e5-8f6b-0c009e2feeb0.png)

И вот я тестирую логин в нашем приложении после багфикса:
![img_0003](https://cloud.githubusercontent.com/assets/2980388/8102584/d195f10e-1029-11e5-9ffd-445c37b8d58b.PNG)

Может быть в полную версию сейчас и не зайти, но что-то мне подсказывает, что эпл на этом же пункте продолжит заворачивать приложения и багфикс ничего не решит.

**Comment by vitalisgreek** [comment]
@comm1x а можете скинуть предшествующие это экрану скрины? мы никак уже не можем попасть на этот экран, хотя еще вчера утром могли

**Comment by mishaboldov** [comment]
@vitalisgreek,@comm1x, исправили, проверьте сейчас.

**Comment by comm1x** [comment]
@mishaboldov Да отлично, работает! Спасибо!

**Comment by vitalisgreek** [comment]
Ура!

**Comment by webserfer** [comment]
Переходите на Android. Там до маразма еще далеко.

**Comment by solarsurfer** [comment]
Думаете, эпл делает свои девайсы и сервисы, чтобы доставить пользователю удобство? Как бы не так! Суть эпла - доставлять чувство дискомфорта, когда для этого нет объективных причин, чтобы пользователь заплатил ему за исправления этих неудобств. Устраивает старый айпад? Всё хорошо? Но вышел новый, он вроде ничем не лучше старого, но потребитель чувствует дискомфорт и покупает его, чтобы избавиться от этого чувства дискомфорта, которое не имеет объективной связи с реальностью. Можно сделать нормальный быстрый апрув приложений как в гугле - но нет, мы будем всем доставлять неудобства. Ваше приложение не подходит по 3м критериям? Жди месяц первый критерий, затем ещё один месяц второй, и третий месяц третий, а потом мы тебя забаним потому что у тебя вообще-то авторизация сделана в контакте, ну и проверять тебя нам надоело, так что будь добр потратить ещё 99$ на новый аккаунт. Можно переслать картинку/музыку на телефон просто по шнуру, но нет, мы это запретим (если связывать с PC), пусть твоя картинка сначала улетит на другой континент, затем в космос, а потом вернётся обратно тебе в карман. "Потому что мы действительно знаем, как доставить твоим мозгам и другим частям тела извращённое удовольствие. Во всяком случае, наш CEO в этом специалист планетарного масштаба".

**Comment by zenden2k** [comment]
@solarsurfer 
Полностью согласен, эппл - это раковая опухоль мобильной индустрии.

**Comment by EugeneNekrasov** [comment]
@mishaboldov, аналогичная проблема у нас в приложении. До сих пор реджектят: если кликнуть по ссылке "все языки", а затем на логотив VK в окне выбора языка, то открывается окно логика мобильного VK и соответственно доступ к музыке. Пожскажите, это будет исправлено?

**Comment by mishaboldov** [comment]
@EugeneNekrasov, пришлите, пожалуйста, id приложения.

**Comment by EugeneNekrasov** [comment]
@mishaboldov, 979854305, но оно не прошло модерацию. Могу в бету добавить.

**Comment by mishaboldov** [comment]
@EugeneNekrasov, я имел в виду id приложения в VK

**Comment by EugeneNekrasov** [comment]
@mishaboldov, 4442410

**Comment by mishaboldov** [comment]
@EugeneNekrasov, а почему вы используете тип "Подключенный сайт" и не используете Standalone-приложение? Возможно, вы также передаете display=page или не передаете этот параметр вовсе. Попробуйте заменить его на display=mobile.

**Comment by EugeneNekrasov** [comment]
@mishaboldov, в нашем случае используем веб-вью из-за большого количества соц сетей, которые надо подключать. Да, передаем параметр display=mobile. 

В бету вашу почту добавил и отправил приглашение.
Еще раз как воспроизводится:
1) в веб-вью открывается форма авторизации (с параметром display=mobile)
2) открывается ссылка сменить язык
3) клик на экране выбора языка по шапке с логотипом VK
4) открывается обычная форма авторизации / регистрации (как на мобилках), через которую и происходит доступ к музыке

**Comment by mishaboldov** [comment]
@EugeneNekrasov, отправьте еще один, пожалуйста, а еще лучше: напишите мне в VK: vk.com/boldov

**Comment by mishaboldov** [comment]
@EugeneNekrasov, исправили.

**Comment by EugeneNekrasov** [comment]
@mishaboldov, спасибо. Быстро вы выкладываете в продакшен :)
