### ISSUE TITLE
VK_PER_NOTIFICATIONS

### ISSUE THREAD

**Issue by pashanexant** [VKCOM/vk-ios-sdk#223]
SCOPE = @[VK_PER_FRIENDS, VK_PER_WALL, VK_PER_AUDIO, VK_PER_PHOTOS, VK_PER_NOTIFICATIONS];

notification permission is ignored for some reason. Please look at the attached image for the reference.

![img_3455](https://cloud.githubusercontent.com/assets/1843815/7785865/9b3f2ecc-015b-11e5-8a37-41ab2e5fc77d.PNG)

**Comment by Dreddik** [comment]
You don't need to pass notification permission for SDK apps.
It's only for web-applications running from vk.com site.
