### ISSUE TITLE
Проблемы с капчей

### ISSUE THREAD

**Issue by iOS-altima** [VKCOM/vk-ios-sdk#224]
Добрый день.
У меня две проблемы, связанные с капчей.
1. Если установить waitUntilDone = YES, и это совпадет с запросом капчи, то приложение напрочь зависает (капча не появляется, vkSdkNeedCaptchaEnter не вызывается). Отсутствует  семафор в нужном месте в SDK?
2. Окошко с капчей вообще не подстраивается под окно. Например, в ландшафтном режиме на iPhone 5 оно поднимается вверх за рамки экрана, так что не видно текст капчи. И если при уже выведенном окне капчи поворачивать телефон, оно уезжает совсем не туда, куда надо. Это, конечно, решаемо, но по-моему, за этим должен следить SDK.

**Comment by Dreddik** [comment]
1) не используйте waitUntilDone
2) пофикшу
