### ISSUE TITLE
Не корректно работает авторизация 

### ISSUE THREAD

**Issue by mznosok** [VKCOM/vk-ios-sdk#227]
Скачиваем исходники. Запускаем тестовое приложение (VKSDKTestApplication). Пытаемся авторизироваться любым способом кроме Share dialog. Открывается webview. Вводим в формах логин и пароль, после соглашаемся на то, что приложению будут доступны данные и получаем экран с текстом:
"Пожалуйста, не копируйте данные из адресной строки для сторонних сайтов. ..." и кнопкой Cancel.

При повторной попытке авторизации все отрабатываем нормально.

**Comment by Dreddik** [comment]
Сейчас то же самое?
