### ISSUE TITLE
Warnings in ios 8.3

### ISSUE THREAD

**Issue by nullproduction** [VKCOM/vk-ios-sdk#228]
VKHTTPOperation.m:38:59: Auto property synthesis will not synthesize property 'lock'; it will be implemented by its superclass, use @dynamic to acknowledge intention

VKUploadPhotoBase.m:64:59: Auto property synthesis will not synthesize property 'state'; it will be implemented by its superclass, use @dynamic to acknowledge intention

**Comment by Dreddik** [comment]
Что-то ничего такого не наблюдаю

**Comment by nullproduction** [comment]
@Dreddik думаю варнинги будут если поставить минимальный таргет 7.0 у проекта
xcode 6.3.2

**Comment by Dreddik** [comment]
Не-а. Закрываю, ок?
