### ISSUE TITLE
swift и static константы в хэдерах

### ISSUE THREAD

**Issue by SanjoDeundiak** [VKCOM/vk-ios-sdk#229]
Нельзя засовывать определения статических констант в хэдеры. Подробней здесь: http://stackoverflow.com/questions/28577147/not-allowing-to-use-constant-defined-in-objective-c-header-file-in-swift-class
В результате при использовании этих констант в свифте линкер выдает ошибку

**Comment by Dreddik** [comment]
Какие константы выдают ошибку?
