### ISSUE TITLE
Постинг фотографии на стену друга

### ISSUE THREAD

**Issue by EgorSobko** [VKCOM/vk-ios-sdk#232]
VKUser *user = self.friendsArray[indexPath.row];
NSLog(@"%@", user.id);
VKRequest *photoRequest = [VKApi uploadWallPhotoRequest:[UIImage imageNamed:@"sliced_truffles"] parameters:[VKImageParameters pngImage] userId:user.id.integerValue groupId:0];
    [photoRequest executeWithResultBlock: ^(VKResponse *response) {
        NSLog(@"Photo: %@", response.json);
        VKPhoto *photoInfo = [(VKPhotoArray*)response.parsedModel objectAtIndex:0];
        NSString *photoAttachment = [NSString stringWithFormat:@"photo%@_%@", photoInfo.owner_id, photoInfo.id];
        VKRequest *post = [[VKApi wall] post:@{ VK_API_ATTACHMENTS : photoAttachment}];
        [post executeWithResultBlock: ^(VKResponse *response) {
            NSLog(@"Result: %@", response);
        } errorBlock: ^(NSError *error) {
            NSLog(@"Error: %@", error);
        }];
    } errorBlock: ^(NSError *error) {
        NSLog(@"Error: %@", error);
    }];

Что я делаю не так? все-равно постить на мою стену, а не на стену друга, почему? При добавлении в реквест VK_API_OWNER_ID : @"userID" вообще пишет ошибку администратора группы, при чем тут группа?

Как мне решить эту проблему?

**Comment by Dreddik** [comment]
Должен работать такой постинг.
```
VKUser user = self.friendsArray[indexPath.row];
VKRequest *photoRequest = [VKApi uploadWallPhotoRequest:[UIImage imageNamed:@"sliced_truffles"] parameters:[VKImageParameters pngImage] userId:user.id.integerValue groupId:0];
[photoRequest executeWithResultBlock: ^(VKResponse *response) {
    NSLog(@"Photo: %@", response.json);
    VKPhoto *photoInfo = [(VKPhotoArray *)response.parsedModel objectAtIndex:0];
    VKRequest *post = [[VKApi wall] post:@{ VK_API_ATTACHMENTS : [NSString stringWithFormat:@"photo%@_%@", photoInfo.owner_id, photoInfo.id], VK_API_OWNER_ID : user.id}];
    [post executeWithResultBlock: ^(VKResponse *response) {
        NSLog(@"Result: %@", response);
    } errorBlock: ^(NSError *error) {
        NSLog(@"Error: %@", error);
    }];
} errorBlock: ^(NSError *error) {
    NSLog(@"Error: %@", error);
}];

```
