### ISSUE TITLE
VKShareDialogController leftBarButtonItem X position misaligned

### ISSUE THREAD

**Issue by jjvarghese** [VKCOM/vk-ios-sdk#233]
Minor visual bug with Cancel button in left bar button item. 
![img_0751 png](https://cloud.githubusercontent.com/assets/567998/8182019/679fbe32-142b-11e5-8762-f379737d1dcd.jpeg)

**Comment by Dreddik** [comment]
It is probably issue with categories on uinavigationbar in your app

**Comment by jjvarghese** [comment]
@Dreddik You're right - thanks & closed :)
