### ISSUE TITLE
Нет фотографии в структуре VKUser

### ISSUE THREAD

**Issue by EasyVote** [VKCOM/vk-ios-sdk#234]
При авторизации пользователя с разрешениями wall, friends, photos, в объекте VKUser для текущего пользователя, полученном с помощью [[VKApi users] get], отсутствует свойство photo_200, а так же любые другие поля, связанные с аватаркой пользователя, разумеется у пользователя в самом Вконтакте аватар установлен. SDK версии 1.1.6.

**Comment by Dreddik** [comment]
[[VKApi users] get:@{VK_API_FIELDS : @"photo_200"}]
