### ISSUE TITLE
Серверная авторизация

### ISSUE THREAD

**Issue by Rusik** [VKCOM/vk-ios-sdk#235]
Хочется иметь возможность использовать серверную авторизацию через сдк, то есть с `response_type = code`.

**Comment by Dreddik** [comment]
Не думаю, что появится в скором времени. Тем более, проще такое сделать вам, так как требуется серверный токен. SDK для клиентов

**Comment by Rusik** [comment]
Я бы мог такое запросто сделать, проблема в том, что тогда юзеру придется логиниться в сафари или вебвью, даже если вк апп уже установлено. А это не очень хорошо

Можно было бы просто добавить протокол для вк апп, чтобы оно могло авторизовывать как по токен, так и по коду. В первом случае оно бы возвращало обратно в приложение пользовательский токен, а во втором возвращало бы код, который приложение уже передавало бы на свой сервер.
