### ISSUE TITLE
VKActivity crash

### ISSUE THREAD

**Issue by igorvlassov** [VKCOM/vk-ios-sdk#236]
Здравствуйте!

При попытке вызова UIActivityViewController'а с VKActivity под эмулятором iPhone5s iOS8.3 получаю крэш. Код взят практически из примера:

    NSString *sMessage = [self makePreview];

    NSArray *items = @[sMessage]; //1
    
    UIActivityViewController *activityViewController =
    [[UIActivityViewController alloc] initWithActivityItems:items
                                      applicationActivities:@[ [VKActivity new]]];

    [activityViewController setValue:@"VK SDK" forKey:@"subject"]; //3

    NSArray *excludeActivities = @[UIActivityTypePostToFacebook,
                                   UIActivityTypePostToTwitter,
                                   UIActivityTypePostToWeibo,
                                   UIActivityTypeMessage,
                                   UIActivityTypeMail,
                                   UIActivityTypePrint,
                                   UIActivityTypeCopyToPasteboard,
                                   UIActivityTypeAssignToContact,
                                   UIActivityTypeSaveToCameraRoll,
                                   UIActivityTypeAddToReadingList,
                                   UIActivityTypePostToFlickr,
                                   UIActivityTypePostToVimeo,
                                   UIActivityTypePostToTencentWeibo,
                                   UIActivityTypeAirDrop
                                   ];
    
    activityViewController.excludedActivityTypes = excludeActivities;
    
    [self presentViewController:activityViewController
                                       animated:YES
                                     completion:^{
                                         // ...
                                     }];

Crash Log:

2015-06-19 10:01:19.484 iExpo[839:156520] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: key cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001124b3c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000111bf1bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x00000001123b8af8 -[__NSDictionaryM setObject:forKey:] + 968
	3   UIKit                               0x00000001108b21a0 -[UIActivityGroupViewController _cachedPreferredItemSizeForString:] + 321
	4   UIKit                               0x0000000110b25357 __81-[_UIActivityGroupViewFlowLayout _evaluatePreferredItemSizeForItemsAtIndexPaths:]_block_invoke + 40
	5   CoreFoundation                      0x00000001123e9f22 __53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 114
	6   CoreFoundation                      0x00000001123e967c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 300
	7   UIKit                               0x0000000110b252c7 -[_UIActivityGroupViewFlowLayout _evaluatePreferredItemSizeForItemsAtIndexPaths:] + 212
	8   UIKit                               0x0000000110b24601 -[_UIActivityGroupViewFlowLayout prepareLayout] + 118
	9   UIKit                               0x0000000110adec46 -[UICollectionViewData _prepareToLoadData] + 67
	10  UIKit                               0x0000000110adf31f -[UICollectionViewData validateLayoutInRect:] + 54
	11  UIKit                               0x0000000110aa39b0 -[UICollectionView layoutSubviews] + 194
	12  UIKit                               0x00000001104ffa2b -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 536
	13  QuartzCore                          0x000000010fc67ec2 -[CALayer layoutSublayers] + 146
	14  QuartzCore                          0x000000010fc5c6d6 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 380
	15  UIKit                               0x00000001104f3675 -[UIView(Hierarchy) layoutBelowIfNeeded] + 607
	16  UIKit                               0x0000000110888394 -[_UIAlertControllerAnimatedTransitioning animateTransition:] + 470
	17  UIKit                               0x000000011058da4e __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 1867
	18  UIKit                               0x00000001104a362c _applyBlockToCFArrayCopiedToStack + 314
	19  UIKit                               0x00000001104a34a6 _afterCACommitHandler + 533
	20  CoreFoundation                      0x00000001123e6ca7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	21  CoreFoundation                      0x00000001123e6c00 __CFRunLoopDoObservers + 368
	22  CoreFoundation                      0x00000001123dca33 __CFRunLoopRun + 1123
	23  CoreFoundation                      0x00000001123dc366 CFRunLoopRunSpecific + 470
	24  GraphicsServices                    0x0000000113d2da3e GSEventRunModal + 161
	25  UIKit                               0x000000011047f900 UIApplicationMain + 1282
	26  iExpo                               0x000000010f1534df main + 111
	27  libdyld.dylib                       0x0000000113857145 start + 1
	28  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Dreddik** [comment]
Крашится только с vkactivity?

**Comment by igorvlassov** [comment]
Да. Мои кастомные работают

**Comment by igorvlassov** [comment]
Возможно, проблема в том, что я не залогинился до того, как создал vkactivity.
Сделал кастомный, который показывает сначала экран логина, если пользователь не залогинился ранее, а потом - превью сообщения, единообразный для разных соцсетей - работает. Можно ишью закрывать.
