### ISSUE TITLE
Swift - не работает import

### ISSUE THREAD

**Issue by kondranton** [VKCOM/vk-ios-sdk#239]
Пишу import VKSdk в AppDelegate - возникает ошибка компиляции из-за того, что фреймворк якобы отсутсвует. Ставил через CocoaPods. Пытался делать бридж из Objective, но не сработало. Как можно исправить?

**Comment by Maxim-Zakopajlov** [comment]
Для меня также актуален данный вопрос.

**Comment by shles** [comment]
тоже столкнулся с подобной проблемой

**Comment by ned1988** [comment]
У меня заработало с бриджeм
`#import "VKSdk.h"`

Как вариант, может отсутствовать настройка в `Build Settings` для `Objective-C Bridging Header` и из-за этого не подхватывает фреймворк

**Comment by kondranton** [comment]
Настройка в Build Settings присутствует, но такой бридж все равно не цепляется. В Swift файлах упорно отказывается видеть VKSdk. Обновил Cocoapods, обновил зависимости, все равно не работает.

**Comment by kondranton** [comment]
Похоже сборка фреймворка для Swift'a не работает, в итоге я заново подсоединил pod через Objective (то есть поменял одинарные кавычки на двойные в Podfile) и в этом варианте бридж действительно сработал.

**Comment by Maxim-Zakopajlov** [comment]
У меня поче-то даже в бридж файле не видит #import <VK-ios-sdk/VKSdk.h>

**Comment by WingedDoom** [comment]
В настройках проекта, во вкладке `General`, нужно внизу в `Linked Frameworks and Libraries` добавить `VK_ios_sdk.framework`, после чего писать `import VK_ios_sdk` в нужных файлах

**Comment by romacv** [comment]
Помогло в General -> Linked Frameworks and Libraries добавить VK_ios_sdk.framework
Затем в Swift нужно в ***-Bridging-Header.h дописать @import VK_ios_sdk;
