### ISSUE TITLE
VKActivity - no icon

### ISSUE THREAD

**Issue by ned1988** [VKCOM/vk-ios-sdk#240]
Hi, I'm using `VKActivity` to share user data, it works great but I have strange UI problem in `UIActivityViewController`.  If press `More` button in `UIActivityViewController`, icon for VK item will be absent (see attached screenshot).

`VKSdk` info:
* `SDK Version 1.1.7`
* `SDK API Version 5.23`

Device info:
* `iPhone 6`
* `iOS 8.1`

![ios simulator screen shot 30 jun 2015 18 50 12](https://cloud.githubusercontent.com/assets/1679724/8436226/49b88536-1f5f-11e5-9a5f-45e864e7a2ab.png)

**Comment by Dreddik** [comment]
I have no idea, why it's happening.
