### ISSUE TITLE
Пропала авторизация через приложение при шаринге

### ISSUE THREAD

**Issue by Brain89** [VKCOM/vk-ios-sdk#241]
Привет.
В версии 1.1.11 пропала авторизация пользователя через приложение при шаринге (VKShareDialogController). До этого через pod работали с 1.1.7, такой тип авторизации был: если приложение не было установлено у пользователя, то в 1.1.7 отправляло в Safari. В 1.1.11 авторизация происходит через webView. Есть ли возможность вернуть авторизацию пользователей через официальное приложение?

**Comment by Dreddik** [comment]
Обновил pod
