### ISSUE TITLE
Переделать методы авторизации

### ISSUE THREAD

**Issue by Dreddik** [VKCOM/vk-ios-sdk#242]
Сейчас авторизация слишком путанная и неочевидная.
Надо переделать

**Comment by driver733** [comment]
Полностью с Вами согласен! Еще было бы неплохо переписать всё на swift, а также добавить поддержку CocoaPods (Dynamic Frameworks - http://blog.cocoapods.org/CocoaPods-0.36/)

**Comment by Dreddik** [comment]
@driver733 CocoaPods поддерживается, dynamic frameworks тоже

**Comment by driver733** [comment]
@Dreddik, хмм, у меня не заработало :( Делал всё по инструкции в readme.

**Comment by driver733** [comment]
@Dreddik, у меня в точности такая проблема.
http://stackoverflow.com/q/31278833/2441104

**Comment by Dreddik** [comment]
@driver733 посмотрите здесь #239, не надо в этой задаче писать
