### ISSUE TITLE
Зачем сдк в принудительном порядке добавляет offline права?

### ISSUE THREAD

**Issue by Rusik** [VKCOM/vk-ios-sdk#243]
Зачем сдк в принудительном порядке добавляет `offline` права?
```
if (![permissions containsObject:VK_PER_OFFLINE]) {
	permissions = [permissions mutableCopy];
	[(NSMutableArray *)permissions addObject : VK_PER_OFFLINE];
}
```

**Comment by Dreddik** [comment]
Чтобы токен был бессрочный, и не надо было каждый день переавторизовываться

**Comment by Rusik** [comment]
А если я хочу, чтобы он был бессрочный? :)

**Comment by Dreddik** [comment]
Offline добавляется не только из-за этого, но это основной аргумент. Пользователю, который будет заходить каждый день в приложение не важно, бессрочный он или срочный, ему важно меньше действий совершать.

**Comment by Rusik** [comment]
А если пользователь не будет каждый день заходить в приложение? Если ему например нужно просто разово расшарить что-то в вк? 

Тут весь вопрос в том, что это всё таки сдк, и лучше дать выбор решать такие вопросы самим разработчикам, хотят они использовать offline доступ или нет, а не жестко обязывать всех это делать. Потому-что я не вижу явных причин для обязательной установки этого параметра. Но например меня, как пользователя вк, пугает фраза в окне авторизации о том, что апп будет иметь постоянный доступ к моим данным. И я как разработчик, хочу иметь возможность не использовать эти права, чтобы таким пользователям как я было не страшно давать доступ приложению.

**Comment by driver733** [comment]
А разве нельзя просто сделать тайм-аут на валидность access-токена внутри приложения? А вообще, вы высегда можете, как юзер, залогаутиться из приложения. По-моему, если кому-то страшно за свои данные, лучше вообще не пользоваться интернетом :)
