### ISSUE TITLE
JSON приходит в неверном формате

### ISSUE THREAD

**Issue by driver733** [VKCOM/vk-ios-sdk#247]
В ответ на простейший запрос приходит неверно отформатированный JSON. Пользуюсь последней версией iOS SDK. Версия API также последняя: 5.34.

запрос: VKRequest * audioReq = [[VKApi users] get]; 

Ответ ( в JSON):
(
{
"first_name" = "Dachnik";
id = 12345678; //<-- должно быть "id" = 12345678
"last_name" = "Neudachnik";
}
)

Исходник: http://pastebin.com/iKJ41w85

Более подробно о проблеме:
http://stackoverflow.com/questions/31362493/correctly-loop-and-retrieve-value-in-swiftyjson

**Comment by Dreddik** [comment]
А проблема-то в чём? iOS форматирует dictionary таким образом, это как-то вам мешает получать данные?
