### ISSUE TITLE
SDK not set up check application settings.

### ISSUE THREAD

**Issue by matrosovDev** [VKCOM/vk-ios-sdk#248]
Hi I have a but that just appears on my customer devices (iPhone and iPad). For me SDK works good.

Which settings should I check?

![unnamed](https://cloud.githubusercontent.com/assets/4507851/8699051/43fbe1e4-2b0b-11e5-9e5a-eb314c350513.png)

**Comment by Dreddik** [comment]
VK applications setting is here https://vk.com/apps?act=manage

**Comment by BrysovVadik** [comment]
Такая же проблема, как у автора, не могли бы конкретно указать поля на которые надо обратить внимание?

**Comment by Dreddik** [comment]
@BrysovVadik обратите внимание на "App Bundle для iOS".
Также, обратите внимание, что инициализируетесь нужным app_id

**Comment by BrysovVadik** [comment]
@Dreddik большое спасибо
