### ISSUE TITLE
VKShareDialogController не игнорирует appearance приложения

### ISSUE THREAD

**Issue by ItsTipTop** [VKCOM/vk-ios-sdk#249]
Получается вот такая штука

![ios simulator screen shot 18 2015 1 35 04](https://cloud.githubusercontent.com/assets/1473763/8758470/3e818d2a-2ced-11e5-8637-08ea8a5d0a6b.png)

**Comment by ItsTipTop** [comment]
Пофиксилось примерно так:
    [[UINavigationBar appearance] setBackgroundImage:nil forBarMetrics:UIBarMetricsDefault];
    [[UINavigationBar appearance] setShadowImage:nil];
    [[UINavigationBar appearance] setTitleTextAttributes:nil];
    
    [[UIBarButtonItem appearanceWhenContainedIn:[UINavigationBar class], nil] setTitleTextAttributes:nil forState:UIControlStateNormal];
    [[UIBarButtonItem appearanceWhenContainedIn:[UINavigationBar class], nil] setTitleTextAttributes:nil forState:UIControlStateHighlighted];
    
    [[UIActivityIndicatorView appearance] setColor:nil];

Вызываю перед presentViewController.

**Comment by Dreddik** [comment]
Ну проблема скорее в том, что вы забиваете всё приложение под свой appearance...
