### ISSUE TITLE
Swift + Cocopoads = VKApi.h file not found

### ISSUE THREAD

**Issue by Maxim-Zakopajlov** [VKCOM/vk-ios-sdk#250]
Приветствую. 
Каким бы образом я не подключал, не как не видит в моем BridgingHeader.h #import "VKApi.h"
Без проблем работают остальные библиотеки, а именно подключал #import &lt;GoogleMaps/GoogleMaps.h>

Вот мой podfile:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 1.2'
pod 'SwiftyJSON'
pod 'Haneke'
pod 'SVProgressHUD'
pod 'MRProgress'
pod 'RealmSwift'
pod 'SWRevealViewController'
pod "GoogleMaps"
pod 'MLPAutoCompleteTextField'
pod 'VK-ios-sdk'

**Comment by Dreddik** [comment]
Попробуйте #import &lt;VKSdk/VKSdk.h>

**Comment by Maxim-Zakopajlov** [comment]
Действительно, помогло!) Спасибо.

**Comment by Maxim-Zakopajlov** [comment]
@Dreddik рано закрыл :(
На симуляторе все хорошо, но вот когда я подключаю девайс и пытаюсь скомпилить проект на него, происходит так же ошибка.

**Comment by MilaFabio** [comment]
@Maxim-Zakopajlov у меня работает с #import <VK_ios_sdk/VKSdk.h>, нашла что в Pods***.debug.xcconfig есть в строке -framework "VK_ios_sdk", и сделала в Bridging-Header.h так же с нижним подчеркивание, сразу ошибки пропали

**Comment by Maxim-Zakopajlov** [comment]
@MilaFabio спасибо! Действительно помогло :)
