### ISSUE TITLE
Проблема с шарингом через VKActivity

### ISSUE THREAD

**Issue by ct4h** [VKCOM/vk-ios-sdk#252]
Для шаринга картинки и текста использую UIActivityViewController и VKActivity. 
Если приложение vk не установлено, то шаринг работает через Safari.
Если приложение vk установлено, при попытки авторизации перенаправляет на пустой экран.
![img_0418](https://cloud.githubusercontent.com/assets/11635807/8981663/e2dc7fea-36c2-11e5-882c-bafe911ac1a5.PNG)

Код шаринга:

    [VKSdk initializeWithDelegate:nil andAppId:@"5011736"];
    [VKSdk wakeUpSession:@[VK_PER_WALL,VK_PER_PHOTOS]];
    
    UIActivityViewController *shareVC = [[UIActivityViewController alloc] initWithActivityItems:@[shareText,shareImage] applicationActivities:@[[VKActivity new]]];
    [shareVC setValue:@"VK SDK" forKey:@"subject"];
    [self presentViewController:shareVC animated:YES completion:nil];

**Comment by mcyril** [comment]
тот же самый экран в процессе авторизации при установленном приложении, только на экране видно JSON:

```JSON
{"error":"invalid_request","error_description":"sdk not set up, check application settings"}
```

без приложения авторизация через Safari работает

**Comment by ct4h** [comment]
mcyril, изначально была именно такая проблема, но прописав корректные айдишники, получил проблему пустого экрана.

**Comment by ct4h** [comment]
В ходе тестирования обнаружил, на пустой экран перенаправляет, если в приложение vk авторизирован администратор приложения.

**Comment by Dreddik** [comment]
@ct4h URL схема vk5011736 прописана в вашем приложении?
Или такое происходит только с админом?
Какие-то изменения есть?

**Comment by ct4h** [comment]
@Dreddik URL схема (все настроено). Происходит только с админом

**Comment by Dreddik** [comment]
А версия VK app последняя, да?

**Comment by ct4h** [comment]
@Dreddik последняя

**Comment by k06a** [comment]
Зачем вообще VKActivity авторизация? Пусть перекидывает в аппу или на сайт и все...

**Comment by ct4h** [comment]
@k06a происходит переброс в приложение или на сайт, на котором пользователь авторизуется, если это нужно, или разрешает доступ к приложение.

**Comment by Dreddik** [comment]
Всё ещё актуально?

**Comment by k06a** [comment]
@Dreddik нужен нормальный шаринг в вк, причём лучше без авторизации. В паре вк то юзер авторизован - пусть через неё и постит куда-нибудь.

**Comment by Dreddik** [comment]
@k06a нормальный шаринг есть в VK клиенте. Надо просто отключать vkactivity, если доступен шаринг в ВК...

**Comment by ItsTipTop** [comment]
@Dreddik а как понять, что доступ шаринг через приложение VK?

**Comment by ItsTipTop** [comment]
@Dreddik Хотя нет. Что-то не работает на последней версии SDK.

Код:

    if (![VKActivity vkShareExtensionEnabled]) {
        VKActivity *vkActivity = [VKActivity new];
        [activites addObject:vkActivity];
    }

Отображается и расширение и активити.

**Comment by Dreddik** [comment]
@ItsTipTop к сожалению, сразу не предусмотрели, будет поддержано в версии 2.5 VK App
