### ISSUE TITLE
VKBatchRequest версия API при объединении запросов

### ISSUE THREAD

**Issue by daymont87** [VKCOM/vk-ios-sdk#254]
При запросе можно указать версию API к которой обращаться например @"v" : @"5.21"
а при объединении разных запросов в один с помощью VKBatchRequest это работает? Просто например у меня один запрос был для 4-ой версии API и другой для 5-ой и когда я объединил их в один то запрос для 4-ой версии вернул результат в формате 5-ой версии API. 
И если указание версии не работает, то к какой версии он обращается?

**Comment by Dreddik** [comment]
Для всех запросов используется единая версия, заданная при инициализации SDK

**Comment by daymont87** [comment]
А если версия не указана при инициализации? Например у меня сейчас используется такая инициализация:

[VKSdk initializeWithDelegate:self andAppId:@"43434343"];

**Comment by Dreddik** [comment]
@daymont87 тогда по умолчанию используется 5.21
