### ISSUE TITLE
Приложение получило reject из за дефолтного YES в vkSdkAuthorizationAllowFallbackToSafari

### ISSUE THREAD

**Issue by pashaisthebest** [VKCOM/vk-ios-sdk#255]
Переходить во время авторизации в Safari теперь стало не по гайдам (надо показывать webView) и мое приложение завернули. Можно я сделаю pull request где `vkSdkAuthorizationAllowFallbackToSafari` будет по дефолту NO?

![screen shot 2015-08-05 at 23 13 46](https://cloud.githubusercontent.com/assets/2697487/9096742/c8fc6fc2-3bc7-11e5-9f4e-e6f5eb43567e.png)

a web page in mobile Safari opens for logging in with VKontakte account, then returns the user to the app. The user should be able to log in without opening Safari first. (это для тех, кто гуглит эту проблему)

**Comment by pashaisthebest** [comment]
Дополнительно хотелось бы понять вот что - если это чинить, то скорее всего надо сразу сделать так, чтобы все работало из коробки. Если `vkSdkAuthorizationAllowFallbackToSafari` выставлять в NO то приложению надо будет обязательно переопределять так-же метод `vkSdkShouldPresentViewController:` и если его не переопределять, то ничего не произойдет, и авторизационный webView не покажется. Предлагаю смотреть - определен ли метод `vkSdkShouldPresentViewController:` в делегате, если да, то просто передавать туда авторизационный контроллер, а если нет, то показывать этот контроллер например в новом window, как делает facebook. Тогда все будет работать из коробки, и у девелоперов будет опциональная возможность самим взять а себя отображение контроллера.

**Comment by Dreddik** [comment]
Какая версия SDK?
Сейчас в сафари не должно перебрасывать
