### ISSUE TITLE
Подскажите, как сделать репост поста из группы

### ISSUE THREAD

**Issue by Kalligraf** [VKCOM/vk-ios-sdk#258]
Пробовал данный вариант запроса:
VKRequest request = [[VKApi wall] post:@{VK_API_FROM_GROUP: @"1", VK_API_GROUP_ID: @"944****", VK_API_POST_ID: @"4"}];
[request executeWithResultBlock:^(VKResponse *response) {

NSLog(@"OK");

} errorBlock:^(NSError *error) {

NSLog(@"failed");

}];
Подскажите, что делаю не так?

**Comment by Dreddik** [comment]
https://vk.com/dev/wall.repost

Можно вызвать как 
`VKRequest * request = [VKRequest requestWithMethod:@"wall.repost" andParameters:@{VK_API_FROM_GROUP: @"1", VK_API_GROUP_ID: @"944****", VK_API_POST_ID: @"4"} andHttpMethod:@"GET"];`

**Comment by Kalligraf** [comment]
Спасибо огромное. Получилось вот так:
    VKRequest * request = [VKRequest requestWithMethod:@"wall.repost" andParameters:@{@"object": @"wall-11111111_4"} andHttpMethod:@"GET"];
