### ISSUE TITLE
Как определить что пользователь пришел из мобильного каталога?

### ISSUE THREAD

**Issue by dadon** [VKCOM/vk-ios-sdk#259]
В документации по интеграции sdk, есть требование:
"Добавить экран авторизации игрока через ВКонтакте, который будет появляться, если пользователь установил игру из мобильного каталога."
Как определить, что пользователь пришел из мобильного каталога, чтобы показать экран с предложением авторизоваться через вк?
Спасибо!

**Comment by Dreddik** [comment]
Позже для этого появится расширение библиотеки

**Comment by Dreddik** [comment]
Вопрос неактуален
