### ISSUE TITLE
Не отправляется личное сообщение

### ISSUE THREAD

**Issue by mr-noone** [VKCOM/vk-ios-sdk#263]
Я в iOS приложении вызываю метод messages.send с помощью кода:

```objective-c
NSString *attachmentsString = @"photo-99430307_376262144,http://izzly.co";
NSString *message = [NSString stringWithFormat:@"%@ izzly.co", self.textView.text];

VKRequest *request = [VKApi requestWithMethod:@"messages.send"
                                andParameters:@{@"user_id": self.userId,
                                                @"message": message,
                                             @"attachment": attachmentsString}
                                andHttpMethod:@"POST"];
[request executeWithResultBlock:^(VKResponse *response) {
    NSLog(@"%@", response);
} errorBlock:^(NSError *error) {
    NSLog(@"%@", error);
}];
```

Мне приходит сообщение ошибки:

>2015-08-14 18:17:26.966 izzly[484:36065] Error Domain=VKSdkErrorDomain Code=-101 "Internal server error" UserInfo=0x16745b00 {NSLocalizedDescription=Internal server error, VkErrorDescriptionKey=<VKError: 0x16740ee0; API error {code: 10; message: Internal server error;}>}

Как исправить? Заранее благодарю

**Comment by Dreddik** [comment]
Вы запросили scope VK_PER_MESSAGES?

**Comment by mr-noone** [comment]
Привет,
Запрашиваю при авторизации:

```objective-c
[VKSdk authorize:@[@"friends", @"wall", @"photos", @"messages"] revokeAccess:YES];
```

**Comment by Dreddik** [comment]
Не знаю даже.
Это при отправке из под администратора приложения, или какой-нибудь тестовый пользователь?
Если аккаунт тестовый, и можно передать данные для входа, свяжитесь со мной в VK ( http://vk.com/dredd ),  разберёмся

**Comment by mr-noone** [comment]
Отправка из под администратора.

**Comment by Dreddik** [comment]
Это повторяется всегда? А из под других пользователей то же самое, или проблема только с одним аккаунтом?

**Comment by mr-noone** [comment]
Привет,

Эта ошибка повторяется всегда с момента разработки 14.08.15.
И она происходит с любым акаунтом.

**Comment by Dreddik** [comment]
self.userId точно содержит правильное значение?
Если задать просто текстом, также будет ошибка?
Попробуйте ещё не передавать ссылку в attachment
В NSError может содержаться поле vkError, может там что-то поподробнее есть?

**Comment by mr-noone** [comment]
Это был неправильный user_id. Спасибо.
