### ISSUE TITLE
Не появляется окно авторизации

### ISSUE THREAD

**Issue by Estanque** [VKCOM/vk-ios-sdk#265]
При попытке интегрировать SDK VK для iOS - не получается даже дойти до авторизации.
Проблема заключается в том, что wakeUpSession всегда возвращает NO и до авторизации не доходит.

if ([VKSdk wakeUpSession]) {
...
}

Внутренний метод VKSdk при попытке получить токен из UserDefaults получает nil.
[VKAccessToken tokenFromDefaults:VK_ACCESS_TOKEN_DEFAULTS_KEY];

Приложение зарегистрировал и vk + APP_ID добавил в URLs.

Подскажите, как исправить так, чтобы все работало.

**Comment by Dreddik** [comment]
Если метод возвращает NO, значит надо авторизоваться

**Comment by Estanque** [comment]
Проблема в том, что не окно авторизации даже не появляется.

**Comment by Dreddik** [comment]
А вы его вызываете?

**Comment by Estanque** [comment]
Я делаю аналогично примеру:
    [VKSdk initializeWithDelegate:self andAppId:APP_ID];
    if ([VKSdk wakeUpSession])
    {
        [VKSdk authorize:@[VK_PER_WALL, VK_PER_OFFLINE]];
    }

Соответственно при вызове wakeUpSession выполняется следующий код:
+ (BOOL)wakeUpSession {
    VKAccessToken *token = [VKAccessToken tokenFromDefaults:VK_ACCESS_TOKEN_DEFAULTS_KEY];
    if (!token || token.isExpired)
        return NO;
    ...

С помощью дебага выяснил, что при запросе VKAccessToken токена из UserDefaults - возвращается nil и wakeUpSession возвращает nil. То есть до кода [VKSdk authorize:...] даже не доходит.

**Comment by Dreddik** [comment]
В примере написано if (![VKSdk wakeUpSession])

**Comment by Dreddik** [comment]
Здесь логика простая: wakeUpSession пытается восстановить предыдущую сессию, если её нет, возвращает NO, и значит вам надо авторизоваться

**Comment by Estanque** [comment]
Спасибо! 
Восклицательный знак я упустил из виду.
