### ISSUE TITLE
Не хватает иконки vk при шаринге

### ISSUE THREAD

**Issue by Sh1mor1nka** [VKCOM/vk-ios-sdk#268]
Если нажать кнопочку "More" рядом с иконкой ВК при шаринге...
![ios simulator screen shot sep 3 2015 13 46 02](https://cloud.githubusercontent.com/assets/2759167/9657749/795f0f56-524c-11e5-80c3-f1944146a6dc.png)
вылезет новая страничка на которой у пункта vk нету иконки.
![ios simulator screen shot sep 3 2015 13 46 04](https://cloud.githubusercontent.com/assets/2759167/9657750/79603250-524c-11e5-9b5d-93450ec89a2f.png)
Версия VK-ios-sdk 1.2.0, ставил из CocoaPods.

**Comment by Dreddik** [comment]
Как-то иконку не подхватывает, не знаю, почему.

**Comment by Dreddik** [comment]
В VKActivity появился метод vkShareExtensionEnabled, если он вернёт YES, то VKActivity нужно исключать из списка активити (с версии VK App 2.5). Эта проблема воспроизводится на iOS 8 и выше, где предпочтительнее использовать Share extension
