### ISSUE TITLE
Appstore submission failure

### ISSUE THREAD

**Issue by gshahbazian** [VKCOM/vk-ios-sdk#269]
<img width="602" alt="screen shot 2015-09-04 at 2 50 31 pm" src="https://cloud.githubusercontent.com/assets/867852/9695219/6a4fe5a8-5314-11e5-9ead-3e49438070be.png">

Xcode 7 beta. iOS 9 app.

**Comment by Dreddik** [comment]
Must be fixed now

**Comment by Zymantas** [comment]
This one isn't fixed in 251447cbd4c1f4e26727c3acface14209211e1e1 revision. VKSdkResources.bundle/Info.plist still contains "CFBundleSupportedPlatforms" array with one element: "iPhoneSimulator"
