### ISSUE TITLE
Appstore submission failure (different reason from #269)

### ISSUE THREAD

**Issue by julien-c** [VKCOM/vk-ios-sdk#270]
<img width="631" alt="screenshot 2015-09-08 a 18 51 24" src="https://cloud.githubusercontent.com/assets/326577/9741403/9fd8aa2c-565a-11e5-9613-2515caa9a3f2.png">

Modifying the resource bundle's `Info.plist` as instructed by Xcode (removing the `CFBundleExecutable` key) solves the issue.

**Comment by Dreddik** [comment]
Must be fixed now
