### ISSUE TITLE
поддержка ios9

### ISSUE THREAD

**Issue by antonkrasilnikov** [VKCOM/vk-ios-sdk#272]
Как я понял СДК еще не собирался под ios9, а жаль, так как релизы горят. Есть несколько проблем
1) нужно указать какие домены сдк использует, иначе авторизация не проходит в связи с новой политикой безопасности (https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/)
2) нужно указать схему vkauthorize в ключике LSApplicationQueriesSchemes иначе установленное приложение VK на устройстве не откроется для авторизации
3) при попытке залить билд в стор выдает ошибку
![vk-error](https://cloud.githubusercontent.com/assets/2527751/9818677/732a9ba2-58b2-11e5-8db3-e4a28598c2fd.png)
4) в ios9 при открывании стороннего приложения теперь спрашивается разрешение на это у пользователя, если он откажется, то авторизация повисает до следующего запуска приложения
  Собственно, вопрос - когда?

**Comment by Yaro812** [comment]
Очень справедливо, ждём не дождёмся!

**Comment by Dreddik** [comment]
Перезалил bundle, указал в readme необходимое, пробуйте

**Comment by Yaro812** [comment]
Та же ошибка

**Comment by antonkrasilnikov** [comment]
спасибо, всё норм. Yaro812 если ты через POD делаешь, то скинь pod кэш, должно помочь.

**Comment by Yaro812** [comment]
да, Антон, заработало, после последнего апдейта
