### ISSUE TITLE
Повторное нажатие на кнопку не открывает модальное окно с авторизацией

### ISSUE THREAD

**Issue by alexwillrock** [VKCOM/vk-ios-sdk#275]
Кнопка в приложении для авторизации через ВКонтакте не открывается при повторной авторизации - пользователь зашел приложение, нажал на кнопку ВКонтакте, увидел модальное окно форму, авторизовался, пользовался приложением, вышел из авторизации, и повторное нажатие по кнопке не вызывает открытие новой формы 

```
- (IBAction)vkontakteSignIn:(id)sender {                   

    [VKSdk forceLogout];

    [VKSdk authorize:VKONTAKTE_SCOPE revokeAccess:true forceOAuth:YES inApp:YES display:VK_DISPLAY_MOBILE];
}

- (void)vkSdkNeedCaptchaEnter:(VKError *)captchaError {
    VKCaptchaViewController *vc = [VKCaptchaViewController captchaControllerWithError:captchaError];
    [vc presentIn:self.navigationController.topViewController];
}

- (void)vkSdkTokenHasExpired:(VKAccessToken *)expiredToken {
    [self vkontakteSignIn:nil];
}

- (void)vkSdkReceivedNewToken:(VKAccessToken *)newToken {

    [_presentator signInWithVkontakteCompleteBlock:^{

        [_router segueToMainOfficeFromSourceView:self withAnimate:true];


    }                                   andFailure:^{

    }];
}

- (void)vkSdkShouldPresentViewController:(UIViewController *)controller {
    [self.navigationController.topViewController presentViewController:controller animated:YES completion:nil];
}

- (void)vkSdkAcceptedUserToken:(VKAccessToken *)token {

    [_presentator signInWithVkontakteCompleteBlock:^{
        [_router segueToMainOfficeFromSourceView:self withAnimate:true];

    }                                   andFailure:^{

    }];
}

- (void)vkSdkUserDeniedAccess:(VKError *)authorizationError {
    [[[UIAlertView alloc] initWithTitle:nil message:@"Access denied" delegate:self cancelButtonTitle:@"Ok" otherButtonTitles:nil] show];
}

- (void)alertView:(UIAlertView *)alertView didDismissWithButtonIndex:(NSInteger)buttonIndex {
    [self.navigationController popToRootViewControllerAnimated:YES];
}
```

**Comment by Dreddik** [comment]
Какие-нибудь ошибки в консоли?
Не используйте этот метод 
```
[VKSdk authorize:VKONTAKTE_SCOPE revokeAccess:true forceOAuth:YES inApp:YES display:VK_DISPLAY_MOBILE];
```
Используйте
```
[VKSdk authorize:VKONTAKTE_SCOPE revokeAccess:YES];
```

**Comment by alexwillrock** [comment]
[VKSdk authorize:VKONTAKTE_SCOPE revokeAccess:YES]; 
проблема решена ) спасибо

**Comment by alexwillrock** [comment]
видимо после обновления, метода [VKSdk authorize:VKONTAKTE_SCOPE revokeAccess:YES]; уже нет, собственно VKSdk.authorize([VK_PER_EMAIL]) не открывает окно регистрации авторизации повторно

**Comment by nsleader** [comment]
Метода [VKSdk authorize:VKONTAKTE_SCOPE revokeAccess:YES] нет.
При повторной попытке авторизоваться ничего не происходит.

**Comment by suzhaev** [comment]
Можете уточнить какой кейс вы покрываете? Есть же wakeUpSession для авторизации.

**Comment by gulzatique** [comment]
@nsleader такой код у меня работает:

@IBAction func vkLoginButton(_ sender: AnyObject) {
        VKSdk.forceLogout()
        let VKSDKDelegate = VKSdk.initialize(withAppId: "<тут номер ваш>")
        VKSDKDelegate?.register(self)
        VKSDKDelegate?.uiDelegate = self
        VKSdk.wakeUpSession(SCOPE as [AnyObject]) { (state, error) -> Void in
            print("VKSdk.wakeUpSession")
            if error == nil {
               VKSdk.authorize(self.SCOPE as [AnyObject])
            }
        }
    }

**Comment by gulzatique** [comment]
уже исправлено во вчерашнем билде
спасибо

Best regards,
Gulzat


2016-11-11 1:36 GMT+06:00 Oleg <notifications@github.com>:
