### ISSUE TITLE
{"error":"invalid_request","error_description":"sdk_bundle is incorrect"}

### ISSUE THREAD

**Issue by shihaodong** [VKCOM/vk-ios-sdk#276]
also this error:{"error":"invalid_request","error_description":"sdk_bundle is incorrect"}. if my iphone has not VK app ,the error is appear.But it's ok when I use IOS simulator.What's the matter?
1. bundle identifier in Info.plist is OK.
2. AppID :code :[VKSdk initializeWithDelegate:self andAppId:@"5055031"];
3. [VKSdk authorize:@[VK_PER_FRIENDS, VK_PER_WALL, VK_PER_AUDIO, VK_PER_PHOTOS, VK_PER_NOHTTPS, VK_PER_EMAIL, VK_PER_MESSAGES] revokeAccess:YES];

**Comment by Dreddik** [comment]
This error may only appear in VK app.
Did you set a correct bundle ID in your [VK application settings](https://vk.com/apps?act=manage)?
Please, check the field named "App Bundle ID for iOS"

**Comment by shihaodong** [comment]
Yes，Bundle identifier for IOS is also OK! What's my wrong? Thanks very much!

**Comment by Dreddik** [comment]
What is iOS version? VK app version?

**Comment by shihaodong** [comment]
ios SDK 8.4,use iphone 6 plus

**Comment by shihaodong** [comment]
VK app version is 2.3, published in 2015.8.25 from APP Store.

**Comment by ufs-slizhik** [comment]
Same problem.

**Comment by ufs-slizhik** [comment]
Ooops. That's my fault. I used the wrong vk AppId.

**Comment by Dreddik** [comment]
Is there any changes?

**Comment by sena1or** [comment]
@Dreddik 

Unfortunately, this behaviour is still active.
Authorisation through Safari is very well, WAIDW?

Thanks!

**Comment by Dreddik** [comment]
@sena1or in VK application settings console on vk.com double check that your application bundle id filled and equal running application.
Check for extra spaces after bundle id string (there is a bug, they may be saved without trimming).

**Comment by sena1or** [comment]
@Dreddik 

Right now don't have access to settings console. Try check some time later, but why on Safari is ok?

P.S. VK app determine my app (show name, icon, etc)

**Comment by Dreddik** [comment]
@sena1or because in Safari you don't have to (and primarily can't) check correctness of callee who trying to authorize and determine it's bundle id. It's more like in-app internal authentication

**Comment by sena1or** [comment]
@Dreddik 

Thank you, on another app work well too. Try re-check first one later.
