### ISSUE TITLE
При выгрузке приложения в App Store с VK SDK возникают ошибки ITMS-90535 и ITMS-90542

### ISSUE THREAD

**Issue by DrBreen** [VKCOM/vk-ios-sdk#277]
При выгрузке приложения в App Store при помощи XCode 7 возникают две нижеследующие ошибки. После удаления ключей CFBundleSupportedPlatforms и CFBundleExecutable из Info.plist для VK-ios-SDK проблема разрешилась и приложение было выгружено в App Store без каких-либо проблем. 

ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/Documents for VK.app/VKSdkResources.bundle' contains an invalid value '( "iPhoneSimulator" )'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Documents for VK.app/VKSdkResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

**Comment by Dreddik** [comment]
Убедитесь, что у вас последняя версия файла

**Comment by miserya** [comment]
та же проблема, с последней версией файла

**Comment by SadhuRus** [comment]
Аналогичная проблема вылезла. Как быть??

**Comment by GalaevAlexey** [comment]
Такая же проблема. Обновил под, попробую перезалить.

**Comment by Bambaster** [comment]
Коллеги, такая же проблема. Есть ли решение?

**Comment by DrBreen** [comment]
Решение есть - не знаю, насколько оно корректное, но мое приложение удалось выгрузить в App Store и оно было пропущено модераторами Apple. Для решения данной проблемы я выполнил следующие шаги:
1) нашел файл Info.plist в пакете VKSdkResources.bundle
2) удалил из этого файла ключ CFBundleSupportedPlatforms
3) удалил из этого файла ключ CFBundleExecutable

**Comment by Bambaster** [comment]
Ну ... я сделал тоже самое ))) проверил, все работает. Заливаю в аппстор, надеюсь все будет гуд.

**Comment by Bambaster** [comment]
Коллеги, предложенное DrBreen решение работает, приложение получило апрув все работает корректно.

**Comment by Dreddik** [comment]
CFBundleExecutable убран из файла
