### ISSUE TITLE
IOS SDK не работает [VKApi audio]

### ISSUE THREAD

**Issue by Earl0Grey** [VKCOM/vk-ios-sdk#281]
День добрый.
![2015-09-23 09 43 44](https://cloud.githubusercontent.com/assets/8833330/10039185/367f38be-61d8-11e5-9d93-aba8d9752d92.png)
![2015-09-23 09 44 20](https://cloud.githubusercontent.com/assets/8833330/10039186/368247de-61d8-11e5-9041-20cc715bdc09.png)
![2015-09-19 17 10 44](https://cloud.githubusercontent.com/assets/8833330/10039220/7041e344-61d8-11e5-89fc-3492df75a48d.png)

 Xcode выдает ошибку No known class method for selector 'audio' на запрос VKRequest * audioReq = [[VKApi audio] get];, указанный у вас в примерах вызова методов(см скрины).

**Comment by terratoss** [comment]
попытайся этим способом.

VKRequest *req = [VKRequest requestWithMethod:@"audio.get" andParameters:nil andHttpMethod:@"GET" classOfModel:[VKAudios class]];
        [req executeWithResultBlock:^(VKResponse *response) {
            for (VKAudio *a in response.parsedModel) {
                NSLog(@"%@ - %@", a.artist, a.title);
            }
        } errorBlock:nil];

**Comment by Earl0Grey** [comment]
так и сделал, спасибо.
