### ISSUE TITLE
AppTransport security protocol. Проблема с видео.

### ISSUE THREAD

**Issue by ERussel** [VKCOM/vk-ios-sdk#283]
В примечаниях к интеграции vk sdk сказано, что если не запрашиваются права nohttps, то в Info.plist не нужно вносить настройки ATS c разрешениями для http запросов к серверу vk. Но с видео все же есть проблемы. На данный момент ссылки на видео внутри постов приходят в формате http.

**Comment by Dreddik** [comment]
Могли бы вы привести пример запроса?

**Comment by ERussel** [comment]
Спасибо за столь быстрый ответ.

Например на запрос:

<VKRequest: 0xXXXXXXX; Method: video.get (GET)>
Printing description of response->_request->_methodParameters:
{
    extended = 1;
    "owner_id" = "-28639294";
    videos = "-28639294_171546076";
}

В ответ получаю объект видео у которого:

player = http://vk.com/video_ext.php?oid=-28639294&id=171546076&hash=4a835dcad4926b01&api_hash=144317860207abc96279b8de7f75

**Comment by Dreddik** [comment]
Разберёмся

**Comment by Dreddik** [comment]
Говорят, пофиксят на следующей неделе

**Comment by ERussel** [comment]
Спасибо, большое! 

Я правильно понимаю, что проблема на сервер, а не в сдк?

**Comment by Dreddik** [comment]
Да, на сервере
