### ISSUE TITLE
Авторизация в iOS 9

### ISSUE THREAD

**Issue by guzenkopavel** [VKCOM/vk-ios-sdk#284]
Здравствуйте. VKSdk version 1.2.2. iPhone 6s. iOS 9.0
Возникла проблема с авторизацией: авторизуюсь методом
[VKSdk authorize:@[VK_PER_WALL, VK_PER_EMAIL]
      revokeAccess:YES
          forceOAuth:YES];
Возвращается canOpenURL: failed for URL: "vkauthorize://authorize" - error: "(null)". Что означает что такого приложения нет. Оно и понятно, его у меня нет. Но в iOS 8 открывался Safari с сайтом VK.

**Comment by Dreddik** [comment]
Используйте [VKSdk authorize:@[VK_PER_WALL, VK_PER_EMAIL] revokeAccess:YES];

**Comment by guzenkopavel** [comment]
[VKSdk authorize:@[VK_PER_WALL, VK_PER_EMAIL] revokeAccess:YES];
[VKSdk authorize:@[VK_PER_WALL, VK_PER_EMAIL] revokeAccess:YES forceOAuth:YES];
[VKSdk authorize:@[VK_PER_WALL, VK_PER_EMAIL]];
Все 3 возвращают ответ canOpenURL: failed for URL: "vkauthorize://authorize" - error: "(null)". Приложения Vk не установлено.
В Info.plist есть.
<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>vkauthorize</string>
	</array>

**Comment by maxprig** [comment]
У меня та же проблема. Началось после обновления XCode до 7 версии и IOS до 9й.

**Comment by mikejd** [comment]
Наблюдаю аналогичную проблему.

**Comment by tweaker** [comment]
Тоже самое.Если какое то решение ?

**Comment by balkarov** [comment]
Точно такая же проблема

**Comment by Torbold** [comment]
У меня та же проблема проявляется и на симуляторе и на реальном девайсе. Нашел ли кто-нибудь решение?

**Comment by pilot34** [comment]
что-то в 1.3.8 так и не починилось :(

**Comment by Samback** [comment]
А может у вас там нет наивнейшее контроллера ? в vkSdkShouldPresentViewController 
он nil и всем вам большой привет

**Comment by ZhukV** [comment]
1. Необходимо верно авторизоваться, с учетом наличия приложения (не забываем об Available Schemes)

```objective-c
    if ([VKSdk vkAppMayExists]) {
        [VKSdk authorize:@[VK_PER_WALL]];
    } else {
        [VKSdk authorize:@[VK_PER_WALL] revokeAccess:YES forceOAuth:YES inApp:YES];
    }
```

2. После, если приложение не установлено, или же схемы нету, будет происходить вызов метода делегата `- (void)vkSdkShouldPresentViewController:(UIViewController *)controller`, где уже Вы должны "презентовать" контроллер, сгенерированный VKSDK.

```objective-c
- (void)vkSdkShouldPresentViewController:(UIViewController *)controller
{
    // Get active viewed controller
    TaleNavigationController *taleNavigationController = [TaleNavigationController sharedInstance];
    [taleNavigationController presentViewController:controller animated:YES completion:nil];
}
```

SDK Version:  `pod 'VK-ios-sdk', '~> 1.1.0'` Относительно версий старше, там еще более все печальней. :(

**Comment by makoni** [comment]
Всё ещё есть проблема на последнем релизе (1.3.11). Если не установлено приложение на телефоне - возвращается ошибка:
canOpenURL: failed for URL: "vkauthorize://authorize" - error: "(null)"

При перезапуске приложения всё работает нормально. Для воспроизведения достаточно сбросить симулятор с iOS 9 и запустить какой-нибудь пример на нём. Пример кода выше уже не помогает т.к. SDK изменился уже.

После авторизации через Safari при использовании VKShareDialogController возвращается в приложение, где плюёт в консоль ошибку и застревает на этом экране:

![2016-01-12 18 20 51](https://cloud.githubusercontent.com/assets/234015/12267476/57c1b104-b959-11e5-83d4-e82e28de50d7.png)

После перезапуска всё начинает работать

**Comment by makoni** [comment]
Похоже, что суть даже не в ошибке в консоли. Она выводится в результате вызова метода vkAppMayExists, где просто проверка на canOpenURL, которая в консоль и выводит эту ошибку.

Проблема в VKShareDialogController. В его методе viewWillAppear вызывается код:

Создаём новый экземпляр как в примерах:
```objective-c
VKShareDialogController *shareDialog = [VKShareDialogController new];
shareDialog.text = @"Какой-то текст";
[self presentViewController:shareDialog animated:YES completion:nil];
```

```objective-c
[VKSdk wakeUpSession:self.parent.requestedScope completeBlock:^(VKAuthorizationState state, NSError *error) {
...
}];
```

Проблема в self.parent.requestedScope - эта проперть в данном случае оказывается почему-то nil и возвращается дефолтный набор - [wall, photos].

Если ты не запрашивал у пользователя этих прав при авторизации - то авторизация сбрасывается. То есть по окончании авторизации статус слетает, на 380 строке файла VKSdk проверка
```objective-c
if ([instance hasPermissions:permissions])
```
возвращает NO и показывается экран, авторизации снова. Естественно, ты снова жмёшь войти, тебя опять кидает на авторизацию, но уже с дефолтным набором прав, ты их получаешь и со 2 раза всё работает.

Я вот думал, что VKShareDialogController автоматически подтягивает права, которые уже есть у accessToken. Но они по умолчанию пустые и возвращается стандартный набор.

Не знаю, баг ли это, но примеры использования везде точно стоит обновить.\

Решение. Явно передавать права:
```objective-c
VKShareDialogController *shareDialog = [VKShareDialogController new];
shareDialog.requestedScope = [[VKSdk accessToken] permissions]; // передаём права явно
shareDialog.text = @"Какой-то текст";
[self presentViewController:shareDialog animated:YES completion:nil];
```

**Comment by svatrous** [comment]
Этот код решает проблему авторизации, когда на телефоне не установлено приложение:

```objective-c

VKSdk *sdkInstance = [VKSdk initializeWithAppId:@"YOUR_APP_ID"];
[sdkInstance registerDelegate:self];
[sdkInstance setUiDelegate:self];
[VKSdk authorize:@[VK_PER_EMAIL, VK_PER_GROUPS]];

//метод протокола VKSdkUIDelegate
- (void)vkSdkShouldPresentViewController:(UIViewController *)controller {
    [self presentViewController:controller animated:YES completion:nil];
}

**Comment by pilot34** [comment]
Я использую VKShareDialogController, так что ручная авторизация через `authorize` мне не подходит. Указание permissions, как посоветовал @makoni не помогло.

Отдебажил до конца: исходная проблема такая, когда установлено приложение, после авторизации `viewWillAppear:` у `VKShareDialogControllerInternal` по нотификейшену `UIApplicationDidBecomeActiveNotification`. И вызывается он после `processOpenURL:` в `VKSdk`.

Когда нет приложение и показывается `SFSafariViewController`, `viewWillAppear:` вызывается до `processOpenURL:` и на этот момент авторизации еще нет, так что на экране остается кнопка "Вход".  

Пока Вконтакте это не починят, пришлось захачить вот таким наследником от диалога:

```objective-c

@interface MyVKShareDialogController : VKShareDialogController

@end

@implementation MyVKShareDialogController

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    
    id targetShareDialog = [self valueForKey:@"targetShareDialog"];
    BOOL willShowSafariController = ![VKSdk vkAppMayExists] && IG_SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"9.0");
    
    if (willShowSafariController && targetShareDialog) {
        doAfter(0.3, ^{
            // вызываем еще раз через 0.3 секунды, чтобы запатчить баг
            // https://github.com/VKCOM/vk-ios-sdk/issues/284
            [targetShareDialog viewWillAppear:animated];
        });
    }
}

@end

```
