### ISSUE TITLE
После авторизации через приложение VK возвращает не в то приложение

### ISSUE THREAD

**Issue by daymont87** [VKCOM/vk-ios-sdk#285]
У меня есть два приложения с разными bundleId:
ru.domain.myAppName
ru.domain.pro.myAppName

На сайте вк соответственно созданы также 2 приложения и в "App Bundle ID для iOS" прописаны для них соответствующие bundleId

Собственно проблема в том, что по одиночке если они установлены, то все работает нормально(переходит и туда и обратно и все авторизуется), но если их установить 2 одновременно, то переходит в приложение VK нормально и авторизуется через нужное приложение, НО почему-то возвращает он после авторизации в то мое приложение (ru.domain.myAppName или ru.domain.pro.myAppName), которое было установлено на устройство первым по счету, то есть например если сначала установлю ru.domain.myAppName - то всегда после авторизации будет возвращать в него что из ru.domain.myAppName что из ru.domain.pro.myAppName и наоборот

Подскажите пожалуйста, из-за чего это происходит и как это исправить?

**Comment by Dreddik** [comment]
Наверное, вы прописали общие URL схемы для обоих приложений

**Comment by daymont87** [comment]
Спасибо, заработало! Просто сделал clean перед сборкой билда и оставил по одной URL схеме для каждого приложения. До этого тоже по одной оставлять пробовал, но clean не делал перед сборкой, видимо в этом проблема была

**Comment by SadhuRus** [comment]
daymont87,  Спасибо за совет! Столкнулся с аналогичной проблемой. Пробовал итак и сяк, но без Clear - не помогало. Потом заработало корректно.
