### ISSUE TITLE
Не возвращает в приложение после авторизации доступа

### ISSUE THREAD

**Issue by icasualfatboy** [VKCOM/vk-ios-sdk#286]
Добрый день!

Делаю шаринг. При попытке расшарить, он спрашивает разрешения в ВК. Переход в приложение вк осуществляется, но после нажатия на экране с пермишенами кнопки "Allow" пользователь остается в приложении VK, переход обратно в искомое приложение не осуществляется. Если возвращаться ручками в искомое приложение, то там остается висеть надпись You are not authorized with VK и кнопка Enter

В чем может быть проблема ?

в info.plist прописаны
<img width="350" alt="screenshot 2015-09-29 16 58 37" src="https://cloud.githubusercontent.com/assets/14890667/10166152/6f92d050-66cb-11e5-9c52-422212e306e4.png">

**Comment by SadhuRus** [comment]
В LSApplicationQueriesSchemes добавьтие ваш vk5087664

**Comment by Dreddik** [comment]
Возможно, вы слишком много раз авторизировались. VK скомпилирована с iOS SDK 8, в котором canOpenURL имеет ограниченное количество вызовов. Возможно, исправится в ближайшем обновлении, гарантировать не могу

**Comment by icasualfatboy** [comment]
@SadhuRus Добавил второй строкой - не помогло ((
@Dreddik Обойти это никак нельзя ? Можно как-то протестировать гипотезу, вдруг я в чем-то другом намудрил ?

**Comment by YuriBalashkevych** [comment]
@Dreddik не возвращает назад в приложение и авторизация не проходит. После аппрува permissions просто видно приложение vk, похоже не дергается url исходного приложения и не вызывается делегатский метод application:openURL. Придется переехать на традиционную авторизацию через webView, правильно я понял?

**Comment by Dreddik** [comment]
@YuriBalashkevych так происходит сразу, или после какого-то времени?
Видимо, Apple отломали canOpenURL для iOS SDK 8 совсем

**Comment by YuriBalashkevych** [comment]
сразу, ничего больше не происходит, хотелось бы фикса, не охота костыль лепить, хоть и временный
xCode 7, iOS 9
на iOS 8  не проверял, может там работает нормально

**Comment by Dreddik** [comment]
Сейчас с последней версией VK app проблема актуальна?
У меня не повторяется
