### ISSUE TITLE
dsymutil warning

### ISSUE THREAD

**Issue by megakozma** [VKCOM/vk-ios-sdk#288]
При компиляции с последней версией происходит такая беда. см скриншот
![2015-10-01 15 33 58](https://cloud.githubusercontent.com/assets/12032306/10218643/e5698fa8-6851-11e5-9fa9-b6c07648b75a.png)

**Comment by megakozma** [comment]
Добавлю, что проверял уже на двух проектах

**Comment by Dreddik** [comment]
Действительно, беда, раз туда попало моё имя пользователя

**Comment by Dreddik** [comment]
Могу посоветовать собирать из исходников или с помощью cocoapods

**Comment by metricell** [comment]
We are facing the same issue here.

-> Xcode 7.0.1
-> Deployment target 7.0

If we change *Debug Information Format* setting from **DWARF with dSYM File** to **DWARF** the warning disappear. But, we can't turn off dSYM file as we need it.

Believed to be related with not being able to find debug symbols.
This similar issue might help, https://github.com/Appboy/appboy-ios-sdk/issues/30

**Comment by megakozma** [comment]
metricell, thanks you!
