### ISSUE TITLE
[[VKApi users] get] возвращает информацию в латинице

### ISSUE THREAD

**Issue by maxprig** [VKCOM/vk-ios-sdk#290]
Добрый день!

Запрашиваю через SDK данные пользователя следующим образом:

VKRequest *user = [[VKApi users] get:@{VK_API_FIELDS : VK_API_PHOTO}];

После выполнения запроса, информация возвращается в латинице. Если же выполнить такой запрос, то все равно приходит всё в латинице:

    VKRequest *user = [[VKApi users] get:@{VK_API_FIELDS : VK_API_PHOTO, VK_API_LANG: @"ru"}];

Как получить информацию в кириллице? (Русскими буквами)

**Comment by balkarov** [comment]
[user setPreferredLang:@"ru"];
