### ISSUE TITLE
VKSdk и Parse.com

### ISSUE THREAD

**Issue by Ryskalo** [VKCOM/vk-ios-sdk#292]
Можно ли как-то заменить openURL:sourceApplication:annotation: в AppDelegate ? 
Parse отказывается работать когда они прописаны, возвращает nil при любых запросах.

**Comment by Dreddik** [comment]
А туда нельзя пробрасывать openURL?

**Comment by Ryskalo** [comment]
Вот так все выглядит
func application(application: UIApplication, /*openURL:NSURL, sourceApplication:String?, annotation:AnyObject?,*/didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {        
        //VKSdk.processOpenURL(openURL, fromApplication: sourceApplication)
        Parse.enableLocalDatastore()        
        // Initialize Parse.
        Parse.setApplicationId("......",
            clientKey: ".....")    
        // [Optional] Track statistics around application opens.
        PFAnalytics.trackAppOpenedWithLaunchOptions(launchOptions)

        return true
    }

**Comment by Dreddik** [comment]
Насколько я знаю, нет метода application:openURL: sourceApplication:didFinishLaunchingWithOptions:

**Comment by Ryskalo** [comment]
То есть альтернативы нет?

**Comment by Dreddik** [comment]
Я говорю о том, что вы замешали два метода в одном. didFinishLaunchingWithOptions - одна функция, openURL - другая.

**Comment by Ryskalo** [comment]
Вот так прописано у меня

openURL:NSURL, sourceApplication:String?, annotation:AnyObject?,didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?

**Comment by Dreddik** [comment]
Так пробовали?
```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    // [Optional] Power your app with Local Datastore. For more info, go to
    // https://parse.com/docs/ios_guide#localdatastore/iOS
    Parse.enableLocalDatastore()
    
    // Initialize Parse.
    Parse.setApplicationId("APPLICATION ID",
        clientKey: "CLIENT KEY")
    
    // [Optional] Track statistics around application opens.
    PFAnalytics.trackAppOpenedWithLaunchOptions(launchOptions)
    
    // ...
}

func application(application: UIApplication,
                 openURL url: NSURL,
    sourceApplication sApplication: String?,
    annotation ann: AnyObject) -> Bool {
    VKSdk.processOpenURL(url, fromApplication: sourceApplication)
}
```

**Comment by Ryskalo** [comment]
сделал так
func application(application sourceApplication: String,
        openURL url: NSURL,
        sourceApplication sApplication: String?,
        annotation ann: AnyObject) -> Bool {
            VKSdk.processOpenURL(url, fromApplication: sourceApplication)
        return true
    }
выдает
-canOpenURL: failed for URL: "vkauthorize://authorize" - error: "(null)"

**Comment by Dreddik** [comment]
Ну всё, продолжайте разбираться, моя работа выполнена
