### ISSUE TITLE
Как воспроизвести видео из ВК?

### ISSUE THREAD

**Issue by iwheelbuy** [VKCOM/vk-ios-sdk#293]
Я уже ознакомился с проблемой "request for video #55" перед тем, как писать здесь.
У меня приложение без прямой авторизации. Значит я не получу массив files с прямыми ссылками на видео.
Получаю поле player с ссылкой на видео такого формата:

https://vk.com/video_ext.php?oid=-26750264&id=166994988&hash=4d8a9f1ef802b400&api_hash=14464412289fe3da6db4d8e7e7a6

или такого:

https://www.youtube.com/embed/vrL4ByUQi_U

Проиграть вторую ссылку через UIWebView я могу (такой был совет в ошибке #55). Однако, первая ссылка проиграна не будет по причине:
"Видеозапись была помечена модератором сайта как.... запрещено встраивать на внешние сайты". UIWebView как раз является этим внешним сайтом, видимо. Отсюда вопрос: без прямой авторизации я могу забыть о проигрывании видео из ВК?

**Comment by Dreddik** [comment]
Конкретно для этого видео – да. Если оно помечено взрослым, воспроизвести не получится

**Comment by iwheelbuy** [comment]
Понял. Тогда такой вопрос еще в догонку:
В приложении VK APP это видео воспроизводится. Может существует возможность передать текущую ссылку из моего приложения в VK APP и оно воспроизведет видео? Если такой возможности нет, то какова вероятность ее появления?

**Comment by Dreddik** [comment]
У vk app слегка расширены полномочия, так что на него нет смысла ориентироваться.
Такой возможности не будет с вероятностью 99% :)
