### ISSUE TITLE
Не подключается делегат в проекте на Swift

### ISSUE THREAD

**Issue by icasualfatboy** [VKCOM/vk-ios-sdk#295]
Добрый день
Пытаюсь в проекте на Swift подключить делегаты

Делаю вот так

```
override func viewDidLoad() {
super.viewDidLoad()

VKSdk.initializeWithAppId("1111111")
VKSdk.registerDelegate(self)
}

```

При том ругается, что ```Cannot convert value of type "ViewController" to expected argument type "VKSdk"```

Пытался еще вот так

```
let sdk = VKSdk.initializeWithAppId("1111111")
sdk.registerDelegate(self)
```

тоже не работает.

Подскажите, плиз, как сделать правильно ?

**Comment by Dreddik** [comment]
Второй вариант должен работать, попробуйте указать тип возвращаемого значения

**Comment by icasualfatboy** [comment]
Попробовал вот так

```
func startVk() -> VKSdk {
        
        let sdk = VKSdk.initializeWithAppId("1111111")
        sdk.registerDelegate(self)
        
        return VKSdk
        
    }
```

Ругается на

```
Cannot convert return expression of type 'VKSdk.Type' to return type 'VKSdk'
```

**Comment by Dreddik** [comment]
Мне кажется, вы работаете со Swift, не разобравшись в языке

**Comment by icasualfatboy** [comment]
Да, я только недавно начал с ним работать

**Comment by Dreddik** [comment]
Вам надо сделать имплементацию протокола, примерно так
```
extension ViewController : VKSdkDelegate {
    func vkSdkAccessAuthorizationFinishedWithResult(result: VKAuthorizationResult!) {
        //...
    }
    
    func vkSdkUserAuthorizationFailed(result: VKError!) {
        //...
    }
}
```

**Comment by Dreddik** [comment]
Либо указать, что ваш контроллер наследуется от VKSdkDelegate
```
class ViewController: UIViewController, VKSdkDelegate { 
func vkSdkAccessAuthorizationFinishedWithResult(result: VKAuthorizationResult!) {
        NSLog("Bla %@", result);
    }
    
    func vkSdkUserAuthorizationFailed(result: VKError!) {
        
    }
...
```

**Comment by icasualfatboy** [comment]
На протокол я подписан, обязательные методы имплементированы.

Вот полный код

```
class ViewController: UIViewController, VKSdkDelegate {

    
    var scope = [VK_PER_EMAIL]
    
    @IBAction func button(sender: AnyObject) {
        
        VKSdk.authorize(scope)
        
    }
    
    func startVk() -> VKSdk {
        
        let sdk = VKSdk.initializeWithAppId("5129688")
        sdk.registerDelegate(self)
        
        return VKSdk
        
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        

        
    }

    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    func vkSdkAccessAuthorizationFinishedWithResult(result: VKAuthorizationResult!) {
        print(result)
        print("Hello")
    }
    
    func vkSdkAccessTokenUpdated(newToken: VKAccessToken!, oldToken: VKAccessToken!) {
        print("vkSdkAccessTokenUpdated")
    }
    
    func vkSdkUserAuthorizationFailed(result: VKError!) {
        
    }

}
```

**Comment by Dreddik** [comment]
Так не работает разве? Ругается при компиляции, или просто ничего не происходит?
```
override func viewDidLoad() {
        super.viewDidLoad()

        let sdk = VKSdk.initializeWithAppId("111111")
        sdk.registerDelegate(self)

    }
```

**Comment by icasualfatboy** [comment]
Заработало! Похоже на глюк икскода, потому что я так пробовал в самом начале и компилятор ругался.
Спасибо огромное!

**Comment by tweaker** [comment]
Аналогичная ситуация, я в разработке на swift полный новичок =) Что я делаю не так? Подскажите пожалуйста 

import UIKit
import VK_ios_sdk

class ViewController: UIViewController, VKSdkUIDelegate {
    
    func vkSdkNeedCaptchaEnter(captchaError: VKError) { }
    func vkSdkTokenHasExpired(expiredToken: VKAccessToken) { }
    func vkSdkUserDeniedAccess(authorizationError: VKError) { }
    func vkSdkShouldPresentViewController(controller: UIViewController) { }
    func vkSdkReceivedNewToken(newToken: VKAccessToken) { }
    func vkSdkAccessAuthorizationFinishedWithResult(result: VKAuthorizationResult!) {}
    func vkSdkAccessTokenUpdated(newToken: VKAccessToken!, oldToken: VKAccessToken!) {}
    
    @IBAction func AuthButton(sender: UIButton) {
        //sender.enabled = false
        print("AuthButton")
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let sdk = VKSdk.initializeWithAppId("111111")
        sdk.registerDelegate(self)
        
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }

}

**Comment by moonvader** [comment]
может в VKSdkUIDelegate не нужно UI ?
