### ISSUE TITLE
VK iOS SDK 1.2.2 vs 1.3.1 update

### ISSUE THREAD

**Issue by matrosovDev** [VKCOM/vk-ios-sdk#296]
Не совсем понимаю новую последовательность.

Раньше у меня было так:

1. Init SDK c APPID и авторизация с нужными для меня  VK_PER_WALL и VK_PER_PHOTOS

` [VKSdk initializeWithDelegate:self andAppId:APP_ID_VKONTAKTE];
   [VKSdk authorize:@[VK_PER_WALL,VK_PER_PHOTOS] revokeAccess:YES];`

Теперь я так понимаю это все заменено
`VKSdk *sdkInstance = [VKSdk initializeWithAppId:YOUR_APP_ID];
[sdkInstance registerDelegate:delegate];
[sdkInstance setUiDelegate:uiDelegate];`

UIDelegate - пока не понял для чего это.

Ок заменил старый код на новый без UIDelegate.

Дальше добавляю

`[VKSdk authorize:scope];

[VKSdk wakeUpSession:SCOPE completeBlock:^(VKAuthorizationState state, NSError *error) {
    if (state == VKAuthorizationAuthorized) {
        // Authorized and ready to go
    } else if (error) {
        // Some error happend, but you may try later
    }
}];`

VKAuthorizationAuthorized не возвращаться а только Initialized.

То есть не совсем понял как это использовать:

Раньше у меня был Helper и он работал, авторизовали юзера если все ок постели на стену инфу:
http://codepaste.net/kwgw79

вроде как бы и понимаю все не понятно как wakeUpSession:SCOPE в Sope передаю @[VK_PER_WALL,VK_PER_PHOTOS]  в апп делегате добавил нужный метод для iOS9

ATS = NSAllowsArbitraryLoads

но ничего не происходит (правда тестирую на симуляторе в иос9 иксод 7)

**Comment by Dreddik** [comment]
```
[VKSdk wakeUpSession:SCOPE completeBlock:^(VKAuthorizationState state, NSError *error) {
if (state == VKAuthorizationInitialized) {
   [VKSdk authorize:SCOPE];
} if (state == VKAuthorizationAuthorized) {
// Authorized and ready to go
} else if (error) {
// Some error happend, but you may try later
}
}];`

**Comment by Dreddik** [comment]
UIDelegate нужен, чтобы перехватывать ошибки капчи и валидации

**Comment by metricell** [comment]
Hello,

I can confirm that all warnings related to debug symbols gone. Thank you for that.

However, we get a build error now.

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SFSafariViewController", referenced from:
      objc-class-ref in VKSdk(VKSdk.o)
      objc-class-ref in VKSdk(VKShareDialogController.o)
ld: symbol(s) not found for architecture arm64

Deployment Target iOS7.0

**Comment by Dreddik** [comment]
@metricell are you using cocoapods?

**Comment by matrosovDev** [comment]
yea I use cocoapods, for 1.2.2 previous code works good, but for 1.3.1 as I
understood we should made that change.

2015-11-02 15:37 GMT+02:00 Roman Truba <notifications@github.com>:

**Comment by metricell** [comment]
@Dreddik No, we use `Installation with source code`. Adding `framework` and `bundle` in the project.

**Comment by Dreddik** [comment]
@metricell add SafariServices framework.

@matrosovDev я вам ответил уже, пробуйте.

**Comment by metricell** [comment]
@Dreddik Great thanks. Should I change `framework` status from `Required` to `Optional`?

P.S. All `dsym` warnings are back! :-(

**Comment by Dreddik** [comment]
@metricell yes, you can mark it optional. Also, try to clean up project. I don't have dsym warning now.

**Comment by metricell** [comment]
@Dreddik I tried clean/build and deleted my content from DerivedData folder with no result. I can see in `Issue Navigator` that it's looking for files in your (I suspect) directory. 
> warning: /Users/**romantruba**/Library/Developer/Xcode/DerivedData/ModuleCache/1QY91VRM3O2J6/Foundation-> A3SOD99KJ0S9.pcm: No such file or directory

**Comment by Dreddik** [comment]
@metricell okay, I now understand, why there is no dSYM warnings :D

**Comment by metricell** [comment]
@Dreddik So, do we miss something here? Are we doing something wrong?

**Comment by Dreddik** [comment]
@metricell can you contact me via email so we can resolve the issue faster?
roman@vk.com

**Comment by Dreddik** [comment]
@matrosovDev ваша проблема решена?

**Comment by AssassinSC** [comment]
[VKSdk wakeUpSession:SCOPE completeBlock:^(VKAuthorizationState state, NSError *error) {
if (state == VKAuthorizationInitialized) {
   [VKSdk authorize:SCOPE];
} if (state == VKAuthorizationAuthorized) {
// Authorized and ready to go
} else if (error) {
// Some error happend, but you may try later
}
}];`

всегда возвращает VKAuthorizationAuthorized просто с wakeUpSession было проще
