### ISSUE TITLE
After update to version 1.3.1 error with code 5 raises after changing IP address.

### ISSUE THREAD

**Issue by bernikowich-cedoni** [VKCOM/vk-ios-sdk#298]
After update from version 1.2.2 to 1.3.1 error with code 5 raises after changing IP address. Looks like this should not be issue when HTTPS is required by user, but it's not required.

Scope:
- (NSArray *)requiredPermissions
{
    return @[VK_PER_FRIENDS, VK_PER_NOHTTPS, VK_PER_OFFLINE];
}

P.S.:
Клево, что так быстро отвечаете, думаю поможете и мне. Был в мейловском офисе, но вас не показывали почему-то, только верхние этажи. :)

**Comment by Dreddik** [comment]
Попробуйте без VK_PER_NOHTTPS
P.S. мы не в мейловском офисе, мы в Петербурге

**Comment by bernikowich-cedoni** [comment]
@Dreddik заработало. А можете подсказать почему так? Реверт на 1.2.2 фиксил мою проблему. Но теперь, на 1.3.2 без VK_PER_NOHTTPS все так же работает.

**Comment by Dreddik** [comment]
Если честно, я и сам не знаю, почему так :)
Смогу посмотреть завтра, если это принципиально

**Comment by bernikowich-cedoni** [comment]
@Dreddik я был бы очень признателен, т.к. решение без объяснения меня не совсем устроит - не смогу спать, пока будет ревью идти.) Это не к спеху, но все еще важно. Большое спасибо за столь быструю помощь. Доброй ночи.)

**Comment by bernikowich-cedoni** [comment]
А вот и нет. Все равно слетает токен. Я плохо проверил.

**Comment by Dreddik** [comment]
Хм. А при разрешении прав приложению, там отображается строчка "доступ в любое время"?

**Comment by Dreddik** [comment]
Вообще хорошо бы код, и скриншот экрана разрешения прав доступа приложению

**Comment by bernikowich-cedoni** [comment]
Не отображается - я как-то и не заметил. Хм.. :|

**Comment by bernikowich-cedoni** [comment]
Какие-то чудеса:
![img_6619](https://cloud.githubusercontent.com/assets/11190974/10896240/a9c355d8-81c9-11e5-8ae1-6e678c6ff8e2.PNG)
![img_6620](https://cloud.githubusercontent.com/assets/11190974/10896243/b08cbc6a-81c9-11e5-9c71-e1a6dd56e1e6.PNG)

**Comment by bernikowich-cedoni** [comment]
Вместо "offline access" "documents".

**Comment by Dreddik** [comment]
Попробуйте сделать полный clean, удалить все файлы из Derived data

**Comment by bernikowich-cedoni** [comment]
@Dreddik первым дело так и сделал - не помогло.

**Comment by Dreddik** [comment]
Интересно увидеть, что возвращает [[object requiredPermissions] componentsJoinedByString:@","]

**Comment by bernikowich-cedoni** [comment]
![screen shot 2015-11-03 at 1 39 52 am](https://cloud.githubusercontent.com/assets/11190974/10896555/ce5fd810-81cb-11e5-9240-7f8f0a69a670.png)

**Comment by bernikowich-cedoni** [comment]
А в UI документы.)

**Comment by Dreddik** [comment]
В общем, завтра погляжу с обеих сторон

**Comment by bernikowich-cedoni** [comment]
permissions = permissions ?: @[];

    if (options & VKAuthorizationOptionsUnlimitedToken) {
        permissions = [permissions mutableCopy];
        [(NSMutableArray *) permissions addObject:VK_PER_OFFLINE];
    }

**Comment by bernikowich-cedoni** [comment]
Ошибка тут.

**Comment by bernikowich-cedoni** [comment]
Или нет.))

**Comment by bernikowich-cedoni** [comment]
![screen shot 2015-11-03 at 1 50 41 am](https://cloud.githubusercontent.com/assets/11190974/10896796/5143d118-81cd-11e5-9e73-edf1159db801.png)

**Comment by bernikowich-cedoni** [comment]
@Dreddik тут скрин, после которого будет легче спать.)

**Comment by Dreddik** [comment]
В общем, уберите у себя оффлайн, и всё заработает

**Comment by bernikowich-cedoni** [comment]
@Dreddik это понятно. Но тут явно баг, было бы неплохо его пофиксить. В любом случае спасибо, что помогли найти проблему так оперативно.)
