### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by ItsTipTop** [VKCOM/vk-ios-sdk#299]
Что-то не очень понимаю логики.

При авторизации открывается safariViewController, не авторизуюсь, жму done (тоже самое если нажать "Отмена" когда показывается экран запроса прав для приложения).

Вызывается метод vkSdkAccessAuthorizationFinishedWithResult и в result ошибка:

    Error Domain=VKSdkErrorDomain Code=-999 "Something went wrong" UserInfo={VkErrorDescriptionKey=<VKError: 0x7fb50c1df3a0; SDK error (request canceled)>, NSLocalizedDescription=Something went wrong}

В доках к методу написано:

Notifies delegate about authorization was completed successfully (!!!!), and token received

Вторая непонятка, зачем тогда нужен метод vkSdkUserAuthorizationFailed? И почему там тип ошибки VKError и можно написать что-то такое:

    switch (result.errorCode) {
        case VK_API_CANCELED:
            break;
        default: {
            [self showError:error];
        }
            break;
    }

А в vkSdkAccessAuthorizationFinishedWithResult обычный NSError. Может тогда либо оставить 1 метод vkSdkAccessAuthorizationFinishedWithResult и туда отдавать или ошибку или токен. Да и вообще как-то чтобы можно было понять, что пользователь отменил авторизацию.

Вот Facebook очень удобно сделали без всяких делегатов, все просто и изящно. Весь код авторизации занимает несколько строчек.

        [login logInWithReadPermissions:@[@"scope"] fromViewController:viewController handler:^(FBSDKLoginManagerLoginResult *result, NSError *error) {
            if (error) {
                [self showError:error];
            } else if (result.isCancelled) {
                [self finishWork];
            } else {
                [self facebookLoginCompleted];
            }
        }];

**Comment by Dreddik** [comment]
vkSdkUserAuthorizationFailed может вызваться в процессе работы.
vkSdkAccessAuthorizationFinishedWithResult - в него приходят результаты авторизации, успех или фейл. Странно, недописал документацию, видимо 😁
Смысл сравнивать с FB, если у них на уровне iOS интеграция?

**Comment by ItsTipTop** [comment]
Про FB скорее не сравнение, а пример. Да и бог с ним.

Проблема все равно остается не решенной. Почему в одном месте тип ошибки VKError, а в другом NSError, это же не логично. Да и неудобно. Как мне тогда понять, что операция отменена пользователем в vkSdkAccessAuthorizationFinishedWithResult. По аналогии с  vkSdkUserAuthorizationFailed

switch (result.errorCode) {
    case VK_API_CANCELED:
        break;
    default: {
        [self showError:error];
    }
        break;
}

**Comment by Dreddik** [comment]
В vkSdkUserAuthorizationFailed вообще не имеет смысл ошибка, скорее всего уберу.
В vkSdkAccessAuthorizationFinishedWithResult ошибка типа NSError, потому что туда может прилететь ещё сетевая ошибка.
Проверить можно так
```
if (result.token) {
       //Okay
    } else if (result.error) {
        if (result.error.vkError.errorCode == VK_API_CANCELED) {
           //Canceled
        } else {
            //Some other error, e.g. network
        }
    }
``

**Comment by Dreddik** [comment]
Напишите, если можно будет закрывать

**Comment by ItsTipTop** [comment]
Спасибо, можно закрывать)

**Comment by ItsTipTop** [comment]
@Dreddik Так для чего в итоге нужен vkSdkUserAuthorizationFailed

**Comment by artyomLisovskij** [comment]
@ItsTipTop поддерживаю вопрос!

**Comment by Dreddik** [comment]
@ItsTipTop @artyomLisovskij vkSdkUserAuthorizationFailed вызывается, если SDK получил ошибку 5, то есть пользователь деавторизовал приложение на сайте, сменил пароль, или ещё что-то в этом духе

**Comment by Anobisoft** [comment]
нажимаем на "Отменить" в приложении Вконтакте,
_errorCode	NSInteger	-101
101 != VK_API_CANCELED

**Comment by iFoxxy** [comment]
Привет.
Обновил SDK – получаю ошибку в 
`(result.error.vkError.errorCode == VK_API_CANCELED)`

> Value of type "Error" has no member of type "vkError"

Что не так?

**Comment by NickyHarm** [comment]
Та же ошибка. Использую UIActivityViewController, чтоб поделиться картинкой. Если приложение vk установлено, то вылезает приложение vk с заголовком Поделиться и висящем сообщении Ошибка сервера. Если vk приложение НЕ установлено, то получаю ошибку (result.error.vkError.errorCode == VK_API_CANCELED). В чем может быть дело?
