### ISSUE TITLE
Не авторизируется iOS 8.4 iPad Air 2

### ISSUE THREAD

**Issue by aarizhov** [VKCOM/vk-ios-sdk#300]
вызываю [VKSdk authorize:@[]];
открывается  webView и просит все ввести, ввожу,
жму разрешить webView скрывается и все...

делегат не приходит
vkSdkAccessAuthorizationFinishedWithResult

Сюда тоже не приходит
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {

Когда установлено приложение VK то при авторизации 
открывается VK приложение и просто висит... активити индикатор крутится и ничего не происходит

на версии 8.1.2 все работает и с приложением и без iPhone 5s

Раньше все работало вот только что обновился и и полезло

**Comment by Dreddik** [comment]
>>Когда установлено приложение VK то при авторизации 
открывается VK приложение и просто висит
Это iPhone или iPad?

**Comment by Dreddik** [comment]
По поводу первой части, проверьте, что у вас делегат не умирает.

**Comment by Dreddik** [comment]
Для iPad вставил костыль, чтобы не переходило в оф. приложение, потому что обнаружил баг с авторизацией пользователей, у которых не включен https по-умолчанию

**Comment by aarizhov** [comment]
"Когда установлено приложение VK то при авторизации 
открывается VK приложение и просто висит"

Это iPad
На iPhone все норм хотя иногда бывает одновременно кидает и в приложение и webView включается

**Comment by aarizhov** [comment]
А как включить https по умолчанию это в Plist где-то? я включу или это в настройках VK

**Comment by Dreddik** [comment]
Я запушил версию SDK 1.3.4, в которой просто не будет открываться vk app на iPad, так что этот вопрос снят.
Нужно поточнее всё таки описать все волнующие проблемы, мне не подходит описание в виде "странное ощущение".
Проверил на симуляторе iPad 8.4, всё работает как положено, смотрите проблему у себя.

**Comment by aarizhov** [comment]
Вы вообще там что-то тестируете? или пользователи SDK тестируют?

**Comment by Dreddik** [comment]
Мы что-то тестируем. Но как-то вот у всех получается разное тестовое окружение, и оказывается, что мы не репрезентативны.
