### ISSUE TITLE
Не работает авторизация в симуляторе IOS 9.1

### ISSUE THREAD

**Issue by balkarov** [VKCOM/vk-ios-sdk#302]
Обновил версию SDK до 1.3.4 и обновил все методы, предназначенные для iOS 9.
На реальном устройстве все работает как надо, а на симуляторе выдает ошибку
```objective-c
-canOpenURL: failed for URL: "vkauthorize://authorize" - error: "(null)"
```

Это прописал:
```objective-c
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>vk</string>
    <string>vk-share</string>
    <string>vkauthorize</string>
</array>
```

**Comment by Dreddik** [comment]
Это не ошибка, скорее предупреждение.
Если на симуляторе не открывается webview или safariviewcontroller, то проверьте, задаёте ли вы uidelegate

**Comment by balkarov** [comment]
Добавил в метод vkSdkShouldPresentViewController presentViewController и заработало...
