### ISSUE TITLE
About Authorization

### ISSUE THREAD

**Issue by charles0126dev** [VKCOM/vk-ios-sdk#303]
When I was requesting for authorization, the safari alert me of this. How can I fix it?

![img_7978](https://cloud.githubusercontent.com/assets/10875536/10935949/43384fce-8324-11e5-8378-40145c33b800.jpg)

**Comment by Dreddik** [comment]
Did you register URL-scheme for your app?

**Comment by charles0126dev** [comment]
Thank you for your replying. I solved the problem now. It's exactly the problem you said.
