### ISSUE TITLE
[VKApi wall] post завершается с ошибкой Access denied: no access to call this method

### ISSUE THREAD

**Issue by tropindv** [VKCOM/vk-ios-sdk#304]
Добрый день.

Запрос [[VKApi wall] post: queryParam ] завершается ошибкой Access denied: no access to call this method.

Реализация такая:
```
    NSString* ownerId = [VKSdk accessToken].userId;
    NSDictionary* queryParam = [NSDictionary dictionaryWithObjectsAndKeys:
                                ownerId, @"owner_id",
                                @"123", @"message",
                                //attachment, @"attachments",
                                nil];

    VKRequest* request = [[VKApi wall] post: queryParam ];
    

    [request executeWithResultBlock:^(VKResponse* response)
    {
        int d = 0;
        d++;
    }
    errorBlock:^(NSError* error)
    {
        int d = 0;
        d++;
    }];
```
До вызова этот метода авторизация проходит успешно, accessToken возвращается, userId не пустой.
При авторизации запрашиваются разрешения: @"friends", @"photos", @"wall", @"groups". 
используется vk ios sdk 1.3.4
среда разработки xCode 7.0
аппарат iPhone 6 plus
версия iOS 8.1.3 

Другой запрос, например VKRequest * request = [[VKApi friends] get: queryParam ], выполняется без ошибок.

**Comment by Dreddik** [comment]
Покажите код инициализации

**Comment by tropindv** [comment]
код инициализации:
```
        sdkInstance = [VKSdk initializeWithAppId:VK_API_ID];
        [sdkInstance registerDelegate:self];
        [sdkInstance setUiDelegate:self];
```

**Comment by Dreddik** [comment]
И авторизации)
И wakeUpSession

**Comment by tropindv** [comment]
код авторизации:
```
static NSArray* authPermissions = @[VK_PER_FRIENDS, VK_PER_WALL, VK_PER_PHOTOS, VK_PER_GROUPS, VK_PER_NOHTTPS];

    [ VKSdk wakeUpSession:authPermissions
            completeBlock:^(VKAuthorizationState state, NSError *error)
    {
        if (state == VKAuthorizationInitialized)
        {
            [VKSdk authorize:authPermissions];
        }
        if (state == VKAuthorizationAuthorized)
        {
            // Authorized and ready to go
            int d = 0;
            d++;
        }
        else if (error)
        {
            // Some error happend, but you may try later
            int d = 0;
            d++;
        }
    }];
```

**Comment by Dreddik** [comment]
Попробуйте сделать [VKSdk forceLogout], и залогиниться снова.
Так же хотелось бы увидеть скриншот экрана разрешения доступа к приложению, может что-то не передаётся.
Просто ваш код у меня отрабатывает без проблем, надо разобраться

**Comment by tropindv** [comment]
[VKSdk forceLogout] выполнил. авторизовался повторно. окно запроса разрешений открылось, разрешения в нем перечислены, нажал "разрешить", но при выполнении запроса wall.post та же ошибка

скриншот:
![vk_auth](https://cloud.githubusercontent.com/assets/15656872/10965265/d6a1c9f0-83bc-11e5-8025-0ae25c9791e6.PNG)

**Comment by Dreddik** [comment]
Тогда надо посмотреть, что лежит в queryParam

**Comment by tropindv** [comment]
queryParam опубликовано в первом сообщении. там тестовый текст "123". owner_id там не пустой. что еще нужно посмотреть?

**Comment by Dreddik** [comment]
Какой id приложения?

**Comment by tropindv** [comment]
в queryParam id приложения нет. в VKSdk initializeWithAppId передаю id моего приложения. я проверил, id указан верный, как в настройках админки vk. в info.plist в URL Types добавлен тоже этот же id с префиксом vk.

**Comment by Dreddik** [comment]
Это хорошо. Так может всё таки скажете id приложения?

**Comment by tropindv** [comment]
я не могу его разглашать. скажите что нужно проверить.

**Comment by Dreddik** [comment]
Отправьте мне его письмом на roman@vk.com

**Comment by tropindv** [comment]
отправил.

**Comment by Dreddik** [comment]
У вас проблема с почтой, никакие письма не идут в вашу сторону.
В принципе, проблема локализована, но разработчики ещё не подправили.
Я сообщу, если что-то изменится

**Comment by tropindv** [comment]
Добрый день. Последнее письмо от вас пришло. 5 нояб. Сообщите когда будет поправлено.
Хочу уточнить, не связана ли эта проблема с тем что sdk подключает к мобильным платформам. 
Приложение уже используется для web версии в контакте ( через браузер ).
Нужно ли для мобильных платформ регистрировать приложение отдельно, с отдельным id?

**Comment by tropindv** [comment]
Добрый день. Проблема потеряла актуальность. Вопрос закрыт.

**Comment by Dreddik** [comment]
В общем, дело в том, что это приложение отключено. Только админы и тестеры могут делать wall.post.
