### ISSUE TITLE
При использовании метода wakeUpSession возвращает всегда VKAuthorizationState.Initialized

### ISSUE THREAD

**Issue by extnous** [VKCOM/vk-ios-sdk#305]
Добрый день! 
Используя метод wakeUpSession таким образом:
VKSdk.wakeUpSession(scope) { (state, error) -> Void in
    if (state == VKAuthorizationState.Authorized) {
             
     } else if (state == VKAuthorizationState.Initialized) {
                
     } else if (error != nil) {
                
     }
 }

всегда возвращается VKAuthorizationState.Initialized. После того как пользователь один раз авторизовался, при следующем открытии приложения и срабатывания метода должен же возвращаться VKAuthorizationState.Authorized?
В info.plist LSApplicationQueriesSchemes добавил, в апделегат нужный код также добавлен, используемый язык swift.

И ещё один вопрос на версии 1.3.4 при авторизации можно как-то отказаться от перехода в vk приложение и авторизацию там с возвратам в своё приложение, и если да, то как?

**Comment by extnous** [comment]
в issue #300 прочитал:
 Dreddik commented 3 days ago
Я запушил версию SDK 1.3.4, в которой просто не будет открываться vk app на iPad, так что этот вопрос снят.

На iPad mini наблюдаю в этой версии sdk все тот же баг, переходит в vk app и там бесконечный Activity Indicator

**Comment by Dreddik** [comment]
Да, надо ждать обновления iPad приложения.

По поводу первого, должно возвращаться Authorized, если пользователь авторизован и не был вызван logout

**Comment by extnous** [comment]
Кхм, а почему тогда может возвращать всегда только VKAuthorizationState.Initialized есть мысли? В VKAuthorizationState.Authorized ниразу не заходил )
Про приложение понятно, спасибо!

**Comment by Dreddik** [comment]
Возможно, у вас объект токена не может сохраниться в keychain. Буду благодарен, если поможете найти проблему, у меня такого не было.

**Comment by extnous** [comment]
В scope был выставлен "notify". При реализации метода wakeUpSession такие права не находил естественно и отсылал на подтверждение прав ещё раз.  Затер их из прав, метод заработал нормально. Issue закрываю, спасибо за ответы!

**Comment by D-Link13** [comment]
Тем не менее, я встретился с такой же проблемой... 
Вот мой helper:
`import Foundation
import VK_ios_sdk

class VKNetworking: NSObject {
    static let shared = VKNetworking()
    static let kVK_APP_ID = "???????"
    let permissions = NSArray(objects: "email") as [AnyObject]
    
    var userEmail = String()
    var userFirstName = String()
    var userLastName = String()
}

extension VKNetworking: VKSdkDelegate {
    func vkSdkAccessAuthorizationFinished(with result: VKAuthorizationResult!) {
        if result.token != nil && result.error == nil {
            if let email = result.token.email {
                self.userEmail = email
            }
            if let user = result.user {
                if let firstName = user.first_name {
                    self.userFirstName = firstName
                }
                if let lastName = user.last_name {
                    self.userLastName = lastName
                }
            }
        }
    }
    
    func vkSdkUserAuthorizationFailed() {
        print("vkSdkUserAuthorizationFailed")
    }
    
    func vkLogin(success:(_ token: NSString) -> (), failure:(_ error: NSError?)->()) {
        VKSdk.wakeUpSession(self.permissions, complete: { (state, error) in
            
            if state == .authorized && error == nil && VKSdk.accessToken() != nil {
                print("authorized")
            } else if state == .initialized {
                print("initialized")
                VKSdk.authorize(self.permissions)
            } else {
                if error != nil {
                   print(error!)
                }
            }
        })
    }
}

extension VKNetworking: VKSdkUIDelegate {
    func vkSdkShouldPresent(_ controller: UIViewController!) {
        
    }
    
    func vkSdkNeedCaptchaEnter(_ captchaError: VKError!) {
        
    }
}`

Вот фрагмент из AppDelegate:
`func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        VKSdk.initialize(withAppId: VKNetworking.kVK_APP_ID).register(VKNetworking.shared)
        return true
    }
    
    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        return VKSdk.processOpen(url, fromApplication: sourceApplication)
    }`

Буду благодарен за помощь!

**Comment by Gargo** [comment]
@RomanTruba отлично - проблема не решена, но баг закрыт

**Comment by RomanTruba** [comment]
@Gargo я ничем не могу помочь, заводите новый issue, возможно, разработчики ВК посмотрят
