### ISSUE TITLE
Есть ли в планах адаптация SDK для react-native ?

### ISSUE THREAD

**Issue by ir4y** [VKCOM/vk-ios-sdk#306]

**Comment by Dreddik** [comment]
Пока планов не было, возможно.

**Comment by doochik** [comment]
Я начал делать обертку, пока есть только авторизация. Можно присоединяться =)

https://github.com/doochik/react-native-vk-sdk

**Comment by ir4y** [comment]
Круто!
Я примерно такое же уже написал :)
У меня есть уже черновик авторизации для Android. Думаю получится сделать кроссплатформенный модуль.
Причём на мой взгляд нативная поддержка нужна только авторизации, дальше можно использовать JS Sdk.
