### ISSUE TITLE
Принудительная авторизация через WebView

### ISSUE THREAD

**Issue by daymont87** [VKCOM/vk-ios-sdk#308]
Здравствуйте! В версии 1.2.2 можно было принудительно авторизоваться через WebView

[VKSdk authorize:scope revokeAccess:YES forceOAuth:YES inApp:YES];

как я понимаю теперь в 1.3 версии этой возможности больше нет предусмотрено? Если да, то можно ли вернуть ее?

**Comment by Dreddik** [comment]
Нет, нельзя. Для чего это вам?

**Comment by daymont87** [comment]
Ну например чтобы предоставить юзеру выбор через какой аккаунт залогиниться(через официальный апп можно залогиниться только под тем юзером, кто уже авторизован в приложении), у меня было раньше 2 варианта на выбор: залогиниться через вк апп или через WebView. Это удобно например если устройством пользуется не один человек(iPad например) и в официальном апе залогинен другой юзер, а он хочет зайти под собой именно

**Comment by Dreddik** [comment]
Хотелось бы уйти от такого сценария. В iOS 9 появилась функция быстрого возврата в предыдущее приложение, если пользователь решит не логиниться и вернуться, sdk покажет webview

**Comment by daymont87** [comment]
Да, но еще много кто сидит на ios7 и ios8. Все же эта ф-ция не была бы лишней и кому она не нужна - просто бы ей не пользовались. В sdk даже я вижу есть метод
 [VKSdk authorize:scope withOptions:VKAuthorizationOptions]; можно было бы просто добавить опцию авторизации через webview
