### ISSUE TITLE
Авторизация в 9.1

### ISSUE THREAD

**Issue by StasevichJack** [VKCOM/vk-ios-sdk#309]
Здравствуйте. VKSdk version 1.3.4. iPhone 5s. iOS 9.1
Возникла проблема с авторизацией.
Добавил делегаты:
@interface BaseVC () <VKSdkDelegate, VKSdkUIDelegate>
Инициирую sdk:
    VKSdk *sdkInstance = [VKSdk initializeWithAppId:ID];
    [sdkInstance registerDelegate:self];
    [sdkInstance setUiDelegate:self];
Авторизуюсь:
    [VKSdk authorize:@[VK_PER_NOTIFY]];
Открывается окно для подтверждения прав доступа вк, подтверждаю, оно закрывается и я остаюсь в приложении вк. Все, никаких действий, методы делегатов не работают.

**Comment by Dreddik** [comment]
URL схема не определена или неверна

**Comment by StasevichJack** [comment]
<key>LSApplicationQueriesSchemes</key>
	<array>
        <string>vk</string>
        <string>vk-share</string>
        <string>vkauthorize</string>
	</array>

**Comment by StasevichJack** [comment]
Я что-то делаю не так ?

**Comment by Dreddik** [comment]
Вы прочитали readme полностью? Вы [прочитали документацию] (https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html#//apple_ref/doc/uid/TP40007072-CH6-SW10)? Вы посмотрели [отличный пример твиттера, как настроить схему] (https://dev.twitter.com/cards/mobile/url-schemes)? Вы понимаете, что делаете, когда копипастите код?

**Comment by StasevichJack** [comment]
Да, я все прочитал и все сделал по примеру, в противном случае я бы не обращался за помощью.

**Comment by StasevichJack** [comment]
Прошу прощения, дело действительно было в URL схеме, т.к. у меня авторизация через facebook и vk эти схемы перемешались между собой и не давали произвести авторизацию. Спасибо.
