### ISSUE TITLE
перестали приходить push нотификации о новых сообщениях

### ISSUE THREAD

**Issue by ooositeseeing** [VKCOM/vk-ios-sdk#310]
Добрый день.
iOS 9.1 iphone 6, iphone 5 перестали приходить push уведомления.
В настройках приложения ничего не менялось, сертификат от эпл (который надо залить в вк в распароленном виде) проверял - работает. 
RegisterDevice возвращает 1 как и прежде.

Подскажите, может в вк что-то поменялось?

**Comment by Dreddik** [comment]
Дайте ссылку на ваш профиль в ВК, пожалуйста

**Comment by ooositeseeing** [comment]
вот ссылка на аккаунт, к которому подцеплено приложение http://vk.com/id310825461

**Comment by Dreddik** [comment]
Меня интересует аккаунт, на который перестали приходить пуши

**Comment by ooositeseeing** [comment]
например этот http://vk.com/id176732121

но пробовал как минимум на пяти аккаунтах и с пяти аккаунтов

**Comment by Dreddik** [comment]
И ещё id приложения, если не сложно. Можно на почту roman@vk.com , если не имеете права разглашать такую информацию.

**Comment by ooositeseeing** [comment]
ID приложения:	5027495

**Comment by Dreddik** [comment]
Спасибо, будем изучать

**Comment by ooositeseeing** [comment]
когда предположительно можно ждать ответ?

**Comment by Dreddik** [comment]
Не могу ничего конкретного сказать по срокам, зависит не от меня

**Comment by ooositeseeing** [comment]
Забыл упомянуть:
#define VK_SDK_VERSION @"1.1.7"
#define VK_SDK_API_VERSION @"5.23"

**Comment by ooositeseeing** [comment]
Проблема решена.

**Comment by maxbpro** [comment]
И в чем проблема была?
