### ISSUE TITLE
Авторизация в VK APP

### ISSUE THREAD

**Issue by iwheelbuy** [VKCOM/vk-ios-sdk#311]
Добрый день. Не знаю, к вам ли обращаться с этой проблемой. Но все же хочется поделиться.
Уже достаточно долго наблюдаю проблему с вылетом VK APP при авторизации: если точнее то при вводе пароля.

Мой пароль начинается на Wh. Вылетает еще до того как я введу третий символ.
Небольшое тестирование показало, что даже если ввести один символ в пароле, потом его стереть, потом опять ввести, то приложение вылетит.

Единственный вариант авторизоваться - составить пароль где-нибудь в другом месте а потом сразу вставить его целиком.

Если проблема не по адресу - прошу прощения. Но если у вас все-таки есть возможность передать данную информацию разработчикам приложения, то, прошу вас, передайте!

Спасибо

**Comment by Dreddik** [comment]
Исправится в следующем обновлении
