### ISSUE TITLE
The VkSdk version 1.3.1 need the minimum iOS9.0 SDK to build app?

### ISSUE THREAD

**Issue by zhangyu528** [VKCOM/vk-ios-sdk#312]
The SFSafariViewControllerDelegate Class is in iOS9 Sdk?

**Comment by zhangyu528** [comment]
Sorry,I found SafariServices.framework need iOS7

**Comment by Dreddik** [comment]
Add SafariServices.framework as optional

**Comment by zhangyu528** [comment]
thanks

**Comment by Dreddik** [comment]
I don't really know the answer.
You have pretty old compiler
