### ISSUE TITLE
places.getCheckins возвращает не то, что запланировано

### ISSUE THREAD

**Issue by iwheelbuy** [VKCOM/vk-ios-sdk#313]
Создал execute метод для получения только последних checkin'ов для определенных мест. Сначала пробовал без ```timestamp```, просто с ```count=1```. Примерной каждый третий ```place``` параметр оставался без последнего checkin'а (а быть они должны 100%). Решил заменить подход на использование ```timestamp``` и тут дела еще хуже оказались. Ожидается, что вернутся более поздние checkin'ы. Иногда срабатывает хорошо. Иногда возвращает более ранние...
```
return API.places.getCheckins({"place":Args.val1,"timestamp":Args.tim1}).items;
```
Отправляю вот с такими параметрами
```
{
    tim1 = 1447425708;
    val1 = 6379761;
}
```
Получаю вот такой ответ с более ранними отметками
```
(
        {
        date = 1446478750;
        id = "19202675_3518";
        latitude = "52.951779";
        longitude = "87.957247";
        "post_id" = 3518;
        text = "\U041f\U043e\U043d\U0435\U0441\U043b\U0430\U0441\U044c \Ud83c\Udfc2  \U043e\U0442\U043b\U0438\U0447\U043d\U044b\U0439 \U043f\U043e\U043d\U0435\U0434\U0435\U043b\U044c\U043d\U0438\U043a \U2603 #\U0448\U0435\U0440\U0435\U0433\U0435\U0448 #maxbus @ Sheregesh, Kemerovskaya Oblast', Russia";
        "user_id" = 19202675;
    },
        {
        date = 1446288791;
        id = "277988099_767";
        latitude = "52.951779";
        longitude = "87.957247";
        "post_id" = 767;
        "user_id" = 277988099;
    } и т.д.)
```
Однако вот с такими параметрами
```
{
    tim1 = 1447428155;
    val1 = 7089430;
}
```
Получаю ожидаемый ответ с ожидаемой отметкой
```
(
    {
        date = 1447428155;
        id = "84350788_6567";
        latitude = "52.951355";
        longitude = "87.954662";
        "post_id" = 6567;
        "user_id" = 84350788;
    }
)
```

**Comment by bernikowich-cedoni** [comment]
@iwheelbuy проверил - все действительно так. Вам стоит написать [сюда](https://new.vk.com/bugs?act=all) - тут же стоит постить вопросы по SDK, а не API.
