### ISSUE TITLE
Проблемка при инициализации SDK

### ISSUE THREAD

**Issue by Sh1mor1nka** [VKCOM/vk-ios-sdk#314]
Здравствуйте, хотелось бы уточнить один момент при инициализации SDK, мне кажется что так писать не стоит, ставил сдк из Cocoapods версия 1.3.6

Вызов метода из примера(обращаем внимание на completeBlock метода):
```Objective-C
[VKSdk wakeUpSession:SCOPE completeBlock:^(VKAuthorizationState state, NSError *error) {
    if (state == VKAuthorizationAuthorized) {
        // Authorized and ready to go
    } else if (error) {
        // Some error happend, but you may try later
    }
}];
```
Все хорошо, теперь смотрим на этот же метод только в сдк, опять же обращаем внимание на completeBlock
```Objective-C
+ (void)wakeUpSession:(NSArray *)permissions completeBlock:(void (^)(VKAuthorizationState, NSError *))wakeUpBlock;
```

уже сейчас можно заметить что completeBlock в обеих примерах выглядит немного так по разному, давайте теперь ручками напишем этот метод, но позволим XCode самому подставить нам completeBlock нажав на нем Enter и посмотрим на результат
![screen shot 2015-11-13 at 19 16 29](https://cloud.githubusercontent.com/assets/2759167/11152434/1b7009fa-8a3b-11e5-8c74-67e03f137623.png)
Не очень похоже на то что в примере, имеем ошибку, по этому предлагаю изменить метод таким образом:
```Objective-C
+ (void)wakeUpSession:(NSArray *)permissions completeBlock:(void (^)(VKAuthorizationState state, NSError *error))wakeUpBlock;
```
тогда код подставиться как в примере и эроров не будет.
Хотя код из примера тоже работает потому что автор передает в блок нужные объекты...

**Comment by mblyk** [comment]
Там же еще нет проверки на nil wakeUpBlock. Если передать nil - падение

**Comment by Dreddik** [comment]
Не могу написать что-нибудь адекватное, чтобы вас не обидеть. Простите.

**Comment by Dreddik** [comment]
@Sh1mor1nka если вы недавно изучаете Obj-C, вам следует узнать, что Xcode часто оставляет неименованными параметры для блоков. Вы сами туда должны написать имена параметров, на что вам намекает компилятор словами "Parameter name omitted".

**Comment by Dreddik** [comment]
@mblyk я не могу придумать ни единого сценария, в котором вам необходимо проигнорировать результат метода `wakeUpSession...`. Возможно, вы неправильно используете SDK

**Comment by Sh1mor1nka** [comment]
@Dreddik Роман я без каких либо претензий, просто я за 3 с лишним года программируя на Objective-C, знакомясь с разными SDK ни разу не встречался с такой инициализацией блока, и мне показалось странно что разработчики SDK которые якобы должны облегчить жизнь другому разработчику создают метод который надо вызвать, дождаться ошибки, дописать свои имена параметров, и только потом он будет работать.

По поводу того что писал @mblyk . У меня например в ``completeBlock``` ничего не происходит потому что на моменте инициализации меня не интересует результат авторизации. Я сдк использую только для шаринга и получения информации о пользователе.
