### ISSUE TITLE
Кэш токена мешает

### ISSUE THREAD

**Issue by rostislawk** [VKCOM/vk-ios-sdk#317]
Использую oauth-авторизацию VK (1.3.7). Сразу хочу сказать, что мне не нужна возможность кэширования токена, потому что нужно получать всегда актуального пользователя (т.е. который в данный момент залогинен). Из-за кэширования сразу несколько проблем:
Предусловие - я получил токен аккаунта А.
1) Если я вылогинился из приложения VK, то я могу использовать этот токен в своем приложении, причем он не считается истекшим. Таким образом создается эффект того, что мое приложение против воли пользователя использует аккаунт ВКонтакте. 
2) Если я зашел в VK с помощью аккаунта Б, то из-за кэшированного аккаунта я не могу никак воспользоваться новым аккаунтом.

Поэтому прошу вас сделать возможность работы без кэша, и чтобы SDK мог отдавать токен текущего аккаунта (и не отдавать токен, если в ВК аккаунт вылогинен). Если мне понадобится кэширование аккаунта, то я смогу его для себя сделать.

**Comment by Dreddik** [comment]
Можете хоть каждый раз после инициализации sdk вызывать `forceLogout`, только это в большинстве случаев вызовет плохой пользовательский опыт. Телефон это больше личная вещь, чем общественная, и у большинства пользователей всегда будет один аккаунт.

**Comment by rostislawk** [comment]
Выходит нужно делать forceLogout не только при инициализации, а и после каждого получения и обновления токена.

**Comment by Dreddik** [comment]
Его делать в принципе не нужно, учитывая, что я написал выше. Достаточно добавить кнопку "выйти", в которой будет вызываться указанный метод.

**Comment by rostislawk** [comment]
Ну я делаю не приложение с постоянным логином в ВК, а приложение с функционалом типа нажми кнопку поделиться в ВК, которое направляет на OAuth-авторизацию. И согласитесь, если в моем приложении делать forceLogout после каждого получения токена, то это больше на костыль похоже, хоть и решает проблему

**Comment by Dreddik** [comment]
Ещё более костыльно будет, если пользователь перед каждой публикацией будет вынужден разрешать ему доступ

**Comment by rostislawk** [comment]
а если пользователь Б, который нажмет кнопку поделиться в ВК, напишет что-то на стене пользователя А, который успел выйти из приложения ВК, то это - хороший пользовательский опыт?  Тут пользователю Б просто не дается шанса. Есть ли способ сделать хорошо пользователю Б, не заставляя при этом пользователя А перед каждой публикацией делать запрос?
