### ISSUE TITLE
Авторизация через Vk

### ISSUE THREAD

**Issue by alexopryshko** [VKCOM/vk-ios-sdk#319]
Пытаюсь сделать авторизацию 
let sdkInstanse = VKSdk.initializeWithAppId(Settings.vk_app_id)
sdkInstanse.registerDelegate(self)
VKSdk.authorize(Settings.vk_options)
Если установлено vk приложение все ок, если его нет, то в логах 
-canOpenURL: failed for URL: "vkauthorize://authorize" - error: "(null)" (понятно т.к. приложения нет).
Но webview не открывается. Что я не учел?

**Comment by Dreddik** [comment]
uiDelegate

**Comment by alexopryshko** [comment]
Да, спасибо. Посмотрел в примере
