### ISSUE TITLE
Проблемы с presentedViewController и SFSafariViewController

### ISSUE THREAD

**Issue by iwheelbuy** [VKCOM/vk-ios-sdk#321]
Назначаю делегата ```VKSdkUIDelegate``` реализую метод
```
- (void) vkSdkShouldPresentViewController:(UIViewController *)controller
{
    FirstController *firstController = (FirstController *)[UIViewController firstController];
    if (firstController != nil && [firstController isMemberOfClass:[FirstController class]])
    {
        [firstController presentViewController:controller];
    }
}
```
где ```FirstController``` мой главный контролер, в котором я хочу показывать всплывающие контролеры (каптча там или авторизация в сафари).
Внутри FirstController я реализую метод:
```
- (void) presentViewController:(UIViewController *)controller
{
    if (self.presentedViewController != nil)
    {
        [self dismissViewControllerAnimated:YES completion:^{
            DLog(@"спрятал");
            [[UIViewController firstController] presentViewController:controller animated:YES completion:^{
                DLog(@"показал");
            }];
        }];
    }
    else
    {
        [self presentViewController:controller animated:YES completion:^{
            DLog(@"показал");
        }];
    }
}
```
В методе я проверяю, показан ли сейчас какой-то контролер. Если показан - прячу старый показываю новый. Если не показан - сразу показываю новый.

Проблема только со случаем, когда какой-нибудь контролер показан. Я прячу старый контролер и показываю ```SFSafariViewController ```. И он показывается абсолютно пустой. Просто белый экран. Я пытался подменить ```SFSafariViewController ``` любым другим контролером внутри метода ```- (void) vkSdkShouldPresentViewController:(UIViewController *)controller``` и любой другой контролер показывается без проблем.

Хотелось бы узнать, почему так происходит с ```SFSafariViewController ```

**Comment by Dreddik** [comment]
Даже управляющих элементов нет? Возможно какой-то баг от apple, а может, презентуется что-то неверно

**Comment by iwheelbuy** [comment]
Закрою тему, думаю проблема в SFSafariViewController.
