### ISSUE TITLE
Не получается авторизоваться если не установлено приложение "VK App".

### ISSUE THREAD

**Issue by mr-noone** [VKCOM/vk-ios-sdk#324]
Я авторизуюсь в приложении при помощи:
```objectivec
[VKSdk authorize:@[@"wall", @"messages"] withOptions:VKAuthorizationOptionsUnlimitedToken];
```
Если на устройстве установлено приложение "VK App" авторизация проходит нормально.
Но если его нет в консоль выводится сообщение:
```
-canOpenURL: failed for URL: "vkauthorize://authorize" - error: "(null)"
```
и ничего больше не происходит.

Версия SDK 1.3.8
Проверял на iOS 8.4.1 & 9.1

**Comment by Dreddik** [comment]
#319
