### ISSUE TITLE
Настройки языка ответа

### ISSUE THREAD

**Issue by solariserj** [VKCOM/vk-ios-sdk#325]
В iOS 9 автоматически язык ответа на запрос не зависит от системного.
исправляется ручной установкой : 
   [notificationReq setPreferredLang:@"ru"];

И работает в iOS 8: автоматическое  изменение языка ответа при смене системного языка устройства.

**Comment by Dreddik** [comment]
В последней версии всё должно быть хорошо

**Comment by Dreddik** [comment]
Какую версию вы используете?

**Comment by solariserj** [comment]
беру с pods

**Comment by solariserj** [comment]
можете закрывать 
обновил  с 1.3.4  на 1.3.8.  все работает
