### ISSUE TITLE
Не сохраняется токен

### ISSUE THREAD

**Issue by aspcartman** [VKCOM/vk-ios-sdk#326]
После каждого перезапуска  `+wakeUpSession:completeBlock:` завершается только с `Initialized` стейтом. После этого я делаю `+authorize:`, полноценно пользуюсь SDK, все нормально, перезапускаю и опять. Что может быть не так?

**Comment by Dreddik** [comment]
Какая версия sdk?
Какой scope?

**Comment by aspcartman** [comment]
`1.3.7`, обновился до `1.3.8`, проблема осталась. 
```objc
 @[ @"photo", @"email", @"friends", @"photos", @"wall" ];
```

Может ли это быть связано с делегатами? Я дерегистрирую UI и General делегатов после получения токена. 

```objc
[sdk unregisterDelegate:(id <VKSdkDelegate>) delegate];
sdk.uiDelegate = nil;
```

**Comment by aspcartman** [comment]
Прошу закрыть, дебагом выяснилось, что код просто не находил `photo` пермишена в токене, ибо такого пермишена и не существует вообще. Наверное стоит такой кейс как-то обработать. Спасибо за быстрый ответ! =)

**Comment by Dreddik** [comment]
Для таких случаев предусмотрены константы, типа VK_PER_PHOTOS

**Comment by aspcartman** [comment]
@Dreddik однако проверка в рантайме не помешает, мало ли пользователи SDK что-то хитрое делают, стоит дать честный отлуп. Перешел на константы).

**Comment by Dreddik** [comment]
Смысл есть

**Comment by D-Link13** [comment]
У меня возникла такая же проблема
Версия SDK - 1.4.4
scope - ["notify", "wall", "offline"]
