### ISSUE TITLE
Push-уведомления

### ISSUE THREAD

**Issue by maxbpro** [VKCOM/vk-ios-sdk#327]
Не пойму что не так с настройками пуш-уведомлений.
Тестировал отправку пуш-уведомлений со своего сервера - все в порядке. Залит pem в приложение на сайте правильный, без запроса пароля.

С помощью метода account.registerDevice зарегистрировал device. Вот мой запрос

{
"device_id" = "ABCD6085-E50C-46C1-9BA3-9B6BE67A255C";
"device_year" = 2015;
sandbox = 1;
settings = "{\"msg\":\"on\",\"friend\":\"off\"}";
"system_version" = ios;
token = ca95c9d53b6007ff49ef8aa6f75ec85c17c081ce1bc15616ea635dddca21880f;
}

Получил в ответ response = 1

Уведомлений нет.

Если запросить

account.getPushSettings, передав device_id ABCD6085-E50C-46C1-9BA3-9B6BE67A255C, то ответ

response: {
disabled: 1,
subscribe: 'msg, chat, friend',
conversations: {
count: 0,
items: []
}
}

При этом, если специально отправить неверный device_id, то ответ аналогичный. Не пойму что не так...

**Comment by Dreddik** [comment]
А сейчас нормально работает? С тех пор кое-что менялось в системе пушей и настроек пушей

**Comment by alex-yatsenko-sas** [comment]
Уже пару дней мучаю пуши, пользовался до этого старой версией API 3.0 там не было device_id, где его брать?

**Comment by Dreddik** [comment]
@alex-yatsenko-sas  Сгенерировать и запомнить

**Comment by alex-yatsenko-sas** [comment]
Не совсем понял, это device_id это то что раньше передавалось в виде токена? Это одно и тоже из этого метода?
`- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken  `
В доках написано:

тут https://vk.com/dev/account.getPushSettings
строка, устаревший параметр, доступен только для версий меньше 5.31

тут https://vk.com/dev/account.registerDevice
строка, обязательный параметр

Я правильно понимаю что это старый token это теперь device_id ?

**Comment by Dreddik** [comment]
Токен - это токен, device_id - это идентификатор устройства, который вы генерируете и запоминаете

**Comment by alex-yatsenko-sas** [comment]
странно документация говорит что token это уникальный идентификатору устройства как и device_id

![2016-02-24 16 07 02](https://cloud.githubusercontent.com/assets/17453594/13287657/d9f031e0-db10-11e5-910e-68dc99360ab8.png)
![2016-02-24 16 07 07](https://cloud.githubusercontent.com/assets/17453594/13287664/e0723f18-db10-11e5-9ab6-c24cc5859004.png)

**Comment by Dreddik** [comment]
Ещё раз: токен вы получаете в iOS в методе делегата `application:didRegisterForRemoteNotificationsWithDeviceToken:`
А device_id генерируете руками и запоминаете. 
Неужели так сложно объясняю, что три раза нужно повторять?

**Comment by AllDmeat** [comment]
Роман, добрый день. Поднимаю закрытую тему, так как настроить пуши в VK — вечная головная боль, а саппорт разводит руками и отправляет к тебе.

Намутил PEM с сертификатом и ключиком (без пароля). Залил в сэндбокс. Не заработало.
Попробовал в качестве пароля к ключу указать «защищенный ключ» из настроек приложения в VK. Залил — не работает. Опять залил PEM без пароля на ключе — не работает. Спустя полчаса-час пуши начали ходить.

Как? Почему не сразу?

В интерфейсе настроек приложения в VK вообще не понятно, залился ключик или нет. Точнее видно, что он когда то был залит, но как давно — неизвестно. «Загружен», и всё тут. Новый, старый или какой — ничего не понятно. Никаких оповещений по завершении загрузки — окно загрузки пропадает и сиди, гадай, что произошло — успешно залился или что-то пошло не так.
Почему бы просто не подписать дату и время последней заливки PEM ключика? Или его название.

Почему нигде при заливке ключика не говорится, что его надо экспортировать без пароля? Ведь стандартное поведение OS X при экспорте ключика — запрос пароля. Всё, что говорит VK при заливке PEM файла — «Подробная документация расположена на сайте Apple». Прекрасно!

Второй день бьюсь с ключиком для продакшна. Всё сгенерил, залил, а пуши не ходят. Тестирую ключики с сертификатами сторонними утилитами (Pusher тот же) — пуши долетают. Заливаю к вам — не долетают.

В конечном итоге, вопросы такие:
1. Как скоро после заливки нового PEM в настройках приложения пуши начнут доходить до приложения?
2. Что за поле «защищенный ключ» в настройках приложения? Когда и для чего его использовать?
3. В API-методе account.getPushSettings мне приходит поле «disabled» со значением «1». В описании к этому полю написано «отключены ли уведомления». Тогда почему мне ходят уведомления на сэндбокс и в официальное приложение VK? И как поменять значение этого поля? Через account.setPushSettings не получается.

Большое спасибо.

**Comment by Dreddik** [comment]
В интерфейсе надо заливать два pem сертификата: sandbox и production. Если у вас универсальный, то в данный момент надо заливать один сертификат в оба поля. Экспортировать сертификат надо без пароля. В pem сертификате должен быть сам сертификат и приватный ключ (это можно посмотреть в текстовом редакторе, открыв в нём pem). В последнее время, osx при экспорте сертификата экспортит и ключ тоже.
Когда регистрируете production, проверьте, что не передаёте флаг sandbox в account.registerDevice

**Comment by AllDmeat** [comment]
Ответ крутой и развёрнутый, спасибо.
А вопросы 1, 2 и 3?

**Comment by Dreddik** [comment]
1) Не предсказуемо, возможно сразу, возможно с задержкой. Связано с кэшем пушилки. Возможно, в интерфейсе будет выводиться лог последних событий
2) Для серверных запросов
3) Значит в настройках приложения в пункте "Push-уведомления" стоит "Не подключены", либо сертификат не загружен. Убедитесь, что обращаетесь к нужному app_id
