### ISSUE TITLE
VKSdk processOpenURL обрабатывает token с задержкой

### ISSUE THREAD

**Issue by iwheelbuy** [VKCOM/vk-ios-sdk#328]
Авторизация происходит через VK App. Там нажимаем разрешить и нас возвращает в приложение и срабатывает метод:
```
- (BOOL) application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options
{
    [VKSdk processOpenURL:url fromApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]];
    return YES;
}
```
В логах посмотрели, токен приходит.
Сразу после этого метода (не понятно зачем) вызывается
```
- (void) vkSdkShouldPresentViewController:(UIViewController *)controller
```
И мы соответственно показываем контролер с авторизацией через Safari. Контролер даже еще не успевает прогрузиться, как срабатывает наш заветный метод:
```
- (void) vkSdkAccessAuthorizationFinishedWithResult:(VKAuthorizationResult *)result
```
Экспериментальным путем было выяснено, что ДАЖЕ если мы откажемся показывать контролер с авторизацией через Safari, то спустя пару секунд после ```[VKSdk processOpenURL:url fromApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]];``` сработает ```- (void) vkSdkAccessAuthorizationFinishedWithResult:(VKAuthorizationResult *)result```.

Поэтому нам приходится либо ставить костыли внутри ```[VKSdk processOpenURL:url fromApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]];```, либо после срабатывания ```- (void) vkSdkAccessAuthorizationFinishedWithResult:(VKAuthorizationResult *)result``` прятать presentedViewController, если он вдруг есть.

Когда у нас нормальный интернет, проблема случается очень редко, но случается. А вот сейчас тестируем на EDGE и проблема происходит постоянно

**Comment by iwheelbuy** [comment]
P.S. пробовали на 1.3.8 и 1.3.7

**Comment by Dreddik** [comment]
Примерно понятна проблема, подумаю, что можно сделать

**Comment by iwheelbuy** [comment]
Опять начал сталкиваться с этой проблемой неожиданно. Но теперь уже на шустром WiFi...

**Comment by Dreddik** [comment]
Должно быть хорошо в версии 1.3.16
Обратите внимание на новый метод делегата
```
- (void)vkSdkAuthorizationStateUpdatedWithResult:(VKAuthorizationResult *)result;
```
Он вызывается после того, как подгрузились данные о пользователе (ранее, данные о пользователе были доступны в vkSdkAccessAuthorizationFinishedWithResult)
