### ISSUE TITLE
Как правильно работать с методами secure?

### ISSUE THREAD

**Issue by tropindv** [VKCOM/vk-ios-sdk#329]
Хочу уточнить как правильно работать с методами secure после авторизации на клиенте.
Мне нужен метод secure.addAppEvent. тут прочитал https://vk.com/dev/secure.addAppEvent что метод можно использовать только с сервера.
дальше прочитал тут про схему вызова с сервера https://vk.com/dev/secure_how_to.
последовательность действий такая:
1. на клиенте вызывается метод sdk [VKSdk authorize:authPermissions]
2. после успешной авторизации вызывается обработчик vkSdkAccessTokenUpdated( VKAcessToken * ) newToken oldToken:( VKAccessToken *)oldToken. Тут newToken заполнен информацией. Какие из полей VKAccessToken надо передать серверу для подстановки в запрос:
'https://oauth.vk.com/access_token?client_id=' + CLIENT_ID + '&client_secret=' + CLIENT_SECRET + '&v=5.40&grant_type=client_credentials'  
в CLIENT_ID подставляю _accessToken
в CLIENT_SECRET подставляю _secret
правильные поля подставляю или нет?

**Comment by Dreddik** [comment]
CLIENT_ID и CLIENT_SECRET, это "ID приложения" и "Защищенный ключ" из раздела настроек приложения

**Comment by tropindv** [comment]
спасибо за ответ. у нас так и было первоначально сделано. взяли из настроек приложения. но после авторизации на клиенте, при выполнении запроса на сервере происходит вот такая ошибка: "error_description": "User authorization failed: access_token was given to another ip address.". если на клиенте не авторизовываться и просто выполнить запрос на сервере, то ошибки нет. в связи с этой ошибкой стал уточнить тут про вариант подстановки в CLIENT_ID и CLIENT_SECRET данных полученных после авторизации на клиенте.

подскажите тогда как избавиться от ошибки "error_description": "User authorization failed: access_token was given to another ip address."

сейчас такое впечатление что есть две авторизации:
на клиенте и на сервере, и они конфликтуют, в результате чего происходит эта ошибка

**Comment by tropindv** [comment]
подскажите как правильно авторизацию делать на клиенте чтобы можно было выполнять серверные методы через сервер? чтобы не было ошибки User authorization failed: access_token was given to another ip address

**Comment by Dreddik** [comment]
Как я себе это вижу:
1) вы авторизируете пользователя в приложении, отправляете токен себе по защищенному соединению
2) методом https://vk.com/dev/secure.checkToken проверяете валидность пользователя, отмечаете, что он рабочий
3) авторизируете сервер через CLIENT_ID и CLIENT_SECRET из раздела настроек приложения, сохраняете выданный серверный токен
4) в нужный момент, сервер со своим токеном вызывает https://vk.com/dev/secure.addAppEvent с user_id = id пользователя, которого вы ранее проверили

**Comment by tropindv** [comment]
в первом пункте клиентский acces_token моему серверу отдаю для проверки его через secure.checkToken?

**Comment by Dreddik** [comment]
Да. Потом его можно хранить для всяких действий пользователя, хотя лучше не хранить

**Comment by tropindv** [comment]
спасибо. попробуем.

**Comment by tropindv** [comment]
попробовали использовать secure.checkToken. не решило проблему. ошибка  User authorization failed: access_token was given to another ip address появляется все равно.

некоторые запросы secure.addAppEvent проходят. но большинство или половина завершается с ошибкой. это так происходит и если проверять клиентский токен и если не проверять. сейчас не вижу разницы. закономерность не выявлена.

пробовали также получать серверный токен каждый раз перед вызовом  secure.addAppEvent.

пробовали после получения, закэшировать серверный токен на определенное время и делать secure.addAppEvent с ним.

ни один из вариантов не оказался лучше остальных. иногда везет и проходят 5 запросов из десяти. иногда один из десяти.

все еще не понятно как правильно работать с secure.addAppEvent.
не понятно какой должна быть верная схема связи клиентского приложения, использующего sdk + нашего сервера + вк secure api.

можете ли подсказать еще варианты решения?

**Comment by Dreddik** [comment]
Простите, я совсем про вас забыл.
Так почему, в итоге, с серверным токеном не получилось, вы можете рассказать подробнее? Он тоже ругается на "access_token was given to another ip address"?

**Comment by tropindv** [comment]
в конце остановились на варианте авторизации сервера через запрос

выполнять запрос 'https://oauth.vk.com/access_token?client_id=' + CLIENT_ID + '&client_secret=' + CLIENT_SECRET + '&v=5.40&grant_type=client_credentials'

после авторизации сервер закешивает полученный токен на сутки.

с этим токеном вызываем secure.addAppEvent.

сообщения ативности постятся, но ошибка  "User authorization failed: access_token was given to another ip address." все равно случается.

закономерность так и не выявили.

сейчас задача потеряла актуальность. тему можно закрывать.
