### ISSUE TITLE
NSInvalidArgumentException при initializeWithAppId

### ISSUE THREAD

**Issue by ZhukV** [VKCOM/vk-ios-sdk#330]
Вообще не могу понять, в чем именно проблема.
SDK подключен через Pod.

Вроде все норм. В симуляторе все работает, проблем нету. А вот на самом устройстве вылазит ошибка:

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[VKSdk initializeWithAppId:]: unrecognized selector sent to class 0x1004d0578
```

Вот собственно и строка инициализации:

```objective-c
self.vkSdk = [VKSdk initializeWithAppId:VK_APPLICATION_IDENTIFIER];
```

Может кто-то знает, в чем именно проблема. Спасибо.

**Comment by Dreddik** [comment]
Попробуйте очистить DerivedData
