### ISSUE TITLE
Документация не соответствует текущей версии. При попытке авторизации без установленного приложения ничего не происходит

### ISSUE THREAD

**Issue by abpopov** [VKCOM/vk-ios-sdk#331]

**Comment by Dreddik** [comment]
Читайте внимательнее https://github.com/VKCOM/vk-ios-sdk/blob/master/README.md

**Comment by abpopov** [comment]
смотрел на vk там старые методы.
А по какой причине может не открываться сафари если нет приложения vk?

**Comment by Dreddik** [comment]
Не задан uiDelegate

**Comment by dimanicholson** [comment]
Ты можешь нормально написать, как задать этот делегат? Вопрос о том, что Сафари не открывается поднимался уже не раз. В фейсбучном фреймворке нет вообще никаких костылей по этому поводу, все сразу работает. 
let sdkInstance = VKSdk.initializeWithAppId("1111111")
sdkInstance.registerDelegate(self)
sdkInstance.setUiDelegate — такого метода просто нет, компилятор показывает ошибку

**Comment by Chiliec** [comment]
```swift
let sdkInstance = VKSdk.initializeWithAppId("1111111")
sdkInstance.registerDelegate(self)
sdkInstance.uiDelegate = self // WTF, почему так, действительно?!
```

**Comment by dimanicholson** [comment]
Блин, ну можно же без сеттеров и геттеров в 2016
```swift
sdkInstance.uiDelegate = self;
```
Там реально создается впечатление, что это метод, который не просто присваивает значение проперти экземпляра, а делает что-то еще, чтобы его зарегистрировать.
> You can register as much common delegates, as you need, but an UI delegate may be only one. After the SDK initialization you should register delegates separately:
