### ISSUE TITLE
Авторизация работает частично

### ISSUE THREAD

**Issue by icasualfatboy** [VKCOM/vk-ios-sdk#332]
Делаю авторизацию, тестирую на двух девайсах. На обоих установлено приложение VK, но переход в приложение VK происходит только на одном устройстве, на втором устройстве при вызове функции авторизации ничего не происходит, полная тишина. А если приложение снести, то в браузер для авторизации не перекидывает, возвращает ошибку, что происходит на обоих девайсах 

    -canOpenURL: failed for URL: "vkauthorize://authorize" - error: "(null)"

Код следующий

Контроллер

    class FirstScreen: UIViewController, VKSdkDelegate, {
    var scope = [VK_PER_EMAIL]
    
    let sdk = VKSdk.initializeWithAppId("1111111")
        sdk.registerDelegate(self)
       
        VKSdk.wakeUpSession(scope, completeBlock: ({
            
            (state:VKAuthorizationState, error:NSError!) -> Void in
            
            if state == .Authorized {
                
                print("we are authed")
                
            } else {
                
                print("we are not authed")
            }
            
        }))

    }

    func vkSdkAccessAuthorizationFinishedWithResult(result: VKAuthorizationResult!) {
    
        if VKSdk.accessToken() != nil {
            
            performVKRequest()
            
        } 
    
    }

    func vkSdkUserAuthorizationFailed() { }
    func vkSdkAccessTokenUpdated(newToken: VKAccessToken!, oldToken: VKAccessToken!) {
    
        print("TokenUpdated")
        
    }
    
    func performVKRequest() {
        
        var mail:String?
        
        print("vkSdkAccessTokenUpdated")
        
        if VKSdk.accessToken() != nil {
            
            var uEmail = VKSdk.accessToken().email
            print(uEmail)
            mail = uEmail
        }
        
        var param = [VK_API_FIELDS: "id,first_name,last_name, photo_max_orig"] as Dictionary  <NSObject, AnyObject>
        
        let request:VKRequest = VKApi.users().get(param)
        
        request.executeWithResultBlock ( {
                (response) -> Void in
                print(response) 
        }, errorBlock: {
                (error) -> Void in
                print("error")
                
        })
        
    }

АппДелегат
https://s.mail.ru/4bnK6EJnj4kx/img-2015-12-08-22-37-10.png

урл схема
https://s.mail.ru/62p2LhiQg3AP/img-2015-12-08-22-15-48.png

апптранспорт
https://s.mail.ru/5grrdEF7FSEV/img-2015-12-08-22-26-05.png

эплекейшенкверис
https://s.mail.ru/NjdYr5sMQjCi/img-2015-12-08-22-16-53.png

В чем ошибка ?

**Comment by icasualfatboy** [comment]
апдейтнул со скрином аппделегата

**Comment by icasualfatboy** [comment]
нашел ошибку в использовании метода в аппделегате, заменил на правильный метод, но приложение на обоих девайсах ведет себя так же
метод поставил вот такой https://s.mail.ru/3hfxs71DaKB3/img-2015-12-08-22-54-08.png

**Comment by iwheelbuy** [comment]
А может дело в том, что надо оба этих метода реализовать в AppDelegate?
Ведь там для разных iOS разные методы нужны.
Вот что написано в пояснении к SDK: [*читать здесь*](https://github.com/VKCOM/vk-ios-sdk#using-sdk)
