### ISSUE TITLE
Есть ли возможность получить список групп (пабликов) юзера?

### ISSUE THREAD

**Issue by rinat-enikeev** [VKCOM/vk-ios-sdk#334]
Здравствуйте! 

Спасибо за SDK. У меня короткий вопрос - можно ли с помощью SDK получить список групп (пабликов), в которых авторизованный пользователь является создателем или администратором? 

Спасибо!

**Comment by iwheelbuy** [comment]
Читали [здесь](https://vk.com/dev/groups.get)? Если не читали, то почитайте!

На что обратить внимание:

**filter** - список фильтров сообществ, которые необходимо вернуть, перечисленные через запятую. Доступны значения *admin*, *editor*, *moder*, groups, publics, events. По умолчанию возвращаются все сообщества пользователя.
При указании фильтра *admin* будут возвращены сообщества, в которых пользователь является администратором, *editor* — администратором или редактором, *moder* — администратором, редактором или модератором.

**Comment by Dreddik** [comment]
Спасибо, @iwheelbuy
