### ISSUE TITLE
VK авторизация ломает авторизацию FB SDK

### ISSUE THREAD

**Issue by archiewahwah** [VKCOM/vk-ios-sdk#336]
Добрый день

В ходе тестирования выяснилось, что добавление в проект авторизации через ВК ломает работающую авторизацию в ФБ. 

Авторизация в ФБ выполняется в апп делегате следующим методом

    func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
        
    return FBSDKApplicationDelegate.sharedInstance().application(application, openURL: url, sourceApplication: sourceApplication, annotation: annotation)
           
    }

Авторизация ФБ работает так - вызывается сафари окно, в котором пользователь грантит пермишен, после этого окно пропадает и происходит возврат в приложение.

В случае, если в аппделагат добавить метод 

    func application(app: UIApplication, openURL url: NSURL, options: [String : AnyObject]) -> Bool {     
        
    VKSdk.processOpenURL(url, fromApplication: UIApplicationOpenURLOptionsSourceApplicationKey)
    return true
    }

то тогда фейсбучное сафари окно при при гранте пермишеннов не убирается и при нажатии внутри окна происходит рефреш контента сафари. В случае же, если метод выше закоментить, то все работает ок, но тогда не работает авторизация ВК.

Как это можно фиксануть ?

**Comment by Dreddik** [comment]
Подучите Swift, и вызывайте их в одном методе

**Comment by maxprig** [comment]
Отлавливайте url, который приходит, и в зависимости от него вызывайте функцию фэйсбука или контакта)

**Comment by Chiliec** [comment]
~~~swift
func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
    FBSDKApplicationDelegate.sharedInstance().application(application, openURL: url, sourceApplication: sourceApplication, annotation: annotation)
    VKSdk.processOpenURL(url, fromApplication: sourceApplication)
    return true
}
~~~
