### ISSUE TITLE
Apple rejected our build because of 10.6

### ISSUE THREAD

**Issue by nullday000** [VKCOM/vk-ios-sdk#337]
Just got a rejection from Apple. What to do, how to fix it?

The reason is rule 10.6:

10.6 - Apple and our customers place a high value on simple, refined, creative, well thought through interfaces. They take more work but are worth it. Apple sets a high bar. If your user interface is complex or less than very good, it may be rejected

10.6 Details

We noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience. Specifically, the user is taken to Safari when attempting to login using VKontakte.

Next Steps

Please revise your app to enable users to sign in or register an account in the app. 

We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page. 

Resources

For additional information on the Safari View Controller API, please see the webpage, What’s New in Safari.

**Comment by Dreddik** [comment]
What version of VK SDK you used?
The latest version supports SafariViewController

**Comment by wacumov** [comment]
Та же самая проблема, то же сообщение от Apple. 
Версия SDK - 1.3.12
Решения, которые предлагались ранее (#64), я так понимаю, были актуальны для предыдущих версий. Метода vkSdkIsBasicAuthorization в протоколе VKSdkDelegate больше нет. 
Что можно сделать для решения проблемы?

**Comment by Dreddik** [comment]
@wacumov У вас показывается safari view controller?

**Comment by wacumov** [comment]
Да. Я так понимаю, это происходит в методе vkSdkShouldPresentViewController

**Comment by Dreddik** [comment]
@wacumov тогда аппелируйте к тому, что у вас используется Safari View Controller. Скриншоты какие-нибудь прислали?

**Comment by wacumov** [comment]
Нет, они скриншоты не присылали.
Предлагаете просто написать, что я и так использую Safari View Controller и отправить им такой скриншот? 
![img_1313](https://cloud.githubusercontent.com/assets/2861871/13889251/9c3638a6-ed56-11e5-9eb1-c7dd85de7fd9.PNG)

**Comment by wacumov** [comment]
Они же ведь, полагаю, и так видели это окно

**Comment by Dreddik** [comment]
@wacumov Это не safari view controller, это просто webview. Хотелось бы увидеть ваш код авторизации

**Comment by wacumov** [comment]
[VKSdk authorize:SCOPE];

**Comment by Dreddik** [comment]
А скриншот ваш из iOS 9?

**Comment by wacumov** [comment]
нет, iOS 8. Сейчас пришлю из iOS 9

**Comment by wacumov** [comment]
вот этот из iOS 9
![img_1559](https://cloud.githubusercontent.com/assets/2861871/13889452/b2547084-ed57-11e5-888d-b584800a669b.PNG)

**Comment by Dreddik** [comment]
Попробуйте приложить этот скриншот, и написать, что уже используете SFSafariViewController

**Comment by wacumov** [comment]
Да, так и сделаю. Спасибо за оперативные ответы!
