### ISSUE TITLE
Проблема VK Share Activity на iOS 8.4 (регрессия)

### ISSUE THREAD

**Issue by richardoti** [VKCOM/vk-ios-sdk#339]
Здравствуйте. Обнаружил возможную ошибку в SDK. Если кто-то из пользователей SDK сталкивался с чем-либо подобным, прошу написать в этой теме.

Описание ошибки:
![artboard 1](https://cloud.githubusercontent.com/assets/8013017/11966460/fd5a3030-a90c-11e5-87fa-e50803683f69.png)

Условия:
VKSDK  последняя на момент написания, 1.3.1
iOS 8.4 (Simulator)

Как повторить:
1. Открыть Share диалог
2. Выбрать VK Activity
3. Ввести логин+пароль
4. Разрешить приложению доступ
***С этого момента проявляется ошибка
5. Приложение возвращается на предыдущий экран и всё ещё пишет, что пользователь не авторизован.
6. Если закрыть Activity и открыть снова, то появляется экран 6, т.е. необходимый.

На iOS 9+ всё работает отлично.

В версии iOS SDK 1.2.2 этой ошибки нет.

**Comment by Dreddik** [comment]
Да, такое возможно. Подумаю, что можно сделать

**Comment by Dreddik** [comment]
#328

**Comment by makoni** [comment]
#348 проблема в этом. Там же и решение + pull request
