### ISSUE TITLE
Проблема авторизации без приложения VK 

### ISSUE THREAD

**Issue by solariserj** [VKCOM/vk-ios-sdk#340]
Здраствуйте 
- если для авторизации использую 
[VKSdk authorize:SCOPE withOptions:VKAuthorizationOptionsDisableSafariController];  то постоянно запрашиваются  права при смене сети. 
- если использую  
  [VKSdk authorize:SCOPE withOptions:VKAuthorizationOptionsUnlimitedToken];   на iOS8 все нормально, а iOS9 когда нет приложения VK то нельзя перелогинится на другой аккаунт. даже когда делаю forceLogut все равно запоминает предыдущую сессию   
Как можно авторизироваться ? При авторизации использую  

  [[VKSdk initializeWithAppId:VKAppID apiVersion:@"5.40"] registerDelegate:self];
   [[VKSdk instance] setUiDelegate:self];
    [VKSdk wakeUpSession:SCOPE completeBlock:^(VKAuthorizationState state, NSError *error) {
        if (state == VKAuthorizationAuthorized) {
            [self startWorking];
        } else {
            if(state == VKAuthorizationInitialized){
                [VKSdk authorize:SCOPE withOptions:VKAuthorizationOptionsUnlimitedToken];
            }else{
                if (!error) {
                    [VKSdk authorize:SCOPE withOptions:VKAuthorizationOptionsUnlimitedToken];
                }
            }
        }
    }];

- (void)vkSdkShouldPresentViewController:(UIViewController *)controller {
    if(![VKSdk vkAppMayExists])
        [self.currentVC/*.navigationController.topViewController*/ presentViewController:controller animated:YES completion:nil];
}

**Comment by solariserj** [comment]
наверное какая то проблема в SFSafariViewController (показывает белый экран, даже на тестовом примере) исправил закомментировав использование SFSafariViewController

//    }
//    else if (safariEnabled && [SFSafariViewController class] && instance.authState < VKAuthorizationSafariInApp) {
//        SFSafariViewController *viewController = [[SFSafariViewController alloc] initWithURL:urlToOpen];
//        viewController.delegate = instance;
//        [viewController vks_presentViewControllerThroughDelegate];
//        instance.presentedSafariViewController = viewController;
//
//        instance.authState = VKAuthorizationSafariInApp;

**Comment by Dreddik** [comment]
Возможно это ваша проблема http://stackoverflow.com/a/34190924/1271424
