### ISSUE TITLE
Проблема с SFSafariViewController

### ISSUE THREAD

**Issue by alexeysergeevich** [VKCOM/vk-ios-sdk#341]
Какая-то непонятная ошибка
SafariServices подключен (установлен как Optional), в linker flags включен -ObjC, valid architecture: arm64, armv7, armv7

Помогите, пожалуйста. А то я уже отчаялся совсем с этой проблемой

![screen shot 2015-12-24 at 02 19 13](https://cloud.githubusercontent.com/assets/8135187/11986846/9d53f2dc-a9e5-11e5-9042-3eed99bf5812.png)

**Comment by Dreddik** [comment]
Картинка не завелась

**Comment by alexeysergeevich** [comment]
Да, прошу прощения. Исправил

**Comment by Dreddik** [comment]
Пробовали почистить DerivedData?
По сути, если фреймворк подключен, не должно быть сильно важно, required он или optional.

**Comment by Dreddik** [comment]
Если у вас больше одного таргета, проверьте, что подключили SafariServices во всех, включая тесты

**Comment by alexeysergeevich** [comment]
Почистил, не помогло, к сожалению

Таргет один

Видимо, я установил sdk неправильно

**Comment by Dreddik** [comment]
А как вы подключаете?

**Comment by alexeysergeevich** [comment]
Перетаскивал в проект фреймворки из какого-то из предыдущих релизов сдк и вставлял строку импорта в header файле

Теперь решил, через cocoapods

Вот содержимое подфайла:

# Uncomment this line to define a global platform for your project
 platform :ios, '6.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'ParseStarterProject' do
pod 'Google/SignIn'
pod "VK-ios-sdk"
end

В командной строке набрал pod install

Но теперь совсем беда :)

![screen shot 2015-12-24 at 03 11 30](https://cloud.githubusercontent.com/assets/8135187/11987214/2674a9fc-a9ec-11e5-9b67-3b2d424f0bb5.png)

**Comment by alexeysergeevich** [comment]
Переустановил сдк правильно. Предыдущие проблемы решились, добавилась новая:
Может, вы знаете как исправить?

![screen shot 2015-12-25 at 15 35 02](https://cloud.githubusercontent.com/assets/8135187/12002887/3bd31d7e-ab1d-11e5-8ff7-4f463a4461e2.png)

**Comment by Dreddik** [comment]
Вы компилируете в iOS 9 SDK?

**Comment by alexeysergeevich** [comment]
Если я правильно понял вопрос, то нет, ios SDK 8.4

**Comment by alexeysergeevich** [comment]
Если в этом дело, то может мне стоить установить какую-нибудь из предыдущих версий VKSdk вместо последней?

**Comment by Dreddik** [comment]
SFSafariViewController не существует в iOS SDK 8, он существует в iOS SDK 9.
Тем не менее, код будет работать на платформах ниже iOS 9 корректно.
Компилируйте новым XCode

**Comment by alexeysergeevich** [comment]
Спасибо за помощь!
Сейчас последует вопрос катастрофически глупый - достаточно будет просто нажать update в AppStore для установки XCode7? Я просто маком начал пользоваться совсем недавно

**Comment by Dreddik** [comment]
Да)

**Comment by artyomLisovskij** [comment]
Спасибо за решение!
