### ISSUE TITLE
 'VKSdk/VKSdk.h' file not found

### ISSUE THREAD

**Issue by habr** [VKCOM/vk-ios-sdk#343]
При запуске VKSDKTestApplication выходит ошибка 
/Desktop/vk-ios-sdk-master/example/VKSDKTestApplication/VKSDKTestApplication-Prefix.pch:16:13: 'VKSdk/VKSdk.h' file not found

**Comment by Ajaxy** [comment]
Ошибка может быть связана с наличием символьных ссылок, попробуйте удалить ссылки и переместить нужные файлы и папки на их место.

**Comment by ashmanov** [comment]
Аналогичная проблема: запускаю пример VKSDKTestApplication, получаю то же. Лучше бы глянуть, что там не так, а то получается, что базовый пример работы не работает из коробки, надо что-то настраивать.

**Comment by WhosYourSkady** [comment]
Если вы устанавливали SDK при помощи cocoapods попробуйте следующее:

Удалите Podfile.lock
Удалите Pods/
Удалите билбиотеку, сгенерированную cocoapods из проекта

Запустите pod install .

**Comment by iamthevoid** [comment]
Для swift (в случае импорта)  не работает import VKSdk, надо использовать import VK_ios_sdk, возможно тут надо попробовать то же имя?
