### ISSUE TITLE
Request: VKSdk.revoke()

### ISSUE THREAD

**Issue by GRIM2D** [VKCOM/vk-ios-sdk#344]
How one will logout? Should I implement this myself?
Now I'm using this:
```swift
VKAccessToken.delete("VK_ACCESS_TOKEN_DEFAULTS_KEY_DONT_TOUCH_THIS_PLEASE")
```

This key found from `VK_ACCESS_TOKEN_DEFAULTS_KEY`

**Comment by Dreddik** [comment]
Try VKSdk.forceLogout()
