### ISSUE TITLE
Приложение ВК открывается, но загрузка данных не происходит

### ISSUE THREAD

**Issue by alexeysergeevich** [VKCOM/vk-ios-sdk#345]
Добрый день, в очередной раз)

Тестирую приложение на устройстве - при нажатии на кнопку логина, открывается приложение вконтакте, но далее, к сожалению, наблюдаю просто активити индикатор и больше ничего не происходит

Есть какие-то идеи с чем это может быть связано?

**Comment by Dreddik** [comment]
iPhone или iPad?

**Comment by maxprig** [comment]
У меня на IPad mini такая же проблема.

**Comment by alexeysergeevich** [comment]
Вообще приложение будет выпущено только в версии для iPhone, но запускаю я его на iPad

**Comment by Dreddik** [comment]
В приложении VK для iPad проблема, поэтому и происходит бесконечная загрузка. В этом году обновится приложения для iPad, проблема исправится

**Comment by alexeysergeevich** [comment]
Спасибо большое! А то я уже приуныл, ибо не было ни малейшего понятия что же идет не так

**Comment by maxprig** [comment]
Вся ирония, увы, в том, что с SDK одной из прошлых версий с текущим приложением VK для IPad все нормально загружается.

**Comment by Dreddik** [comment]
@maxprig а с какой из прошлых версий?

**Comment by Dreddik** [comment]
@maxprig вообще, проблема в приложении, но мне прям интересно стало

**Comment by maxprig** [comment]
define VK_SDK_VERSION @"1.2.2"
define VK_SDK_API_VERSION @"5.23"

Вот с этим SDK все работает)

**Comment by Dreddik** [comment]
@maxprig спасибо *__*

**Comment by maxprig** [comment]
@Dreddik :3
