### ISSUE TITLE
No error/success delegate call if user rejects access to an email

### ISSUE THREAD

**Issue by Sega-Zero** [VKCOM/vk-ios-sdk#346]
Prerequisites:
1. iOS 8
2. No vk app installed
3. No login cookies saved

Steps to reproduce:
1. Call `[VKSdk authorize:@[@"email", @"photos"]]`
2. Pass login and password into UIWebView instance form
3. In the app authorize dialog click "Deny access to email" link
4. Click Allow button

Expected result:
An error callback to a delegate(s), since no token is present in the `redirect_uri`.

Actual result:
No callback to a delegate(s), the app is stuck in waiting for an answer.

____
I'm not sure, but, probably, there have to be an extra `else` branch in `webView:shouldStartLoadWithRequest:navigationType:` when checking for blank.html

**Comment by Dreddik** [comment]
Check in version 1.3.11

**Comment by Sega-Zero** [comment]
Seems like fixed, also, a task is actually a duplicate of #347
