### ISSUE TITLE
Похоже, не удается получить картинку юзера ВК

### ISSUE THREAD

**Issue by alexeysergeevich** [VKCOM/vk-ios-sdk#350]
Добрый день, в очередной раз

Прикрепляю скрин кода, на месте где брейкпоинт стоит - выдает ошибку, unexpectedly found nil while unwrapping an optional value
Токен получаю вроде, все должно быть в порядке

с "photo_50" тоже не работает

![screen shot 2016-01-14 at 14 49 16](https://cloud.githubusercontent.com/assets/8135187/12323675/7edcbb50-bace-11e5-8f7d-960ef07e02d7.png)

**Comment by Dreddik** [comment]
В parameters нужно передавать [ VK_API_FIELDS : "photo_50,photo_100" ]

**Comment by alexeysergeevich** [comment]
Спасибо!

Сразу задам небольшой вопрос, а то у меня в ближайшие несколько часов не будет возможности проверить работу кода:
После  этого:
 let photo: AnyObject = uInfo[0].objectForKey("photo_50")//photo_50//
                    
Правильно ли я получаю картинку? Мне ее надо как PFFile в Parse загрузить

                    var avatar = UIImage()
                    if let data = NSData(contentsOfURL: photo as! NSURL) {
                        avatar = UIImage(data: data)!
                    }
                    
                    let imageData = UIImagePNGRepresentation(avatar)
                    let imageFile = PFFile(name:"user_avatar.png", data:imageData!)

**Comment by Dreddik** [comment]
Вам лучше подойдёт NSURLSession
https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSession_class/#//apple_ref/occ/instm/NSURLSession/dataTaskWithRequest:completionHandler:

**Comment by alexeysergeevich** [comment]
О, никогда этим не пользовался. Спасибо, буду разбираться

**Comment by Dreddik** [comment]
Есть успех?

**Comment by alexeysergeevich** [comment]
Да, картинку получил, все получилось

На всякий случай код, вдруг кто наткнется на проблему:

  var avatar = UIImage()
                    var imageFile = PFFile()
                
                    var imgURL: NSURL = NSURL(string: photo as! String)!
                    let request: NSURLRequest = NSURLRequest(URL: imgURL)
                    NSURLConnection.sendAsynchronousRequest(
                        request, queue: NSOperationQueue.mainQueue(),
                        completionHandler: {(response: NSURLResponse?,data: NSData?,error: NSError?) -> Void in
                            if error == nil {
                                
                                
                                avatar = UIImage(data: data!)!
                                
                                imageFile = PFFile(name:"user_avatar.png", data:data!)
                            
                                
                            }
                    })

**Comment by alexeysergeevich** [comment]
Правда сработало на одном устройстве, а при запуске на другом получаю вот это:

![screen shot 2016-01-15 at 16 05 01](https://cloud.githubusercontent.com/assets/8135187/12353708/38d34726-bba2-11e5-96fc-5539a397561c.png)

Строку с ошибкой xcode не показывает

В прошлый раз это решалось через Clean. Сейчас нет
