### ISSUE TITLE
Ошибка trap EXC_BREAKPOINT

### ISSUE THREAD

**Issue by alexeysergeevich** [VKCOM/vk-ios-sdk#352]
Не успел дописать коммент к предыдущей темы до ее закрытия

Логин сработад на одном устройстве, а при запуске на другом получаю вот это:

![screen shot 2016-01-15 at 16 05 01](https://cloud.githubusercontent.com/assets/8135187/12353789/aeda3fba-bba2-11e5-923c-6b7cf26236db.png)

Строку с ошибкой xcode не показывает

В прошлый раз это решалось через Clean. Сейчас нет

**Comment by Dreddik** [comment]
Если вы не специалист в Swift, то незачем и браться тогда. Я за вас программу не напишу и не отлажу. У некоторых пользователей может быть аватарка, у некоторых не может. Некоторые поля в апи могут приходить, некоторые нет. Я вам подсказал уже, как можно что-то сделать, дальше сами.

**Comment by alexeysergeevich** [comment]
Да, все справедливо. Прошу прощения за глупый вопрос

Оказалось у пользователя не оказалось аватара в вк, хотя уверял, что все есть
