### ISSUE TITLE
swift 2.0: "Type 'classname' does not conform to protocol 'VKSdkDelegate'"

### ISSUE THREAD

**Issue by Matsepura** [VKCOM/vk-ios-sdk#354]
@required методы указал

    class VKFirstTableViewController: UITableViewController, VKSdkDelegate {

    let friendsInRequest = 5
    var friendsArray = NSMutableArray()
    
    var scope = [VK_PER_EMAIL]
    
    @IBAction func button(sender: AnyObject) {
        
        VKSdk.authorize(scope)
        
    }

    
    override func viewDidLoad() {
        super.viewDidLoad()
        let sdk = VKSdk.initializeWithAppId("111111")
        sdk.registerDelegate(self)
        
        
        //        let sdkInstance = VKSdk.initializeWithAppId("5231898")
        //        sdkInstance.registerDelegate(self)
        //        sdkInstance.uiDelegate = self
        VKSdk.authorize(["friend"])
        //        getFriendsFromServer()
        //        letOAuht2()
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
    // MARK: - OAuth2

    func vkSdkAccessAuthorizationFinishedWithResult(result: VKAuthorizationResult!) {
        print(result)
        print("Hello")
    }
    
    func vkSdkAccessTokenUpdated(newToken: VKAccessToken!, oldToken: VKAccessToken!) {
        print("vkSdkAccessTokenUpdated")
    }

    func vkSdkUserAuthorizationFailed(result: VKError!) {
        print(result)
    }
    
    func vkSdkTokenHasExpired(expiredToken: VKAccessToken!) {
        print("vkSdkTokenHasExpired")
    }
    
Что не так делаю?

**Comment by Chiliec** [comment]
```swift
func vkSdkUserAuthorizationFailed(result: VKError!) {
    print(result)
}
```
где Вы такое нашли? В протоколе этот метод описан без параметров
```swift
public func vkSdkUserAuthorizationFailed() {}
```

**Comment by Matsepura** [comment]
Прошу прощения, моя ошибка
