### ISSUE TITLE
VKDocs.h not found

### ISSUE THREAD

**Issue by npenzin** [VKCOM/vk-ios-sdk#356]
Поставил через Cathage. Подрубаю .framework и при билде в VKApiModels.h и VKApi.h говорит not found VKApiDocs.h
Закомментил импорты, сбилдилось, но не уверен, что не упадет в рантайме

**Comment by Chiliec** [comment]
Та же фигня! Пришлось жестко зафиксировать версию в Cartfile.

**Comment by VyacheslavAlexeev** [comment]
@Chiliec а какую версию зафиксировали?

**Comment by Chiliec** [comment]
Особо не экспериментировал, взял какая перед обновлением была, прошлогодняя ещё, 1.3.8

**Comment by Dreddik** [comment]
Должно быть окей

**Comment by npenzin** [comment]
@Dreddik сработало, спасибо:)
