### ISSUE TITLE
Авторизация под другим пользователем

### ISSUE THREAD

**Issue by StasevichJack** [VKCOM/vk-ios-sdk#358]
В приложении необходимо авторизоваться через vk. Моя авторизация:
 <pre> [VKSdk wakeUpSession:SCOPE completeBlock:^(VKAuthorizationState state, NSError *error) {
        if (state == VKAuthorizationAuthorized) {
            [self login];
        } else if (state == VKAuthorizationInitialized) {
            [VKSdk authorize:SCOPE];
        } else if (error) {
        }
    }]; </pre>
Вопрос такой: как мне поменять пользователя при авторизации? Если при выходе из приложения делать `[VKSdk forceLogout];` каждый раз придется утверждать разрешения
![jyzw5ps54q0](https://cloud.githubusercontent.com/assets/9402284/12581101/9e01f4f2-c445-11e5-8a62-86960633dfb3.jpg)
А если сразу делать `[VKSdk authorize:SCOPE];` без вызова `wakeUpSession` для проверки сессии - тогда не срабатывают делегаты.

**Comment by diejmon** [comment]
Тоже интересует этот вопрос.

**Comment by Aft3rmathpwnz** [comment]
Присоединяюсь к вопросу

**Comment by ashmanov** [comment]
Присоединяюсь к вопросу

**Comment by Dreddik** [comment]
Тут есть 3 возможных варианта:
1) у пользователя VK app. Тогда пользователя никак не сменить, только если он сам зайдёт в VK app и перелогинится
2) у пользователя нет VK app, и iOS 9. Тогда у него будет кнопка выйти
3) у пользователя нет VK app и не iOS 9. Тогда forceLogout. 
Но вообще не рекомендуется делать какие-либо перелогины, или пытаться делать forceLogout кроме как для при нажатии кнопки "выход из аккаунта" в приложении, потому что вы только добавите людям боли.
Мы считаем, что устройство для пользователя индивидуально, и пользователи, использующие несколько аккаунтов, скорее исключения, чем правило.
