### ISSUE TITLE
Ошибка: this application has no right to authorize

### ISSUE THREAD

**Issue by iwheelbuy** [VKCOM/vk-ios-sdk#359]
Using VK-ios-sdk (1.3.12)

Вот такую ошибку получает один из пользователей. Больше никто не жаловался, хотя установок было уже больше 1000. У человека установлен jailbreak. Не удалось найти материалов по данной ошибке.

Сможете прояснить ситуацию?

![Image of Yaktocat](https://cs7054.vk.me/c540109/v540109338/14202/jKa4C5HhyGc.jpg)

**Comment by N-Code-N** [comment]
Надо удалить VK-твики

**Comment by iwheelbuy** [comment]
Интересно. Буду знать!
