### ISSUE TITLE
Autorisation

### ISSUE THREAD

**Issue by diretix** [VKCOM/vk-ios-sdk#361]
Кароче я танцевал неделю с бубном с этой авторизацией но в итоге зарешал все что мог, авторизация проходит без проблем, но при выходе из сафари или проги вк в моем приложении остается этот спойлер с кнопкой enter. и при нажатии cancel ниче не происходит. вот код : 

    func vkSdkShouldPresentViewController(controller: UIViewController!)
    {
        sd.requestedScope = VKAccessToken().permissions
        sd.text = "You are already logged in"
        self.presentViewController(sd, animated: true, completion: nil)
    }

   и на кнопке пока что это

    if VKSdk.vkAppMayExists()
    {
                    VKSdk.authorize(["VK_PER_WALL"])
     }else{
                    VKSdk.authorize(["VK_PER_WALL"], withOptions: VKAuthorizationOptions.UnlimitedToken)
     }  

как его закрыть? 
все остальное по инструкции, как надо.

**Comment by Ksen17** [comment]
знаю что не ответ 
но можешь пожалуйста рассказать как ты добился нормальной авторизации 
я тоже пляшу с бубном и пока пляски не приносят ничего
заранее спасибо

**Comment by ferz222** [comment]
У меня при авторизации через сафари, если нажать кнопку отмена, ни один делегат не срабатывает. Кто знает как это побороть?

**Comment by diretix** [comment]
почти все починил, но все равно есть траблы, вот [ФАЙЛ С КОДОМ](https://drive.google.com/file/d/0B-5zXuxEf8WnUGZGVU1lMjRMVzQ/view?usp=sharing) внутри все описано.
