### ISSUE TITLE
Открытие диалога шаринга в официальном приложение через ссылку

### ISSUE THREAD

**Issue by nullproduction** [VKCOM/vk-ios-sdk#363]
Знаю про UIActivityViewController и VKShareDialogController, но интерересует есть ли возможность открыть диалог шаринга в официальном приложение через url. Например если из своего приложение сделать открытие ссылки [vk://vk.com/id1](url) произойдет открытие страницы Дурова в официальном приложение, если ли что-то подобное для диалога шаринга? Вижу в докуменатиции LSApplicationQueriesSchemes - vk-share, но непонятно то ли это и как им пользоваться.

**Comment by Dreddik** [comment]
Предусмотрен только share extension, куда можно запихивать разные вещи, типа ссылок, текста, картинок, видео. Пользователь сам решает, куда постить.
Поддерживается iOS 8 и выше.
