### ISSUE TITLE
shareDialog.vkImages не загружает фото

### ISSUE THREAD

**Issue by ADevelopStudio** [VKCOM/vk-ios-sdk#365]
При шаринге фото из Маркета - не могу дождаться загрузки его в окно диалога.  Возможно, что-то делаю не так.
Моя фотка: 
                                {
                    "album_id" = "-53";
                    date = 1454028732;
                    height = 400;
                    id = 398954857;
                    "owner_id" = "-113131459";
                    "photo_130" = "https://pp.vk.me/c631125/v631125822/e6fe/uCAUXY850cc.jpg";
                    "photo_604" = "https://pp.vk.me/c631125/v631125822/e6ff/5u1MawLQMn0.jpg";
                    "photo_75" = "https://pp.vk.me/c631125/v631125822/e6fd/RblA75Sd7pE.jpg";
                    "photo_807" = "https://pp.vk.me/c631125/v631125822/e700/jvGINIQQ2R8.jpg";
                    text = "";
                    "user_id" = 1050822;
                    width = 610;
                }
добавляю вот так: 
`        shareDialog.vkImages = ["-113131459_398954857"]
`

в окне диалога висит "ромашка" бесконечно.
тестовое из примера если брать: 
`shareDialog.vkImages = ["-10889156_348122347","7840938_319411365","-60479154_333497085"];`
то все нормально загружается. Возможно в маркетных фотках как то по другому?

**Comment by Dreddik** [comment]
Фотка спрятана, и происходит Access Denied

**Comment by ADevelopStudio** [comment]
Ды, я уже решил грузить ее по новой просто

**Comment by Dreddik** [comment]
Скорее всего, фотки от товаров нельзя просто так шарить, нужно прикреплять товары, а share dialog пока не умеет. Возможно, надо будет научить его :|
