### ISSUE TITLE
VK Activity всегда возвращает completed = true

### ISSUE THREAD

**Issue by flowip** [VKCOM/vk-ios-sdk#366]
Думаю это скорее всего относится к мобильному приложению VK, а не сюда. Но вероятно разработкой занимаются те же люди. 

Нет возможности определить было ли что-то расшарено через VK Activity или диалог просто открыли и закрыли.

`[activityViewController setCompletionWithItemsHandler:^(NSString *activityType, BOOL completed, NSArray *returnedItems, NSError *activityError)`
При закрытии всегда возвращаются одни и те же данные:
`activityType = "com.vk.vkclient.shareextension",
completed = true,
returnedItems = nil,
activityError = nil`

Стандартные Activity (Twitter, Facebook, сообщения, почта и т. д.) вообще не вызывают этот callback если диалог просто открыли и закрыли без расшаривания.

**Comment by Dreddik** [comment]
Посмотрим

**Comment by Dreddik** [comment]
Исправится в 2.6

**Comment by flowip** [comment]
Спасибо! Жду.
