### ISSUE TITLE
Не отрабатывает vkSdkAccessAuthorizationFinishedWithResult

### ISSUE THREAD

**Issue by artyomLisovskij** [VKCOM/vk-ios-sdk#368]
Приложение успешно идет на авторизацию по:
`[VKSdk authorize:@[VK_PER_EMAIL]];`
авторизуюсь, но при возвращении в приложение
`- (void)vkSdkAccessAuthorizationFinishedWithResult:(VKAuthorizationResult *)result{`
не вызывается(поставил внутри функции и breakpoint'ы, и nslog.
Куда копать?

До этого всё работало через vkSdkReceivedNewToken.

**Comment by HiDaN4** [comment]
Делегат не забыл поставить? 
VKSdk* vkinstance = [VKSdk initializeWithAppId:@"APP_ID"];
[vkinstance registerDelegate:self];

**Comment by artyomLisovskij** [comment]
@HiDaN4 Забыл зарегистрировать, спасибо.
