### ISSUE TITLE
photos.get при запросе cover фотографии в системного альбома возвращает пустое фото

### ISSUE THREAD

**Issue by edementiev** [VKCOM/vk-ios-sdk#369]
photos.get при запросе cover фотографии системного альбома (id отрицательное) возвращает пустой список

Приходится вставлять костыль и запрашивать все фотки и потом перебирать их и искать по id

        var parameters = ["album_id":albumId, "photo_ids": photoId]
        if let aid = Int(albumId) {
            if (aid < 0) { parameters = ["album_id":albumId] }
        }
        let request = VKRequest(method: "photos.get", parameters: parameters)
        ................

**Comment by Dreddik** [comment]
Сделайте photos.getById с параметром photos = [your_id] + "_" + photoId
