### ISSUE TITLE
Не работает vksdk.authorize

### ISSUE THREAD

**Issue by Ksen17** [VKCOM/vk-ios-sdk#370]
Пытаюсь сделать логин таким образом 
`VKSdk.wakeUpSession(["wall","offline"], completeBlock: {state, error in
            print(state)
            if(state==VKAuthorizationState.Authorized){
                self.vkShare()
            }else{
                VKSdk.authorize(["wall","offline"])
                self.vkShare()
            }
        })`
если установлено мобильное приложение то при нажатие разрешить оно просто остается в приложение vk те открываются новости в вк и при повторном открытии моего приложения 
заново требует залогиниться 
при логине через safari оно так же не открывает обратно мое приложение

**Comment by HiDaN4** [comment]
Вы сделали необходимые настройки как показано здесь https://vk.com/dev/ios_sdk ?
А именно подготовка Standalone-приложения и URL-схемы в iOS приложении.

В iOS app, вы зарегистрировали делегаты? 

let vkinstance = VKSdk.initializeWithAppId("APP_ID")
    vkinstance.registerDelegate(self)
    vkinstance.setUiDelegate(self)

* в вашем closure следует изменить логику для случая если пользователь не авторизован, так как в текущем состоянии вы вызываете VKSdk.authorize метод и self.vkShare(), в то время как VKSdk.authorize начнет авторизацию и последующий вызов вашего локального метода ни к чему не приведет. Поэтому вынесите VKSdk.authorize из этого scope и вставьте в protocol method "vkSdkAccessAuthorizationFinishedWithResult"

**Comment by flashpress** [comment]
В моем случае открывается приложение VK, и если там разрешить происходит возврат в мое приложение, но при этом метод vkSdkAccessAuthorizationFinishedWithResult делегата не вызывается. Почему такое может быть? Спасибо.

**Comment by HiDaN4** [comment]
Вы скорее всего зарегистрировали только UI делегат. Вы точно вызвали метод registerDelegate ?

**Comment by flashpress** [comment]
Да, этот метод вызывается:
`[VKSdk initializeWithAppId:appId];
[VKSdk authorize:[NSArray arrayWithObjects:@"wall", @"photos", nil]];
[[VKSdk instance] registerDelegate:self];
[[VKSdk instance] setUiDelegate:self];`

**Comment by Dreddik** [comment]
Не зарегистрирована схема в Info.plist

**Comment by mercooliye** [comment]
надо зайти в проекте Xcode в info - там внизу будут url types и там добавить vk{id приложения в вк}. и МЛЯТЬ ни слова этого в документации - это камень вкашникам)))))

**Comment by RomanTruba** [comment]
Ссылка на туториал твиттера по настройке url-схемы была актуальна, но теперь перенаправляет на какое-то дерьмо.

**Comment by mercooliye** [comment]
ну да - но в чем сложность добавить как у fb сделано - там при добавлении в info.plist схема отлично региться, я написал чтобы для себя потом вспомнить - Потмоу что второй раз уже сталкиваюсь с этим - и вспоминаю только к концу дня)))

**Comment by danilovdev** [comment]
Дорогие разработчики vk, а свою нормальную документацию кто мешает написать? без ссылок на твитеры и на чужие туториалы. Это позор!
