### ISSUE TITLE
Смена пользователя при авторизации через Сафари

### ISSUE THREAD

**Issue by Nikita2k** [VKCOM/vk-ios-sdk#371]
Добрый день. 
Удалить приложение вк с устройства/попробовать на симуляторе.
Версии ос: 8, 9

Сценарий:
1. Установить тестовое приложение
2. Запросить токен 
3. Разлогиниться
4. Повторно попросить токен

**Результат:** окно с кнопками "разрешить" и "отмена" с пользователем с шага2
**Ожидаемый результат:** возможность сменить пользователя с шага2/окно для ввода логина и пароля

В данный момент `forceLogout` не обеспечивает реальный "выход", тк потом можно зайти без логина и пароля

**Comment by daddyboo** [comment]
+1

**Comment by yakovtsova** [comment]
+1

**Comment by shkrebets** [comment]
+1

**Comment by HiDaN4** [comment]
На самом деле сессия сохраняется в сафари. Пользователь должен выйти из профиля в сафари/vk app чтобы произвести авторизацию другими данными.
