### ISSUE TITLE
Можно ли проверить инициализирована sdk или нет?

### ISSUE THREAD

**Issue by nullproduction** [VKCOM/vk-ios-sdk#373]
Есть модуль Share с шарингом в вконтакте и другие соц сети. Инициализация sdk происходит в самом модуле. Есть несолько приложений в который подключается этот модуль как cocapods зависимость. При этом в одном из приложений используется vk sdk и есть своя инициализация. 

Вопрос, можно ли сделать проверку инициализированна sdk или нет, чтобы в модуле использовалась инициализация от основного приложения и если ее не существует производилиась собсвенная инициализация.

Так не работает:
```
if VKSdk.instance() == nil {
            
} 
```

Любые идеи как сделать это

**Comment by Dreddik** [comment]
Можно проверить ```VKSdk.instance().currentAppId == nil```

**Comment by nullproduction** [comment]
@Dreddik Нельзя :) При обращении к VKSdk.instance() будет креш если vkSdkInstance ноль

`ZAssert(vkSdkInstance, @"VKSdk should be initialized. Use [VKSdk initialize:delegate] method");`

**Comment by nullproduction** [comment]
Думаю стоит упоминуть что работаю из swift, хотя и в obj-с должно упасть из-за вызова  ZAssert

**Comment by nullproduction** [comment]
Thx
