### ISSUE TITLE
Получение списка друзей с русскими именами

### ISSUE THREAD

**Issue by d0ping** [VKCOM/vk-ios-sdk#375]
Запрашиваю список друзей через VKApiFriends get приходит полный список, с указанным набором полей, но у всех контактов last_name и first_name латиницей. Хотя оригинальные значения на сайте и в официальном приложении кирилицей. 
Что то нужно дополнительно указывать?

**Comment by gritsov** [comment]
У VKRequest
 - (void)setPreferredLang:(NSString *)lang;

**Comment by d0ping** [comment]
Спасибо
