### ISSUE TITLE
VKShareDialogController не отправляет содержимое, возвращается алерт с ошибкой

### ISSUE THREAD

**Issue by archiewahwah** [VKCOM/vk-ios-sdk#378]
Текст алерта : 

    An error accuired while executing your request. Please, try later.

Код шаринга

            var imgArray = [AnyObject]()
            let share = VKShareDialogController()
            share.text = "Введите текст..."
            let img = VKUploadImage(image:self.i, andParams: nil)
            imgArray.append(img)
            let link = NSURL(string: "")
            share.shareLink = VKShareLink(title: nil, link: link)
            share.uploadImages = imgArray
            share.completionHandler = { Void in
                self.dismissViewControllerAnimated(true, completion: nil)
                
            }
            self.presentViewController(share, animated: true, completion: nil)

С сетапом в приложении все нормально, другие запросы к апи работают, авторизация тоже работает. 

В чем может быть проблема ?

**Comment by Dreddik** [comment]
Может из-за пустого линка

**Comment by archiewahwah** [comment]
Пробовал заполнять линк, результат аналогичен

**Comment by Dreddik** [comment]
А можете просто сделать wall.post, минуя share dialog?

**Comment by archiewahwah** [comment]
var request = VKApi.uploadWallPhotoRequest(self.i, parameters: VKImageParameters.pngImage(), userId: 53742355, groupId: 0)
            request.executeWithResultBlock(
                {
                    (response) -> Void in
                    print(response)
                }, errorBlock: {
                    (error) -> Void in
                    print(error)
            })

Возвращает

    <VKResponse: 0x176f49a0; API response: (
        {
        "album_id" = "-14";
        date = 1458042620;
        height = 476;
        id = 405617227;
        "owner_id" = 53742355;
        "photo_130" = "https://pp.vk.me/c630225/v630225355/1b4d9/lDxuaZn0PcA.jpg";
        "photo_604" = "https://pp.vk.me/c630225/v630225355/1b4da/mycMUkyeZzg.jpg";
        "photo_75" = "https://pp.vk.me/c630225/v630225355/1b4d8/3VRCV-ecwDM.jpg";
        "photo_807" = "https://pp.vk.me/c630225/v630225355/1b4db/nFb3ER4C0RQ.jpg";
        text = "";
        width = 638;
    }
    )>

Но на стене пустота

**Comment by Dreddik** [comment]
Это не wall.post. Надо сделать запрос VKRequest.requestWithMethod("wall.post", parameters: ...)

**Comment by archiewahwah** [comment]
Запостилось после добавления пермишенна VK_PER_WALL.

С шарингом аналогично, после выдачи пермишенна заработал 

Спасибо!
