### ISSUE TITLE
Баг VKShareDialogController - не прикрепляет фото, если нет .shareLink

### ISSUE THREAD

**Issue by archiewahwah** [VKCOM/vk-ios-sdk#379]
Если у VKShareDialogController() не проперти .shareLink, то фотка, прикрепленная через uploadImages, не показывается в окне шаринга 

Вот такой код показывает в шаринге только текст

            var imgArray = [AnyObject]()
            let share = VKShareDialogController()
            share.text = "Введите текст..."
            let img = VKUploadImage(image:self.i, andParams: nil)
            imgArray.append(img)
            share.uploadImages = imgArray

Приходится делать вот так

            var imgArray = [AnyObject]()
            let share = VKShareDialogController()
            share.text = "Введите текст..."
            let img = VKUploadImage(image:self.i, andParams: nil)
            imgArray.append(img)
            let link = NSURL(string: "")
            share.shareLink = VKShareLink(title: nil, link: link)
            share.uploadImages = imgArray

**Comment by Dreddik** [comment]
Какая версия SDK?
Такой баг был, но сейчас не повторяется

**Comment by archiewahwah** [comment]
Скачивал с cocoapods. Как посмотреть там?

**Comment by Dreddik** [comment]
Cmd+Shift+O –> VKSdkVersion

**Comment by archiewahwah** [comment]
#define VK_SDK_VERSION @"1.3.12"
#define VK_SDK_API_VERSION @"5.40"

**Comment by Dreddik** [comment]
Ну обновите
