### ISSUE TITLE
После успешной авторизации через приложение повторно вызывается функция авторизации

### ISSUE THREAD

**Issue by zuganianin** [VKCOM/vk-ios-sdk#380]
Вызываем авторизацию
vkAppMayExists возвращает  true 
авторизуемся в приложении VK
после возврата в свое приложение срабатывает 

- (void)handleDidBecomeActive; 
внутри, которого

if (self.authState == VKAuthorizationExternal) {
            [VKSdk authorize:[vkSdkInstance.permissions allObjects] withOptions:vkSdkInstance.lastKnownOptions];
        }

после вызова функции открывает сафари или webview и после этого срабатывает колбек успешной авторизации.

подскажите пожалуйста, для чего необходим повторный вызов авторизации ?
чем грозит выпиливание данного участка кода?

**Comment by Dreddik** [comment]
Используется, чтобы разработчикам не нужно было повторно вызывать authorize.
Наверное, срабатывает из-за задержки с обработкой токена. 
Поменяю логику.

**Comment by zuganianin** [comment]
Спасибо

**Comment by Dreddik** [comment]
Должно быть хорошо в версии 1.3.16
