### ISSUE TITLE
Restore VK API from existing AccessToken?

### ISSUE THREAD

**Issue by guicaro** [VKCOM/vk-ios-sdk#383]
Hello:

I am trying to do a simple request using iOS SDK. I am using Swift 2.2 and iOS 9.2. I have managed to get login working and can get an accessToken, however, **when one stops the Simulator and restarts again how can one bring back the accessToken?**

I was saving this VK accessToken in ParseServer and associating it to my Parse user. Then in another of my ViewControllers where I want to get the VK profile photo I try:

```
VKAccessToken.init(token: vkToken, secret: vkSecret, userId: vkUser)
```

This last line fails (vkSecret is nil). I tried following the "Using SDK" section from your [documentation](https://vk.com/dev.php?method=ios_sdk) but that seems to be outdated as `initializeWithDelegate` method does not even exist. Thus I was trying something like this on my ViewController:

```
        VKSdk.initializeWithAppId("<MY ID HERE>")

        VKSdk.wakeUpSession(scope, completeBlock: {
        (state: VKAuthorizationState, error: NSError!) -> Void in
            if (state == VKAuthorizationState.Authorized) {
                print("*** We are authorized")

                var myUser: VKUser? = nil
                let imageVKRequest = VKApi.users().get()
                imageVKRequest.executeWithResultBlock({
                    (response: VKResponse!) -> Void in
                    myUser = (response!.parsedModel as! VKUsersArray).firstObject() as? VKUser
                    }, errorBlock: {(error: NSError!) -> Void in
                        print("\(error)")
                })
                print("\(myUser?.photo_50)")
            } else if ((error) != nil) {
                print("*** Error with VK API")
            }
        })
```
1. Should one save the access token via something like `saveTokenToDefaults` from the VKAccessToken class? If so, then how does one bring it back, maybe the `init!(token accessToken: String!, secret: String!, userId: String!)` initializer?
2. Is there a state diagram of how one should use the VK API when handling the access token?

**Comment by guicaro** [comment]
In my last comment when I say "The last line fails" I really meant to say that the line is irrelevant, it compiles fine and has no problems at runtime even if `vkSecret` is nil. However the following line returns nil for `accessToken` even if `vkToken` and `vkUser` had correct values for the `VKAccessToken.init` initializer

```
let accessToken = VKSdk.accessToken()
```

**Comment by guicaro** [comment]
I tried reseting my device in simulator and my mongoDB instance (backend for ParseServer). I wanted to test having a valid session right after login but when I navigate to the ViewController with my `VKSdk.wakeUpSession` block from above seems like the block is skipped at runtime (none of my print statements execute). My class header for that ViewController only inherits the UIViewController:

```
MyMottosViewController: UIViewController {
```

**Comment by andriko13** [comment]
A couple things you might want to do/try. 
First, you should register `MyMottosViewController` as a vkSdk delegate. Do so by appending the delegate name to the class declaration, like so:
```class MyMottosViewController: UIViewController, VKSdkDelegate {```
 or in Objective-C,
```@interface FirstViewController : UIViewController <VKSdkDelegate> {```
Remember that you need to do this in both the interface and implementation.

You then want to set up the delegate in your source code, right in between the following methods:
```
VKSdk.initializeWithAppId("<MY ID HERE>")
// your delegate stuff goes here
VKSdk.wakeUpSession(scope, completeBlock: {
```

In Objective-C, this would like like follows:
```
NSArray *SCOPE = @[VK_PER_FRIENDS, VK_PER_WALL, VK_PER_AUDIO, VK_PER_PHOTOS, VK_PER_EMAIL, VK_PER_MESSAGES];

[[VKSdk initializeWithAppId:APP_ID] registerDelegate:self]; 
[[VKSdk instance] setUiDelegate:self];
[VKSdk wakeUpSession:SCOPE completeBlock:^(VKAuthorizationState state, NSError *error) {
    if (state == VKAuthorizationAuthorized) {
        // we are authorized, do stuff here
    } else if (error) {
        // We are not authorized (possibly because of a lack of connection), display an alertview with error message
        [[[UIAlertView alloc] initWithTitle:nil message:[error description] delegate:self cancelButtonTitle:@"Ok" otherButtonTitles:nil] show];
    }
}];
```

I would also recommend testing on a real device, strange things happen on the simulator.
Hope this fixes your issue, cheers.

**Comment by thePsguy** [comment]
> I would also recommend testing on a real device, strange things happen on the simulator.

I also faced problems with wakeUpSession in the simulator for a long time. But have now realized the cause. 
Since wakeUpSession uses keychain for retrieving and storing the token, enabling `Keychain Sharing`  under `Capabilities` seems to fix the issue.

**Comment by guicaro** [comment]
Interesting, thanks @thePsguy
