### ISSUE TITLE
Указание пола при регистрации

### ISSUE THREAD

**Issue by wacumov** [VKCOM/vk-ios-sdk#384]
Здравствуйте. Мое приложение было отклонено по той причине, что при регистрации нового пользователя пол является обязательным полем. Как можно решить эту проблему?

> Hello,
> 
> Thank you for supplying that information about your app. During the review of your app we found that it was requiring the users to enter their gender at registration. For your app to be in compliance with guideline 17.2 it would be appropriate to make gender an optional selection. You can find more details about the 17.2 guideline below.
> 
> Best Regards,
> App Store Review
> 
> 17.2 Details
> 
> We noticed that your app requires users to register with personal information to access non account-based features. Apps cannot require user registration prior to allowing access to app content and features that are not associated specifically to the user.
> 
> Specifically, when we were registering for a user account within the app we found that gender was required. However, we could not find any features that required gender within the app.
> 
> We’ve attached screenshot(s) for your reference.
> 
> Next Steps
> 
> User registration that requires the sharing of personal information must be optional or tied to account-specific functionality. Additionally, the requested information must be relevant to the features.
> 
> ![temp ihqrttih](https://cloud.githubusercontent.com/assets/2861871/14010582/80aa598c-f1a7-11e5-80ff-057c95bd2c23.png)

**Comment by Dreddik** [comment]
Постараемся исправить в ближайшее время

**Comment by homocogitum** [comment]
У меня такая же проблема. Можно ли хотя бы как-то показать окно логина без возможности регистрации? Просто логин по имейлу(или телефону) и паролю.

**Comment by homocogitum** [comment]
@wacumov , вам удалось решить эту проблему с Apple?

**Comment by wacumov** [comment]
Нет, не удалось
