### ISSUE TITLE
Не подтягиваются ресурсы из VKSdkResources.bundle

### ISSUE THREAD

**Issue by jpavelua** [VKCOM/vk-ios-sdk#385]
Всем привет.  Подскажите пожалуйста, такая проблема: Шаринг-Диалог не содержит компоненты:

![2016-03-29 11 55 45](https://cloud.githubusercontent.com/assets/4697416/14102800/75db131e-f5a5-11e5-945c-b38401fd899a.png)

Подозрение падает конечно же на "невидимость" VKSdkResources.bundle , но вроде либа подключена правильно , даже в поиске по проекту видна

![2016-03-29 11 44 18](https://cloud.githubusercontent.com/assets/4697416/14102822/90fb72f6-f5a5-11e5-864b-a87f5eaaca05.png)

![2016-03-29 11 48 09](https://cloud.githubusercontent.com/assets/4697416/14102829/9e66ce86-f5a5-11e5-9267-3305b606a975.png)

![2016-03-29 11 51 25](https://cloud.githubusercontent.com/assets/4697416/14102838/abc6b7d0-f5a5-11e5-98fb-56f6ed31c6ee.png)

![2016-03-29 11 57 05](https://cloud.githubusercontent.com/assets/4697416/14102845/b4cee60e-f5a5-11e5-9785-878ae56cc45a.png)

Не поверите, сегодня нужно заливать((!!

Может ли это быть из-за пробела в названии проекта?
Заранее всем спасибо!

**Comment by Dreddik** [comment]
Вы ресурсы линкуете как библиотеку, а надо добавлять в copy bundle resources

**Comment by jpavelua** [comment]
Нижайший поклон! Появилось!
