### ISSUE TITLE
Проблема с push сообщениями

### ISSUE THREAD

**Issue by extnous** [VKCOM/vk-ios-sdk#386]
Добрый день. Приходит всего одно пуш уведомление при установки программы. Т.е. устанавливаю приложение, приходит всего одно сообщение пуш и дальше перестают приходить. Удаляю его, устанавливаю заново и также приходит всего одно сообщение и все. 
pem файлы проверял, нормально работают. Раньше пуш нормально приходил в sandbox режиме, затем перестал. Пересобрал Сертификаты для пуша и pem файлы из них и залил заново, стали приходить по 1 сообщению за установку программы так сказать.
Не подскажите в чем может быть проблема? )

**Comment by Dreddik** [comment]
Нужен I'd пользователя ВК

**Comment by extnous** [comment]
54690847 вот на этом

**Comment by Dreddik** [comment]
У вас универсальный сертификат для push-уведомлений?

**Comment by ren6** [comment]
У меня вообще пуши перестали приходить. Общаюсь с поддержкой, думают уже третий день.
Проснифал траффик из AppStore версии приложения. Сертификаты точно правильные, было все проверено через сторонние программы.
<img width="317" alt="2016-03-30 11 24 52" src="https://cloud.githubusercontent.com/assets/1678575/14136821/f729860a-f675-11e5-88bb-d4977c3a7acb.png">
vk id: 2937360

**Comment by Dreddik** [comment]
По всей видимости проблемы связаны с переходом на new provider api и http/2. Для ваших сертификатов не подцепляется apns-topic, решаем, что делать

**Comment by ren6** [comment]
о! заработали только что сами собой. Видимо вы там починили, спасибо :)

**Comment by ren6** [comment]
странно, только что пара пушей пришло и снова перестало

**Comment by ren6** [comment]
@Dreddik есть известия по этой проблеме? Очень жду, когда проблема решится

**Comment by denis-minnetdinov** [comment]
@Dreddik Роман, здравствуйте. Есть новости по этой проблеме? Спасибо

**Comment by Dreddik** [comment]
Пока нет

**Comment by ren6** [comment]
@Dreddik Нет новостей по проблеме? Или может есть способ, как обойти ее? я даже не могу сертификат старого образца сгенерировать – сейчас в developer portal генерируются sandbox+production push-сертификаты(

**Comment by Dreddik** [comment]
@ren6 на этой неделе должно быть сделано.

**Comment by denis-minnetdinov** [comment]
@Dreddik еще не сделано?

**Comment by denis-minnetdinov** [comment]
@Dreddik ?

**Comment by ren6** [comment]
Пуши приходят примерно в 5-10% сообщений. Очень странно. Но до сих пор еще не работают как следует.
