### ISSUE TITLE
Не чистится кэш, после удаления приложения(SFSafariViewController).

### ISSUE THREAD

**Issue by Beniamiiin** [VKCOM/vk-ios-sdk#388]
Добрый день.

iPhone 6s, iOS 9.3, устанавливаю свое приложение, авторизуюсь через вк(SFSafariViewController), удаляю приложение, заново ставлю, пробую еще раз авторизоваться, но вместо странички для ввода логина и пароля, открывается страница запроса разрешения для использования пермишенов для последнего залогиненого юзера. Все тоже самое делаю на устройстве с iOS 8, где используется UIWebView и такой проблемы не наблюдаю. Т.о. складывается ощущение, что SFSafariViewController кеширует данные, но как бы их почистить при удалении приложения?

**Comment by Dreddik** [comment]
Никак. SFSafariViewController использует те же куки, что и Safari, и в них влезать нельзя.

**Comment by Beniamiiin** [comment]
Хм, получается, если юзер авторизовался и потом взял удалил приложение и снова поставил, то теперь он никак не сможет вести новые данные, всегда будут использоваться сохраненные? И эту проблему надо решать, как-то локально?

**Comment by Dreddik** [comment]
Он может нажать кнопку выйти в верхнем углу. Если кнопка выйти не появляется, нужно обновить sdk, так как использовался ошибочный параметр display.

В целом, всё так, но в этом есть и плюс: если пользователь был уже авторизован в сафари в ВК, то ему не придётся вводить данные снова

**Comment by Beniamiiin** [comment]
У меня сейчас стоит версия 1.3.12, в этой версии должна быть кнопка "Выйти"?

**Comment by Dreddik** [comment]
Нет, обновитесь

**Comment by Beniamiiin** [comment]
Обновился. Я еще тут немного подебажил и возник еще вопрос.
Метод `+[VKSdk wakeUpSession:(NSArray *)permissions completeBlock:(void (^)(VKAuthorizationState, NSError *error))wakeUpBlock]` возвращает `state = VKAuthorizationAuthorized`, даже после переустановки приложения, это нормально?

**Comment by Dreddik** [comment]
Вполне возможно, т.к. токен сохраняется в keychain, и может быть прочитан вашим приложением после удаления и установки

**Comment by Beniamiiin** [comment]
Понял, спасибо.
