### ISSUE TITLE
не авторизовывается

### ISSUE THREAD

**Issue by nubideus** [VKCOM/vk-ios-sdk#394]
после VKSdk.authorize просто выплевывает:
`-canOpenURL: failed for URL: "vkauthorize://authorize" - error: "(null)"`

facebook все работает

**Comment by nubideus** [comment]
я понял надо было wakeUpSession

**Comment by nubideus** [comment]
vkSdkShouldPresentViewController не вызывается

**Comment by weet1** [comment]
у меня та же проблема при работе с VKShareDialogController:

```
VKShareDialogController *shareDialogVC = [VKShareDialogController new];
shareDialogVC.text = textString;
shareDialogVC.uploadImages = @[[VKUploadImage uploadImageWithImage:image andParams:[VKImageParameters jpegImageWithQuality:0.8]]];
[shareDialogVC setCompletionHandler:^(VKShareDialogController *dialog, VKShareDialogControllerResult result) {
    [rootViewController dismissViewControllerAnimated:YES completion:nil];
}];
[rootViewController presentViewController:shareDialogVC animated:YES completion:nil];
```

**Comment by smorodinaios** [comment]
наверняка у Вас вызывается 
`- (void)vkSdkShouldPresentViewController:(UIViewController *)controller`
но Вы его не обрабатываете

**Comment by kollapze** [comment]
@nubideus проверьте, что Вы корректно обрабатываете
`- (void)vkSdkShouldPresentViewController:(UIViewController *)controller;`

**Comment by iamthevoid** [comment]
**nubideus**, Вы сначала закрыли тикет, а потом написали в нем новый вопрос, скажите, а первый, получается, решили? Не подскажете, как?

**Comment by nubideus** [comment]
@iamthevoid я не решил вопрос. я забил и переключился на другие задачи.

кидает ошибку:
-canOpenURL: failed for URL: "vkauthorize://authorize" - error: "(null)"

vkSdkShouldPresentViewController обрабатывается **правильно**, но не вызывается.

**Comment by Dreddik** [comment]
У sdk есть два делегата, сделанные для вашего удобства, чтобы вы могли свободно показывать что нужно, где вам нужно. Это VKSdkDelegate и VKSdkUIDelegate. Первых может быть несколько, второй только один. Задавать их нужно раздельно.
```
[sdkInstance registerDelegate:delegate];
[sdkInstance setUiDelegate:uiDelegate];
```
Я не знаю, задали ли вы оба, или один, вы об этом не писали. Не знаю, какая у вас OS, и подробностей тоже не знаю.
Такие вопросы обычно игнорирую, потому что лень разбираться, и их уже десятки здесь были, одинаковых.

**Comment by nubideus** [comment]
vkSdkShouldPresentViewController вызвался.
https://github.com/VKCOM/vk-ios-sdk/issues/79#issuecomment-114848001

```
    static var vkUIDelegate = {
        () -> VKSdkUIDelegate in
        class Anonymous: NSObject, VKSdkUIDelegate {
            @objc func vkSdkShouldPresentViewController(controller: UIViewController!){
                print(123123123)
            }
            @objc func vkSdkNeedCaptchaEnter(captchaError: VKError!){
                print(123123123)
            }
        }
        
        return Anonymous()
    }()
```

раньше было 

`        vkSdk!.uiDelegate = {..}()` поэтому делегат чистился и на момент авторизации был nil

**weak** public var uiDelegate: VKSdkUIDelegate! внезапно

**Comment by iamthevoid** [comment]
Я где то наткнулся на решение а ля: 
func vkSdkShouldPresentViewController(controller: UIViewController!) {
        if !VKSdk.vkAppMayExists() {
            presentViewController(controller, animated: true, completion: nil)
        }
    }

И да, работает, только  так понимаю это костыль больше. Если не вызывать принудительно жтот метод, то не открывается контроллер с авторизацией.

**Comment by nubideus** [comment]
@iamthevoid по-другому никак

**Comment by iamthevoid** [comment]
Тогда наверное стоило бы отразить это в документации
