### ISSUE TITLE
'VKSdk.h' not found

### ISSUE THREAD

**Issue by IlyaMyasoedov** [VKCOM/vk-ios-sdk#396]
Добрый день. Я пытаюсь войти в приложение через социальную сеть ВКонтакте (приложение написано на Swift). Все классы определяются, но когда я собираю проект для тестирования на устройстве, то получаю ошибку
![2016-04-19 16 07 59](https://cloud.githubusercontent.com/assets/10130086/14640438/3c65e1ee-064a-11e6-80fc-c0b2fe5cfc98.png)

Мой проект расположен здесь https://yadi.sk/d/NUNZ5s7ir7z4S
Буду благодарен за любой совет и помощь.

**Comment by Dreddik** [comment]
Попробуйте #import <VKSdk/VKSdk.h>

**Comment by IlyaMyasoedov** [comment]
@Dreddik , спасибо за ответ!! Но к сожалению, он мне не помог. Дело в том, что сами файлы, которые внутри, XCode видит (все классы распознаются). Среда не видит саму зависимость #import <VKSdk/VKSdk.h>
![2016-04-19 17 56 32](https://cloud.githubusercontent.com/assets/10130086/14643824/89eb3c94-0658-11e6-880e-cdb99c4cc92f.png)

**Comment by dima3000** [comment]
В подсах другое названи пакета, не такое как `README.md`.
@Dreddik, можно его изменить (либо в `README.md`, либо в подсах), кстати говоря?

Попробуйте:
```swift
#import <VK_ios_sdk/VKSdk.h>
```

**Comment by Dreddik** [comment]
@dima3000 ну вот pods раньше по-другому работал, теперь почему-то так. Изменить можно

**Comment by IlyaMyasoedov** [comment]
@dima3000 , @Dreddik После измененения зависимости на 

```
#import  <VK_ios_sdk/VKSdk.h>
```
проект перестал видеть классы:

Экран моего контроллера
![2016-04-20 08 49 52](https://cloud.githubusercontent.com/assets/10130086/14664633/5b31242c-06d5-11e6-95cd-66d9c804f00b.png)

Мой Аппделегат
![2016-04-20 08 50 35](https://cloud.githubusercontent.com/assets/10130086/14664636/604ac1a2-06d5-11e6-9eaf-c19013648f0c.png)


Но сама зависимость теперь распознается 
![2016-04-20 08 51 05](https://cloud.githubusercontent.com/assets/10130086/14664645/74f9e088-06d5-11e6-83cb-5fe4c2a86461.png)

**Comment by dima3000** [comment]
Добавьте в каждый файл:
```swift
import VK_ios_sdk
```

**Comment by IlyaMyasoedov** [comment]
@dima3000, Спасибо! Этот способ сработал
