### ISSUE TITLE
В VKAuthorizationResult пропало поле user

### ISSUE THREAD

**Issue by Dalein** [VKCOM/vk-ios-sdk#400]
При удачной авторизации у объекта VKAuthorizationResult есть токен, но нет поля user - что вызывает падение приложения, если идет обращение к этому полю. Id юзера можно получить из result.token.userId, но вопрос: оттуда оно вдруг не исчезнет, как внезапно исчезло поле user?

**Comment by Dreddik** [comment]
Оно не пропало, если у вас swift, нужно объявлять его optional

**Comment by Dreddik** [comment]
Поле заполняется после вызова метода делегата `vkSdkAuthorizationStateUpdatedWithResult`
