### ISSUE TITLE
Просит авторизацию через Safari View Controller

### ISSUE THREAD

**Issue by solariserj** [VKCOM/vk-ios-sdk#405]
При ревью выдало сообщение о том что при авторизации не виден URL. Вот текст притензии

We also noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience.

Next Steps

Please revise your app to enable users to sign in or register an account in the app.

We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.

Resources

For additional information on the Safari View Controller API, please see the webpage, What’s New in Safari.

**Comment by Dreddik** [comment]
Убедитесь, что у вас последняя версия SDK, Safari давно не используется

**Comment by Dreddik** [comment]
Какие-то новости?
