### ISSUE TITLE
-canOpenURL: failed for URL: "vkauthorize://authorize" - error: "(null)"

### ISSUE THREAD

**Issue by x123y456z789** [VKCOM/vk-ios-sdk#407]
Дико извиняюсь, но я только изучать начал Obj-C и первый раз знакомлюмь с VK SDK, т. к. попросили тестовое задание выполнить...
Возникается ошибка такая, которая в теме. В чём может быть проблема? Я что-то не догоняю скорее всего, направьте плиз)

**Comment by Dreddik** [comment]
Это просто ошибка системы, на неё можно не обращать внимания

**Comment by x123y456z789** [comment]
А почему окно авторизации не выходит на симуляторе Xcode? Я думал из-за этой ошибки о_О
![jyzw5ps54q0](https://cloud.githubusercontent.com/assets/15248225/15425999/6a249294-1e94-11e6-8f84-07e73ba97181.jpg)
P. S. Мне очень стыдно за такие вопросы конечно(
