### ISSUE TITLE
Как работать с https://vk.com/dev/secure.checkToken?

### ISSUE THREAD

**Issue by iFoxxy** [VKCOM/vk-ios-sdk#411]
Добрый день!
Я вызываю авторизацию в приложении через `VKSdk.authorize([VK_PER_EMAIL,VK_PER_FRIENDS,VK_PER_WALL,VK_PER_OFFLINE])`.
Полученный в  `vkSdkAccessAuthorizationFinishedWithResult`  токен отправляю на сервер, где планирую его валидировать через secure.checkToken

Предварительно пытаюсь протестить валидацию токена и получаю вот такой результат: 
![image](https://cloud.githubusercontent.com/assets/10603050/16129100/219a0ee0-340c-11e6-96b9-4c98fbf0e31e.png)
Что я делаю не так, подскажите пожалуйста?

**Comment by bernikowich-cedoni** [comment]
Разные ID приложений?

**Comment by iFoxxy** [comment]
@bernikowich-cedoni я же нигде не указываю ID приложения при checkToken, как он может быть разным?

**Comment by Dreddik** [comment]
Консоль в dev разделе не серверное приложение, а особенное. Через него не надо пытаться что-то валидировать
