### ISSUE TITLE
Какая-то беда с парсингом на iOS10.

### ISSUE THREAD

**Issue by bernikowich-cedoni** [VKCOM/vk-ios-sdk#412]
Не могу понять, что не так. Видимо какие-то изменения с ```objc/runtime.h```.

**Comment by p-stoychek** [comment]
Подтверждаю!
VKUsersArray *array = response.parsedModel;
если посмотреть, response.json, то данные имеются, однако если взять array.items.count, то выходит пустой массив

**Comment by ren6** [comment]
Подтверждаю!
VKUsersArray *array = response.parsedModel;
если посмотреть response.json, то данные имеются, однако если взять array.items.count, то выходит пустой массив
