### ISSUE TITLE
Локализация

### ISSUE THREAD

**Issue by Agarunov** [VKCOM/vk-ios-sdk#416]
При добавление в проект VK sdk с версией 1.4.1 (с помощью cocoapods) возникает проблема при использование маркросов NSLocalizedString().
NSLocalizedString ищет строки в файлах Localisable.strings не моего проекта, а в поде vk-ios-sdk.

**Comment by Dreddik** [comment]
Обновите до 1.4.2

**Comment by Agarunov** [comment]
Заработало.
