### ISSUE TITLE
No Podfile in project directory

### ISSUE THREAD

**Issue by georgiiprok** [VKCOM/vk-ios-sdk#417]
Hello, Im trying to install this framework, but it says that no Podfile found. How to bypass this? If import this like sub-project have issue with vktests.h ( no found too) 
Thank you

**Comment by Dreddik** [comment]
Sorry, I don't understand, what you're trying to do.

**Comment by georgiiprok** [comment]
Пытаюсь добавить фреймворк в проект

**Comment by Dreddik** [comment]
Каким способом? Нужны подробности
