### ISSUE TITLE
Не реагирует на кнопки в окне авторизации

### ISSUE THREAD

**Issue by deonisiy162980** [VKCOM/vk-ios-sdk#418]
После открытия окна авторизации невозможно выйти с него ни по нажатию кнопки "Разрешить", ни по нажатию кнопки "Отмена". При нажатии "Done" окно авторизации открывается снова. Access token получен, Bundle id и App id совпадают. Как быть? 
[VK_Denis.zip](https://github.com/VKCOM/vk-ios-sdk/files/349622/VK_Denis.zip)

**Comment by Dreddik** [comment]
https://github.com/VKCOM/vk-ios-sdk#setup-url-schema-of-your-application

**Comment by deonisiy162980** [comment]
Сделал, не помогает.
