### ISSUE TITLE
Ошибка с кодировкой при регистрации через vkApp. В email %40 вместо @.

### ISSUE THREAD

**Issue by Hoderu** [VKCOM/vk-ios-sdk#419]
Запрашиваю регистрацию с подтверждением через vkApp, и после переадресации приходит строка урла в неверной кодировке. Видимо иногда не хватает removingPercentEncoding. 

Баг появляется на ipad mini 2 with retina. 
Проверил на iphone 5s, на нем все впорядке.

**Comment by Hoderu** [comment]
![wrong_email](https://cloud.githubusercontent.com/assets/8759057/16689674/238f87b8-4535-11e6-93df-5ac152814521.png)
Ожидалось hoderu@yandex.ru

**Comment by Hoderu** [comment]
![wrong_email](https://cloud.githubusercontent.com/assets/8759057/16689786/aeb70b36-4535-11e6-8db9-c4b89f6746c1.png)
Ожидалось hoderu@yandex.ru

**Comment by ren6** [comment]
@Hoderu данная проблема связана с недавним изменением метода VKUtil escapeString. Смотри https://github.com/VKCOM/vk-ios-sdk/issues/424

**Comment by Dreddik** [comment]
Должно быть исправлено

**Comment by Hoderu** [comment]
Не поправилось.
Беда проиходит на ipad mini 2(model: me814ru/a).
Версия vk app для ipad: 2.0.1
Версия  vk-ios-skd: "VK-ios-sdk 1.4.3"

**Comment by KopachevskiiYuriy** [comment]
Подтверждаю. Проблема с кодированием емейла была давно и не ломалась и не чинилась недавними правками. Видимо айпад-приложение как-то иначе кодирует данные перед передачей по url-схеме
