### ISSUE TITLE
Не реагирует на кнопки в окне авторизации

### ISSUE THREAD

**Issue by deonisiy162980** [VKCOM/vk-ios-sdk#421]
После открытия окна авторизации невозможно выйти с него ни по нажатию кнопки "Разрешить", ни по нажатию кнопки "Отмена". При нажатии "Done" окно авторизации открывается снова. Access token получен, Bundle id и App id совпадают, URL Schema в info.plist настроена. Как быть?[VK_Denis.zip](https://github.com/VKCOM/vk-ios-sdk/files/355495/VK_Denis.zip)

**Comment by G-Julia** [comment]
Аналогичная проблема.

**Comment by suzhaev** [comment]
@deonisiy162980 при нажатии "Done" окно авторизации открывается снова. , потому что вы вызываете

    ACAuthManager.sharedInstance.authorize

в методе <code>viewDidAppear</code>

**Comment by suzhaev** [comment]
@deonisiy162980 насколько я понял, вы неправильно работаете с авторизацией в делегате приложения, проверьте методы в UIApplicationDelegate

    @available(iOS 9.0, *)
    func application(application: UIApplication,openURL url: NSURL, options: [String: AnyObject]) -> Bool {
        return VKSdk.processOpenURL(url, fromApplication: options[UIApplicationOpenURLOptionsSourceApplicationKey] as! String)
    }
    
    @available(iOS, introduced=8.0, deprecated=9.0)
    func application(application: UIApplication,openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
        return VKSdk.processOpenURL(url, fromApplication: sourceApplication!)
    }

**Comment by Proxwian** [comment]
Столкнулся с той же проблемой..
