### ISSUE TITLE
Плохое качество изображений в методе wall.get в аттаче и типом "link"

### ISSUE THREAD

**Issue by sergey-makkena** [VKCOM/vk-ios-sdk#423]
Здравствуйте, в методе **wall.get** в **attachments** c link: 'page' возвращается изображение с очень низким качеством. Причем, в официальных приложениях vk качество изображений высокое. 
вот **json** который я получил:

-----------НАЧАЛО-----------
```
attachments: [{
type: 'link',
link: {
url: 'http://dogtricks....r-dlja-doma-i-ulicy',
title: 'Чем занять собаку: игры с собакой дома и на улице (20 игр), как играть с собакой на прогулке',
caption: 'dogtricks.ru',
description: 'ТОП 20 веселых игр с собакой на прогулке и дома. Прочитайте, чем занять собаку, во что можно поиграть с собакой дома и на улице',
photo: {
id: 419598105,
album_id: -2,
owner_id: 60784937,
photo_75: 'https://pp.vk.me/c633729/v633729937/38b81/kh9puh7Sc3E.jpg,
photo_130: 'https://pp.vk.me/c633729/v633729937/38b82/Kvq5VdtBEok.jpg,
photo_604: 'https://pp.vk.me/c633729/v633729937/38b83/gr7gUAEgtLo.jpg,
width: 150,
height: 83,
text: '',
date: 1468358284
},
is_external: 1
}
}],
```
-------------КОНЕЦ------------

Вот непосредственно эти изображения в низком качестве:

```
photo_75: 'https://pp.vk.me/c633729/v633729937/38b81/kh9puh7Sc3E.jpg,
photo_130: 'https://pp.vk.me/c633729/v633729937/38b82/Kvq5VdtBEok.jpg,
photo_604: 'https://pp.vk.me/c633729/v633729937/38b83/gr7gUAEgtLo.jpg,

```
Вот для проверки ссылка:
https://new.vk.com/dev/wall.get?params[owner_id]=-124839875&params[count]=5&params[filter]=owner&params[extended]=1&params[v]=5.52

Очень бы хотелось, чтобы разработчики исправили эту проблему, так как сильно портится качеcтво отображаемого контента.

**Comment by sergey-makkena** [comment]
@Dreddik стоит ждать решение этой проблемы?

**Comment by Dreddik** [comment]
Когда я смотрел на вашу проблему в первый раз, обнаружил, что в других ссылках качество изображений нормальное. Видимо, бывают проблемы с определением качества

**Comment by sergey-makkena** [comment]
Тут дело вот в чем, если добавлять ссылку в пост и указать свое изображение, то оно выходит с хорошим качеством, а если вк сам вытягивает изображение - то плохое качество.
Официальное приложение использует этот же SDK или там более прокаченный?

**Comment by Dreddik** [comment]
Ссылку тянет не SDK и не приложение, а сервер

**Comment by sergey-makkena** [comment]
Да, я это понимаю. У вас есть возможность заглянуть под капот и посмотреть какие размеры получает офф приложение через сдк? 
Что то подсказывает что сервер разделяет запросы между офф приложением и сторонними.
Я заметил, что во всех сторонних приложениях есть проблемы с качеством отображения изображений в ссылках...

**Comment by Dreddik** [comment]
Нет, ссылки везде одинаково приходят. Но я поговорю с разработчиком, ответственным за ссылки со стороны сервера

**Comment by sergey-makkena** [comment]
Спасибо, будем ждать от вас весточки :)

**Comment by Dreddik** [comment]
А как именно вы сделали тот пост, через приложение или через сайт?

**Comment by sergey-makkena** [comment]
Ту ссылку я создал через сайт.
Сейчас я создал ссылку через оф приложение с текстом: http://mail.ru - изображение не подгрузилось совсем, только текст.
Затем создал: https://mail.ru - изображение появилось.
Качество во всех случаях плохое... кроме оф приложения.

**Comment by Dreddik** [comment]
В апи есть малодокументированная фича photo_sizes. Если в ответе есть объект photo, то можно передать photo_sizes=1 и вы получите нарезанные по-разному фотки. В вашем случае, это будет вот так http://api.vk.com/method/wall.getById?posts=-124839875_5&photo_sizes=1&v=5.50
И качество картинки можно получить хорошее.
Без photo_sizes в link попадает маленькая картинка, потому что оригинал не удаётся пропорционально поресайзить.

**Comment by sergey-makkena** [comment]
Оххо! Вот это поворот :) 👍 Спасибо!
