### ISSUE TITLE
Легальность audio api

### ISSUE THREAD

**Issue by kavolorn** [VKCOM/vk-ios-sdk#426]
Здравствуйте,

Довольно давно в гугле прикрыли мой аудио плеер, который использовал официальный сдк для прослушивания музыки. Якобы на меня написали из Warner Music. В ios вообще не пустили.

Вроде как ВКонтакте ищет или уже заключила правовые отношения с владельцами музыки. Это как то может повлиять на то, чтобы мой плеер можно было опубликовать снова?

Ну и вообще интересно услышать мысли по этому вопросу, если такие есть.

**Comment by Dreddik** [comment]
Я не могу никак прокомментировать ситуацию, но вряд ли сторонние плееры будут легальны. Ведь договор заключен между ВК и правообладателями, а не между вашей компанией и правообладателями.

**Comment by kavolorn** [comment]
Я вообще никакие деньги за приложение не беру. Хочу использовать только официальный легальный API. Не является ли тогда нелегальным любое использование вашего API?

**Comment by kavolorn** [comment]
* Понял что не можете прокомментировать. Но не понимаю зачем API, который нельзя использовать)

**Comment by Dreddik** [comment]
API был давно, вряд ли его просто будут убирать.
Думаю, как раз проблема будет в том, что вы в своём приложении будете предоставлять доступ к функциям, которые по договору ВК-правообладатели должны быть платными. 
И ещё я думаю, правообладателей не будет волновать источник аудиофайлов, а наличие конкретно у вас прав на использование музыки в коммерческих или некоммерческих целях.

**Comment by kavolorn** [comment]
Ага, понял, спасибо. Если вдруг будут новости - пишите, интересно будет услышать!
