### ISSUE TITLE
Не могу авторизоваться в iOS приложении через VK SDK

### ISSUE THREAD

**Issue by PlastininA** [VKCOM/vk-ios-sdk#428]
Здравтсвуйте. Я столкнулся с проблемой : Не могу авторизоваться в iOS приложении через VK SDK. Использую язык программирования swift.

Импортировал vk sdk через obj-c мост. Выполнил все, описанные шаги для iOS.
Реализовал все делегаты.
Вставил данный код в точку вызова :

VKSdk.wakeUpSession([VK_PER_WALL, VK_PER_PHOTOS, VK_PER_OFFLINE]) { (state, error) -> Void in
if (state == .Authorized) {
print ("Authorized")
} else if ((error) != nil) {
print(error)
} else {
print ("NotAuthorized")
let scopePermissions = ["email", "friends", "wall", "offline", "photos", "notes"]
if VKSdk.vkAppMayExists() == true {
VKSdk.authorize(scopePermissions, withOptions: .UnlimitedToken)
} else {
VKSdk.authorize(scopePermissions, withOptions: [.DisableSafariController,.UnlimitedToken])
}

}

}

Открывается приложение ВК => нажимаю "разрешить использование" => все. Ничего не происходит приложение вк не закрывается, вызов делагата не происходит.
Что делать? Окажите, пожалуйста, помощь. Спасибо.

**Comment by Dreddik** [comment]
Я так понимаю, проблема решена

**Comment by yarodevuci** [comment]
таже проблема

**Comment by yarodevuci** [comment]
как решить?

**Comment by suzhaev** [comment]
@yarodevuci url-scheme настроили?

**Comment by yarodevuci** [comment]
Да все настроил по инструкции. Вылетает окно контакта жму разрешить дальше перекидывает в мое приложение и опять открывается веб вью 
Я так понял делагат который проверяет на токен ссылку и убирает веб вью не вызывается

**Comment by suzhaev** [comment]
В каком методе вызывается авторизация? случайно не во viewwillappear?

**Comment by yarodevuci** [comment]
во viewDidLoad.  Авторизация вызывается автоматически когда я делаю запрос на API

**Comment by suzhaev** [comment]
@yarodevuci а в VKSDKTestApp все работает у вас?

Скиньте либо тестовый проект либо подробнее где какие ошибки, так совсем непонятно

**Comment by yarodevuci** [comment]
Спасибо за быстрые ответы
вот мой проэкт https://github.com/yarodevuci/VKMusic
Я использую SDK на Swift но по структуре от такой же как в данном случае только на Swift. Если есть возможность посмотреть, буду очень признателен. Спасибо

**Comment by suzhaev** [comment]
@yarodevuci с вопросами о SwiftyVK лучше идти к ним, я думал вы наш используете

**Comment by yarodevuci** [comment]
а ваш SDK со Swift 3 хорошо совместим?

**Comment by poglicier** [comment]
@yarodevuci Работать можно

**Comment by erlaha95** [comment]
Добавьте в .plist файл
<key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>vk{YOUR_APP_ID}</string>
            </array>
        </dict>
    </array>
