### ISSUE TITLE
audio.get не возвращает все аудиозаписи

### ISSUE THREAD

**Issue by rsimenok** [VKCOM/vk-ios-sdk#430]
Собственно как получаю свои аудио:
мой id 13189080
``` Objective-C
VKRequest *audioReq = [VKApi requestWithMethod:@"audio.get" andParameters:@{VK_API_OWNER_ID : myid}];
[audioReq executeWithResultBlock:^(VKResponse *response) {
//
} errorBlock:^(NSError *error) {
//
}];
```

Пример ответа от SDK (обратите внимание на названия первых пары песен)
```
<VKResponse: 0x79e96910; API response: {
    count = 1424;
    items =     (
                {
            artist = "Big Pun";
            date = 1469483718;
            duration = 255;
            "genre_id" = 3;
            id = 456239107;
            "owner_id" = 13189080;
            title = "Fire Water";
            url = "https://psv4.vk.me/c6158/u238856122/audios/d0c3a9d4b03b.mp3?extra=QNQIdQHu4I-e6uf7Mhc_CFc8CcZ5JnYfxWpNh2puWs9ZWneqSBThPYF7CNJ9HPofV5bIXwYIiprKLI59Pqd5R7NCv8YhPbAZKfX0nyLVZvHIUPVN2wE6YACJNfuDT3-ilA3lKx5Pt1o";
        },
                {
            artist = "Detsl aka Le Truk ";
            date = 1469193473;
            duration = 194;
            "genre_id" = 3;
            id = 456239104;
            "lyrics_id" = 343998460;
            "owner_id" = 13189080;
            title = "Made in Brazil";
            url = "https://cs7-1v4.vk-cdn.net/p24/8cabacf50269f4.mp3?extra=M2WJSGg8_mOncbKZa4pus46yhrcyi6p0OOsFQJSBM-H8ZEf_TI1Ty7qnw-FGhSh-pKrXGI8YShTPmdaTO6OvkV6m7OWrtPgt2YE0bH6fbch5iC8ymFfIPV9GoOwQKC2ewsveO34FvOg";
        },
                {
            artist = "Die Antwoord";
            date = 1469189837;
            duration = 288;
            "genre_id" = 22;
            id = 456239103;
            "owner_id" = 13189080;
            title = "Banana Brain";
            url = "https://cs7-2v4.vk-cdn.net/p7/b1b6b16bb6bccd.mp3?extra=d3G7PDUlIUMtUO4HIEtXsvhBkd8M6XH2ArJROmZqYpWklBWJlKBJjg6QFjf2YExi4yOwXdXEP1ZpET7-HhjbqO_fLrXgjpulu90VAgBK9n8sxE1Bhih2jX0aV9Nyj9bGj2Ry0pK4KsA";
        },
....
}
```

Сравним с тестовым API [vk.com/dev/audio.get](https://new.vk.com/dev/audio.get?params[owner_id]=13189080&params[need_user]=0&params[count]=7&params[v]=5.53)
```
response: {
count: 1424,
items: [{
id: 456239109,
owner_id: 13189080,
artist: 'Big Pun',
title: 'Wishful Thinking',
duration: 240,
date: 1469484550,
url: 'https://cs7-4v4.v...7slp_uU8Iq3eOtOxYj8',
lyrics_id: 344601637,
genre_id: 3
}, {
id: 456239108,
owner_id: 13189080,
artist: 'Big Pun',
title: 'My Turn',
duration: 228,
date: 1469484047,
url: 'https://psv4.vk.m...ZtfQPu511rN_QGZy7hs',
genre_id: 3
}, {
id: 456239107,
owner_id: 13189080,
artist: 'Big Pun',
title: 'Fire Water',
duration: 255,
date: 1469483718,
url: 'https://psv4.vk.m...Mv-EQHr5lV7gKk4Ztg4',
genre_id: 3
}
....
}
```

Поле count в обоих случаях показывает одинаковое количество аудиозаписей, но запрос из SDK вернул только 1201 из 1424 обещаных. Что это может быть?

**Comment by Dreddik** [comment]
Изъятые аудиозаписи могут не возвращаться в API, но count будет больше

**Comment by rsimenok** [comment]
@Dreddik так а что значит изъятые?) в VK для андроид они отображаются, и на сайте я их послушать могу...

**Comment by Xotab4ik** [comment]
Изъятые не отображаются, все верно. Но у меня та же проблема, аудиозаписи на сайте в списке есть, прослушать могу, поделиться могу, даже в других приложениях они отображаются, а в моем нет

**Comment by vik12J** [comment]
Аналогичная проблема audio.get, так же из приложения возвращает не все песни, с сайта в тестовом API возвращает все. Разобрался кто нибудь в чем проблема?

**Comment by rsimenok** [comment]
@vik12J @Xotab4ik Парни а попробуйте кто-то не через SDK бросать запрос на через AFNetworking или нативно, кому как нравится :) , интересно что он вернет, а то у самого руки не доходят...

**Comment by vik12J** [comment]
У меня через запрос через URL с токеном в XML возвращает не все песни.

**Comment by astrochili** [comment]
@rsimenok десктопное приложение под OS X без SDK, через AFNetworking такая же история. Да что там приложения, достаточно просто в браузере POST запрос отправить - там та же история, результат будет отличаться от тестового API. Не очень прозрачно получается: для API аудиозаписи изъяты, а вебе присутствуют.

**Comment by rsimenok** [comment]
устроим в официальном репозитории VK SDK обсуждение как обмануть API?)

**Comment by kimihailv** [comment]
@rsimenok довольно легко: используем прямую авторизацию https://vk.com/dev/auth_direct, используя app_id и secret какого-либо официального клиента вк, они легко гуглятся. На днях столкнулся с этой проблемой.

**Comment by yarodevuci** [comment]
@rsimenok А Можно подробнее как это сделать ? Я получил токен а что с ним делать то?

**Comment by rsimenok** [comment]
@yarodevuci сори, о чем речь идет?)

**Comment by yarodevuci** [comment]
@rsinmenok речь об обмане VK API подставившись под оф приложение. Вод допустим я знаю эпп айди и секрет фразу прошел прямую авторизацию и в ответ получил токен и айди. А как дальше быть с ним? Через SDK я не могу зайти.

**Comment by OwnageIsMagic** [comment]
@yarodevuci https://vk.com/dev/first_guide
