### ISSUE TITLE
Двойной dismiss после нажатия кнопки Done в SFSafariViewController

### ISSUE THREAD

**Issue by ryuzmukhametov** [VKCOM/vk-ios-sdk#432]
Здравствуйте, 

Хотел бы описать следующую ситуацию с которой я столкнулся при интеграции VK-ios-sdk (1.4.2) в свой проект.
Я переопределяю метод vkSdkShouldPresentViewController в котором я делаю вызов:
[myViewController presentViewController:safariControllerFromParameter animated:YES completion:nil]; 
После показа SFSafariViewController и нажатия на кнопку Done у меня происходит двойной dismiss для SFSafariViewController и для myViewController.
Если вместо нажатия на кнопку Done нажать на Cancel, то dismiss только один для SFSafariViewController.
Считается ли такое поведение корректным и должен ли я самостоятельно обрабатывать эту ситуацию?

Спасибо

**Comment by Dreddik** [comment]
Вы делаете present в контроллере, который тоже presented?

**Comment by ryuzmukhametov** [comment]
Да, myViewController уже presented.

**Comment by Dreddik** [comment]
А Done нажимаете на странице или в верхнем левом углу?

**Comment by ryuzmukhametov** [comment]
В верхнем углу.

**Comment by ryuzmukhametov** [comment]
Мне помогает зануление делегата с помощью строчки:
safaryViewController.delegate = nil;
Т.о. игнорируется вызов в VKApi.h:
```
- (void)safariViewControllerDidFinish:(SFSafariViewController *)controller {
   [[self class] processOpenURL:[NSURL URLWithString:@"#"] validation:NO];
  }

```
И программа начинает работать без двойного dismiss. Возможно в этом решении есть какие-то подводные камни.

**Comment by Dreddik** [comment]
Это точно не решение)

**Comment by ryuzmukhametov** [comment]
Это точно :)
