### ISSUE TITLE
Не проходит авторизация через Safari

### ISSUE THREAD

**Issue by Xotab4ik** [VKCOM/vk-ios-sdk#433]
Язык программирования - Swift

Кое-как добился вызова Safari View, но после нажатия на "Разрешить"

![2016-08-06 15 11 58](https://cloud.githubusercontent.com/assets/16893175/17455906/95b36efa-5bf0-11e6-947a-ecf37d7ed318.png)

Появляется следующая ошибка. Наблюдается как в симуляторе, так и на реальном устройстве

**Comment by BdevNameless** [comment]
Та же история. VK-ios-sdk (1.4.4).

**Comment by Xotab4ik** [comment]
@BdevNameless и что-то мне подсказывает, что ответа мы либо не дождемся, либо он будет очень не скоро. Пожалуйста, если найдешь решение, сообщи в данном треде

**Comment by BdevNameless** [comment]
@Xotab4ik , вроде справился с проблемой.
Во-первых https://github.com/VKCOM/vk-ios-sdk#setup-url-schema-of-your-application, переименовал URLSheme на "vk3123**".
Так же изменил импорт VKSdk в коде с "#import VKSdk.h" на "@import VK_ios_sdk;". Ставил SDK через cocoapods + use_frameworks!. https://github.com/VKCOM/vk-ios-sdk#installation-with-cocoapods.
Надеюсь тебе это как-то поможет

**Comment by Xotab4ik** [comment]
@BdevNameless черт возьми. Проблема была во мне, я не добавил URL Types. Спасибо тебе, так бы я еще долго мучился.
![2016-08-07 17 52 59](https://cloud.githubusercontent.com/assets/16893175/17462218/62ab721a-5cd0-11e6-8ed2-e2085414f9ac.png)
