### ISSUE TITLE
Авторизация через VK APP

### ISSUE THREAD

**Issue by ShagaleevAlexey** [VKCOM/vk-ios-sdk#435]
Мне необходимо следующее: по нажатию на кастомную кнопку в моем приложении пользователя перенаправляет на приложение VK. Там он разрешит доступ и пользователь возвращается обратно в мое приложение.
Сейчас следующая ситуация. Если в настройках приложения VK оставить пустое поле Authorized redirect URI, то при перенаправлении в VK APP будет ошибка: "redirect_uri was wrong domain, check application settings", а если поставить тот что хочу, то будет: "redirect_uri is incorrect domain, check application settings".
Какой нужно задать Authorized redirect URI для того чтобы VK APP адекватно воспринимало его?
![screen shot 2016-08-24 at 17 12 28](https://cloud.githubusercontent.com/assets/9031664/17933673/6dab5c3c-6a2e-11e6-980a-a7a9ba21354f.png)

Спасибо.

**Comment by suzhaev** [comment]
@ShagaleevAlexey Какое приложение у вас? Должно быть "Standalone-приложение".

**Comment by ShagaleevAlexey** [comment]
@suzhaev да. После вашего вопроса проблема отпала сама собой, так как раньше было Web-приложение. Потому что до текущего момента требовалась OAuth аутентификация, а сейчас нужно реализовать через VK APP.
Так что спасибо:)

**Comment by artuska** [comment]
На странице настроек приложения я в упор не вижу ничего, хоть сколько-то похожего на выбор Standalone- или Web-аппликации. Что я делаю не так?

И еще, а если мне нужно, чтобы работала и Oauth- и App-авторизация? Ибо у меня Cordova-аппликация, которая работает и в браузере и в мобильном телефоне как аппликация — в браузере я использую Oauth, а в телефоне хочу, чтобы авторизация происходила из VK-аппликации.

**Comment by artuska** [comment]
Ах, так, я понял — для веб-версии мне нужно создать Веб-приложение, а для мобильной версии нужно создать Standalone-приложение.
