### ISSUE TITLE
Авторизация в VK APP

### ISSUE THREAD

**Issue by ShagaleevAlexey** [VKCOM/vk-ios-sdk#437]
Доброго времени суток.

Проблема следующая. При вызове [VKSdk authorize:scope]; происходит переход в VK APP, вызывает vkSdkAccessTokenUpdated:oldToken: с nil параметрами. И если далее нажать на кнопку Allow (разрешить) в VK APP, то экран просто закроется и приложение VK останется.
vkSdkUserAuthorizationFailed не вызывается. Запрашиваю разрешение получать почту пользователя.

**Comment by suzhaev** [comment]
@ShagaleevAlexey проблема решилась?

**Comment by ShagaleevAlexey** [comment]
Да, но было бы замечательно если бы кто-нибудь скинул пример авторизации и в Facebook App.

**Comment by NatalliaSemicheva** [comment]
@suzhaev @ShagaleevAlexey у меня такая же проблема, и я не знаю, как ее решить

**Comment by ShagaleevAlexey** [comment]
> @suzhaev @ShagaleevAlexey у меня такая же проблема, и я не знаю, как ее решить

уже не помню как решил эту проблему
Попробуйте поиграться с настройками приложения
