### ISSUE TITLE
ios 10 sharing

### ISSUE THREAD

**Issue by BrysovVadik** [VKCOM/vk-ios-sdk#438]
Доброго времени суток, подскажите пожалуйста, что я делаю не так?
Открывается приложение ВК, в нём экран на разрешение прав, я нажимаю разрешить, этот экран пропадает, остается включенным приложение ВК, ничего не происходит. Я нажимаю в левом верхнем углу вернуться в приложение. Там срабатывает метод vkSdkShouldPresentViewController - открывается сафари с экраном разрешения прав. Нажимаю разрешить - пишет что сафари не может открыть эту страницу. Нажимаю готово. Возвращается в приложение и там падает в метод vkSdkUserAuthorizationFailed

`[[VKSdk initializeWithAppId:******] registerDelegate:self];
        [[VKSdk instance] setUiDelegate:self];`
        
        `@weakify(self);
        [VKSdk wakeUpSession:@[VK_PER_FRIENDS, VK_PER_WALL, VK_PER_PHOTOS, VK_PER_NOHTTPS, VK_PER_EMAIL, VK_PER_MESSAGES]
               completeBlock:^(VKAuthorizationState state, NSError *error) {
                   @strongify(self);
                   if (state == VKAuthorizationAuthorized) {
                       VKShareDialogController *shareDialog = [VKShareDialogController new];
                       shareDialog.text = @"This post created created created created and made and post and delivered using #vksdk #ios";
                       shareDialog.uploadImages = @[ [VKUploadImage uploadImageWithImage:imageForSharing andParams:nil] ];
                       shareDialog.shareLink = [[VKShareLink alloc] initWithTitle:****** link:[NSURL URLWithString:*****]];
                       [shareDialog setCompletionHandler:^(VKShareDialogController *dialog, VKShareDialogControllerResult result) {
                           [self dismissViewControllerAnimated:YES completion:nil];
                           if (result == VKShareDialogControllerResultDone) {
                           }
                       }];
                       [self presentViewController:shareDialog animated:YES completion:nil];
                       
                   } else {
                       [VKSdk authorize:@[VK_PER_FRIENDS, VK_PER_WALL, VK_PER_PHOTOS, VK_PER_NOHTTPS, VK_PER_EMAIL, VK_PER_MESSAGES]];
                   }
               }];`

**Comment by suzhaev** [comment]
@BrysovVadik ваша проблема похожа на эту:
[https://github.com/VKCOM/vk-ios-sdk/issues/421#issuecomment-244370754](url)

**Comment by BrysovVadik** [comment]
Не совсем. У меня вообще не падает в метод - (BOOL)application:(UIApplication *)application openURL:(nonnull NSURL *)url options:(nonnull NSDictionary<NSString *, id> *)options {

**Comment by suzhaev** [comment]
@BrysovVadik URL Scheme задали?

**Comment by BrysovVadik** [comment]
Задал, но неправильно. Identifier прописал, а URL Schemes нет - там же в обоих полях одно и тоже должно быть. В этом и была проблема! Спасибо!
