### ISSUE TITLE
Авторизация запрашивает больше прав, чем указано

### ISSUE THREAD

**Issue by analvandal** [VKCOM/vk-ios-sdk#441]
Для авторизации пользователя в приложении использую

```
VKSdk.wakeUpSession(["messages"]) { (state, error) in
     //Some code
}
```

В scope указан только доступ к "messages", но в окне авторизации приложения VK в списке указана информация пользователя и offline-доступ.
С информацией пользователя еще можно понять, но как используется offline-доступ? Почему он в списке?

![shot](https://cloud.githubusercontent.com/assets/16415741/18646668/3d25bc96-7ebb-11e6-88d8-6a09d3c7111b.png)

**Comment by suzhaev** [comment]
Offline-доступ всегда запрашивается для standalone приложений
