### ISSUE TITLE
Столкнулись с такой проблемой, что приложение ВК не пропускает запрос на открытие стороннего приложения iSpring Play.

### ISSUE THREAD

**Issue by alexanderBaranov** [VKCOM/vk-ios-sdk#442]
Не открывается внешнее приложение через webview приложения Вконтакте на iPad.
Способ воспроизведения:
1. Клиент размещает в ВК короткую ссылку со своего аккаунта iSpring Cloud вида http://ispri.ng/ctcZ
2. Через приложение ВК для iPad проходит по ней. Открывается webview со страницей презентации.
3. Нажимает кнопку "Запустить". 

В результате webview не пропускает ссылку для открытия приложения iSpring Play.

**Команда по кнопочке "Запустить" пытается отработать  ссылку со схемой ismobile://.... и ,видимо, webView эту ссылку перехватывает и не пропускает ее. Нужно чтобы приложение ВК по этой ссылке открывало приложение iSpring Play.**

Можем ли мы расчитывать на скорое исправление?

**Comment by suzhaev** [comment]
Используйте Universal links для iOS 9 +

Universal links let you replace custom URL schemes with standard HTTP or HTTPS links. Universal links work for all users: If users have your app installed, the link takes them directly into your app; if they don’t have your app installed, the link opens your website in Safari. To learn more about universal links, see [Support Universal Links](https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html#//apple_ref/doc/uid/TP40016308-CH12).

**Comment by alexanderBaranov** [comment]
Мы в курсе, но наше приложение поддерживает платформы начиная с iOS 7. Поэтому вернемся к выше описанной проблеме и повторюсь: можем ли мы расчитывать на скорое исправление?

**Comment by suzhaev** [comment]
> В результате webview не пропускает ссылку для открытия приложения iSpring Play.

Это вы на какой iOS проверяете?

**Comment by alexanderBaranov** [comment]
iOS 10

**Comment by suzhaev** [comment]
> Используйте Universal links для iOS 9 +
@alexanderBaranov на iOS 10 нужно использовать universal links

А вот для iOS 8, думаю, все работает со схемой ismobile://

**Comment by alexanderBaranov** [comment]
Да, все верно. Изначально дали не правильную наводку, что и на ios 8  не  работает. Сейчас проверил и все норм. Значить будем править мы.
