### ISSUE TITLE
xcode 8 'class' is unavailable

### ISSUE THREAD

**Issue by gneil90** [VKCOM/vk-ios-sdk#445]
'class' is unavailable: use 'self' instead
return [data isKindOfClass:NSArray.class] ? data : nil;

**Comment by gneil90** [comment]
can anyone create a branch, I will fix it and will open pull request?

**Comment by suzhaev** [comment]
Are you sure?
Method 'class' in new Xcode has OBJC SWIFT UNAVAILABLE, this means - unavailable in Swift.
vk-ios-sdk - Objective-C project, I've successfully built it with xcode 8.
