### ISSUE TITLE
Не вызываются методы класса VKSdkDelegate

### ISSUE THREAD

**Issue by vitaly-greenbox** [VKCOM/vk-ios-sdk#446]
Здравствуйте. Методы классы `VKSdkDelegate` не вызываются. Использую Unity3d.

Мои действия.
1) Собираю `.framework` из проекта https://github.com/VKCOM/vk-ios-sdk и добавляю его к проекту. Ранее использовал Cocoapods. Результат тот же.
2) Добавил реализацию `openUrl` в делегат приложения (пробовал версию как для iOS9 так и для iOS8 и ниже). Метод точно вызывается. Данные вполне корректные приходят. При регистрации например, что-то типа `vk<APP_ID>?accessToken = ... &userID=...`.
3) Добавил строки в `Info.plist`. Если один из пунктов не добавить из списка `LSApplicationQueriesSchemes` то при вызове `openUrl` в логах пишется ошибка, о том, что такой-то запрос не определён.
4) Добавил URL приложения по мануалу `Твиттера`. Если этого не сделать, то после регистрации через приложение VK моё приложение не открывается.
5) Реализовал `VKSdkDelegate` и `VKSdkUIDelegate`. В методах выполняю только NSLog.
6) Инициализацию выполняю так:
```
VKSdk *sdkInstance = [VKSdk initializeWithAppId:@"5614810" apiVersion: @"5.53"];

[sdkInstance registerDelegate:[TestDelegate new]];
[sdkInstance setUiDelegate:[TestUIDelegate new]];
```
7) Взываю `wakeUpSession`. В лог выводится `пользователь не авторизован и можно выполнить авторизацию`. Т.е. CallBack для `wakeUpSession` выполнился.
```
NSArray* scope = @[@"friends", @"wall"];    
[VKSdk wakeUpSession:scope completeBlock:^(VKAuthorizationState state, NSError *error) {
	if (state == VKAuthorizationAuthorized) {
		NSLog(@"wakeUpeSession: autorize");
    } else if (error) {
		NSLog(@"wakeUpeSession: no aoutorize. Call autorize");
    }
}];
```
8) Выполняю авторизацию. При этом метод `openUrl`, в делегате приложения, вызывается, но методы `VKSdkDelegate` нет. Ошибки в логе так же отсутствую. Код авторизации:
```
NSArray* scope = @[@"friends", @"wall"];      
[VKSdk authorize: scope];
```
9) Выполняю снова `wakeUpSession` в логе отображается `пользователь авторизован`.
10) Другие запросы тоже работают нормально. Например запрос на получение списка пользователей для приглашения в приложения выводит ошибку в лог если пользователь не авторизован и возвращает корректный список после авторизации. Код запроса:
```
VKRequest* rUsers = [VKRequest requestWithMethod:@"apps.getFriendsList" parameters:@{@"extended" : @"1", @"type" : @"invite", @"count": @"5000", @"fields": @"photo_100" }];

[rUsers executeWithResultBlock:^(VKResponse *response) {
	NSLog(@"InviteFriendsList: %@", response.json);
} errorBlock:^(NSError * error) {
	NSLog(@"InviteFriendsList eror: %@", error);
}];  
```
Использовал версии плагина `1.3.17` и `1.4.4`.
В настройках приложения на сайте VK нужно указать 2 поля `App Bundle ID для iOS`, `App Id для iOS`. Пока указано только `Bundle ID`.

С чем может быть связано отсутствие вызова методов `VKSdkDelegate`?

**Comment by suzhaev** [comment]
А что такое [TestDelegate new]?
Можно целиком код функции, где присваивается делегат? 

Скорее всего объект класса TestDelegate удаляется из памяти, потому что вы его нигде не храните. Попробуйте посмотреть чему равен delegate объекта sdkInstance в момент авторизации, скорее всего там будет nil

**Comment by vitaly-greenbox** [comment]
Благодарю. Вы правы проблема в ссылках. 

Оператор `new` включает в себя вызов `alloc` и `init`. https://developer.apple.com/reference/objectivec/nsobject/1571948-new?language=objc
Т.е. можно заменить `TestDelegate* testDelegate = [[TestDelegate alloc] init];` на `TestDelegate* testDelegate = [TestDelegate new];`:

Код метода выглядел так
```
extern "C" {
	void VKSdkInitialize(const char* appID, const char* apiVersion) {
		VKSdk* vkSdkInstace = [VKSdk initializeWithAppId:ParseCharUTF8ToNSString(appID) apiVersion:ParseCharUTF8ToNSString(apiVersion)];

		[vkSdkInstace registerDelegate:[TestDelegate new]];
		[vkSdkInstace setUiDelegate:[TestUIDelegate new]];
	}
}
```
Если изменить его так. То всё работает. 
```
static TestDelegate* testDelegate;
static TestUIDelegate* testUIDelegate;

extern "C" {
	void VKSdkInitialize(const char* appID, const char* apiVersion) {
		VKSdk* vkSdkInstace = [VKSdk initializeWithAppId:ParseCharUTF8ToNSString(appID) apiVersion:ParseCharUTF8ToNSString(apiVersion)];
		   
		testDelegate = [TestDelegate new];
		testUIDelegate = [TestUIDelegate new]];
		   
		[vkSdkInstace registerDelegate:testDelegate];
		[vkSdkInstace setUiDelegate:testUIDelegate];
	}
}  
```
Извиняюсь. Не учёл особенности языка.
