### ISSUE TITLE
Не все методы указаны

### ISSUE THREAD

**Issue by sssbohdan** [VKCOM/vk-ios-sdk#447]
Прочитал полностью документацию по api, но не нашёл методы для работы со статистикой страницы(не статистикой группы). К примеру запрос выглядит так -  https://vk.com/stats?mid=<your_id> но в документации ни слова о нем. Как мне послать такой запрос с клиента?Спасибо.
![screen shot 2016-10-04 at 00 04 28](https://cloud.githubusercontent.com/assets/14069947/19054037/35e929ac-89c6-11e6-8ea7-b333335814ab.png)
![screen shot 2016-10-04 at 00 04 36](https://cloud.githubusercontent.com/assets/14069947/19054038/36005ad2-89c6-11e6-9b23-df6a35b9323f.png)

**Comment by suzhaev** [comment]
Если такого метода нет в документации, значит вы никак не можете работать со статистикой страницы на данный момент.
