### ISSUE TITLE
Не вызывается vkSdkAccessAuthorizationFinishedWithResult

### ISSUE THREAD

**Issue by Sunrizzin** [VKCOM/vk-ios-sdk#451]
Добрый день!
При попытке регистрации открывается приложение VK и спрашивает разрешение. Далее вне зависимости от того, что выберу - vkSdkAccessAuthorizationFinishedWithResult не будет вызываться.

 в viewDidLoad - 
 `let vk = VKSdk.initialize(withAppId: "5668863")
        vk!.register(self)`

регистрирую - 

`VKSdk.authorize(self.SCOPE)`

Где может быть ошибка? Заранее спасибо!

**Comment by suzhaev** [comment]
Scheme настроили?
https://github.com/VKCOM/vk-ios-sdk#setup-url-schema-of-your-application

**Comment by Sunrizzin** [comment]
да, конечно: в info.plist
```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>vk</string>
    <string>vk-share</string>
    <string>vkauthorize</string>
</array>
```

AppDelegate - 
```
    private func application(application: UIApplication, openURL url: URL, sourceApplication: String?, annotation: AnyObject) -> Bool {
        VKSdk.processOpen(url as URL!, fromApplication: sourceApplication)
        return true
    }
```

**Comment by suzhaev** [comment]
Посмотрите еще раз документацию, это немного не то

> To authorize via VK App you need to setup a url-schema for your application, which looks like vk+APP_ID (e.g. vk1234567).

**Comment by Sunrizzin** [comment]
Извиняюсь, напутал. Вот такая схема.
<img width="1792" alt="2016-10-17 22 10 40" src="https://cloud.githubusercontent.com/assets/16189633/19441034/bb1ed090-94b6-11e6-90ef-602a99e07df5.png">

**Comment by suzhaev** [comment]
Посмотрите тут еще:

https://github.com/VKCOM/vk-ios-sdk/issues/446
https://github.com/VKCOM/vk-ios-sdk/issues/443

`private func application(application: UIApplication, openURL url: URL, sourceApplication: String?, annotation: AnyObject) -> Bool` вызывается?

**Comment by Sunrizzin** [comment]
`private func application(application: UIApplication, openURL url: URL, sourceApplication: String?, annotation: AnyObject) -> Bool` - НЕ вызывается

по #446 -  поправил, теперь и инициализация и авторизация вызываются вот так:
```
override func viewDidLoad() {
        super.viewDidLoad()
        let vk = VKSdk.initialize(withAppId: "5668863")
        vk!.register(self)
        
        VKSdk.wakeUpSession(self.SCOPE) { (state: VKAuthorizationState, error) in
            switch state {
            case .authorized:
                print("OK, authorized")
                break
            case .initialized:
                print("OK, initialized")
                VKSdk.authorize(self.SCOPE)
                break
            case .error:
                print("Error")
                break
            default:
                print("Failed")
            }
        }
    }
```

по #443 - схема установлена. Приложение открывается, запрашивает разрешение, возвращает обратно в моё приложение.

**Comment by Sunrizzin** [comment]
Нашёл в чём была проблема. В функции из AppDelegate, она должна выглядеть вот так:

```
func application(_ app: UIApplication,
                     open url: URL,
                     options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        VKSdk.processOpen(url, fromApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as! String!)
        
        return true
    }
```

Большое спасибо за помощь!
