### ISSUE TITLE
Токен для Push notifications

### ISSUE THREAD

**Issue by BigBadBird** [VKCOM/vk-ios-sdk#457]
В каком формате нужно отправлять Device token?

**Comment by BigBadBird** [comment]
Посылаю такой запрос:
        VKRequest *request = [VKApi requestWithMethod:@"account.registerDevice" andParameters:@{@"token": [[[[deviceToken description]
                                                                                                             stringByReplacingOccurrencesOfString: @"<" withString: @""]
                                                                                                            stringByReplacingOccurrencesOfString: @">" withString: @""]
                                                                                                           stringByReplacingOccurrencesOfString: @" " withString: @""],
                                                                                                @"device_id":uniqueIdentifier,
                                                                                                @"sandbox":@(1),
                                                                                                @"system_version":@"iOS 10",
                                                                                                @"settings":@"{\"msg\":\"on\",\"friend\":\"off\"}"}];
        [request executeWithResultBlock:^(VKResponse*response) {NSLog(@"response %@", response.responseString);} errorBlock:^(NSError*error){NSLog(@"error %@", error);}];

Сертификаты залил, но уведомления так и не приходят.

**Comment by suzhaev** [comment]
Формат у вас вроде правильный. Сертификаты правильно сделали?

**Comment by BigBadBird** [comment]
@suzhaev  Эксопртирую ключ и сертификат в один p12 файл, далее создаю из него сертификат командой openssl pkcs12 -in cert.p12 -out Certificates2.pem -nodes. В полученном файле через текстовый редактор вижу, что находится и сертификат и ключ, но сам вк ругается "Данный файл не является сертификатом. [contain invalid characters]"

**Comment by BigBadBird** [comment]
Проблему решил, открыл сертификат в текстовом редакторе и удалил всякие Bag Attributes из него. Все заработало.
