### ISSUE TITLE
wakeUpSession после авторизации не достает старую сессию

### ISSUE THREAD

**Issue by iwheelbuy** [VKCOM/vk-ios-sdk#458]
Возможно я ОПЯТЬ криво все делаю но почему-то не хочет будить старую сессию...
Swift 3, XCode 8.0, симулятор, сдк 1.4.4
Пробовал с разными пермишенами, не помогло.
После авторизации запрос проходит, т.е. вроде правильно авторизуюсь.
Куда копать - не знаю... Вот проект: https://github.com/iwheelbuy/Viper

**Comment by suzhaev** [comment]
404 ошибка по ссылке

**Comment by iwheelbuy** [comment]
поправил

**Comment by suzhaev** [comment]
Для проектов на swift нужно включить keychain sharing в настройках проекта. В документации, к сожалению, это никак не указано, поправим.

<img width="875" alt="2016-11-08 18 45 39" src="https://cloud.githubusercontent.com/assets/19522238/20105711/b0176782-a5e3-11e6-9d67-d3de6a18a587.png">

**Comment by iwheelbuy** [comment]
Понял. Спасибо!

**Comment by suzhaev** [comment]
Это лишь решение проблемы. Сама проблема глубже: мы храним токен в keychain, используем метод SecItemAdd. Для проектов на swift этот метод возвращает ошибку: [-34018 (errSecMissingEntitlement)](https://www.osstatus.com/search/results?platform=all&framework=all&search=-34018), повторяется это не у всех и не всегда. 

Вот ссылки по этому поводу:

http://stackoverflow.com/questions/20344255/secitemadd-and-secitemcopymatching-returns-error-code-34018-errsecmissingentit
https://forums.developer.apple.com/thread/4743#14441
https://forums.developer.apple.com/thread/4743#126088

Судя по всему это баг в iOS. Со своей стороны мы можем только отлавливать и ошибку и показывать ее, что и нужно сделать.

Схожие issue: https://github.com/VKCOM/vk-ios-sdk/issues/452, https://github.com/VKCOM/vk-ios-sdk/issues/383
