### ISSUE TITLE
Проблема с кол-вом возвращаемых данных, которые запрашиваются через execute

### ISSUE THREAD

**Issue by iwheelbuy** [VKCOM/vk-ios-sdk#459]
Добрый вечер. Проблема возможно не связана с **vk-ios-sdk**, однако и такое я не исключаю. Поэтому решил сначала сюда написать!

Задача небольшая и простая: поиск будущих мероприятий по заданным словам. Вот пример текущей реализации хранимой процедуры, которая выполняет нужный поиск. Если выполнить процедуру, то получится около 200-300 событий (на момент написания issue).

```
var group_ids = [];
var x = 0;
var titles = ["шерегеш", "sheregesh"];
while (x < 2 && group_ids.length < 500) {
    group_ids = group_ids + API.groups.search({
        "v":5.60,
        "count":500 - group_ids.length,
        "q":titles[x],
        "type":"event",
        "future":1
    }).items@.id;
    x = x + 1;
}
var fields = "start_date,finish_date,members_count,member_status";
return API.groups.getById({
    "v":5.60,
    "group_ids":group_ids,
    "fields":fields
});
```

Проблема заключается в том, что иногда возвращается какой-то крайне небольшой массив объектов. Вот пример лога возвращаемых объектов.

```
"<-----" 200
"<-----" 14
"<-----" 200
"<-----" 200
"<-----" 200
"<-----" 200
"<-----" 14
"<-----" 200
```

Анализируя методы, используемые в хранимой процедуре, можно прийти к выводу о том, что **API.groups.getById** может выдавать разные данные в зависимости от ключа доступа.

Может ли получиться так, что **vk-ios-sdk** отправляет какой-то другой ключ (без ключа) или еще что-то в этом духе? Любая помощь пригодится! (:

Тестовый код можно найти в репозитории: https://github.com/iwheelbuy/viper (ветка: WrongData2)

**Comment by iwheelbuy** [comment]
Забыл сказать, что причина, по которой я подумал о причастности **vk-ios-sdk** к получению неверных данных, заключается в том, что я так и не смог воспроизвести неверных данных на сайте ВК выполняя хранимую процедуру

**Comment by iwheelbuy** [comment]
Либо кто-то что-то сделал, либо на сайте магия происходит... В общем сел докапываться до корня проблемы. А проблемы не стало! Закрою пока issue

**Comment by iwheelbuy** [comment]
Проблема опять появилась...

**Comment by suzhaev** [comment]
Возможно API.groups.search не отрабатывает как надо в while, из-за флуд контроля, например, поэтому и получаете небольшой массив. Скорее всего проблема в этом, попробуйте отказаться от while

От ключей доступа результат тоже зависит, конечно:

> Этот метод можно вызвать без ключа доступа. Возвращаются только общедоступные данные.
> Этот метод можно вызвать с ключом доступа пользователя.
> Этот метод можно вызвать с ключом доступа сообщества.

если через SDK пользователь авторизован, то будет подставляться ключ доступа пользователя.

**Comment by iwheelbuy** [comment]
Ого... очень интересное замечание насчет while! Попробую, спасибо!
Да, авторизован через SDK. Тогда вариант с некорректным ключом исключаю.
Отпишусь о результатах, еще раз спасибо

**Comment by iwheelbuy** [comment]
Заменил while. Словил опять малое кол-во данных.

Нашел проблемное место!
Малое кол-во данных возвращается потому, что возвращаются данные только для одного из двух запросов. А именно для запросов: "шерегеш" и "sheregesh" бывает не приходит ответ для слова "шерегеш". Т.е. время от времени для слова "шерегеш" возвращается пустой массив. Это явно не вина SDK, поэтому закрываю тему. Спасибо за помощь!
