### ISSUE TITLE
Можно ли использовать standalone app для приложения с другим bundle id?

### ISSUE THREAD

**Issue by D-Link13** [VKCOM/vk-ios-sdk#463]
Подскажите пожалуйста, с выходом swift 3 решил переделать свое приложение на новое. Могу ли я использовать standalone app от старого приложения или создавать новое? Если могу, то что нужно изменить в настройках standalone кроме bundle id? Спасибо за внимание!

**Comment by suzhaev** [comment]
Можете, по идее ничего кроме bundle id менять не нужно. Попробуйте - должно работать.
