### ISSUE TITLE
XCode не видит хеддеры

### ISSUE THREAD

**Issue by victorshablyko** [VKCOM/vk-ios-sdk#466]
Добрый вечер. Я подключил SDK (пробовал двумя способами: cocoapods и embedded binaries, разумеется это 2 разных проекта)

Все запускается до тех пор когда я импортирую хеддер:
`#import <VKSdk.h>`

Вылетают 3 ошибки:
![2016-11-27 18 03 57](https://cloud.githubusercontent.com/assets/2326148/20649644/8a15f2f4-b4cc-11e6-8cc6-0a9dd336e32f.png)
![2016-11-27 18 04 14](https://cloud.githubusercontent.com/assets/2326148/20649645/8a41aade-b4cc-11e6-83c3-0f38ee5725fb.png)

Пробовал также

`
#import <VKSdkFramework/VKSdkFramework.h>

#import <VKSdk/VKSdk.h>

#import <VK_ios_sdk/VKSdk.h>
`
file not found

Кто-нибудь сталкивался с таким

**Comment by suzhaev** [comment]
Должно починиться

**Comment by victorshablyko** [comment]
Спасибо, обновил pod и все заработало
