### ISSUE TITLE
Ошибка при вызове VKSdk.authorize(scope)

### ISSUE THREAD

**Issue by nikolaykletskin** [VKCOM/vk-ios-sdk#467]
Добрый вечер.

При попытке вызова VKSdk.authorize(scope) получаю ошибку:
-canOpenURL: failed for URL: "vkauthorize://authorize" - error: "Не удалось завершить операцию. (OSStatus, ошибка -10814)"

Запускаю приложение в эмуляторе (Swift 3, iOS 10.0)

### Выполненные действия:

1. Создал standalone-приложение Вконтакте.
2. Настроил в info.plist приложения URL-types по мануалу из Twitter. По вбитому в Safari урлу vkXXXXXXX:// приложение открывается.
3. Настроил в info.plist приложения

```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>vk</string>
    <string>vk-share</string>
    <string>vkauthorize</string>
</array>
```

4. Добавил в AppDelegate метод:

```
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        VKSdk.processOpen(url, fromApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as! String!)
        
        let sdkInstance = VKSdk.initialize(withAppId: "VK_APP_ID")
        sdkInstance!.register(self)
        sdkInstance!.uiDelegate = self
        
        let scope = ["friends", "email"]
        VKSdk.wakeUpSession(scope, complete: {(state: VKAuthorizationState, error: Error?) -> Void in
            if state == .authorized {
                NSLog("authorized")
            } else {
                VKSdk.authorize(scope)
            }
            return
        })
        

        return true
    }
```

5. Запускаю приложение. Перехожу в Safari, ввожу в адресной строке vkXXXXXXXX://. Открывается диалоговое окно с предложением открыть приложение. После подтверждения выполняется представленный выше код и в момент вызова VKSdk.authorize(scope) получаю озвученную вначале ошибку.

Смотрел смежные issues, но найти там ответ не получилось (опыта довольно мало).

**Comment by D-Link13** [comment]
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
let vkSDK = VKSdk.initialize(withAppId: VKNetworking.kVK_APP_ID)
        vkSDK?.register(VKNetworking.shared)
        vkSDK?.uiDelegate = VKNetworking.shared

return true
}
```

```
func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        VKSdk.processOpen(url, fromApplication: sourceApplication)
        return true
    }
```

Попробуйте переписать AppDelegate таким образом

**Comment by nikolaykletskin** [comment]
Не совсем понял. Чем должен быть VKNetworking? Как есть код не сработает.

Если суть предложения в перенесении инициализации SDK в application() c другой сигнатурой, то я сейчас это попробовал. Результат тот же. Я получаю ошибку 10814 и все. Это, как я понимаю, вызвано тем, что на эмуляторе нет приложения VK. Но почему в таком случае не появляются заявленные "SFSafariViewController or webview".

Из описания VKSdk.authorize():
> Starts authorization process to retrieve unlimited token. If VKapp is available in system, it will opens and requests access from user. Otherwise SFSafariViewController or webview will be opened for access request.

**Comment by nikolaykletskin** [comment]
Спасибо за расширенную версию.) Буду смотреть.

Не подскажете, почему в текущем варианте не происходит вызова SFSafariViewController или webview, как заявлено в доках? Правильно ли я понимаю, что если все правильно, VKSdk.authorize должен вызывать их без написания какого-то дополнительного кода?

**Comment by D-Link13** [comment]
VKNetworking - такой себе хелпер, чтоб держать код более структурированным.. Он должен соответствовать протоколам VKSdkDelegate и VKSdkUIDelegate. Когда Вы вызываете VKSdk.authorize приложение пытается вызвать авторизацию ВК (через приложение Вк или же если такого нет, то через браузер)... Далее после того как нажмете "Разрешить" должна сработать url схема и Вас перекинет обратно в Ваше приложение и вызовется метод делегата VKSdkDelegate (либо vkSdkAccessAuthorizationFinished если все хорошо, либо vkSdkUserAuthorizationFailed если что то пошло не так).
На счет тестирования на симуляторе ничего сказать не могу, лучше пробуйте на девайсе.

**Comment by suzhaev** [comment]
@nikolaykletskin делегат поддержали?

**Comment by nikolaykletskin** [comment]
@suzhaev Да, поддержал.

```
import UIKit
import VK_ios_sdk

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, VKSdkDelegate, VKSdkUIDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        let sdkInstance = VKSdk.initialize(withAppId: "XXXXXXX")
        sdkInstance?.register(self)
        sdkInstance?.uiDelegate = self
        return true
    }
    
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        VKSdk.processOpen(url, fromApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as! String!)
        
        return true
    }
    
    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        VKSdk.processOpen(url, fromApplication: sourceApplication)
        return true
    }

    // MARK: vkSDK Delegate
    func vkSdkAccessAuthorizationFinished(with result: VKAuthorizationResult!) {
        NSLog("finished")
    }
    
    func vkSdkUserAuthorizationFailed() {
        NSLog("failed")
    }
    
    func vkSdkShouldPresent(_ controller: UIViewController) {
        NSLog("present")
    }
    
    func vkSdkNeedCaptchaEnter(_ captchaError: VKError) {
        NSLog("captcha")
    }
}
```


Попробовал запустить на устройстве: если есть приложение VK, но вызывается оно; если его удалить, валится ошибка:

```
-canOpenURL: failed for URL: "vkauthorize://authorize" - error: "Не удалось завершить операцию. (OSStatus, ошибка -10814)"
```

И происходит вызов
```
func vkSdkShouldPresent(_ controller: UIViewController) {
        NSLog("present")
}
```

Перехода в браузер нет. На устройстве iOS 10.1.

**Comment by D-Link13** [comment]
дайте код вызова VKSdk.wakeUpSession

**Comment by nikolaykletskin** [comment]
```
import UIKit
import VK_ios_sdk

class MemTypesViewController: UIViewController {

    @IBOutlet weak var simpleMemButton: UIButton!
    @IBOutlet weak var expressionButton: UIButton!
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.view.backgroundColor = UIColor.nDarkColor()
        simpleMemButton.backgroundColor = UIColor.nBrightSkyBlueColor()
        simpleMemButton.layer.cornerRadius = 5
        expressionButton.backgroundColor = UIColor.nDarkPeriwinkleColor()
        expressionButton.layer.cornerRadius = 5
        
        let scope = ["friends", "email"]
        VKSdk.wakeUpSession(scope, complete: {(state: VKAuthorizationState, error: Error?) -> Void in
            if state == .authorized {
                NSLog("authorized")
            } else {
                NSLog("tryin to authorize")
                VKSdk.authorize(scope)
            }
            return
        })
        
        // VKNetworking.shared.vkLogin()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
}
```

**Comment by D-Link13** [comment]
Добавьте в свой проект этот файл, и в нужном контроллере добавьте VKNetworking.shared.vkLogin() (лучше на viewWillApear)

```
import Foundation
import VK_ios_sdk

class VKNetworking: NSObject {
    static let shared = VKNetworking()
    static let kVK_APP_ID = "XXXXXXX"
    let permissions = NSArray(objects: "email", "wall", "photos") as [AnyObject]
    
    var userEmail = String()
    
    func vkLogin(completion: @escaping (Bool) -> ()) {
        VKSdk.wakeUpSession(self.permissions, complete: { (state, error) in
            if state == .authorized && error == nil && VKSdk.accessToken() != nil {
                print("vk authorized")
                completion(true)
            } else if state == .initialized {
                print("vk initialized")
                VKSdk.authorize(self.permissions)
            } else {
                if error != nil {
                    print(error!)
                }
                completion(false)
            }
        })
    }
    
    func vkLogout() {
        VKSdk.forceLogout()
    }
}

extension VKNetworking: VKSdkDelegate {
    func vkSdkAccessAuthorizationFinished(with result: VKAuthorizationResult!) {
        if result.token != nil && result.error == nil {
            if let email = result.token.email {
                self.userEmail = email
            }
        }
    }
    
    func vkSdkUserAuthorizationFailed() {
        print("vkSdkUserAuthorizationFailed")
    }
}

extension VKNetworking: VKSdkUIDelegate {
    func vkSdkShouldPresent(_ controller: UIViewController!) {
        
    }
    
    func vkSdkNeedCaptchaEnter(_ captchaError: VKError!) {
        
    }
}
```

**Comment by suzhaev** [comment]
@nikolaykletskin ну все правильно, вот тут нужно презентить контроллер

```
func vkSdkShouldPresent(_ controller: UIViewController) {
        // выполняйте present контроллера
}
```

**Comment by nikolaykletskin** [comment]
@D-Link13 Я пробовал и с вашим вспомогательным классом (еще коммент остался). Результат был такой же. Пока я просто вернулся к своему изначальному варианту.

**Comment by nikolaykletskin** [comment]
@suzhaev Понял, спасибо. Смутила документация VKSdk.authorize():

> Starts authorization process to retrieve unlimited token. If VKapp is available in system, it will opens and requests access from user. Otherwise SFSafariViewController or webview will be opened for access request. 

Я предполагал, что этот метод презентит контроллер "из коробки".
