### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by victorshablyko** [VKCOM/vk-ios-sdk#471]
Интегрировал VKSdk с помощью pods
Как только импортирую хеддер, получаю следующее: 
`#import <VKSdk.h>`

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_VKSdk", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in WelcomeViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Очевидно, xcode не может собрать проект для arm64, тестовое приложение нормально работает но там sdk подключено с помощью embedded frameworks.
Что я делаю не так?

На всякий случай скрин
![2016-12-06 16 42 56](https://cloud.githubusercontent.com/assets/2326148/20929561/3bb32fba-bbd3-11e6-8f7a-8508a630cbe3.png)

Edit
Уточню, ошибка возникает не тогда, когда импортирую хеддер, а когда пытаюсь использовать sdk, например:

`[VKSdk processOpenURL:url fromApplication:sourceApplication];`

или

`[[VKSdk initializeWithAppId:@"5749233"] registerDelegate:self];`

**Comment by suzhaev** [comment]
Видимо неправильные настройки проекта у вас, попробуйте так. 
К SDK это отношения особо не имеет
<img width="737" alt="m9ecb" src="https://cloud.githubusercontent.com/assets/19522238/20972312/88b3fe2a-bca5-11e6-9ff6-4509250178b4.png">

**Comment by victorshablyko** [comment]
Для тех, кто столкнется с такой же проблемой, добавьте

`$(inherited)`

в Other Linker Flags

**Comment by RitualNoise** [comment]
Enable Bitcode = NO
