### ISSUE TITLE
Интеграция с Auth0

### ISSUE THREAD

**Issue by DevAlloy** [VKCOM/vk-ios-sdk#473]
У ребят есть отличный туториал: https://auth0.com/docs/connections/social/vkontakte
Который даже работает для web-приложений, но не для standalone. Собственно проблема в том, что невозможно указать redirect_uri.

Подскажите, что можно сделать в данной ситуации?

**Comment by suzhaev** [comment]
А почему не использовать SDK?
Вообще, создаете scheme для приложения своего и указываете его в качестве redirect_uri
