### ISSUE TITLE
Can't access userId

### ISSUE THREAD

**Issue by diehardest** [VKCOM/vk-ios-sdk#476]
I use the standard auth way from the example project. From the method 
`- (void)vkSdkAccessAuthorizationFinishedWithResult:(VKAuthorizationResult *)result` 
I getting token, however the user object is nil so I can't retrieve the userId.

**Comment by suzhaev** [comment]
Try [VKSdk accessToken].localUser

> Contains basic current user information. Available after delegate method -[VKSdkDelegate vkSdkAuthorizationStateUpdatedWithResult:] called

**Comment by Ksen17** [comment]
Та же проблема 
[VKSdk accessToken].localUser
возвращает nil
