### ISSUE TITLE
Проблема с авторизацией через приложение в iOS 

### ISSUE THREAD

**Issue by yaroslav-tytarenko** [VKCOM/vk-ios-sdk#479]
Здравствуйте, поставил с App Store приложение DriverNotes
https://itunes.apple.com/ua/app/drivernotes/id527626833

В итоге после попытки зайти в любое другое приложение на айфоне через vk, меня редиректит на DriverNotes! Подозреваю у него так же настроенная схема как и у вас. 

https://drive.google.com/open?id=0B-wAs2pVR0THNk13eE5Wck9TOEU

**Comment by DennisRitchieUA** [comment]
У меня такая же проблема, в нашем приложении при попытке авторизоваться через VK открывается DriverNotes после чего когда я возвращаюсь в свое приложение sdk открывает SFSafariViewController через которое проходит авторизация

**Comment by suzhaev** [comment]
Да, есть такая проблема. DriverNotes использует такую же scheme, как наше приложение. К сожалению iOS не гарантирует их уникальность. Попробуем решать проблему напрямую с разработчиками. Спасибо.
