### ISSUE TITLE
shareDialog setCompletionHandler не работает

### ISSUE THREAD

**Issue by MikeRage** [VKCOM/vk-ios-sdk#490]
[shareDialog setCompletionHandler:^(VKShareDialogControllerResult result) {
<#code#>
}]; - данная конструкция вызывает ошибку еще до компиляции.

xcode предлагает другой вариант:
    [shareDialog setCompletionHandler:^(VKShareDialogController *, VKShareDialogControllerResult) {
        <#code#>
    }];
но тут тоже ошибка(parameter name omitted), и не могу понять как этим пользоваться.. подскажите плиз что с этим делать?

**Comment by beltik** [comment]
Такая же ошибка.

**Comment by suzhaev** [comment]
Нужно указать названия параметров 

[shareDialog setCompletionHandler:^(VKShareDialogController *controller, VKShareDialogControllerResult result) {
<#code#>
}];
