### ISSUE TITLE
Share with Vk app issue

### ISSUE THREAD

**Issue by beltik** [VKCOM/vk-ios-sdk#492]
Добрый день! У меня есть приложение использующее vk sdk, я как понимаю если на устройстве есть Vk app, то при попытке авторизоваться мое приложение будет связываться с Vk app чтобы предоставить возможности пошарить новости. Все отлично, только если после предоставления прав для шаринга сделать логаут во Vk app, как получить колбэк в мое приложение что пользователь разлогинен и запросить новые права (для другого пользователя который залогинен во  vk app)? Если я правильно понимаю, сейчас при авторизации выдается беконечный токен, и сделать логаут можно только посредством [VKSdk forcelogout];

**Comment by suzhaev** [comment]
Еще актуально?

**Comment by beltik** [comment]
Ну видимо если ничего не меняли то проблема осталась, но для меня уже не актуально.
