### ISSUE TITLE
VKError.errorCode is not VK_API_CANCELED if user cancels

### ISSUE THREAD

**Issue by alex-dorokhov** [VKCOM/vk-ios-sdk#494]
SDK: 1.4.6
iOS: 9.3.5

1. Произвожу процесс авторизации через приложение VK.
2. Во время того как приложение VK спрашивает о предоставлении доступа моему приложению, нажимаю **отмена**. 
3. Получаю ошибку через vkSdkAccessAuthorizationFinishedWithResult: _nsError.vkError.errorCode == -101 (VK_API_ERROR)_
_nsError.vkError.errorMessage == "User denied your request"_

Однако ожидалось VK_API_CANCELED.

**Comment by dashvlas** [comment]
Та же проблема

**Comment by suzhaev** [comment]
Все правильно, юзер запретил вашему приложению доступ.
VK_API_CANCELED отдается в других случаях. Например, когда пользователь закрыл web view с авторизацией.
