### ISSUE TITLE
Не получается авторизоваться

### ISSUE THREAD

**Issue by iSpartak** [VKCOM/vk-ios-sdk#5]
Добрый день. Пытаюсь реализовать авторизацию как в примере и по документации но ничего не выходит. Тестовое приложение с одним UIViewController, при вызове 

[VKSdk authorize:@[VK_PER_FRIENDS, VK_PER_WALL, VK_PER_AUDIO, VK_PER_PHOTOS, VK_PER_NOHTTPS]];

открывается Safari и пытается пойти на страницу с авторизацие oAuth. Периодически ругается на Page not found, когда-же она появляется то после логина при нажатии на кнопку доверять, также ругается на инвалидный линк.
Запускается на iPhone 5 with iOS 7 на котором также установленно последнее VK app.  Но authorize его не видет и открывает сафари. По документации же должно быть новое UIWebView или VK app....

**Comment by Anatoliy-Kondrik** [comment]
Здравствуйте.
Пожалуйста, помогите разобраться...

sdk скачал на днях, собрал xcode, подключил libVKSdk.a к qt-проекту. Вызываю [VKSdk authorize:SCOPE];, открывается окно запроса доступа, нажимаю Allow, возврат в моё приложение не выполняется и не вызывается методы делегата.

Скорее всего, дело в моём делегате. Коды...

```
static NSArray *SCOPE = nil;
static VKDelegate *vkDeleg = nil;
static VKSdk *sdkInstance = nil;

bool IosUtils::loginTthroughVKontakteSDK()
{
        sdkInstance = [VKSdk initializeWithAppId:@"5291592"]; // TEST
        vkDeleg = [[VKDelegate alloc] init];
        [sdkInstance registerDelegate:vkDeleg];
        [sdkInstance setUiDelegate:vkDeleg];

        [VKSdk wakeUpSession:SCOPE completeBlock:^(VKAuthorizationState state, NSError *error) {
            if (state == VKAuthorizationInitialized) {
                SCOPE = @[VK_PER_FRIENDS, VK_PER_WALL];
                [VKSdk authorize:SCOPE];
             }
        }];
}

@interface VKDelegate : NSObject <VKSdkDelegate, VKSdkUIDelegate>
@end

- (void)vkSdkAccessAuthorizationFinishedWithResult:(VKAuthorizationResult *)result
{
   NSLog(@">>>>>>>>>>>>>>>>>>>>> vkSdkAccessAuthorizationFinishedWithResult!");
}

- (void)vkSdkUserAuthorizationFailed {
    NSLog(@">>>>>>>>>>>>>>>>>>>>> vkSdkUserAuthorizationFailed!");
}

- (void)vkSdkShouldPresentViewController:(UIViewController *)controller {
        NSLog(@">>>>>>>>>>>>>>>>>>>>> vkSdkShouldPresentViewController!");
}

- (void)vkSdkNeedCaptchaEnter:(VKError *)captchaError {
        NSLog(@">>>>>>>>>>>>>>>>>>>>> vkSdkNeedCaptchaEnter!");
}
@end
```

В app делегате openUrl прописан, но не разу не был вызван
```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    Q_UNUSED(app)

    NSLog(@" >>>>>>>>>>>>>>>>>>>>>>> befor OPEN URL");
    bool wasHandled = [VKSdk processOpenURL:url fromApplication:sourceApplication];
    if (wasHandled)
        return wasHandled;
    NSLog(@" >>>>>>>>>>>>>>>>>>>>>>> AFTER OPEN URL");
...
}
```

Единственный вызов делегата sdk происходит, если вручную перейти на своё приложение после неудачной авторизации. Вызывается метод: 
- (void)vkSdkShouldPresentViewController:(UIViewController *)controller {
        NSLog(@">>>>>>>>>>>>>>>>>>>>> vkSdkShouldPresentViewController!");
}

**Comment by Anatoliy-Kondrik** [comment]
Нашел свою ошибку. Не был выполнен пункт из инструкции Setup URL-schema of Your Application.

**Comment by NikKovV** [comment]
Тем, у кого всё ещё проблемы с тем, что не вызывается метод в App Delegate:
https://dev.twitter.com/cards/mobile/url-schemes
https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html#//apple_ref/doc/uid/TP40007072-CH6-SW10
И наиболее удобно: https://developers.facebook.com/docs/ios/getting-started

Нужно настроить URL types: vk{your-app-id}.

**Comment by Bubcagop** [comment]
Добрый день, приложение после логина , при повторном входе все равно требует подтвердить разрешение (allow app to). 
- (void)login {
    if ([VKSdk isLoggedIn])
    {
        [self setupAppSettings];
        
    } else {
        [VKSdk wakeUpSession:self.scope completeBlock:^(VKAuthorizationState state, NSError *error) {
            switch (state) {
                case VKAuthorizationAuthorized:
                    // User already autorized, and session is correct
                    break;
                    
                case VKAuthorizationInitialized:
                    [VKSdk authorize:self.scope];
                    break;
                    
                default:
                    [NSTimer scheduledTimerWithTimeInterval:3.0
                                                     target:self
                                                   selector:@selector(handleTimer)
                                                   userInfo:nil
                                                    repeats:NO];
                    break;
            }
        }];
    }
    
}
