### ISSUE TITLE
wall.get secure

### ISSUE THREAD

**Issue by diretix** [VKCOM/vk-ios-sdk#503]
что за обновления с открытыми методами, пообновляли как обычно а че да как использовать сами думайте...
работаю на свифте, запилил вк сдк по инструкции все четко работало без регистрации или входа, запрашивал открытый волл гет, стена прилетала, парсил итд, теперь надо как то добавить сервисный код, как это сделать?? пробовал пилить в реквест "access_token":" сервисный код", респ говорил что код УЖЕ недейсвителен. че делать?? 

вк заюзан по стандартным инструкциям, до вейк ап, но без регистрации или входа пользователя, сам по себе чисто черпает стену.

**Comment by suzhaev** [comment]
@diretix https://vk.com/dev/access_token?f=3.%20Сервисный%20ключ%20доступа
В документации все описано)
