### ISSUE TITLE
Просто нереально разобраться в доках... (Основные игровые механики)

### ISSUE THREAD

**Issue by yomanx** [VKCOM/vk-ios-sdk#504]
Доброго времени суток, 

Скопился ряд вопросов, ответы на которые может знать только разработчик.
(Очень много людей на форумах разработчиков точно так же не знают ЧТО И КАК ДЕЛАТЬ!)

**1. ОТПРАВЛЯЕМ ПОДАРКИ ДРУЗЬЯМ. (ЗАПРОСЫ)**
- Наш запрос:
```
VKRequest * request = [VKRequest requestWithMethod:@"apps.sendRequest"
parameters:@{@"user_id":friendID,
@"type":@"request",
@"text":[NSString stringWithFormat:@"Take some %@!", gift],
@"name":gift}];
```
- **ВОПРОС:** Теперь, я хочу получить этот подарок на втором устройстве со второго аккаунта.
- Как мне опросить, есть ли для меня подарок ?
- Нужно ли его потом удалять самому, или он сам удаляется?
*В Facebook SDK есть методы получения подарка а в доках ВК - ПУСТО!! Никаких объяснений, никакого примера, ничего.

**2. РЕАЛИЗАЦИЯ ПОЗИЦИИ ДРУЗЕЙ на игровой карте**, (рамки с портретами на уровнях и тп)
НАПРИМЕР Делаем на базе метода secure.setUserLevel/secure.addAppEvent, пытаюсь отправить:

```
VKRequest * request = [VKRequest requestWithMethod:@"secure.setUserLevel"
                                                parameters:@{@"user_id":[VKSdk accessToken].userId, @"client_secret":@"1ec522291ec522291ec52229831e99a45211ec51ec5222947941781275765f2557b047c", @"level":@"1"}];
```
**ВОПРОС:**
И получаем ошибку: User authorization failed: client_secret is incorrect
Почему неправильный client_secret? Секерт в коде стоит из Личного кабинета приложения.
Если не правильный запрос, дайте пример корректного. 

![photo_2017-06-26_22-59-14](https://user-images.githubusercontent.com/3980592/27557709-2ef1e0d4-5ac3-11e7-9f63-04a8563c3c18.jpg)

**Comment by yomanx** [comment]
Есть кто?

**Comment by suzhaev** [comment]
По поводу второго пункта, из документации:
`Сервисный ключ доступа можно использовать только для запросов с серверной стороны приложения, его нельзя передавать и хранить на клиенте. `

**Comment by suzhaev** [comment]
По первому вопросу: никак)

**Comment by yomanx** [comment]
По второму вопросу, только сервисный ключ передавать нужно, или хранить очки, и тп (базу данных) и все остальное на сервере своём нужно тоже?

**Comment by suzhaev** [comment]
@yomanx ну это уже как реализуете, по логике конечно да)

**Comment by yomanx** [comment]
Я так понимаю, примера кода по "Сервисный ключ доступа можно использовать только для запросов с серверной стороны приложения,"  тоже просить нет смысла?)

**Comment by suzhaev** [comment]
@yomanx ну это уже к iOS sdk отношения особо не имеет, вряд ли смогу чем-то помочь.
