### ISSUE TITLE
VKShareDialogController - не выйти из UIAlertController

### ISSUE THREAD

**Issue by palagichev** [VKCOM/vk-ios-sdk#508]
При ошибке создания поста показывает UIAlertController без кнопок. 
`UIAlertController *alert = [UIAlertController alertControllerWithTitle:nil message:VKLocalizedString(@"ErrorWhilePosting") preferredStyle:UIAlertControllerStyleAlert];
        [self presentViewController:alert animated:YES completion:nil];`

**Comment by atom-wintermute** [comment]
https://github.com/VKCOM/vk-ios-sdk/pull/497 - починка
