### ISSUE TITLE
Авторизация под другим пользователем, смена. (куки не удаляются)

### ISSUE THREAD

**Issue by NikKovIos** [VKCOM/vk-ios-sdk#510]
Добрый день) 
У меня точно такая же проблема как описана в https://github.com/VKCOM/vk-ios-sdk/issues/7

`VKSdk.forceLogout()` не удаляет куки, соответсвенно зайти под другим пользователем нет возможности.

Помогло только 
```swift
let cookies = HTTPCookieStorage.shared.cookies
for cookie in cookies! {
     if cookie.domain.contains("vk.com") {
          HTTPCookieStorage.shared.deleteCookie(cookie)
     } 
}
```

**Comment by KonstantinBerkow** [comment]
На самом деле самому почистить куки тоже не поможет (forceLogout тоже это делает), так как дело в куках сафари, пользовтаель должен сам нажать "Выйти".
Но можно авторизоваться не используя `SFSafariViewController`, тогда проблемы не будет:
```
switch state {
case .unknown: fallthrough
case .initialized:
    // В данном случае можно и без опции
    VKSdk.authorize(vkPermissions)                
case .authorized:
    // А вот в таком случае будет показана чистая вебвьюха
    // впрочем некоторые считают WebView злом 🙂 (https://twitter.com/krausefx/status/970119355471147008)
    VKSdk.forceLogout()
    VKSdk.authorize(vkPermissions, with: .disableSafariController)
// other cases
}
```

**Comment by NikKovIos** [comment]
В версии 1.5.1 теперь куки удаляются в методе `forceLogout`.
