### ISSUE TITLE
Вопрос: Как перейти в Офф приложении на пользователя с определённым ID?

### ISSUE THREAD

**Issue by SadhuRus** [VKCOM/vk-ios-sdk#517]
Видел у других была такая фишка - кликаешь в своём приложении на пользователя и открывается официальное приложение VK App и там сразу переходит в профиль этого пользователя. Как такое сделать?

**Comment by suzhaev** [comment]
@SadhuRus уже не нужно?

**Comment by SadhuRus** [comment]
Уже нашёл. Спасибо @suzhaev
