### ISSUE TITLE
Не поддерживается OAuth авторизация на iOS 11.

### ISSUE THREAD

**Issue by YuriyNovikov** [VKCOM/vk-ios-sdk#518]
Шаги:
1. Склонировать репозиторий
2. Открыть example проект в Xcode 9
3. Собрать и запустить на iOS 11 симуляторе
4. Нажать 'Get new access token'

Выдается:
A problem repeatedly occurred on "https://oauth.vk.com/authorize?revoke=1&response_type=token&display=mobile&scope=photos%2Cwall%2Cmessages%2Cfriends%2Cemail%2Coffline%2Cnohttps%2Caudio&v=5.40&redirect_uri=vk3974615%3A%2F%2Fauthorize&sdk_version=1.4.6&client_id=3974615"

**Comment by ynewdev** [comment]
Какая-то локальная проблема, т.к. на другой машине нормально.

**Comment by YuriyNovikov** [comment]
Какая-то локальная проблема, т.к. на другой машине работает нормально.
