### ISSUE TITLE
EXC_BAD_ACCESS on VKSdk.authorize

### ISSUE THREAD

**Issue by alexnivanov** [VKCOM/vk-ios-sdk#534]
When I approve/cancel authorisation in VK app, I get EXC_BAD_ACCESS when returning to my app:

`Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`

Current version is VK-ios-sdk (1.4.6)

**Comment by Ksen17** [comment]
Абсолютно тоже самое 
все сделал по инструкции
Очень нужна помощь
вызываю 
```
VKSdk.initialize(withAppId: "6425897").register(self)
        VKSdk.authorize(["email","offline","friends"])
```
все методы реализованы 
при возвращение в приложение пишет 
`Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`

**Comment by alexnivanov** [comment]
Ещё одна деталь:

При возвращении в приложение можно отловить событие
`func applicationWillEnterForeground(_ application: UIApplication) {`

После этого происходит `EXC_BAD_ACCESS`

До этого вызова дело не доходит:

```
func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        VKSdk.processOpen(url, fromApplication: sourceApplication)
        return true
    }
```

**Comment by michanical** [comment]
Тоже самое
Причем работающее до этого приложение теперь не работает :(

**Comment by alexnivanov** [comment]
@michanical у меня раньше тоже работало :(

**Comment by AnnieSemenova** [comment]
Помогло использование 

```
 func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
    }
```

вместо 

```
func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
    }
```

данный метод помечен как Deprecated и не используется в iOS выше 9.0

**Comment by alexnivanov** [comment]
@AnnieSemenova а где тогда взять sourceApplication для
`VKSdk.processOpen(url, fromApplication: sourceApplication)`

**Comment by AnnieSemenova** [comment]
Вот так можно
`VKSdk.processOpen(url, fromApplication: options[.sourceApplication] as! String)`

**Comment by alexnivanov** [comment]
@AnnieSemenova спасибо огромное, помогло!!!
