### ISSUE TITLE
UIWebView deprecated

### ISSUE THREAD

**Issue by alexeymilakhin** [VKCOM/vk-ios-sdk#549]
Не изволите ли обновить свой SDK?

**Comment by bobile** [comment]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/8956402/64196920-8ba3f700-ce8d-11e9-9fa6-f55b50213949.png">

**Comment by oboupo** [comment]
https://github.com/VKCOM/vk-ios-sdk/pull/551
