### ISSUE TITLE
Нет поддержки изменений по privacy в iOS 13

### ISSUE THREAD

**Issue by kattouf** [VKCOM/vk-ios-sdk#553]
Начиная с iOS 13, эпл не раскрывает bundleId приложения, из которого был запрос на открытие целевого приложения, если они не из одной тимы:
https://developer.apple.com/videos/play/wwdc2019/708/?time=1277

> If the team identifier of the originating app is different than the team identifier of the current app, the value of the key is nil.  

https://developer.apple.com/documentation/uikit/uiapplication/openurloptionskey/1623128-sourceapplication

Отсюда такая проблема, что мы более не можем корректно пользоваться  следующим методом из VK SDK
Наверное стоит сделать какую то адаптацию под эти изменения
```
/**
 Checks passed URL for access token.
 
 @param passedUrl url from external application
 @param sourceApplication source application
 @return YES if parsed successfully
*/
+ (BOOL)processOpenURL:(NSURL *)passedUrl fromApplication:(NSString *)sourceApplication;
```

**Comment by kattouf** [comment]
Пока как вариант, должен работать костыль: если iOS 13 и схема совпадает с той, что регалась для вашего приложения в админки вк (и лежит в вашем plist), то передавать в сурс апликейшн bundleID приложения вк

**Comment by kattouf** [comment]
Не с первого раза обнаружил, что оказывается SDK умеет обрабатывать «плохой» случай, если в ‘sourceApplication’ передавать nil, так что у всех, кто не обрабатывает отсутствие этого значения, все будет работать исправно (:
Но даже так, считаю что стоит добавить явности и как минимум обновить описание параметров метода и ридми, чтобы было ясно что параметр опционален

**Comment by oboupo** [comment]
#554
