### ISSUE TITLE
Что вообще происходит с этим sdk и сервером vk в целом?!

### ISSUE THREAD

**Issue by Gargo** [VKCOM/vk-ios-sdk#580]
Проверяю авторизацию через `wakeUpSession` - не авторизован, ок, авторизую. Перезапускаю приложение - не авторизован, начинаю копаться в коде - токен от vk предоставляет меньше прав, чем я запросил.
Ну ладно, убираю в запросе права, которые мне не дают. Сбрасываю эмулятор, повторяю те же шаги. Мне снова выдает чуть меньше прав, чем запрашиваю, поэтому я снова не авторизован при перезапуске.
Ну ок, может быть что-то заглючило, поэтому снова убираю в запросе права и повторяю шаги. Мне выдает еще меньше прав.
Я торговаться правами на доступ должен с вк что ли - запрашивать больше, чем нужно?)

Я кажется догадываюсь, в чем дело - сравните константы:
https://vk.com/dev/permissions
https://github.com/VKCOM/vk-ios-sdk/blob/master/library/Source/VKPermissions.m
Походу значения констант сбились начиная с VK_PER_VIDEO.

Судя по истории все сломал некий @AlikhanMussabekov 27 августа 2020

**Comment by FugaziBro** [comment]
Такая же ерунда, бро.
Притом уже давно
