### ISSUE TITLE
Ошибка в парсере прав доступа пользователя, которая ломает постинг на стену.

### ISSUE THREAD

**Issue by gromwel** [VKCOM/vk-ios-sdk#585]
В данном коммите из прав доступа был убран доступ к аудио, но убран был так, что все остальные права поехали. 
https://github.com/VKCOM/vk-ios-sdk/commit/a661a5853a43d7ce2190d9c22e513972f89ecd5d#diff-caf5737b4d8e738b85da9e81210a4f0ad41385de0fc66ca14079ba47341332c7

Сравнивал с правами доступа в документации:
https://vk.com/dev/permissions?f=1.%20Права%20доступа%20для%20токена%20пользователя

Из-за этого, в методе `VKSdk.wakeUpSession` я получаю состояние `initialized` вместо `authorized`.

Исправьте пожалуйста.

**Comment by avsmirnov567** [comment]
Closed by #581, released in 1.6.2
