### ISSUE TITLE
!!!! Int кодировка scopes в VKPermissions.m не совпадает с официальной документацией

### ISSUE THREAD

**Issue by antonkrasilnikov** [VKCOM/vk-ios-sdk#586]
Зарелизился со свежей версий VK SDK iOS и у всех пользователей слетел логин - теперь при КАЖДОМ заходе в приложение перекидывает в ВК на логин. Начал дебажить и оказалось, что scopes от последнего логина, сохраненные локально в key chain, не совпадает со scopes, что на сервере, причем на сервере они вообще не те, что я запрашиваю. После более детального изучения, оказалось, что int кодировка scopes, зашитая в sdk, не совпадает с ОФИЦИАЛЬНОЙ документацией! Совпадает только первые 3

https://vk.com/dev/permissions

![image (1)](https://user-images.githubusercontent.com/2527751/106192731-a3d09080-61bd-11eb-8411-06dfa3440a44.png)
![image](https://user-images.githubusercontent.com/2527751/106192748-a7fcae00-61bd-11eb-9349-2d4bc1bb0a57.png)

**Comment by avsmirnov567** [comment]
Closed by #581, released in 1.6.2
