### ISSUE TITLE
Поддержка Xcode 14

### ISSUE THREAD

**Issue by Reload225** [VKCOM/vk-ios-sdk#595]
Проект не собирается на Xcode 14, ругается на подпись.

![Screenshot 2022-06-30 at 12 39 34](https://user-images.githubusercontent.com/33464222/176649183-2faf1937-70e7-436f-993d-aaed776341ee.png)

**Comment by SoundBlaster** [comment]
Вам необходимо выбрать в селекторе Team свой профиль разработчика или команду, в которой вы состоите.

**Comment by Reload225** [comment]
а почему в сторонней либе нужно свой профиль разработчика указывать? и почему именно ваша либа это просит, а другие нет?)

**Comment by SoundBlaster** [comment]
Здесь речь идет о фреймворке с ресурсами ([Mach-O type - Bundle](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/MachOTopics/1-Articles/building_files.html)), его требуется скопировать в банд вашего приложения для динамической загрузки при старте, для этого необходимо его заэмбедить в настройках ваше приложения. Если конечно вам действительно требуются ресурсы из этого бандла. Это каcается и Xcode 13. Можете попробовать выбрать `Embed Without Signing` - должно работать и без подписи. Но я не рекомендую этот вариант.

**Comment by SoundBlaster** [comment]
Если вам не требуются ресурсы вы можете удалить их из подпроекта Pods → Таргет VK-ios-sdk → Вкладка General → Frameworks and Libraries

**Comment by NikKovIos** [comment]
@Reload225 это баг xcode. Ты можешь сделать pod deintegrate && pod install и без этого заработает. Не только в этом sdk такая проблема.

**Comment by Reload225** [comment]
Да, пофиксил этим скриптом 

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
