### ISSUE TITLE
Авторизация через приложения

### ISSUE THREAD

**Issue by DmitryKuchin** [VKCOM/vk-ios-sdk#599]
Последние две недели не работает авторизация через официальное приложение. Переход в приложение происходит, однако в нем ссылка на авторизацию не обрабатывается, не открывая алерт подтверждения логин-данных. Попробовал посмотреть, какую ссылку он передает в приложение, чтобы там активировать запрос на авторизацию, но не заметил в ней, что можно поменять, чтобы исправить это. Дадите комментарий по этому случаю?

**Comment by Igralino** [comment]
Спасибо за сообщение об ошибке! 
Исправление реализовано в версии 1.63: в ней отключен переход в приложение ВКонтакте, в связи с тем, что в некоторых случаях он мог работать некорректно.
