### ISSUE TITLE
Не видит хедер файлы библиотеки

### ISSUE THREAD

**Issue by firuz1844** [VKCOM/vk-ios-sdk#61]
Все сделал шаг за шагом по инструкции. Xcode не видит ни в какую хедер файлы библиотеки. Пишет VKSdk.h file not found. Пробовал путь прописать в Search Paths, не помогает.
PS Надо ли папку с SDK в проект копировать?

**Comment by Djecksan** [comment]
Добрый день. У меня проект на swift 
Development Target 8.0
Подключил SDK через pods

**Не видит хедер файлы библиотеки**

P.S после установки фреймворка в поды ничего не предпринимал. Может что то где то прописывать нужно?

**Comment by abrgitlab** [comment]
@Djecksan и те, кто наткнулся на аналогичную проблему:
#import <VK_ios_sdk/VKSdk.h>

Как я понял, ето верно для любой библиотеки с тирешками в пути, в bridge-файле все тире на подчёркивания заменяются
