### ISSUE TITLE
Авторизация через модальное окно

### ISSUE THREAD

**Issue by vmalov** [VKCOM/vk-ios-sdk#64]
С ходу не нашел возможности авторизации через модальное окно. Хотели сделать регистрацию и логин пользователя в приложении только через Вк. Зареджектили по пункту 10.6 : 

Reasons

10.6: Apple and our customers place a high value on simple, refined, creative, well thought through interfaces. They take more work but are worth it. Apple sets a high bar. If your user interface is complex or less than very good it may be rejected
10.6

We found the following issues with the user interface of your app:

The app opens a web page in mobile Safari for logging in, then returns the user to the app. The user should be able log in without opening Safari first.

These examples identify types of issues discovered in your app but may not represent all such issues. It would be appropriate to thoroughly evaluate your app to address these types of issues.

---

Resources for learning how to improve your app:
- Review the UI Dos and Don'ts
- Watch the video The Ingredients of Great Apps to understand the basics of great apps
- Watch the video “Designing User Interfaces for iPhone and iPad Apps” for practical design tips
- Read the iOS Human Interface Guidelines and double check that your app's user interface adheres to these valuable guidelines.
- Read the App Design Basics section of the iOS App Programming Guide. 
- Watch the iOS Development Videos to learn about programming and design tips.

**Comment by SadhuRus** [comment]
Столкнулся с точно такой-же проблемой. Причём только на третьем апдейте. Первые два, точно также переправлялись в браузер сафари и всё  было ок. А на третьем, видимо проверяющему что-то не понравилось и он отклонил. Аппеляцию не вижу смысла подавать - тока трата времени. Хотя и жаль, что они смотрят на безопасность пользователя "сквозь пальцы".

Вероятно буду показывать WebView. Всем успехов!

**Comment by groschovskiy** [comment]
Почему ругается на SCOPE?

**Comment by ADevelopStudio** [comment]
тоже получил Реджект. Пришлось исправлять. 
На Swift это выглядит так:
                    if VKSdk.vkAppMayExists() {
                        VKSdk.authorize(VKSCOPE)
                    } else {
                        VKSdk.authorize(VKSCOPE, withOptions: VKAuthorizationOptions.DisableSafariController)
                    }
