### ISSUE TITLE
iOS 8. Не срабатывает делегат

### ISSUE THREAD

**Issue by ItsTipTop** [VKCOM/vk-ios-sdk#79]
Тестирую на симуляторе ios 8. Авторизация через Safari проходит успешно. Возвращает в приложение, но делегат о получении нового токена не срабатывает. Другие делегаты тоже не срабатывают.

```
- (IBAction)onVK:(id)sender
{

    [VKSdk initializeWithDelegate:self andAppId:@"...."];

    if ([VKSdk wakeUpSession])
    {
        NSDictionary *params = @{ ....
                                  };

        [self loginWithParams:params];
    }
    else{
        [VKSdk authorize:@[VK_PER_WALL, VK_PER_PHOTOS, @"email"] revokeAccess:NO forceOAuth:NO inApp:NO];
    }
}

#pragma mark - VKSdkDelegate
- (void) vkSdkRenewedToken:(VKAccessToken *)newToken {
    NSLog(@"renew");
}

- (void)vkSdkNeedCaptchaEnter:(VKError *)captchaError {
    VKCaptchaViewController *vc = [VKCaptchaViewController captchaControllerWithError:captchaError];
    [vc presentIn:self];
}

- (void)vkSdkTokenHasExpired:(VKAccessToken *)expiredToken {
    [VKSdk authorize:nil];
}

- (void) vkSdkReceivedNewToken:(VKAccessToken *)newToken {
    NSDictionary *params = @{ ......
                              };

    [self loginWithParams:params];
}

- (void)vkSdkShouldPresentViewController:(UIViewController *)controller {
    [self presentViewController:controller animated:YES completion:nil];
}

- (void)vkSdkUserDeniedAccess:(VKError *)authorizationError {
     NSLog(@"authorizationError");
}
```

P.S: полностью рабочий код на ios 7

**Comment by mxl** [comment]
У меня была такая же проблема. Оказалось, что я создавал экземпляр класса, реализующего VKSdkDelegate, в контексте метода другого класса и не сохранял ссылку на экземпляр за пределами метода.

**Comment by Ryskalo** [comment]
Есть пример простого проекта с использованием этого SDK? Не могу разобраться с ним.

**Comment by Djecksan** [comment]
Все привет. Была такая же проблема как и у всех тут. Помог комментарий mxl. К тому времени как должен был вызваться метод **vkSdkReceivedNewToken** у делегата, ios высвобождала обьект реализующий этот метод из памяти и поэтому он был nil. 

Решением стало просто обьявить обьект реализующий делегат свойством.
