### ISSUE TITLE
Проблема с авторизацией

### ISSUE THREAD

**Issue by applejournalcource** [VKCOM/vk-ios-sdk#80]
Здравствуйте, у меня такая проблема, при авторизации открывается сафари, там есть выбор "Разрешить" или "Отклонить", так вот, по нажатию на любую из кнопок вылетает сообщение "Не удается открыть страницу, так как адрес недействителен". Такое сообщение появляется на любом из устройств, на котором я запускал приложение.

**Comment by VladimirSharaev** [comment]
а как решена? можно пояснить?

**Comment by iFoxxy** [comment]
@applejournalcource подскажите, пожалуйста, как вы решили проблему?

**Comment by ravilich86** [comment]
У меня такая же проблема. Подскажите пожалуйста в чем ошибка, где что прописать забыл?

**Comment by nastasiasha** [comment]
у меня было такое, когда были неправильные настройки URL-схемы. Надо зайти в настройки проекта -> Info -> URL Types. Указать идентификатор и URL-схему в виде vk123456

**Comment by NikKovIos** [comment]
Look at this guide to install properly  https://github.com/west0r/SwiftyVK
