### ISSUE TITLE
Загрузка больших фотографий друзей

### ISSUE THREAD

**Issue by maxim4to** [VKCOM/vk-ios-sdk#82]
Запрашиваю список друзей, потом получаю аватарку каждого пользователя. Использую поле "photo_max_orig", но приходят маленькие фотографии, разрешения от 200 на 200 до 400 на 700 примерно, в основном по длиной в 400px. Как можно получить фотографию большего размера? А лучше максимального.

VKRequest *friendsRequest = [VKRequest requestWithMethod:@"friends.get" andParameters:@{ VK_API_FIELDS : @"uid,first_name,last_name,sex,bdate,has_mobile,photo_100,photo_200_orig,photo_200,photo_400_orig,photo_max,photo_max_orig,domain,contacts,connections,site,screen_name", @"order" : @"name"} andHttpMethod:@"GET" classOfModel:[VKUsersArray class]];

...

image = [UIImage imageWithData:[NSData dataWithContentsOfURL:[NSURL URLWithString:friend.photo_max_orig]]];
NSLog(@"%@", NSStringFromCGSize(image.size)); //{400, 400}, {400, 622}, {200, 200}, {400, 622}... и т.д.

**Comment by novixon** [comment]
Мне помогло изменение флага photo_sizes на 0! Они и так возвращаются нормально.
