### ISSUE TITLE
Sdk_bundle error

### ISSUE THREAD

**Issue by yapetrichka** [VKCOM/vk-ios-sdk#98]
Invalid_request : sdk_bundle is incorrect. При авторизации через WebView все проходит успешно, а через приложение возвращает данный ответ.

**Comment by zhangyu528** [comment]
Register a app to vk ,but still return {"error":"invalid_request","error_description":"sdks_bundle is incorrect"}  why? I miss some step?

**Comment by Dreddik** [comment]
@zhangyu528 did you fill App Bundle for iOS field?

**Comment by zhangyu528** [comment]
Yes. and App Id for iOS was filled.

**Comment by zhangyu528** [comment]
App Bundle is Bundle name in info.list?

**Comment by Dreddik** [comment]
App bundle is a bundle identifier in Info.plist

**Comment by zhangyu528** [comment]
thanks, then App Id for iOS is?

**Comment by Dreddik** [comment]
App ID is the Apple ID for your application from itunesconnect

**Comment by zhangyu528** [comment]
My app is Demo test,now.:(

**Comment by Dreddik** [comment]
So you don't need to fill this field. Only bundle

**Comment by zhangyu528** [comment]
Thank you ! It is OK.

**Comment by zhangyu528** [comment]
Share something,but alert " An error accord while executing your request.Please try later"
Yesterday, it is OK ,use vkSdkTest application 's Vk+application Id

**Comment by Dreddik** [comment]
Maybe today our service feels not really good

**Comment by zhangyu528** [comment]
Error: Error Domain=VKSdkErrorDomain Code=-101 "Access denied: no access to call this method" UserInfo=0x7fae62db0ef0 {VkErrorDescriptionKey=<VKError: 0x7fae62d15320; API error {code: 15; message: Access denied: no access to call this method;}>, NSLocalizedDescription=Access denied: no access to call this method}
code is
VKAccessToken* token = [VKSdk getAccessToken];
    NSInteger userId = [token.userId intValue];
    image = @"4.png";
    VKRequest* request = [VKApi uploadWallPhotoRequest:[UIImage imageNamed:image] parameters:[VKImageParameters pngImage] userId:userId groupId:60479154];

**Comment by zhangyu528** [comment]
Access denied 
Make sure that you use correct identifiers and the content is available for the user in the full version of the site.

**Comment by zhangyu528** [comment]
How to make sure that use correct identifiers and the content?

**Comment by zhangyu528** [comment]
I   found it!
need to set  SCOPE = @[VK_PER_FRIENDS, VK_PER_WALL, VK_PER_AUDIO, VK_PER_PHOTOS, VK_PER_NOHTTPS, VK_PER_EMAIL, VK_PER_MESSAGES];

**Comment by zhangyu528** [comment]
Dear，Dreddik 
I have a problem that how to test "apps.sendRequest".The app is demo,is not be approved.
Thank you so much!

**Comment by dippol** [comment]
Thanks a lot!
I got same error then used FBSDKShareDialog.
 Error Domain=VKSdkErrorDomain Code=-101 "Access denied: no access to call this method" UserInfo={NSLocalizedDescription=Access denied: no access to call this method, VkErrorDescriptionKey=<VKError: 0x1c466060; API error {code: 15; message: Access denied: no access to call this method;}>}

To solve issue i change SCOPE
SCOPE = @[VK_PER_EMAIL, VK_PER_FRIENDS, VK_PER_GROUPS];

to

SCOPE = @[VK_PER_FRIENDS, VK_PER_WALL, VK_PER_AUDIO, VK_PER_PHOTOS, VK_PER_NOHTTPS, VK_PER_EMAIL, VK_PER_MESSAGES];
