### ISSUE TITLE
При авторизации через приложение ошибка

### ISSUE THREAD

**Issue by ghost** [VKCOM/vk-ios-sdk#99]
{"error":"invalid_request","error_description":"redirect_uri has wrong domain, check application settings"}

Схема url прописана в xcode по документации (vk2243292). При авторизации в Сафари та же ошибка.

Из-за чего такое?

**Comment by valnoc** [comment]
Столкнулся с такой же ошибкой
Приложение standalone
Прописал url type - vk+ID

Делаю
initializeWithAppId
registerDelegate
setUiDelegate
wakeUpSession
authorize

{"error":"invalid_request","error_description":"redirect_uri is incorrect...."}

подскажите, в чем может быть проблема?

**Comment by printercu** [comment]
@Dreddik Подскажите, нет информации, будет ли возможность использовать одно приложение и для сайта и для мобильных приложений в ближайшее время?

**Comment by Dreddik** [comment]
@printercu такая возможность уже есть, нужно обратиться в поддержку в разделе "Помощь" у вашего приложения

**Comment by printercu** [comment]
Поддержка ничем помочь не смогла. 

```
- Увы, к подключенным сайтам мы пока не можем добавлять параметры мобильных приложений. 
- может к standalone-приложению можно добавить возможность oauth авторизации на сайте?
Или есть другой способ использовать один app_id на сайте и в приложениях?
- На сайте пока нельзя. Можно в мобильных и десктопных приложениях.
```

**Comment by Dreddik** [comment]
@printercu извините, неправильно вас понял. Действительно, я говорил о связи мобильное-десктопное приложение. Сайт-приложение пока не планировали, но, возможно, есть смысл обсудить

**Comment by printercu** [comment]
Это было бы удобно. Но, в принципе, сейчас проблем не столь серьезные: пользователям на сайте и в приложениях надо отдельно разрешать доступ, ну и статистики общей на одной странице нет.

Я сначала подумал, что user_id может быть app-scoped как в другой сс. Но пока он глобальный в ответах апи, то больших проблем нет.

**Comment by printercu** [comment]
@Dreddik столкнулись с этой проблемой: https://new.vk.com/dev/need_validation
Я так понимаю, сейчас идет расчёт на то что нативное приложение будет пользоваться полученным access_token на том же девайсе, где и получило токен. Тогда при передаче токена на сервер и выполнения запроса с него  ВК будет думать, что пользователь зашел из необычного места и надо проверить его. Хотя в этой ситуации ничего опасного нет, если токен не попал к злоумышленникам.

Если же токен утек, то текущий подход с подтверждением не защищает на 100%, т.к. ПО, которое украло токен, может показать и страницу для редиректа. Да  и в целом подход не совсем верный - пользователь же не перемещался никуда, а отрабатывает система как-будто перемещался. 

Такую ситуацию можно решить, если дать возможность использовать один апп_ид и на сервере и в нативных приложениях, и добавить вайтлист IP серверов. В дальнейшем для улучшения безопасности, можно добавить возможность включить обязательную подпись запросов (`appsecret_proof`).
